label sitwithcarl:
stop music fadeout 3.0
play loop "reststop.ogg" fadein 3.0
"Eu tô cansado, e me sinto horrível. Eu só não tenho a energia pra ficar procurando todo mundo agora."
"O Flynn voltou pra Echo, e parece que o Leo foi atrás do TJ, mas eu não acho que o lince quer nós todos ao redor dele agora."
"Suspiro, esfregando meu rosto antes de sentar na cadeira ao lado do Carl."
show Carl Rejected at center with dissolve
"Ele olha para mim, lentamente abaixando o que é definitivamente um baseado da mão dele."
m "— O quê? Eu não ligo."
"Eu faço um gesto de \"pode ir\" com minha pata."
"Porém Carl discorda com a cabeça, enfiando o baseado descascado no bolso da frente." # disheveled tube = baseado descascado ?
c "— Nah, eu sempre meio que me sinto um cuzão quando o outro cara não gosta." #isn't into it = não gosta
m "— Quer que eu saia?"
"Ele nega com a cabeça rapidamente mexendo os chifres."
c "— Não mano. Eu só fumo quando não tem mais nada pra fazer."
m "— Ah."
"Temos um momento de silêncio e eu sinto uma pequena pressão de quebrá-lo já que fui eu quem interrompeu sua sessão de bolagem." # bake session = sessão de bolagem ?
m "— Na verdade eu experimentei alguns anos atrás."
show Carl Neutral with dis
"Carl parece surpreso."
c "— Ah sério? Como foi?"
"Eu encolho os ombros."
m "— Meio ruim. Foi num bolhinho, eu acho." # muffin = bolhinho ? (SideStory Party)
show Carl Annoyed with dis
"Carl faz uma expressão de desaprovação ao escutar isso."
c "— Comestíveis."
m "— É, bem, eu acabei comendo um, não senti nada por um tempo. Quando me dei conta eu tava desmaiado no chão e todo mundo preocupado."
c "— Nossa, que merda."
m "— Foi meio engraçado, mas eu não acho que vou experimentar de novo na minha vida inteira."
"Carl tira o baseado de volta do bolso e o ergue."
c "— É por isso que você devia usar um desses. É mais leve no cérebro"
m "— É, bem, acho que eu só não gosto da ideia de botar fumaça nos meus pulmões."
show Carl Rejected with dis
"Carl coloca o baseado de volta no bolso."
c "— Entendo."
"Novamente, há alguns segundos de silêncio e eu tento pensar em algo pra falar, mas o Carl fala antes de mim."
play music "neutral.ogg"
show Carl Neutral with dis
c "— Loucura, né?"
"Eu assumo que ele está falando sobre o que acabou de acontecer."
m "— É, loucura."
c "— Mas cê sabe como ele é. Ele tá se arrependendo de tudo agora."
m "— Quer dizer, seria melhor ele só não ter falado pra início de conversa."
m "— O que ele disse pro TJ, mano... Ele sempre implica com ele, mas aquilo passou do limite."
"Carl coça atrás de um dos seus chifres, depois coça o nariz."
c "— Bem é, acho que eu nunca entendi isso também. Zoar o TJ é tipo... zoar uma nuvem."
c "— Mas o Flynn não faz por mal, normalmente. Ele gosta do TJ."
"Percebi durante essa viagem que o Carl está defendendo bastante o Flynn, apesar dele ser o alvo da maioria das piadas do lagarto."
"Eu já tinha visto o Flynn dar rasteira no Carl e agarrando ele pelo pescoço várias vezes desde que cheguei aqui."
"Você imaginaria que envelhecer mudaria isso, mas eu juro que eles agem igual moleques mais do que antes."
m "— Então você e ele ainda parecem bem próximos. Vocês saem bastantes?"
c "— Uhum, um pouco, mais porque não tem nada pra fazer. Ele tem um amigo em Payton que ele saí, também."
m "— Então o que que vocês fazem?"
"Eu sei que o Flynn não gosta de videogames nem um pouco, e o Carl provavelmente não se interessa em ir em boates toda noite."
"Ele levanta os ombros."
c "— Às vezes a gente saí pra pescar, ou só dirigimos por Payton."
c "— Mas na maioria das vezes eu tô em casa."
m "— Jogando videogames?"
c "— Jogando videogames, assistindo filmes, websexo com IA– o de sempre."
"Eu sorrio."
m "— Que triste, eu teria feito websexo com você se soubesse que você não tinha mais ninguém."
show Carl with dis
c "— Sei lá mano, aquilo combina todos os fetiches das pessoas que conversaram com ela. Deixou minha sexualidade fodida de todos os jeitos."
m "— Ah é?"
c "— Aham, parece que não importa o que eu fale pra ela, ela tá amarrada em um algum armazém, vendada sem algumas partes do corpo."
m "— Cê subestima minhas habilidades."
c "— Ah, e uma troca de sexo que vem do nada no meio da conversa."
m "— Bem, quando você não tá tendo sexo com um robô, faz outras coisas?"
"Ele ri."
c "— Eu tecnicamente não consigo sair por conta própria mais."
m "— Presumo que seus pais decidiram não te dar um carro novo?"
c "— É... Ah! Olha isso."
"Ele se inclina para o meu lado e pega o celular. Não consigo evitar de notar que é uma marca cara, provavelmente entre R$4.000."
"Mas ele não está me mostrando o celular. Ao invés disso ele toca na tela algumas vezes e passa por algumas fotos."
"Eu juro que vejo uma imagem do Flynn sem calça abrindo o cu pra câmera."
"Porém o Carl passa bem rápido por cima, e agora estou vendo a imagem de um sedã novinho em folha–"
"–exceto que a frente tá perfeitamente dobrada em torno de um poste com uma placa de pare."
"Eu reconheço a placa; Eu já tinha visto ela do lado de fora de um mercadinho, ainda dobrada num ângulo ridículo."
"Acho que a cidade não se importou o suficiente pra ajeitar ela."
"O poste em si está quase encravado no meio do capô."
m "— Caralho."
"Carl ri e dá um zoom na tela."
c "— É. Derrubei o celular e quando voltei pro volante o caralho desse poste tava bem na minha frente."
m "— Sério, Carl? Por que cê tava no celular?"
c "— Sei lá. Quando eu chego na cidade eu não acho que vai ter alguém na rua."
"Suspiro, então percebo uma grande, redonda, batida no lado direito do para-brisa, parecendo uma teia de aranha e um branco esmagado." # spot = batida ? smashed white = branco esmagado ?
m "— Eita, isso é–"
c "— Uhum!"
"Carl bate na cabeça para fazer um efeito, o som oco que ela emite combinando bastante."
m "— Cê confia demais nisso... e você realmente precisa começar a usar o cinto de segurança."
"Ele encolhe os ombros e guarda o celular no bolso antes de se inclinar na cadeira e fechar os olhos."
c "— Pra quê?"
m "— Uh, pra não morrer?"
c "— Acontece com todos mais cedo ou mais tarde. Pra que não sair mais cedo o possível?"
"Ele deixa a voz leve durante essa frase pesada."
"Não tenho ideia do que responder a isso, então não respondo, mas ele quebra o silêncio de novo em pouco tempo."
c "— Então como tá indo Pueblo, cê chegou a ver a Chelsea?" # gênero?
"Às vezes eu esqueço que o Carl foi para Pueblo comigo. Foi só por um semestre, mas nos divertimos muito."
m "— É de boa, mas eu não cheguei a ver ela." # gênero?
c "— É uma faculdade grande né. Enfim, o que é esse projeto que cê tá fazendo?"
m "— É só um dossiê de notícias sobre Echo, sério. Meio sobre como ela decaindo."
c "— Huh."
"Eu já disse isso para ele, mas o Carl nunca se lembra muito."
m "— Talvez eu centralize em toda aquela situação do \"cadáver na mina\" que aconteceu lá atrás."
"Carl abre os olhos e olha pra mim."
c "— Então você precisa de tipo, coisas de história, tipo livros e registros antigos e tal?"
m "— Uh, é. Se tiver relação."
"Carl se senta mais reto e sorri."
c "— Bem, por que cê não me disse antes! A gente tem um monte de coisas no vão entre a fundação e o piso da minha casa lá de antigamente."
m "— Sério? Que tipo de coisas?"
"Carl encosta um casco em uma das pedras circulando a fogueira e começa a balançar a cadeira para trás."
c "— Bem, seja lá o que minha familia guardou durante os anos. Aquele cara, hum..."
"Carl estala os dedos algumas vezes."
c "— Cê sabe, aquele cara... que fundou esse lugar, uh..."
m "— James?"
c "— É, isso. Ele é tipo, meu tataravô, ou algo assim. Eu acho que a gente ainda tem algumas dessas coisas de antigamente."
c "— Meus pais tavam pensando fazer algo tipo um museu de Echo, mas eles nunca fizeram."
"Isso talvez seja realmente útil para mim."
"Tudo que eu tinha planejado era talvez olhar alguns jornais antigos ou registros da cidade e acabar assim."
"Acabar vendo algumas coisas antigas de perto poderia ser bem legal."
m "— Na real isso pode ser uma boa ideia."
"Carl sorri."
c "— Ótimo. Eu sempre meio que quis dar uma olhada nessas coisas, mas o vão é assustador pra caralho. Cê tá livre hoje à noite?"
"Pela primeira vez o Carl realmente parece bem empolgado."
c "— Ah pera, esquece. O Flynn vai me levar numa consulta no dentista cedo. Que tal ás 11 amanhã?"
"Eu sorrio."
m "— Tá combinado."
c "— Perfeito! AAI!"
show Carl Surprised with dis
$ renpy.pause(0.1, hard=False)
hide Carl with dissolve
play sound "fall.ogg"
with vpunch
"Carl dá um chute ansioso na pedra e, enquanto a cadeira está balançando para trás, as pernas de trás praticamente quebram sob seu peso."
"Ele cai diretamente de costas no chão, a cadeira completamente esmagada sob sua bunda."
show Carl Sheepish with dissolve
"Eu rio e claramente me sinto mal, mas o Carl apenas se levanta com um sorriso envergonhado, olhando para a pilha quebrada."
stop music fadeout 3.0
stop loop fadeout 3.0
c "— Bem, o Leo vai ficar puto."

scene bg creepylake
with opening_fade
play music "meeting1.mp3" fadein 10.0

"Estou dirigindo pela estrada ao lado do lago."
"O Carl está sentando ao meu lado."
"Ele está na cadeira que ele quebrou."
"Continuo mandando ele usar o cinto, mas ele não se recusa."
"Viro em uma rua na qual não me lembro."
"Desce diretamente ao lago."
"Por algum motivo não consigo parar."
"Me preparo para o impacto, mas quase não sinto nada."
"Nós simplesmente afundamos no lago."
"Começo a tentar tirar o cinto, mas está preso."
"Olho para o Carl e ele sorri antes de abrir a própria porta."
"Água entra, e ele começa a sair."
"Logo a água está sobre minha cabeça, e não importa mais que sou uma lontra."

jump carltuesday