label leothursday:

window hide
stop music fadeout 3.0
stop loop fadeout 3.0
scene bg thursday
with transition_fade
$ renpy.pause(3.0, hard=True)

scene bg route93
with dissolve
stop music fadeout 3.0
play loop "highway.ogg" fadein 3.0
window show
"By morning, Leo seems to have perked up a little."
"It starts with some good news from Flynn."
"Carl had been in the crawlspace."
"According to him it had been too hot to sleep anywhere but there."
"Of course, that's fucking insane, but it's definitely something Carl might do."
"In better spirits, Leo suggests we go out to some burger joint, to which I agree."
"On the way we chat about my project."
l "\"So obviously I don't wanna spend ALL of our time just having fun. You have a project to do, after all!\""
m "\"Yeah.\""
"I don't remind him that most of this messing around has been his idea."
l "\"Though we do need to hang out with TJ today, if that's okay. I promised him we would yesterday. He's been...feeling kinda down, obviously.\""
"I look down at my sausage biscuit sandwich, the excess grease glistening in the sunlight shining through my window."
l "\"I was thinking the park.\""
m "\"Yeah. That sounds like fun.\""
l "\"So what do you still need to do?\""
"I take a bite to give myself time to think."
m "\"Mmh, Well...\""
m "\"Honestly I'm not too sure...The whole premise is about the body that was found in the mine.\""
l "\"Yeah, what was that about?\""
m "\"Well, I read about it on a website. Apparently some guy's mutilated body was found in the mines and everyone in the town lost their minds.\""
l "\"A website?\""
m "\"Yeah.\""
l "\"Uh...shouldn't you have a better source than that?\""
m "\"Well—\""
l "\"Especially if the whole idea of your project is based off of that.\""
"I blush; someone like Leo chastising me about journalistic integrity is kind of embarrassing."
"It's not that he's stupid. I guess I'm just used to feeling like the brains of our little dynamic."
m "\"I mean, it's cited. I just need to get the book, which is something else we'll need to do. Do you have a library card?\""
l "\"No.\""
m "\"Wow, surprising.\""
l "\"But I could sign up for one.\""
"Leo nudges me."
l "\"Don't be bitter. I just want you to do a good job.\""
m "\"I'm the one that went to college. I know what I'm doing.\""
"Leo laughs."
l "\"You know I read a study about college kids.\""
m "\"A study? Sounds like something you wouldn't know about considering you didn't go to college.\""
l "\"Right. Anyway, it was about how college doesn't make you smart, just more liberal.\""
m "\"Uh-huh, so is that a bad thing?\""
l "\"Well, paying twenty thousand a year to get indoctrinated just doesn't appeal to me.\""
"I frown."
m "\"Is that why you stopped going, or have you just been looking up these studies to make yourself feel better about quitting?\""
"Leo pauses."
l "\"That's a strong word. I guess I just realized that what I had was good enough.\""
l "\"My dad makes more than most college grads, and he's teaching me the trade, too.\""
"Leo pauses as he changes lanes around a massive sixteen-wheel carrying what looks like steel."
l "\"And I'm already certified.\""
m "\"Okay...Where exactly are you going with this?\""
l "\"I just want to make sure you're okay with that, is all...\""
m "\"Oh, well, I'm not Jenna. As long as you're doing what you want I really don't care what it is you decide to do.\""
"Leo smiles."
l "\"Well good! And if we, you know—I'm not saying we will—but if we ever got together again, I'll be able to support you.\""
m "\"Well, just don't make fun of me for going to college, or what degree I decided to go into.\""
l "\"You know, you're a good enough writer already. You could have just started up a blog, or something.\""
m "\"What?\""
l "\"I just read that that's what journalism is these days.\""
"I start sulking again."
m "\"Maybe you should stop looking these things up. At least I'm learning to do something.\""
m "\"It's not like I just got a degree in psychology and stopped there.\""
l "\"Well, didn't you tell me you wanted to go into history? Isn't that worse?\""
m "\"Let's just drop it.\""
"Leo looks at me out of the corner of his eye."
l "\"Chula...I'm not making fun of you.\""
m "\"Well, when someone starts sounding like my dad I think that's a good time to end the conversation.\""
l "\"Aww, you're not into that?\""
m "\"...Definitely not.\""
"We drive in silence for a while as Leo pulls out his food from the brown, grease-stained paper bag.\""
"As we're heading back, he nudges me."
l "\"Hey, I have an idea?\""
"He talks with his mouth full, one hand holding onto his sausage biscuit while the other steers."
m "\"Are you asking me? Hey, both hands on the wheel!\""
"Leo chuckles as he swigs from his orange juice carton with his steering paw before returning it to the wheel."
m "\"Even when I'm in the car you drive like shit.\""
l "\"Hey, I'm way more careful when you're with me.\""
m "\"That makes me feel so much better...\""
l "\"Good!\""
"He takes another huge bite."
"I wait while he chews and when he finishes he takes another bite."
m "\"You were saying?\""
l "\"Oh yeah! You know those train tracks behind my yard, didn't you say they were important somehow?\""
m "\"Yeah. Echo used to be an important junction.\""
l "\"Well, why don't we go there and you can film some stuff? The rail yard is only like, a five minute walk away.\""
"I think."
m "\"Actually, yeah, that's a good idea.\""
"Leo smiles, panting a little in the heat, looking proud of himself."
l "\"Cool, we'll go over once we get back.\""
stop loop fadeout 3.0

scene bg railyard with fade
play music "oldwinds.ogg"
"There's not much left of the old train yard."
"The building that used to service the junction is basically gone save for the foundation."
"There are two groups of abandoned freight cars with \"Goldengate Southwestern\" in chipped paint on the sides."
"I'm happy to see it since it'll help with the scenery I'm trying to capture."
"After doing a few panning shots along with some closeups of the cars, I lean against an old freight car with my head back."
"I close my eyes against the heat."
"It's almost noon so it's almost impossible to find any good shade out here."
"For some reason, it's only now that I'm realizing how stupid it was to do this so early."
"The sunset would have looked a lot better, along with it being a lot cooler."
"Leo's been gone almost twenty minutes at this point. He said he was gonna get some water bottles, but it's been a while."
"The sweat seeping into my shirt makes my skin crawl."
"After looking around, I peel it off and hang it up against a small, metal ladder on the frame of one of the freight cars."
"I lean back against the exact same spot I was earlier, where it isn't burning hot and resume closing my eyes."
"Vaguely I wonder how many miles this thing has covered, how much of the country it's seen."
"The railway was closed down in the 60s so it's at least over 50 years old."
"Unless they're just using Echo as a dump for unwanted train cars and left them here recently."
stop music fadeout 5.0
play loop "reststop.ogg" fadein 3.0
"A lot older than I am...there's something weirdly comforting about leaning against something that's been through so much. Almost reassuring."
"It's like swimming in an old river, or lake that's been around for millions of years."
"Something brief connected to things that are permanent."
play sound "drygrass.ogg"
"I hear rustling through the grass on the other side of the car, but I keep my eyes closed."
m "\"Leo, I think I'm gonna die. I'm not built for the heat.\""
"I wait, but he doesn't say anything."
m "\"Leo?\""
play sound "drygrass2.ogg"
"The rustling starts up again: a long, slow drag through the dried vegetation. This time it sounds like it's coming from under the train."
m "\"Leo?\""
"I finally open my eyes and step away from the car, turning around to look at it like I can see through it."
m "\"What are you doing?\""
"Obviously trying to scare me. Leo was never as subtle as Jenna, but he did his fair share of at least trying."
"I lean over to look under the car, glaring."
m "\"You know, if you're tryin—\""
"I'm met with emptiness under the car, just dirt, dead grass and rusted rails."
"Was it some kind of animal? It sounded pretty big to be—"
show Leo at center
play sound "impact.mp3"
with vpunch
l "\"Chase!\""
m "\"FUCK!\""
"A heavy paw slams on my shoulder and I jump as Leo shouts right next to my head."
"I stumble forward, but he grabs me up, laughing."
play music "comeover.ogg"
show Leo Wry with dis
l "\"Hahahahaha! Holy shit, I've never seen you jump THAT hard before.\""
"Normally I'd be pissed, but that build up just had me glad it was Leo."
m "\"How the hell did you do that?\""
l "\"Do what?\""
m "\"That whole setup you did.\""
l "\"Well, you see, first I take my hand and slap it on your shoulder—\""
m "\"No, the whole walking around behind me and making that dragging sound under the car.\""
show Leo Questioning with dis
l "\"Huh?\""
"Leo looks confused."
"I frown. I guess it would have been kind of impossible for someone Leo's size to sneak around like that without me seeing him."
l "\"Did you hear something?\""
"Leo mimics my earlier position and bends over to look under the train."
m "\"Yeah, but there wasn't anything there. I thought you were trying to scare me.\""
l "\"Well, I was, but I didn't do that. Probably some animal or something. There's a lot of weird wildlife out here, you know.\""
show Leo with dis
"He stands up."
l "\"That would have been a good idea though.\""
m "\"It sounded really heavy, like a person.\""
l "\"Could have been. You know, a lot of the weirder people around here like to come here to get drunk, or high, or whatever.\""
m "\"Sounds fun...\""
"I must still look a little unnerved because Leo sets a hand on my shoulder."
l "\"Well, I'm here now, so don't worry.\""
"His eyes drift down to look at my torso."
l "\"Daaamn...You've kept in shape. Well, better shape!\""
"I smirk, rubbing a shoulder."
m "\"Swimming everyday helps.\""
show Leo Wry with dis
"Leo rubs my shoulder, grinning."
l "\"You look good.\""
m "\"You always say that.\""
l "\"And I always mean it.\""
m "\"Well...thanks.\""
"I've gotten to the point where I've just stopped pretending that there isn't at least something still there between us."
"And I think I've stopped pretending that nothing's gonna happen on this trip...eventually."
"What really worries me is what will happen after."
"Leo, meanwhile, slides his hand over my stomach."
l "\"Not that I'd care if you gained any weight. That happens, but I like you this way.\""
m "\"Yeah, it happens.\""
"I only hesitate for a moment."
"I slide my own hand under his shirt and Leo makes a soft gasping noise as I press it up against his stomach."
show Leo Embarassed with dis
"His ears fold back, though he keeps a grin on his face."
l "\"Being a wolf makes it harder, you know.\""
m "\"I believe you.\""
"As if to try and convince me he hasn't really gained weight he flexes his abs, flattening the soft fur of his stomach against my palm."
"Steel wrapped in velvet."
m "\"But you know I'm into that.\""
show Leo Wry with dis
"I get the urge to adjust my pants so my dick isn't jamming so uncomfortably into the crotch..."
"...but I don't want to make it THAT obvious that I'm aroused."
l "\"You mind feeling some other part of me? You're making me feel fat.\""
"I giggle before I slide my hand up his torso."
show Leoexp Wry with dis
hide Leo
"This exposes more of his white stomach all the way up to his chest and I can feel his pounding heart."
m "\"That better?\""
"Leo just gives a breathy, laughing exhale as he lets me feel him."
"He sidles closer, resting both of his hands on my waist."
"I feel his pec with my hand as I thumb through his fur to find the nipple underneath, feeling it harden in response."
"Leo shudders and grins at me."
l "\"Heh, I think this place does things to us, Chase. Remember our first kiss?\""
m "\"This isn't the exact spot.\""
"Was it really six years ago already?"
"I sigh, then slide both of my hands under his shirt and wrap them around his waist, burying my face in his chest."
"Leo hugs back as he starts nibbling at my ears, which makes me gasp."
m "\"Hey! Can't we just...enjoy the moment?\""
"Leo giggles."
l "\"I am.\""
show Leoexp with dis
"I look up at him and—I'm not sure if I just run into it—but we kiss."
"It's a small peck, but then Leo puts his hand behind my head and pushes me deeper into the kiss."
"He opens his muzzle to clamp around mine, his warm tongue pressing up against my lips."
"I'm still for a moment, and so is he, waiting for me to respond."
"When I do, it's with my paws around his back, me kissing back."
play sound "twigsnap.ogg"
"A soft crack to my right makes me jerk my head from the kiss to look over."
show Kudzu at right behind Leo with dissolve
"Kudzu's standing there, his arms folded."
show Leoexp Embarassed at left with moveinleft
stop music fadeout 5.0
show Leo Embarassed at left with dis
hide Leoexp
"Leo coughs in surprise, pulling back as well and wiping his muzzle."
l "\"OH—uh—Kuduz...Kudzu, what's up?\""
"The raccoon's expression is hard to read, as usual, but I see the corner of his muzzle quirk up after a while."
play music "neutral.ogg"
ku "\"Not much. What's up with you?\""
l "\"Oh, you know...stuff.\""
show Kudzu Wry with dis
"Leo laughs and, finally, Kudzu smiles."
m "\"Hey Kudzu.\""
"I speak up, feeling awkward staying silent after Kudzu caught us like that."
"He nods in my direction."
ku "\"Chase. So what are you guys really doing out here? Seems like kind of a dumpy place to be...doing that.\""
"I blush, but turn and point to my camera bag sitting inside the opening of a car."
m "\"I was filming for my project. This place is important to Echo's history.\""
ku "\"I see.\""
l "\"We could ask you the same thing!\""
ku "\"Well, I'm not exactly doing 'that' am I? Anyway, I just take walks sometimes on my days off.\""
m "\"In the middle of the day?\""
ku "\"Usually.\""
show Kudzu with dis
"He narrows his eyes at me, clearly thinking that I'm suspicious about something so I quickly add:"
m "\"I mean, it just gets so hot out here at this time of day. I'd die.\""
"Kudzu shrugs his shoulders nonchalantly."
ku "\"I dunno. I go for walks a lot. That's what I was doing last night when I found you two.\""
show Leo with dis
l "\"Hey, thanks for stepping in last night. That could have ended badly...\""
"Kudzu shrugs again."
ku "\"It would have. Had to do something, didn't I?\""
l "\"Well, we appreciate it.\""
stop music fadeout 3.0
"Leo wraps an arm around me and hugs."
show Leo Neutral with dis
l "\"So, uh, how was he when he came to?\""
play music "quiet.ogg" fadein 5.0
ku "\"Pissed, obviously.\""
l "\"He always is.\""
show Kudzu Depressed with dis
ku "\"But...he said some things last night. You should stay away from him for a while.\""
"Kudzu's normally placid face shows some concern for the first time."
show Leo Questioning with dis
l "\"What, he say he was gonna kill me?\""
"Leo says it lightly, like it's not a big deal."
ku "\"Among other things.\""
show Kudzu with dis
"His eyes flick to me."
"I give a start."
m "\"What?\""
show Leo Annoyed with dis
l "\"Whoa, wait, did he say some shit about Chase?\""
"Leo's hackles rise, and I can seem him starting to bare his teeth."
ku "\"Again, he was on something last night. He might not even remember it, but I'm just warning you to be careful around him from now on.\""
"Kudzu looks back at Leo."
ku "\"Don't provoke him.\""
l "\"I wouldn't if he wasn't such a fucking asshat.\""
ku "\"Just ignore him.\""
l "\"I swear to God, if he talked about doing shit to Chase...\""
"His grip tightens even more around me."
m "\"Hey, I'll be gone in a few days, don't worry about me...I am worried about you.\""
l "\"I'm just getting really tired of that meth-skeleton messing with everything I do. And if he fucking tries something with you—\""
ku "\"Leo...\""
"The air is tense and I can feel Leo growling deep in his throat."
"Wanting to change the subject, I speak up."
stop music fadeout 5.0
show Leo Neutral with dis
m "\"Um, hey, Kudzu! You know we were gonna go out to the park and hang out. Did you want to come?\""
show Kudzu with dis
ku "\"Thanks, but I think I'm good.\""
show Leo with dis
"Leo perks up from his brooding."
l "\"You know what? I think that's a good idea. We were gonna play some soccer, but there's only gonna be three of us. You could help even it out.\""
"Kudzu thinks."
ku "\"Hmm, well, I suppose I could use a work out.\""
l "\"Hah! You're just like TJ. I think you guys'll get along great!\""
"I don't really see TJ and Kudzu getting along just because they're fitness conscious. They're practically night and day."
l "\"Well, we're heading out right about now. You gonna come?\""
"Kudzu hesitates for a second longer before he nods his head in a quick jerk."
ku "\"Alright, yeah, why not?\""
"And with that I gather up my equipment and we head back to Leo's house."
stop loop fadeout 3.0
scene bg route93 with fade
play background "highway.ogg" fadein 3.0
"It's not surprising that Echo hardly has an inch of flat grass in the entire town."
"Leo says they're planning to lay down sod next to the lake when the area is further developed, but as of now we have to settle for a park near Payton."
"It's a plain stretch of grass, usually used for youth soccer games."
"In fact, I can remember when I was part of that same organization, back when my stubby legs didn't matter as much."
"Of course, after a few years it became clear that, being an otter, I wasn't built for the sport."
"That's when I took up swimming (of course) but then I realized that I wasn't really great at that, either."
"Of course, I could out swim any non-aquatic, but when it came to the other otters, I was pretty much bottom of the barrel."
"As we drive TJ sighs next to me."
scene bg field
"I look over at him and he's got his elbow against the arm rest, staring out the window as we pull into the empty parking lot."
m "\"Everything alright?\""
"TJ's ears perk and he looks over at me, clearly forcing a smile."
t "\"Of course!\""
m "\"You don't seem that way. What's up?\""
"I lean closer to him."
"Leo's talking to Kudzu in the front, so we have some amount of privacy."
"TJ looks down at his lap for a moment, then just shrugs."
t "\"I think it's pretty obvious, Chase. This whole trip has been pretty...pretty bad.\""
"I'm about to counter that it hasn't been that bad, but he goes on."
t "\"I just think it might have been best if I hadn't come...I feel bad, is all.\""
"The way he tries not to frown, but does anyway, is both heartbreaking and adorable at the same time."
"I automatically rest a paw on his shoulder reassuringly."
m "\"Shi—stuff happens, right? We came here to have fun, and that's what we're doing right now.\""
t "\"Yeah. It's just that I feel bad for everyone else. What happened yesterday, I think it affected everyone.\""
m "\"No way! I had a great time with Leo yesterday. Wasn't sad at all.\""
"I realize that that statement makes me look like a total asshat, but TJ just nods as Leo parks the car."
stop background fadeout 3.0
l "\"We're here!\""
scene bg field2 with dissolve
play music "carefree.ogg" fadein 5.0
"As we reach the field Kudzu immediately starts jogging the length of it while TJ stretches."
"I stand there awkwardly for a second, not really sure if I should join them since that felt a little overboard for something so casual."
"At least I hope it's casual."
"Leo rests the soccer ball against his hip as he joins me."
show Leo at center with dissolve
l "\"Heh, they're so eager, huh?\""
m "\"Apparently.\""
l "\"Well, it's not a bad idea. Don't want to pull anything.\""
"So me and Leo do a few awkward stretches before the other two join us in the middle of the field."
l "\"So! Time to pick teams!"
show Kudzu at right with dissolve
ku "\"There's only four of us. Shouldn't be too hard.\""
l "\"You wanna pick?\""
"Kudzu looks between us before his eyes settle on me."
ku "\"Chase.\""
m "\"Oh, okay.\""
show Kudzu Wry with dis
ku "\"Probably best to keep the lovers off the same team to avoid distraction. I at least want a little bit of a challenge.\""
"Kudzu gives Leo a little smirk."
show Leo Wry with dis
"I blush, but Leo smiles easily, rolling his eyes."
l "\"It's not like that.\""
ku "\"Mhm, sure.\""
show TJ at farleft with dissolve
t "\"Sooo, I'm on Leo's team?\""
"TJ sidles up to Leo's side and the wolf puts an arm around his shoulders."
l "\"Yep! You're lucky to have me. You know, in my country we had a war over soccer once.\""
ku "\"I don't believe you.\""
l "\"It's true! Thousands died in the Fútbol War!\""
m "\"Wait, do you call it football? Because that seems pretty confusing since you're really into the other football.\""
l "\"I live here now, so fútbol is soccer and football is football. But if I were to call soccer football, I'd call it fútbol.\""
show TJ Neutral with dis
t "\"Wait, what?\""
show Leo Embarassed with dis
l "\"Puchica...let's just start.\""
"Kudzu looks around."
ku "\"Since there's so few of us why don't we just play half field? Grab a few rocks to mark the goal.\""
scene bg field2 with dissolve
"After that's done we start playing and, for me, it's pretty much a disaster."
"TJ, of course, dominates all of us."
"He dodges around me with ease, making me look like an idiot as I spin around trying to catch him, falling on my ass more than once."
"Kudzu is able to hold his own for the most part, but TJ gets it past him without much difficulty."
"I think the lynx realizes how badly he's beating us after a while and starts to ease off."
"He passes it to Leo more often and only really steps in when we get near the goal."
"Leo, while big, is slow as hell and I actually manage to steal the ball from him a few times."
"I also think it's because he's not taking this seriously at all because he keeps laughing and slapping me with his tail when I run past."
"At one point, with the score at like, 7-0, I manage to get near the goal."
"TJ jogs in as I kick the ball clumsily and it's so clear that he misses on purpose that everyone busts out laughing as it rolls into the net."
"TJ frowns."
show TJ at center with dissolve
t "\"What? That was a great kick, Chase.\""
"I lean over, resting my hands on my knees as I gasp for breath."
m "\"If you're gonna let me score you HAVE to make it look more convincing than that, man...also, I'm not five, I can handle getting my ass kicked.\""
show TJ Sheepish with dis
$ renpy.pause(0.3, hard=False)
hide TJ with dissolve
"After a while we switch up teams with TJ on my side and Kudzu and Leo together."
"It's a bit more even after that, with me being TJ's handicap and all."
stop music fadeout 5.0
"After about half an hour we call it quits and head back to the parking lot where Leo throws us water bottles."
scene field with dissolve
play loop "reststop.ogg" fadein 3.0
"I wipe my face as I sit on one of the parking blocks."
"Even though it's early evening the weather is still waaay too damn hot."
"Leo and TJ are already up again, TJ showing him some of the moves he had so viciously used on me."
"I'm glad to see that TJ is somewhat happy again. His ears are up and he's smiling as he runs circles around Leo."
l "\"'Ey! How am I supposed to learn anything if you're just using them on me? Just trying to make me look dumb, eh?\""
t "\"Sorry, sorry! Alright, first thing you need to do...\""
"I notice Kudzu standing a few feet away, watching along with me."
m "\"So I guess you've known Leo since you moved to Echo?\""
"Kudzu looks over at me before leaning back against Leo's van."
show Kudzu at center with dissolve
ku "\"Yeah. He saw me moving in and insisted on helping, so that's how I met him.\""
m "\"Sounds like Leo.\""
"Kudzu takes a swig from his water bottle."
ku "\"He's a good guy.\""
m "\"Definitely...so you used to live here, right? In Payton?\""
ku "\"Unfortunately. I guess Leo told you?\""
m "\"Yeah.\""
"I also remember Leo saying that some bad things had happened in the city for the raccoon, so I wonder if I should press or not."
m "\"Hey, sorry if it seemed like I was making fun of your name a few days ago...it's a cool name! Just different, you know?\""
show Kudzu Wry with dis
"Kudzu smirks."
ku "\"No, I know it's weird. You just caught me at a bad time, is all.\""
"I spread my legs out, sighing as my knees pop."
m "\"Uuugh, I'm not built for running around.\""
ku "\"Well yeah, you're built for swimming.\""
"I raise my eyebrows at his bluntness."
"It's not really a speciesist thing to say, but most people don't often point out a species' aptitude."
m "\"Um, so I guess I wonder why you'd move to Echo. It's such a dump.\""
show Kudzu with dis
"Kudzu's silent for a while."
"In the meantime we watch Leo fall on his ass after TJ kicks the ball between his legs."
ku "\"People.\""
m "\"Huh?\""
ku "\"People are the reason why I left Payton.\""
m "\"Oh.\""
"Payton is technically a small city with just 70,000 people."
"Compared to Pueblo, that's nothing."
ku "\"The more people there are the worse it is. It's the same anywhere.\""
m "\"Ah, okay.\""
"Kudzu goes on."
ku "\"Sure, in Echo there's a hundred shitty people...but in Payton there's fifty thousand of them. I prefer Echo.\""
"His tone is so dark at this point that I don't even respond."
"Something definitely happened here in Payton and I don't dare ask what it was."
"Luckily I'm saved an awkward silence as Leo haphazardly kicks the ball in our direction and TJ comes running up to us.\""
l "\"Dammit! Alright I think that's enough for today.\""
"He jogs over, wiping his face."
show Leo at left behind Kudzu with dissolve
l "\"Man, I need a shower. You two getting along?\""
"When Kudzu doesn't saying anything I pipe up."
m "\"Yep!\""
show Leo Neutral with dis
"Leo frowns, clearly sensing something's wrong."
l "\"Well, okay...Anyway, let's go out and get some ice cream. I've really been craving it."
"I stand up slowly, knees popping again as we all pile into the car."
scene bg route93 with fade
stop loop fadeout 3.0
play background "highway.ogg" fadein 3.0
"As we drive TJ continues to stare out the window, but his ears are up and he doesn't seem so depressed anymore."
"I lean over towards him."
m "\"You feeling better?\""
"TJ turns to look at me, smiling."
t "\"Yeah, it was fun playing with you guys.\""
"I grin."
m "\"You're insanely good.\""
"He shakes his head."
t "\"Not compared to the other guys at school. I'm not...aggressive enough, but it's fun.\""
m "\"Well, I'm glad you're feeling better.\""
"TJ nods."
t "\"It's too bad we can't come back and do it again tomorrow.\""
m "\"Hm? Why not?\""
"Not that I'm crazy about doing it again, but I'm not sure what would prevent it."
"He looks at me."
t "\"Well, your project.\""
"I frown."
m "\"I don't think—\""
l "\"Hey! What flavor do you guys want?\""
"Leo practically shouts back at us."
"I look around; we aren't even at the ice cream parlor yet."
"That doesn't seem to matter to TJ, though."
t "\"Oh! Cookie dough! It's been so long since I've had it.\""
l "\"Really? I didn't know you liked that flavor.\""
stop background fadeout 3.0
"And somehow Leo's able to keep up the conversation about ice cream flavors all the way to the actual ice cream parlor."

play background "eveningcall.ogg" fadein 5.0
scene bg railyardevening with slow_dissolve
"I decide the shots I got earlier in the day were too bright, not representative of the sad state of the town that I wanted."
"The setting sun does a better job of capturing the desolation, and bittersweet depression of it all. A metaphor for an end, in a way."
"At least, that's how I hope it comes across."
"I lean back against the old, rusted car, clicking through the images I'd taken."
"It feels very quiet, despite the wildlife around me."
"And so that's why it's easy for me to pick out the footsteps headed in my direction."
play loop "trailsteps.ogg"
"At first I think it's Leo and I wonder how he's finished up with his shower so quickly."
"But then I realize that the crunch of dried vegetation is too soft, too light to be Leo."
show Clint with dissolve
"I look up, kind of hoping to see Kudzu, but instead I'm greeted with the sight of Clint headed in my direction."
"My grip tightens on the camera, watching as he approaches around the bend of the tracks."
stop loop fadeout 3.0
"He doesn't see me at first. As he gets to the tracks he hops onto one of the metal rails and balances there, walking along like he's on a tightrope."
"Does everyone in Echo just come here to take a walk?"
"I think about walking around the train car, out of his line of sight and hide until he passes me."
"While I'm thinking this, he loses his balance and stumbles off the rail and that's when he looks up."
"Of course, I'm the first thing he sees and we both just sort of stand there, watching each other."
"I don't know what to do. Kud said Clint probably didn't remember anything from last night, but I'm not willing to bet on it."
"It does look like he's not even sure who I am, though."
"His eyes are squinted almost shut, mouth all screwed up as he scratches his head comically."
"He leans forward, almost to the point of falling over again."
"Definitely on something."
show Clint Smirk with dis
"At that moment a look of recognition spreads across his face and his mouth opens wide."
play sound "steps.ogg"
"Then he starts jogging straight for me."
"The abruptness of his movements startle me and I almost drop the camera."
"I angle myself away from the car so I'm not backed up against it and start taking steps back as he gets closer."
"He stops, though, about ten feet away and points at me."
cl "\"Hey! I know yoouuu!\""
m "\"Uh...\""
"I'm at a loss for what to say."
"He's wobbling back and forth, his eyes wide open."
cl "\"Your name!\""
"There's an awkward pause as I try to determine whether or not he's asking a question."
m "\"M—my name? Chase?\""
"Why did I tell him that?"
cl "\"You're Leo's fag friend!\""
m "\"Uh...\""
stop background fadeout 5.0
play music "quiet.ogg"
"I'm distracted again because that's when I see the handle of a pistol just poking out from the front of the waistband of Clint's jeans."
"Clint glares."
cl "\"Fuckin' Leo...why do you hang out with that creep?\""
m "\"I, uh...\""
"I'm looking around, trying to decide the best way of escape in case he loses it."
cl "\"I mean, he's always saying shit to me, always saying shit about my dad...he had a perfect fucking life and rubs it in my goddamn face!\""
"I take a few, innocuous steps back so that the end of the car is right next to me, in case I have to duck behind it."
m "\"I—I don't think Leo's life was that easy. It was pretty bad back in his country—\""
cl "\"Fuckin' beaner comin' here to make my fuckin' life even worse!\""
cl "\"Couldn't go home and be happy, couldn't go outside and be happy...I can't be happy anywhere!\""
"He sneers at me."
cl "\"And you. You fuck him, don't you?\""
"I just stare at him and don't say anything."
"I feel like anything I say could set him off, but he waits patiently, expecting an answer."
m "\"Clint...\""
cl "\"Don't you!?\""
"He shudders visibly, clenching his eyes shut."
cl "\"Fucking imagining you licking his fat ass is disgusting!\""
cl "\"I don't even fuckin' care that you're faggin' around...but with him.\""
"If I wasn't so afraid of the whole situation I probably would have laughed just then."
"I take another step back."
m "\"Hey, I was actually just about to head out. You know, I'm doing this project. That's why I'm here.\""
"He glares at me."
m "\"Me and Leo broke up a few years ago. We're just friends.\""
show Clint Nervous with dis
cl "\"You don't know what he's like. The things he did to me...it was way worse than what I ever did to you.\""
m "\"But hey, I do need to head out. We can talk about this later—\""
show Clint Smirk with dis
"He sees me stepping around the car and immediately his hand shoots to the handle of the gun."
stop music fadeout 2.0
play loop "eveningcall.ogg"
cl "\"Hey!\""
"I freeze, watching his hand, preparing to throw myself to the ground if he pulled it out."
"At the same time I'm praying that he'll shoot his dick off if he does."
"He glares at me."
cl "\"What the hell are you even doing out here anyway?\""
"With shaking hands, I point to the camera around my neck."
m "\"I—I told you. I'm d—doing a project!\""
"I try to smile as I hold it up."
cl "\"Just about Echo? What the fuck is there to say about it?\""
"His hand loosens on the pistol and I manage to steady my voice enough to actually speak."
m "\"Well...there's a history to it, you know. There's history to everything. I'm just trying to figure it out.\""
show Clint with dis
"Clint looks around, seeming to forget about his gun."
cl "\"Oh like—like this railroad?\""
m "\"Yeah...like this railroad.\""
"Clint's eyes are vacant as he stares at the ground and I think about making a run for it again."
cl "\"Oh!\""
"I jump as he snaps his head up."
cl "\"My dad once told me that his dad knew a guy that got killed here back in like, the 50s.\""
m "\"Oh?\""
"Despite the fact that there's a crazy meth head in front of me with a gun, I still find myself becoming interested."
cl "\"Yeah, like, some guy was trying to hop on one. Like way back then that's how people would get around.\""
cl "\"So this guy was trying to hop on this train here when it was leavin' the station, but he missed jumping on.\""
"Clint sits down in the dry and dusty weeds and spreads his legs out over the rails."
cl "\"And he falls down like this...and it runs over his legs!\""
"Clint brings both hands down in chopping motions over his thighs."
cl "\"Blood goes everywhere and yeah, he's dead, right?\""
"He looks up at me and I realize he's actually waiting for an answer."
"I guess his questions are never rhetorical."
m "\"Uh, I'd assume so...right?\""
show Clint Smirk with dis
cl "\"Wrong! They found him a few hours later and, somehow, the fucker's still alive!\""
m "\"Oh.\""
"I'm already starting to doubt this story, or at least this version of it."
cl "\"The stumps is packed with dirt so he stopped the bleedin' but he's gone crazy by now.\""
cl "\"He's goin' on about some creature that came to him and spoke whispers in his ear.\""
"Well, at the very least I can just stick this story somewhere slow in the project to keep things somewhat interesting."
"One of those local urban legends type stuff."
cl "\"But then he goes to the hospital and they think he's gonna live, but he jumps out the fucking window and kills himself!\""
"Clint stands up and brushes himself off."
show Clint Nervous with dis
cl "\"My dad used to tell me that story a lot...not like I wanted to hear it, but he liked tellin' me things I didn't wanna hear.\""
"I don't quite know what to say to that, but I want to keep on his good side so I make a show of pulling a notebook out of my bag."
m "\"Well thanks, Clint, that actually helps me out a lot!\""
"But Clint is still off in his own world, staring off at some trees in the distance."
cl "\"It's weird that you needed to hear that story because I come here because of it.\""
m "\"For closure...or something?\""
cl "\"Because of that guy...Sometimes I think I see him when I'm all high. And I hear things here, too.\""
cl "\"It's scary, but I do it anyway 'cuz it's different. In this town, everything's always the same, but you can make it change if you want.\""
"At that point he starts walking again, off the tracks and towards that group of trees."
"I decidedly don't follow him, instead hurriedly making my way back to Leo's house."
stop loop fadeout 3.0

scene bg leokitchen with fade
"I have a lot of time to calm down on the walk back."
play music "neutral.ogg"
"Leo is splayed out on his couch, picking through a TV dinner on his lap."
show Leo at center with dissolve
l "\"There you are! I warmed one up for you, too, but it's probably cold by now.\""
m "\"That's alright, I'll just, uh, put it back in.\""
"Leo watches me as I head into the kitchen adjacent to the living room."
l "\"Hey, what's up?\""
"My dinner is sitting on the stove top and I make an effort not to wrinkle my nose at the sculpted \"rib\" meat covered in BBQ sauce."
"Watery mashed potatoes compliments the gooey mess."
m "\"Nothing. Just tired, is all.\""
play sound "microwave1.ogg"
"I toss the dinner back into the microwave and set the timer to two minutes."
play loop "microwave2.ogg" fadein 3.0
"As it's warming I turn back around to lean against the counter and face Leo in the living room."
m "\"Hey, I was wondering something.\""
l "\"Hm?\""
"Leo looks back up at me, ears falling back a little."
m "\"It's about Clint.\""
show Leo Neutral with dis
"Leo's brow furrows."
m "\"I mean, you guys are at each other's throats.\""
m "\"I know there's always been some...animosity between you two, but I don't remember it being this bad.\""
"I frown."
m "\"You guys practically want each other dead.\""
"Leo pins his ears back while he licks BBQ sauce off his fingers."
l "\"I really don't know, Chase. If I had to say, I think it would be the drugs.\""
m "\"The drugs?\""
l "\"Mhm. Whatever he's taking, it's pretty hardcore. I mean, he's a goddamn skeleton now, right?\""
m "\"Yeah...\""
l "\"But it's not like I'm responsible for it. I just treat him like he treats everyone else.\""
"I open my mouth, hesitate, then finally ask what's been bothering me."
m "\"When we were younger, would you say that you...bullied him?\""
show Leo Questioning with dis
"Leo frowns."
l "\"What's bringing all of this up?\""
m "\"Nothing. I'm just curious is all.\""
show Leo Neutral with dis
"Leo starts to smooth down the fur on his head, all poofed out from his shower."
l "\"I mean, I wasn't nice to him, of course, but he was an asshole to everyone else. Like I said; I did to him what he did to others.\""
"He coughs."
l "\"Maybe a little worse.\""
m "\"Worse? What he did to us was pretty bad, though. He tried to burn me with a cigarette once.\""
show Leo Annoyed with dis
l "\"See, when you tell me shit like that I don't feel bad for any of the things I did to his worthless ass.\""
stop loop fadeout 2.0
play sound "microwave3.ogg"
"I'm saved from having to respond to that as the timer goes off."
"I turn around to pull my food out of the microwave before grabbing a plastic fork and sitting down next to Leo."
show Leo Neutral with dis
"We eat in a slightly awkward silence."
"By the time I'm almost finished I'm feeling a little nauseous."
m "\"Ugh—not to be rude, but do you always eat this stuff?\""
l "\"Huh?\""
"He looks up with a mouth full of mashed potatoes."
m "\"This microwavable dinner stuff.\""
"He swallows loudly."
l "\"Yeah. You don't like it?\""
show Leo Embarassed with dis
"He lowers his ears again, looking embarrassed."
m "\"It's fine! I mean, it's just...sad?\""
"I look at him sheepishly."
l "\"Ha! You little fucker. I get better food sometimes. This is just easier.\""
m "\"Yeah.\""
"I drag a plastic fork through the flaky potatoes."
m "\"And what qualifies as better food? The diner?\""
l "\"Hey, it's not like I can't afford it. I make good money!\""
"I laugh."
m "\"This isn't about money. I just think you're lazy.\""
show Leo Wry with dis
"Leo mock growls and leans over to grab me."
"I yelp theatrically and try to hold my tray steady as he yanks me sideways to lay down against him, our heads on the armrest."
m "\"Hey! I gotta throw away my tray. It's full of gross TV dinner water.\""
"Leo nuzzles into my neck."
l "\"Mmmh, put it on the floor.\""
m "\"Ew, gross.\""
l "\"You can throw it away when I'm ready to get up.\""
m "\"Since when do you decide when I can or can't get up?\""
l "\"Since you decided to mouth off to me. Now you're the one that's gonna be cooking all of my meals and cleaning up my house, Chula.\""
"I shiver and he responds by spooning me tighter."
"Clearly Leo's gaged that I'm passed the point of resisting at this point in my little vacation and he's taking advantage of it."
l "\"{i}Estoy loco por ti{/i}.\""
"He rolls the \"R\" dramatically."
"Definitely taking advantage of it."
"We're both too tired to do anything more which is probably for the best and, within a few minutes, I've passed out."

jump leofriday
