label tjwednesday:
window hide
stop music fadeout 3.0
scene bg AllWednesday
with transition_fade
$ renpy.pause(3.0, hard=True)
scene bg motelfull
with dissolve
show Jenna at center with dissolve
play loop "shower.ogg" fadein 3.0
window show
j "\"Apparently no one can get in touch with him.\""
"Jenna leans back against the dresser, running a brush through the fur on her neck and head, still a little damp from the shower."
m "\"Did they try his landline? Maybe he just muted his phone. He sleeps in like, everyday.\""
"Jenna shrugs."
j "\"I'm gonna assume that they have.\""
m "\"So no one told him he was gonna have a party?\""
"Jenna turns around and leans towards the mirror above the dresser, brushing away loose fur."
j "\"It's a 'surprise' party, right?\""
m "\"I guess. It's just that it's not really his birthday.\""
"Jenna sighs."
j "\"It's just an excuse to do something in this shitty town.\""
"I see Jenna glance at the door to the bathroom, as if worried TJ can hear her curse, even with the shower running."
"I let out my own sigh."
m "\"Well, I'm sorry I dragged you here, Jenna. I thought it would be fun is all.\""
stop loop fadeout 3.0
"Jenna finishes whatever she's doing in the mirror and turns back around to face me."
play loop "showerfan.ogg" fadein 3.0
j "\"Hey, it's not the town I came to see. It was you guys.\""
m "\"Yeah, well, you don't seem very happy about that, either.\""
"Jenna frowns."
j "\"If I didn't want to be around you guys I'd have left by now. I have friends in Payton that could take me to the bus stop.\""
"I don't say anything, choosing to lean back on the bed and close my eyes, still tired from the fucked up dreams I had last night."
show Jenna Depressedhips with dis
j "\"Sorry, I'll stop complaining.\""
"I massage my forehead with one hand."
m "\"It's still the beginning of the week. We've got time to turn this around.\""
j "\"It's really just Flynn.\""
"I look over at her."
m "\"Is he coming?\""
show Jenna Neutralhips with dis
j "\"Yep. Leo said he had a talk with him, so...\""
m "\"I mean, Flynn gets over stuff pretty quick. I think it won't be awkward if we don't let it be.\""
"Jenna looks at the shower door, the sound of the dryer blowing loudly behind it."
j "\"It's not really Flynn that I'm worried about. The things he said to TJ—\""
"I rub my eyes."
m "\"If it gets to that point, me and Teej will just cut out early and go somewhere else, maybe Janice's place.\""
"I open my eyes to look at Jenna."
m "\"You going with us?\""
show Jenna Smilinghips with dis
"Jenna smirks at me."
j "\"I think I have some studying to do.\""
m "\"Oh, come on.\""
j "\"Anyway, what if Flynn has another—\""
"She immediately cuts herself off as the door suddenly cracks open."
"I see one of TJ's blue eyes looking through the opening."
"The eye widens and the door quickly closes again."
"Suddenly it swings back open and the lynx comes striding out in just his pants."
show TJ-noshirt-n at right with dissolve
t "\"'Scuse me, Jenna.\""
"Jenna moves over and TJ reaches into one of the drawers to pull out a polo shirt."
t "\"Forgot my shirt.\""
"He mumbles before turning back around and hurrying to the bathroom."
hide TJ-noshirt-n with dissolve
"I catch a glimpse of the insides of his ears which are bright red."
"The door snaps shut again."
"We both stare at the door a while before Jenna speaks up again."
stop loop fadeout 5.0
j "\"If Flynn can keep his mouth shut until the end of the week, then we just might be able to get through this.\""

scene echoroad
with fade
play background "highway.ogg" fadein 3.0
"I stare out the window as we roll down the dusty streets of Echo."
"Honestly, it doesn't look much worse off than how I left it."
"The roads might be a little worse, but I assume that's because they haven't done any maintenance since winter."
f "\"I'm regrettin' not lettin' him know we're comin'. You know? You'll be lucky if he even gets his ass out of bed.\""
l "\"We'll call him, then.\""
f "\"And what if he doesn't answer?\""
"Leo doesn't say anything, instead focusing back on the road. TJ fills the silence after a while."
t "\"Well, I don't think it's too weird. It's just like we're hanging out again. Nothing wrong with that.\""
f "\"Sure, but making it about Carl is just...weird. Maybe if his birthday was like, next week? Two weeks tops.\""
j "\"Oh hush, Flynn. It'll just be like we're hanging out. You acting weird about it isn't going to help anything.\""
"The car starts slowing down and I snap out of my daydreaming to look up, knowing that we definitely aren't at Carl's house yet."
stop background fadeout 5.0
play loop "engine.ogg" fadein 3.0
"That's when I see a round canine figure standing further up on the side of the road."
"She's standing in the dirt that separates the road and the field in front of a broken and rusted barbed wire fence."
l "\"I think that's Janice.\""
"I look over at Leo and he seems concerned, his brows furrowed as he careful steers the car right up next to the coyote."
"I can see why; she's crouched over, elbows on her knees, staring at the ground."
l "\"Roll down your window, Chase.\""
"I do as he says, struggling a little with the old crank handle."
f "\"The hell is she doing out here?\""
"We come to a stop next to the coyote, kicking up some dust."
l "\"I dunno...HEY!\""
"Leo leans over me and smiles out at Janice who's still looking at the ground."
l "\"Everything al—\""
"Leo's voice cuts off in a weird choking sound."
"I look at him, confused, then look back out the window and I can't help myself, but I gasp."
"It was hard to tell from the angle, and all the dust kicked up by the van, but now I can see that Janice has her pants down around her thighs..."
"...I can also see everything else."
"I sit back quickly and avert my eyes, looking out the windshield instead."
f "\"What the fuck.\""
j "\"Oh my God. Leo, keep going.\""
"Jenna whispers it, her voice strained."
l "\"Oh! Uh, sorry, uh—\""
"Leo stops talking and I chance a glance out the window again."
"Janice is looking at us now, and she's smiling."
"It's a weird smile because it isn't touching her eyes."
"It's unnerving."
"Leo stares back."
m "\"Leo, go.\""
"I hiss out the side of my mouth, staring out the windshield again. He seems reluctant to, though, looking concerned."
l "\"Janice, do you need some help?\""
"His tone is one you might use on a toddler...or a crazy person."
"I don't hear her say anything, except maybe a grunt. Leo bravely keeps trying, though."
l "\"We can give you a ri—\""
"Leo stops talking in time for me to hear a pattering sound."
"It's a sound I recognized well from back when I would take a piss on the dirt roads of Echo when no one was around."
"The van lurches forward, then resumes a smoother acceleration back onto the empty road."
f "\"Holy shit! What the fuck was that!?\""
l "\"I don't...\""
"Leo's frowning, looking as confused as I've ever seen him."
l "\"Should I—should I go back?\""
t "\"No!\""
"I look back and see TJ covering his face."
j "\"Maybe. She could be having some kind of psychotic episode.\""
f "\"Or maybe she just had to piss.\""
l "\"I don't think so. Did you see the way she looked at me?\""
m "\"She was probably just on somethin'. Isn't everyone?\""
l "\"No, she doesn't do stuff like that.\""
m "\"Well, maybe she does? You never know with people.\""
"Again, Leo doesn't say anything and neither does anyone else."
"I glance back at TJ who's sitting in the very back seat with Jenna."
"He's got his ears down, looking into his lap where he's fidgeting with his hands."
"I know he's probably thinking the same thing I am, which is that we're supposed to help Janice with her spring cleaning, or whatever."
"I want to ask him about it, but the dead silent van is making me feel like now isn't the best time."

stop loop fadeout 3.0
scene bg mansion with fade
show Flynn Annoyed at left with dissolve
play background "reststop.ogg" fadein 3.0
f "\"I fuckin' told ya!\""
"Leo stabs the doorbell again, frustration etched across his face."
m "\"Can you please keep the cursing down just a little bit?\""
"I can't help but notice TJ wince at every F-bomb."
"He's been keeping his distance from Flynn, always standing on the opposite side of our little group."
"I shift the bag I'm carrying around in my hands, trying to look through the frosted glass on the sides of the door."
m "\"Maybe he's getting high?\""
show Jenna at right with dissolve
j "\"He should still be able to hear.\""
m "\"I mean, maybe he just doesn't want to?\""
"TJ holds up his phone."
show TJ Neutral at center with dissolve
t "\"He's not answering his phone either.\""
play sound "knock.ogg"
"Leo knocks on the door hard, his bicep bulging."
j "\"Well, I guess breaking the door might get us inside.\""
"Leo stands back, paws on his waist as he takes a deep breath."
"He's determined."
"And I guess he should be considering he set all of this up."
hide Jenna
hide TJ
with dissolve
show Flynn Annoyed at center with moveinright
f "\"We shoulda just told him to meet us at the diner, or somethin'.\""
show Leo Questioning at farright with dissolve
l "\"Do they lock their windows?\""
show TJ Surprised at left with dissolve
t "\"What!?\""
show Leo Annoyed with dis
"Leo growls."
l "\"It's not like we're breaking in!\""
show TJ Rejected with dis
"TJ's ears pin back, a frown on his face."
"The wolf puts a paw to his forehead, closing his eyes."
show Leo Neutral with dis
l "\"Sorry, but I think he's just asleep and it shouldn't be too hard to just get in there and wake him up.\""
"I look over at the side of the house and see a window well."
"I point at it."
m "\"What about that?\""
l "\"Too small.\""
show Jenna at farright with dissolve
j "\"I could probably fit.\""
hide Jenna with dissolve
"She hops off the front porch and crouches down next to the window, pushing at it."
j "\"Wait, there's a security sticker here.\""
f "\"Well ya gotta arm it first and Carl's such a lazy ass I know he didn't.\""
f "\"'Sides, if we set it off we can just run. It's not like they'll show up anytime soon.\""
"Jenna hesitates, then pushes at the window again, but it doesn't budge."
j "\"Locked.\""
l "\"Let's try the one above it.\""
j "\"That's too high.\""
l "\"I'll boost you up.\""
t "\"I think this is going a little too far.\""
"Leo ignores him  and stands next to the window before making a platform for Jenna's foot with his paws."
"Steadying herself with her paws against the wall of the house, Leo easily lifts Jenna and she manages to grab the ledge."
f "\"Fuckin' hell, this is so fuckin' stupid.\""
"Flynn mutters next to me, but I ignore him."
"Jenna pushes against the window and it glides open easily."
l "\"Yes! Now I'm gonna boost you all the way up. Hold on.\""
j "\"Careful!\""
"Like they're some kind of cheerleading duo, Leo shoves Jenna all the way up with one paw and she disappears through the window."
"Her bush tail is the last thing we see...until she pokes her head back through."
j "\"Kitchen; I fell in the sink.\""
l "\"Great! Now unlock the door.\""
"She disappears again and we make our way back to the front door."
f "\"Leo, you're fucking crazy.\""
l "\"If you don't shut your fuckin' mouth Flynn I'll kick you right in your vag. Sound good?\""
f "\"Jesus, calm your—\""
"Leo turns on him, one foot in front of the other."
"Flynn shuts up."
"TJ's eyes are wide, even though he's staring down at the steps."
"I want to put my arm around him."
hide Flynn
hide Leo
hide TJ
with dissolve
"Finally, we hear the door rattling and it opens."
play sound "dooropen.ogg"
show Jenna Neutralhips at center with dissolve
j "\"Called his name but he didn't answer...\""
f "\"Well he's gotta be here. It's not like he can go anywhere...or would want to.\""
scene bg kitchen with dissolve
stop background fadeout 3.0
play music "quiet.ogg" fadein 3.0
"Carl's house is as massive and immaculate as I remember it."
"It is a mansion, after all."
"Well, maybe less immaculate than I remember."
"There are a few wrappers and pizza boxes on the marble counter."
"I assume that's because Carl's parents aren't here to tell him not to be a slob."
"Flynn immediately heads up the stairs."
f "\"Yo, Carl!\""
"I set the bag down on the table and TJ sets the cake there too."
"I look over at him."
m "\"You alright?\""
show TJ Neutral at center with dissolve
t "\"I'm good! Why?\""
m "\"Just asking. So...\""
"I rub the back of my head, trying to think of how to bring it up."
t "\"What is it?\""
m "\"Um, Janice.\""
t "\"Oh, yeah.\""
"TJ mirrors my pose, rubbing behind his own head."
t "\"I'm actually really worried about her.\""
m "\"I mean, should we still go?\""
"TJ looks at me, surprised."
t "\"Of course! Especially now. We need to make sure she's okay.\""
m "\"Oh, yeah, maybe we should.\""
"I actually don't feel like we need to do that at all considering she's probably just really, really high."
"I was going to suggest that we could at least postpone the visit until tomorrow so she had time to come down."
"But TJ's shock at my suggestion has me holding my tongue for now."
show Leo Annoyed at left behind TJ with dissolve
l "\"Chase, you check in the back! TJ, downstairs.\""
"Leo barks at us before hustling past toward the hallway."
hide Leo with dissolve
"We both look at each other before I shrug and head for the back door."
hide TJ with dissolve
"I stare out the glass window on the door for a while, wondering why Carl would even be out there."
"The old playset with the swings is gone, and so is the tree house that used to be in one of the two trees."
"The branch near the base of the tree that we used as a step has been cut away, too."
"Carl and I used to play up in that tree house all the time when we were younger."
"I open the door and step out onto the concrete steps."
scene bg backyard with dissolve
play loop "reststop.ogg" fadein 3.0
"I feel a pang of sadness seeing it gone. I had a lot of memories up there."
"I can remember the day when we started building it."
"I mean, Carl's dad had built the base of it, but left the rest up to us."
"Duke, the old weasel, had a pile of random junk in his backyard and he gave us permission to take from it as long as we cleaned it all up."
"I'd told TJ that if we cleaned up the pile, my dad would take us to the movies that night."
"We pretended to help clean up, even though we were just taking what we wanted for the tree house."
"We hauled it away in a wagon, telling TJ that we were taking it to the corner for recycling, or something, and that he should keep going."
"Of course, we didn't go back."
"I don't know why I thought we'd get away with that."
"Apparently TJ was there for three more hours before Duke came out and found out what had happened."
"I was grounded for the longest that I'd ever been."
"I cringe and close my eyes, face getting hot at the memory of being forced to apologize to TJ."
m "\"Fucking asshole.\""
"I mumble it to myself."
"We were especially cruel to TJ those couple of years."
"It was probably because of the age difference."
"Me and Carl had been 10, TJ was 8."
"For some reason, two years feels like two decades when you're that old."
"Still, there isn't really an excuse for how shitty I was to him."
"Even after that happened, we never let him up into the tree house."
"I was a real shitty kid, but I know TJ doesn't hold it against me."
"Still, the idea of taking advantage of TJ's trusting nature is just so...terrible."
"I sigh, giving the rest of the yard a cursory glance even though I know Carl's not out here."
"I'm a little worried, but I'm sure there's some sort of explanation for where he's gone."
scene bg kitchen with dissolve
stop music fadeout 5.0
stop loop fadeout 5.0
"I turn back around, deciding to help with the search inside."
"That's when I see a flash of a fat, orange and gray tail disappearing down the downstairs steps."
"I blink."
"Jenna walks past."
show Jenna at center with dissolve
j "\"I'm gonna go look in the garage. I don't think he's even in the house, though.\""
m "\"Okay.\""
hide Jenna with dissolve
"As Jenna heads for the garage door, I head for the stairs."
scene bg basement with dissolve
"The cool air wafting up from the dark hallway ahead of me is a marked contrast to the heat from outside."
"I fan out my shirt a bit as I look at the multiple doors lining the hallway."
"The only open one is at the end of the hall, though, and I can hear a low voice coming from it."
"It's Flynn's, for sure."
"As I pad up to the opening, I can start to make out what he's saying."
f "\"—but I just wanted you to know that I'm not mad at you...'Kay?\""
"I don't hear a response as I stand just outside the door."
"From here, all I can see is a few cardboard boxes and a neatly-made bed that probably hasn't been touched in years."
"A guest/storage room?"
f "\"Come on, man. I'm tryin'. I was mad yesterday and I shouldn't have fuckin' sent that.\""
"Flynn's voice comes from further into the room, on my left."
"I grit my teeth, wavering between going in now, or just hoping for the best and letting it play out."
t "\"I need to go...\""
f "\"I was just tryin' to figure out—\""
t "\"Don't—\""
"I hear some rustling in the room and that's when I realize that I have to step in."
"I hold on to the door frame as I poke my head in."
show TJ Depressed1 at left
show Flynn Annoyed at right
with dissolve
play music "loneliness.ogg"
"Flynn has TJ backed up against what looks like doors to a closet."
"TJ's cowering in the corner while Flynn has a hand on the lynx's shoulder, grabbing onto the fabric of his shirt."
"TJ's ears are pinned flat against his head and he's looking up at Flynn with a grimace."
"Then his eyes flick to mine as he notices me."
f "\"Let me talk for a sec—\""
"Flynn notices TJ staring over his shoulder and he jerks his head in my direction."
"The second he sees me, his hand drops away from TJ's shoulder."
"We stare at each other for a few seconds and I swallow loudly."
m "\"You guys find Carl?\""
"My question sounds all the more stupid in the dead silence that follows."
"Flynn's gaze drifts to the wall over TJ's head where he stares coldly for a few seconds, his jaw working furiously."
"I start to worry he's summoning up another one of his tantrums."
"Instead, after about five seconds, he turns on his heel and stalks out of the room."
"I have to move out of the way as he brushes past me."
hide Flynn with dissolve
"When I look back into the room TJ's already moved to stand in front of a mirror on the wall."
show TJ Depressed1 at center with  moveinright
"He straightens out his shirt, then vigorously combs the fur on his face."
"He does a weird back and forth on his cheek ruffs with one of his hands, even though they look fine to me."
m "\"TJ?\""
t "\"Hm!?\""
"TJ snaps his head in my direction, one of his ears twitching."
m "\"Are you...okay?\""
t "\"I'm okay!\""
"TJ says it fast and loud, giving his shirt one last tug."
t "\"Let's keep looking for Carl.\""
"He makes a point of looking around the room."
t "\"I don't think he's here!\""
"As he moves past me to leave the room, I grab his arm."
"He jumps and looks back at me, eyes wide."
"I quickly let him go, realizing just how closely I'm mimicking what Flynn had done just a minute ago."
m "\"Do you wanna ta—\""
t "\"No!\""
"I blink in surprise."
t "\"No, I don't want to talk about it...sorry.\""
"His ears are down again and he's looking at the floor."
t "\"Let's...let's just keep looking.\""
"He turns away again, but I feel like I should say something more."
"I want to make him feel better, get him away from Flynn."
stop music fadeout 10.0
m "\"Do you wanna go for a walk, or something?\""
"TJ turns back around to stare at me questioningly."
m "\"I mean, to keep looking for Carl. He's not in the house, so maybe he's gone out somewhere around town?\""
"TJ nods in understanding, the distressed look melting off his face."
show TJ Sheepish with dis
t "\"Ohh, that could be a good idea. We should tell Leo.\""
"I feel a surge of relief at having been able to distract TJ, and now I wanna keep that going."
scene bg kitchen with dissolve
"Luckily, we don't see Flynn on the way out."
"A distracted and frustrated Leo quickly waves us off as he continues his search in the ground floor bedrooms."
l "\"Probably got high and passed out somewhere.\""
"He mutters absent-mindedly as we head out the door."
scene bg flashback1 with dissolve
play music "oldwinds.ogg"
"I immediately realize what a bad idea it is when I step out into the sun."
"TJ, on the other hand, brightens up the second we step out of the mansion."
"That, at least, makes me feel a little bit better."
stop music fadeout 5.0
"We walk in silence for the first few minutes, looking at the rolling hills and mountains, cactus, and sage brush."
"It's one of those days where I'm not sure if the heat is worse coming from the sun above me, or the baking black asphalt under my feet."
stop music fadeout 5.0
play loop "reststop.ogg" fadein 3.0
show TJ at center with dissolve
play music "banter.ogg" fadein 3.0
t "\"How is school going for you?\""
"I blink out of my burning-alive-trance and try to focus on the question."
m "\"Oh, it's okay. Just kinda tedious, ya know?\""
"At the same time, I get a pang of panic realizing how much work still needed to be done on my project."
"I'm able to convince myself that I still have half the week...I'll figure something out."
m "\"What about you?\""
t "\"It's great!\""
m "\"Athletic training, right?\""
t "\"Yep!\""
m "\"So what exactly do you do, train people for sports?\""
"TJ laughs."
t "\"Well, it's more to do with injuries, recognizing them, preventing them, treating them if I can.\""
m "\"I didn't know that's what you do. So are you like a doctor, or something?\""
"He laughs again, but like always, TJ's able to do it in a way that you know he's not laughing at you."
t "\"Definitely not, that would be really hard. I guess you could say an athletic trainer is a healthcare professional.\""
m "\"Cool, cool.\""
"I try to keep from panting."
m "\"I thought...I thought you would have been more into like, coaching, or something. You like sports.\""
"TJ shakes his head."
t "\"No, I'd be terrible at that. I can't yell at people all day.\""
t "\"Is there even a degree for coaching?\""
m "\"I think most people that want to coach just get a teaching degree in history so they can 'teach'—\""
"I make air quotes."
m "\"—at a high school while also coaching. They 'teach to coach'.\""
t "\"Oh yeah, that's how it was at our school.\""
"I step an a particularly sharp rock and bite my lip to keep from yelping."
t "\"I really just wanted to do something involving athletics.\""
m "\"Do you like it, the whole athletic training thing?\""
t "\"Yeah! Well, it is my first year, so who knows, but I think I do.\""
m "\"So you just like helping people?\""
t "\"That, and I just like sports.\""
"TJ's quiet for a second."
t "\"It probably sounds silly, but it seems to make life seem more simple?\""
m "\"Sports?\""
t "\"Yeah, or exercising. There's a goal and something in your way like the other team, or a big hill—\""
"TJ kicks a pebble up from the ground and catches it on the top of his foot before launching it down the road."
t "\"—and your only job is to get around that to get to your goal.\""
"The lynx laughs."
t "\"I don't know if that makes any sense.\""
m "\"I think it does. I'm kind of like that with video games, I guess.\""
t "\"I can see that.\""
"I try to kick a pebble up onto the top of my foot like TJ did, but I end up just kicking it off the side of the road."
m "\"How did you do that?\""
t "\"Oh, I just got lucky that time; usually it doesn't work. I am on the soccer team, though.\""
"I think about how I didn't even bother trying out for my school's swim team for otters."
"I already knew how mediocre I was."
t "\"But I also just like being on the side of a field with all the cheering and lights. It's fun.\""
"As we continue down the road we walk past the charred foundations of an old trailer."
"While the brush has mostly grown back, scorched earth and black sage brush skeletons still remain."
stop music fadeout 5.0
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"At that moment my phone goes off and I pull it out, having to cup my hand over the top so I can see the screen under the bright sun."
"It's a text from Leo."
call text_chase("leo") from _call_text_chase_6
call text_0("", "Found him") from _call_text_0_6
#"\"Found him\""
""
m "\"Hey, they found Carl.\""
t "\"Oh! Where?\""
m "\"He didn't say, just that they found him.\""
t "\"Well that's great!\""
m "\"Yeah.\""
"I smile as a little ball of tension in my chest that I didn't even know was there dissipates."
call text("m", "Great! Where was he?") from _call_text_8
""
#"I send Leo a response asking where Carl was."
call text_end from _call_text_end_6
"I look back over my shoulder at the mansion resting at the base of the mountains, the distance and heat making it hazy."
"I really don't want to walk all the way back."
t "\"Maybe he just took a walk like us and got back?\""
m "\"Maybe.\""
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"My phone buzzes in my hand as I get another response from Leo."
call text_chase("leo") from _call_text_chase_7
call text_0("", "no party carl isnt feelin good") from _call_text_0_7
#"\"no party carl isnt feelin good\""
""
"I frown."
call text_end from _call_text_end_7
t "\"What?\""
m "\"Said Carl isn't feeling good so there's not gonna be a party?\""
show TJ Neutral with dis
t "\"Oh.\""
"TJ looks back at the mansion with me, airing out his shirt with both hands while he does."
"As much as it sucked for me to be under this sun, it's always worse for TJ with that thick fur."
"I copy him, airing out my own shirt, starting to feel self-conscious again about my musk."
t "\"Should we head back? I hope he's okay.\""
"I think about all the shitty tension going on back there and grimace."
m "\"I dunno. We could do something else?\""
"TJ appears to think, his hands on his hips."
"Then his face lights up."
show TJ with dis
t "\"Hey! Janice's house is right down the road. We can get a head start on the work.\""
m "\"Oh.\""
"I'd almost forgotten about that."
"While I'd definitely planned to go, I didn't want to now, under this heat."
"TJ jumps in place, like he's warming up for a game."
t "\"It'll feel good to do something after sitting around all day.\""
"I stare at TJ, absolutely baffled by his enthusiasm."
show TJ Sheepish with dis
t "\"What?\""
m "\"I mean.. well first of all, it's work. Second, aren't you worried about how she's gonna be when we get there?\""
"I stare down the road at the approximate spot where we'd seen her just an hour ago."
"She's not there now, obviously, but the memory still sends chills up my spine."
t "\"Well, I want to make sure that she's okay, too.\""
m "\"I dunno, we should give her at least a few hours to...recover.\""
"TJ stops bouncing and rubs his arm."
t "\"Sorry, um, if you don't want to I can just go...\""
"I glare at him."
m "\"Oh, don't guilt me.\""
t "\"I'm not! I just don't want you to be mad at me.\""
"I stretch, feeling sweat trickling down the sides of my face."
m "\"We could wait until evening, at least.\""
t "\"Ah, yeah, I guess we could do that.\""
"The disappointment on TJ's face is so obvious there's no way he's not doing it on purpose."
m "\"Okay, so what if she opens the door and she's still got her pants down?\""
"TJ blanches."
t "\"Chase!\""
m "\"I'm just saying, that's what could happen. There's no telling what she's on.\""
t "\"Janice isn't like that.\""
m "\"So maybe she was just having some sort of episode? Everyone's crazy here.\""
t "\"All the more reason to check on her.\""
"I rub my face."
m "\"Come ooooon.\""
t "\"It's fine! I can just go.\""
"TJ folds his arms and leans in closer."
t "\"Or maybe, you know, she just had to pee.\""
"He whispers the last few words like they're the worst cuss words in the world."
"I snort and close my eyes."
m "\"Fine.\""
"I wipe the back of my hand across my forehead."
m "\"But if I have a heatstroke, it's all on you.\""
t "\"Oh gosh, don't say that. If you feel dizzy, or sick, you're going inside.\""
"The thought of sitting inside with Janice while I cool down is almost as unbearable as the thought of manual labor."
"Still, TJ looks happy, which is worth it, I guess."
scene bg janicehouse with fade
play music "neutral.ogg" fadein 3.0
show Janice Happy at right with dissolve
ja "\"Well, I gotta say, I didn't expect you two down here this early!\""
"We follow the old coyote around the side of the house, weaving through sage brush and tumbleweeds."
ja "\"It's a bit hot right now, but if yer feelin' up to it!\""
show TJ at left with dissolve
t "\"Yeah, we just didn't have much else to do today.\""
"Janice, as far as I can tell, has been acting completely normal."
"I at least expected her to be embarrassed knowing what she'd done in front of us."
"Assuming she remembered it at all."
"I'm fine with not ever bringing it up again, though, and I'm sure TJ feels the same way."
"Once we reach the back of Janice's house, I'm amazed to see a pile of tumbleweeds maybe ten feet high against the house."
"The pile sticks out another five feet from the wall."
m "\"Whoa.\""
"Janice puts her hands on her hips, looking at the mess."
ja "\"Whoa is right. Been a few years since I got around to doin' this. Can't see out the back window anymore!\""
"Janice chuckles."
"TJ claps his hands and smiles."
t "\"This won't be hard at all!\""
"I feel like he's saying that for my sake."
"It's so hot, I just want to lay down and die right here in the dirt."
ja "\"Should be pretty quick! That's why I got another job...\""
"The corner of my eye twitches."
"Janice turns to point out towards her backyard."
"Or at least what would be her backyard if there was a fence or something to separate it from the wilderness beyond."
ja "\"See that pile 'o wood there?\""
"She indicates what is indeed a pile of old, crumbling wood."
ja "\"Used to be a shed there. Been there for God knows how long. You boys mind salvagin' the good bits for firewood?\""
"Janice turns back to the small, shack-like abode that is her house."
ja "\"You can pile it up against the side of the house.\""
"I give TJ the dirtiest look I can while he helplessly tries to keep a smile on for Janice."
"She shields her eyes against the sun."
ja "\"Wow, it's a real scorcher today. I'll have lemonade made in a few.\""
hide Janice with dissolve
"And with that, Janice heads back around the house, her heavy footsteps crunching through the brush."
"We're quiet for a few minutes, both staring at the pile of tumbleweeds."
show TJ at center with moveinright
t "\"She seems okay!\""
"I crouch in the dirt, putting my head in my hands."
t "\"I think she just had an embarrassing moment and acted awkward about it. I do it all the time!\""
"I don't say anything."
show TJ Neutral with dis
t "\"Chase, are you okay?\""
"I shake my head silently."
t "\"It's not that bad, we can do this!\""
"I sigh, deciding whether or not I'm actually gonna leave TJ then come back when it's not so hot."
play sound "pour2.mp3"
"That's when I hear running water."
show TJ with dis
"I look up and see a grinning TJ standing at the corner of the house, holding up a green hose."
"Water trickles out the metal-capped end."
t "\"Thought I forgot about you and water? Remember, every fifteen minutes at least!\""
"Despite my bad mood, I can't help but smile a little at his continued enthusiasm."
"I stand up and walk over to the hose, taking it from TJ and letting the icy water run over my head while he looks on approvingly."
"I have to keep myself from moaning at how good it feels."
"Once I'm done, I look back at the pile of tumbleweeds."
stop music fadeout 5.0
m "\"So what are we supposed to do with all these? She didn't tell us where to put them.\""
t "\"We'll just throw them off to the side. The wind will take care of them.\""
play music "comeover.ogg"
"So we set to work."
"Janice had at least left gloves for us so we didn't have to worry about anything sharp going through our hands."
"I still get poked through my shirt or even in the face if I pull one out awkwardly."
"TJ, I can't help but notice, is a lot faster than I am."
"He's working at a quick and steady pace, not caring at all when a tumbleweed hits him in the face."
"I get a few more messages from Leo asking where we are."
"When I tell him, he doesn't reply."
"Soon enough, I'm sweating buckets, dark circles forming under my arms and around my neck."
"Ten minutes in and I have to take off my shirt, letting it hang on a rusty metal outcrop under the window."
"I notice TJ giving me sidelong glances after I do."
"I grin at him."
m "\"What, enjoying the show?\""
show TJ Surprised with dis
"TJ jumps."
t "\"Wha—No!\""
show TJ Sheepish with dis
"TJ quickly looks away again, working faster than ever on the tumbleweeds which are already half gone at this point."
"I notice he's got the same sweat stain pattern as I did."
m "\"Hey, you can take yours off, too. It feels really good!\""
"TJ stops and pants for a while, staring at the rest of the tumbleweeds."
m "\"I mean, might as well do it now. We still have a ton of wood to move after this.\""
"He flicks his ears and I can see him blushing."
m "\"Are you embarrassed!? Don't you shower naked with other dudes at school?\""
t "\"Well yeah, but—\""
m "\"But what?\""
"TJ huffs and finally pulls his shirt off, forcing a smile as he goes over to hang it up next to mine."
"I notice that he does it with crossed arms, the way girls do."
hide TJ with dissolve
show TJn at center with dissolve
t "\"There, happy?\""
m "\"What's with you and being all weird about having your shirt off? You were the same way this morning.\""
"TJ sighs."
t "\"I was trying not to make it weird, but you two were just staring at me when I opened the door.\""
"I laugh and TJ puts his hands on his hips."
t "\"Just remember that when we're done we're going to have to check our torsos for ticks, too.\""
m "\"Oh, yeah...\""
"That dampens my spirits."
m "\"Man, this sucks.\""
"TJ pants quietly for a few seconds."
t "\"It is a little hot...\""
m "\"So you do admit this was a bad idea!\""
t "\"No! I mean, maybe? But at least we'll have the evening to do something once we finish, right?\""
"He smiles at me hopefully."
"That does brighten my mood a little."
m "\"Wanna go to the diner?\""
"TJ smiles before bending over towards the tumbleweeds again."
t "\"Yeah, sure, I was wanting to try the—AAAAAAAGGH!\""
show TJn Surprised with dis
with vpunch
stop music fadeout 5.0
"I jump a foot into the air, almost falling into the tumbleweeds."
t "\"Go, go, go!\""
hide TJn with dissolve
"TJ's off like a bullet, running away from the pile in my direction."
"Confused, I jump out of his way, then follow him around the side of the house as I look at where he'd been standing."
"I don't see anything, but his reaction is enough to get the fur standing up on the back of my neck."
"TJ comes to a stop toward the front of the house."
m "\"What the hell!? What happened?\""
"I finally catch up to him, panting under the heat."
"TJ's gasping, too, but probably more out of fear."
show TJn Surprised with dissolve
t "\"A.. tarantula.\""
"A reflexive shiver runs up my body and I wring my hands out."
m "\"No!\""
"I'm suddenly very conscious of everything around me, all the little twigs and branches of the sage brush looking like spiders."
m "\"Are you sure!?\""
t "\"Yes!\""
"TJ's voice is high pitched and squeaky as he shakes his hands."
"He's laughing to himself nervously."
t "\"I was reaching down for another one and when I touched it it moved and it was a giant, freaking spider!\""
"TJ must be really freaked out because I rarely hear him use even that word."
"We both stand there for a minute and TJ looks towards the back of the house again, biting his lip."
"There's something a bit off with the way he's acting, though. Maybe a little over-exaggerated?"
"I narrow my eyes."
m "\"Is this another prank?\""
t "\"Ha! No!\""
"TJ looks back at me and shakes his head, his eyes wide."
t "\"It was right there...it's probably still there now.\""
m "\"Dude, you better not be joking around with me on this, it's gonna make the rest of today sooo much worse.\""
"He shivers again, but I'm still suspicious. TJ could be a good actor when he wanted."
t "\"It was definitely a tarantula.\""
"The front door suddenly opens and Janice pokes her head out."
ja "\"Oh my stars! Who are these two handsome young men in my yard?\""
show TJn Surprised at left with easeoutleft
show Janice at farright with dissolve
"The old coyote comes out, looking us up and down, especially TJ."
show TJn Sheepish with dis
"The lynx notices and grips an arm with one of his hands, as if trying to cover up under her gaze."
ja "\"Mmh-mh! And what's with all that hollerin'?\""
"I frown at the old coyote's forwardness."
m "\"Um—\""
"I look at TJ, but he doesn't say anything."
m "\"TJ says he saw a tarantula...\""
"Janice claps a paw to the side of her face."
ja "\"Well I'll be darned. A blonde?\""
t "\"M—maybe? I've never seen one before.\""
ja "\"Well, they're all over around here, ya just never see 'em because they only come out at night.\""
"Janice shields her eyes again."
ja "\"This time a' day is way too hot for 'em. Was probably a huntsman.\""
"All this talk about spiders is making me want to just walk the fuck back to the motel right now."
t "\"It wasn't.\""
"TJ mumbles next to me, but I don't think Janice hears him."
ja "\"Just wanted to let you two know that I made some lemonade and I have some cookies in the oven, too!\""
"TJ forces a smile onto his face."
t "\"Aw, thank you, Janice!\""
"She grins at him."
ja "\"You are just the most adorable thing!\""
"She moves forward to pinch his cheek ruffs and somehow he manages to stay smiling while she does it."
hide Janice with dissolve
"Finally, Janice bustles back inside as I give TJ a long look."
show TJn Surprised with dis
"He throws his hands up in the air."
t "\"I'm not lying!\""
"I can see him turning red under his fur, so I leave it for now."

scene bg janicehouse with dissolve
"We look around for a while but can't find any trace of the spider."
"Getting back to work is difficult, and I keep jumping at the sight of anything long and spindly."
"Which, when you're clearing out tumbleweeds, is everything."
"On top of that, I see several smaller spiders and, every time I do, I jump and run a few steps away before I try to shoo them off."
"TJ recovers a lot faster, though, and pretty soon he's tossing out tumbleweeds at the same pace he was earlier."
"This makes me even more suspicious."
"Anyway, it's not a bad sight."
"TJ's way more in shape than I am, the tight muscles in his back easily standing out and gliding under the fur."
"I catch myself staring several times and I'm pretty sure he does, too."
"Once we're almost finished, I have to straighten up, pushing my hands into my lower back to make it crack."
show TJ-noshirt-n with dissolve
play music "neutral.ogg" fadein 3.0
t "\"Sore?\""
m "\"A little bit.\""
"TJ tosses out one of the last tumbleweeds before walking up to my side."
t "\"Does it always hurt?\""
"He puts a hand on my lower back and starts sliding it around."
m "\"Um, not really? Just when I'm bending over and stuff.\""
"He's quiet for a moment, teasing through the fur on my back."
"I start to blush, but that's when he applies some pressure to a muscle."
"I grimace and arch."
t "\"Wow, that's stiff!\""
"I hiss and try to writhe away, but he puts a hand on my shoulder to hold me in place."
"He giggles."
t "\"Hold still for a second.\""
m "\"Well, when you're digging in like that—\""
t "\"That's because you're all tensed up. Just relax.\""
"I try to do as he says, even though it's extremely uncomfortable."
t "\"So otters are known for having bad backs.\""
m "\"I know. My dad can barely move these days.\""
t "\"That's terrible.\""
"I shrug."
m "\"He still gets around. Just needs pain meds.\""
t "\"Which you don't want to have to rely on.\""
"My shoulder bumps TJ's chest and his long whiskers brush my ear."
t "\"It's the short legs and long back.\""
m "\"Rude.\""
t "\"You have to bend over more than most of us. Keep a good posture, and lift heavy things with your knees.\""
"His fingers dance a bit lower before pulling back."
t "\"You'll thank yourself twenty years from now when you're not in constant pain.\""
"I put both my hands on my back, feeling warm and a lot more loose."
m "\"Hey, I actually do feel a little better.\""
t "\"Great!\""
"I'm impressed with how much TJ knows about otters. He probably knows the same amount about all the other species, too."
m "\"You know, you're really smart.\""
"TJ ducks his head modestly."
t "\"Oh, I'm just repeating what I've learned.\""
m "\"I mean, I forget everything I learned within a week.\""
t "\"I do too, sometimes. Just have to keep studying until it sticks.\""
"TJ looks around."
t "\"Actually, I really wish you could lay down somewhere. Then I could give you a real massage.\""
m "\"That would be amazing.\""
t "\"I could give you one tonight when we're back at the motel!\""
m "\"You sure?\""
"The thought has me feeling warm, and not just in my back."
t "\"Of course! I mean, I did sort of drag you out here...\""
m "\"Don't worry about it! It's actually kind of nice. Haven't done work like this in a few years.\""
"TJ smiles back at me."
t "\"It is, isn't it?\""
"He leans back and stretches and I have to force myself not to stare at his arching torso."
t "\"I think that's it for the tumbleweeds, though.\""
"I look a little forlornly at the pile of boards."
"TJ follows my gaze and gives me a sympathetic smile."
t "\"Remember, with the knees!\""
"TJ says brightly as he marches over to the pile."
hide TJ-noshirt-n with dissolve
stop music fadeout 3.0
"We find out pretty quickly that, while there aren't any tarantulas, the ruins of the shed are infested with spiders."
"Several of them black widows."
"Because those are actually dangerous compared to blondes, TJ goes in to ask Janice for bug spray."
"I go back to water myself again with the hose, letting the freezing water run down the sides of my head and off my snout."
m "\"Fucking spiders. Fucking everywhere.\""
"I shiver again."
"I've been uptight ever since TJ had (faked?) seeing that tarantula."
"I stand back up, letting the water run down my back and front, sighing at how good it feels."
"I hear the front door open and shut and the sound of TJ's footsteps coming around the house."
"Looking back down at still-running hose in my hand, I smirk."
"TJ did start this little prank war, so I don't feel too bad for what I'm about to do."
"I press myself up against the side of the house (making sure there aren't any spiders first)."
"The second I see the lynx's foot stick out from around the corner I swing the hose up."
"My original intention had been to wet the front of his pants so that it looked like he pissed himself."
"Unfortunately, he's too far away from the house and instead he's left staring at me while an arch of water falls short of him by a good three feet."
"He's holding stuff, but I don't take the time to see what it is before I press my thumb to the opening of the hose and send a spray straight into TJ's face."
play sound "pour.mp3"
"TJ gasps like he just fell into ice water and stumbles back, almost tripping."
"I laugh."
stop loop fadeout 5.0
play music "TJtheme.ogg"
t "\"Chase! What the heck!?\""
"I finally cut the stream of water, revealing a furiously blinking and dripping lynx."
"In one hand is a broom and in the other is a plate of what probably used be cookies."
"They look kind of mushy now."
m "\"Aw, crap.\""
"TJ drops the broom to examine his plate of cookies."
"He tips it to the side and lets a stream of murky, crumb-filled water slosh out from the plate."
t "\"They smelled so good, too...\""
"I walk over and take the plate from him."
m "\"Well, the ones on the top aren't so bad, just a little soggy.\""
"TJ wrinkles his nose."
t "\"Just throw them out into the desert. I'd feel bad if Janice saw.\""
"I pick up a cookie and take a bite. It is a bit soggy on the surface, but it's warm and gooey in the center."
m "\"Mmmmh.\""
"TJ looks at me in horror."
t "\"Chase!\""
m "\"What? This tastes freakin' amazing. Quit being so uptight and take a bite.\""
"I take another."
t "\"Stop! What if that's irrigation water?\""
"That makes me pause for a second, but I shrug."
m "\"I swallowed water all the time when I swam in the lake.\""
"I wonder right after I say that if I shouldn't be mentioning the lake at all around TJ, but he just shakes his head, making his way around me."
show TJn Rejected with dissolve
t "\"If you start throwing up tonight then we'll know why.\""
m "\"But I'll have you to take care of me, doctor.\""
t "\"I don't know much about actually being sick.\""
"He watches me anxiously as I take another bite."
m "\"Still, it really is good.\""
"I point at the broom in the dirt."
m "\"What's with the broom?\""
"TJ bends down to pick it up."
t "\"Janice didn't have any bug spray, so she said to brush off the boards with this.\""
"I groan."
t "\"I was thinking you could do the brushing and I'll do the lifting since your back is sore.\""
"I groan."
t "\"Don't worry. Janice says if we get bit to let her know so she can take us to the hospital.\""
m "\"Comforting.\""
t "\"Yeah...listen, I'm sorry about all this. I didn't know it was gonna be so tough on you.\""
"I swallow guiltily."
m "\"I'm mostly joking. It's really just how spider-y it is that's the worst part.\""
t "\"I'll buy at the diner when we're finished, okay?\""
"I smile at him."
"I'm not hurting for money at all, but I know it'll make TJ feel better if I let him."
m "\"Alright, that's a deal.\""
scene bg janicehouseafternoon with dissolve
"It's afternoon at this point, the sun low enough that Janice's house is casting a shadow across the backyard."
"Of course, that shadow is a good few feet away from where we're working."
"I set to work trying to sweep away spiders, their egg sacs, and all kinds of other bugs while TJ grabs the big boards and drags them across the yard."
"I'm pretty bad at it, trying not to yelp while I jerk the end of the broom back and forth like an idiot."
"TJ tells me several times that I can sit it out, but I'd feel way too guilty if I did."
"At one point, I almost flick a spider onto TJ which sends him screaming."
"But several apologies and nervous laughs later, we're back at it."
"It takes a lot longer than it should, mainly because of all the sweeping I'm doing, but a few hours later we're down to the last few boards."
"Most of what's left is rotting, crumbling wood."
"TJ wipes a hand across his forehead."
show TJ Neutral at center with dissolve
t "\"Well, I'd say this is the last one.\""
"I give the board a cursory brush, happy to not see any spiders on this one."
m "\"Hey, I was thinking; you wanna go on another hike tomorrow? We could invite the others to go with us.\""
"TJ looks up at me."
t "\"You sure? I thought you didn't like it.\""
m "\"Again, I complain a lot. I had fun.\""
show TJ with dis
"TJ smiles."
t "\"Well alright, that'd be awesome!\""
"He's grinning, now, and that makes me feel even better."
t "\"Alright, let's get this done and we can go to the diner and plan it out.\""
m "\"Sounds like a plan.\""
"With that, TJ flips the board and reveals a massive tarantula."
stop music fadeout 2.0
"Eight beady black eyes reflect the sun and soon I'm almost blinded by it."
"They bore into me and the spider turns slowly, crab-like on its legs, so it can face me."
"My stomach turns and the ground tilts."
"I feel like I'm falling off the edge of the world."
"I grab for something, anything, but all there is is air around me, and I fall into the darkness."
scene bg black with dissolve
unk "\"Just count when the shoulders are down, alright?\""
scene bg fb5 with slow_dissolve
play music "eveningcall.ogg" fadein 3.0
"I feel like water's rushing through my ears and I have to widen my stance to keep from falling."
unk "\"Are you listening?\""
m "\"Huh?\""
unk "\"Chaaaaaase.\""
m "\"What?\""
"I try to focus on the kid in front of me."
show Young_Sydney_casual Worried_arm with dissolve
sy "\"Did you die, or something?\""
m "\"I dunno, I was just thinking of something else.\""
show Young_Sydney_casual with dis
sy "\"Ha, you're dumb.\""
m "\"You're dumb.\""
t "\"I don't feel good.\""
show Young_Sydney_casual at right with easeoutright
show Young_TJ Sad at left with dissolve
"Toby stands there with his arms around his stomach, his ears down."
sy "\"Quit being a baby, Toby. Just one more round!\""
t "\"I don't want—\""
sy "\"Go!\""
hide Young_Sydney_casual
hide Young_TJ
with dissolve
"Sydney grabs Toby by the shoulders and sticks a leg out behind his legs."
play sound "bodyfall.ogg"
scene bg fb5 with hpunch
"TJ is easily tripped and goes down on his back in the dirt."
"I get the feeling that the lynx is purposely losing so he can be done with it."
"Sydney doesn't like that and tries to pull TJ back up before rolling the lynx onto his stomach."
"He yanks on Toby's ears."
t "\"OW!\""
"I step closer."
m "\"Okay! Sydney wins!\""
"I raise a hand and point it at Sydney, just wanting this to stop."
"Sydney keeps going and grabs his shirt that he'd thrown on the ground earlier and wraps it around Toby's neck."
m "\"Sydney!\""
sy "\"Hardcore rules! It's all legal!\""
m "\"Come on...\""
"Toby grabs at his neck and his eyes widen as Sydney leans back, pulling Toby's head back with him."
"The lynx's arms flail around, his mouth wide open."
"I stand there, confused. Is it okay if it's not against the rules?"
"Sydney laughs and leans even further back, looking excited and happy."
"Toby stares at me with wide, bulging eyes."
stop music

scene bg janicehouseafternoon
show TJ Surprised at center
play loop "reststop.ogg"
m "\"STOP!\""
"I reach forward and grab onto TJ."
t "\"Chase! Chase, can you hear me!?\""
"TJ's looking down at me with his wide, blue eyes."
m "\"Toby?\""
t "\"I—what?\""
"I blink up at him, feeling sick."
"TJ feels my head, then stands up and starts pulling me along the ground."
m "\"What...what are you—\""
t "\"Gotta...get you...inside.\""
"He grunts as he pulls me and that's when my stomach lurches and I roll over and vomit up the cookies."
t "\"Crap...crap!\""
"I can hear TJ starting to panic, so I grab at him."
"I have to cough and spit several times before I can speak."
m "\"No, I'm fine. Don't freak out.\""
t "\"No you're not! Can you stand up?\""
m "\"Yeah, yeah, I'm good.\""
"I get up on wobbly but stable enough legs."
"TJ puts an arm around me."
t "\"We're calling an ambulance once we get inside.\""
m "\"No, I'm alright.\""
t "\"No! You're not alright. This is serious.\""
"He starts limping me towards the front of the house."
t "\"I should have been keeping an eye on you.\""
"TJ's voice cracks and I stop him."
m "\"Hey, look at me. I'm okay.\""
"I look him in the eyes and see tears threatening to spill over."
m "\"I'm just really hungry and I stood up too fast...then I got dizzy.\""
"TJ looks back at me, studying my face."
m "\"Just don't call an ambulance for me, not yet at least.\""
"I force a laugh."
m "\"Definitely can't afford that right now.\""
show TJ Rejected with dis
"TJ's quiet for a moment, then starts pulling me to the front again."
t "\"We're getting you inside at least. I should never have had you work under this heat.\""
m "\"I'm just tired. We should go to the motel instead.\""
t "\"Inside, now. Just in case.\""
stop loop fadeout 3.0

scene bg janicehouseafternoon with dissolve
"Janice is happy to let us sit on the couch for a while, drinking lemonade."
"TJ doesn't tell her what happened, but he glances at me every now and then, as if worried I'm gonna face plant off the couch."
"I feel a little bit dizzy, but otherwise fine."
"I keep thinking back to that tarantula, but TJ hasn't said anything about it so I decide not to bring it up, yet."
"Meanwhile, TJ is making awkward conversation with Janice."
"I lean my head back, hungry and tired."
show Janice at right with dissolve
ja "\"Mainly it's the wood-chopping that'll be the hard part. My back isn't nearly as good as it once was.\""
show TJ Sheepish at left with dissolve
t "\"Oh yeah, I imagine.\""
ja "\"I guess I was hopin' I could get just a little more help...\""
t "\"Oh!\""
ja "\"If you didn't mind, of course.\""
"I lift my head from the couch to look at TJ."
ja "\"I got tomorrow off as well and I'll be free to show ya what needs to be done if you're willin'.\""
"TJ's stuck with his mouth open, then he smiles."
t "\"Of course!\""
"I frown."
"Janice beams at him."
ja "\"You are just a little life-saver, Tobias!\""
show TJ with dis
t "\"No problem, ma'am.\""
ja "\"And so proper, too!\""
"TJ avoids making eye-contact with me, a smile plastered to his face all the while."
"Janice suddenly turns her gaze on me and I'm forced to wipe the glare off my face."
ja "\"How were those cookies?\""
m "\"Oh! Good, they were good, huh TJ?\""
"TJ, still smiling, just gives a curt nod."
ja "\"Good, good. My secret recipe.\""
"She winks at me, and I feel a little uncomfortable because the smile doesn't touch her eyes."

scene sunset with fade
"It's a short walk to the diner and I berate TJ the entire way."
t "\"I'm sorry! She just sort of pushed it on me.\""
m "\"You can always say no.\""
t "\"I can't just say no!\""
m "\"Or at least that you had other plans."
"TJ stays quiet as I push open the door to the diner."
scene bg diner with dissolve
play music "neutraldiner.ogg"
m "\"I was kind of looking forward to hanging out again.\""
"TJ keeps quiet as we sit down, so I give up and just lean my head back again, eyes closed."
"It's quiet for a few minutes before TJ finally speaks up."
show TJ Neutral at left with dissolve
t "\"How are you feeling?\""
"I rub my eyes gently, a headache now replacing the dizziness that I'd felt earlier."
m "\"Tired, my head hurts.\""
t "\"I really shouldn't have done that. I'm so s—\""
m "\"Stop...apologizing, please. It's fine. It wasn't the heat.\""
"TJ frowns and sits back, looking out the window at the sunset."
m "\"Sorry, I'm not mad. I just don't wanna see you beat yourself up over it, ya know?\""
"I don't tell him that his constant fretting and apologizing is grating on my headache."
t "\"Well, make sure you try to eat. You might just need energy.\""
m "\"Here's hoping.\""
"At that moment a young stag that I vaguely recognize comes up to our table."
"It's weird seeing someone so young and fresh in Janice's position."
"Once he gets to our table, though, his eyes light up."
unk "\"Teej!?\""
show TJ with dis
"TJ sits up suddenly, a big grin spreading across his face."
t "\"Julian!\""
m "\"Julian?\""
show Julian at right with dissolve
"It's been a while since I've seen him."
"He's bigger, and so are his antlers. I barely recognize him."
ju "\"And Chase, too!? What in the world are you two doing here?\""
t "\"Visiting! I didn't know you had a job here. That's cool!\""
show Julian Happy with dis
"Julian grins."
ju "\"Not really, but it pays some of the bills.\""
"At that point I phase out of the conversation, letting the two of them catch up."
"TJ had a lot of friends in high school. He had been technically popular."
hide Julian with dissolve
"It's a good few minutes before the stag finally takes our orders."
"Once Julian bustles off to another table, TJ grins at me."
t "\"Aw man, it's good to see him again.\""
m "\"Yeah, that's cool.\""
"With the stag gone, the awkward silence quickly closes in on us again."
"I'm too tired to do much about it, though."
"I lean my head back again, closing my eyes, feeling like I might fall asleep right there."
show TJ Neutral with dis
t "\"So...\""
"I open them and see TJ looking at me before he quickly looks away again."
m "\"What?\""
t "\"Um...\""
"He fiddles with the stack of napkins."
t "\"You called me Toby earlier.\""
m "\"Did I?\""
"But I remember even as I say it."
t "\"Yeah.\""
show TJ Sheepish with dis
"TJ forces a laugh."
t "\"It's been years since you've called me that.\""
m "\"Yeah...\""
stop music fadeout 10.0
"We're quiet for a moment."
show TJ Neutral with dis
t "\"So...why did you call me that?\""
m "\"I dunno. Guess I was just a little loopy after passing out.\""
t "\"Ah.\""
"I eye him carefully."
m "\"Do you mind if I call you that?\""
t "\"Um, TJ is fine.\""
"So yes."
play music "bittersweet.ogg" fadein 15.0
"I study TJ, the way he's sort of hunched in on himself, his ears twitching."
m "\"Are YOU okay?\""
t "\"Yeah, I'm fine.\""
"I go back and forth between deciding if I should bring up the whole Flynn incident or not."
"Despite his best efforts, TJ isn't fooling anyone that he's not bothered by what happened."
"Of course he would be."
m "\"Do you—Do you wanna talk about what happened on Monday?\""
"TJ's quiet and I kick myself."
"I'm given a little more time to think of what I'm gonna say next as Julian brings our food and strikes up another conversation."
show TJ with dis
"TJ, again, is able to easily slip into a smile and chat away with the stag."
"The smell of the burger has my mouth watering and it's incredible when I take a bite."
"It's striking how easy it is for TJ to just put on a smile and act cheerful."
"It makes me wonder how much of it is actually genuine."
"I'm almost halfway done with my burger by the time Julian is angrily called back to the kitchen by the cook."
"TJ goes quiet again and starts plucking at his salad."
"I swallow and set down the burger, my stomach turning a bit at what I'm planning to say."
m "\"I was thinking about this before we got here.\""
t "\"About what?\""
m "\"That maybe we could use the time we have here to remember what happened, to find...\""
show TJ Rejected with dis
"TJ finally looks at me and the sadness I see in his eyes makes my heart plummet."
m "\"...find closure?\""
"TJ's quiet, staring at his salad."
m "\"I don't know, man. I just know how bad it is for you, still, and I just want to figure out how we can...\""
"I search for the right words."
m "\"...be at peace with it.\""
"TJ's still quiet."
m "\"I don't know, man.\""
"I finally say and slump in my booth, feeling like I ruined the evening."
t "\"How would we do that?\""
"His tone is shaky, but genuinely curious."
m "\"I don't know. Talk about it, talk about it with the others? Not Flynn, just the others.\""
"TJ looks out the window again."
m "\"Maybe even go to the lake, talk about it there...I dunno.\""
"I almost choke on the word \"lake\", still worried about saying it in front of TJ."
t "\"Maybe.\""
m "\"Maybe?\""
"TJ sighs and finally looks at me with a small smile."
show TJ Neutral with dis
t "\"Maybe, but right now I just want to hang out with you and have a good time, okay?\""
m "\"Okay.\""
t "\"So stop being so angry. It's making me sad.\""
"I pick up my burger, my stomach loosening up enough that I feel like I can eat again."
m "\"Sorry, I was just looking forward to—\""
t "\"And stop apologizing.\""
"He says it with a smirk, then almost immediately frowns."
t "\"I mean—sorry, that was rude.\""
show TJ Teasing2 with dis
"I laugh at him, and he smiles back."
"I take another bite and look out the window."
"I feel a lot better now and now I'm pretty sure I only passed out because I didn't have any food in me."
m "\"By the way, did you ever see that tarantula again, after that first time you saw it?\""
show TJ Sheepish with dis
"TJ shudders."
t "\"Ugh, no, thank goodness.\""
"I look out the window at the brilliant sunset."
m "\"Ah, that's good...\""

stop music fadeout 3.0
stop loop fadeout 3.0
scene bg black with slow_dissolve
scene bg fb5
show nightoverlayred
with dissolve
play music "eveningcall.ogg" fadein 3.0

"He tries to walk away from me, but I kick him in his lower back and he goes stumbling forward onto his knees."
"He stays there, not bothering to move at all."
"I glare at the back of his head, breathing hard."
m "\"How does it feel when it's happening to you?\""
"My voice shakes as I yell at him."
"I'm not used to doing something like this."
"It felt so.. gross."
"But at the same time I feel like I'm finally teaching him a lesson."
"He's had this coming for so long."
m "\"Why are you so mean to him?\""
show Young_Sydney_casual behind nightoverlayred with dissolve
"He doesn't answer, instead slowly getting up to his feet, wiping his face with the back of his hand."
"I'd told him to come out here to make one of his treasure hunts, just so I could confront him like this."
"It's not going how I thought it would, though."
"He's just standing there, not saying anything."
"Finally he starts to walk away again, shoulders slumped, ears and tail down."
"I feel another burst of anger, following him."
hide Young_Sydney_casual with dissolve
play sound "bodyfall.ogg"
scene bg fb5
show nightoverlayred
with vpunch
"I quickly overtake his slow pace and shove him as hard as I can in the back."
"His head snaps back before he falls flat on his stomach on the ground."
"He stays there for a long, long time while I stare at him."
"I can't remember what happened after that..."
stop music fadeout 3.0



jump tjthursday