label tjfriday:
stop music fadeout 3.0
window hide
scene bg friday
with transition_fade
$ renpy.pause(3.0, hard=True)
scene bg motelfull with dissolve
window show
"TJ gets up early in the morning and I fall in and out of sleep as he moves around the room quietly."
"The shower turns on at some point and I think I hear Jenna's voice."
"I fall asleep again and when I wake up next I see Jenna in the corner of the room, sitting at the little table and typing away on her laptop."
"I stare at her groggily until she notices me."
show Jenna at center with dissolve
play music "neutral.ogg" fadein 3.0
j "— Morning."
m "— Mmmh..."
j "— Still tired? It's almost noon."
"I rub my face into my pillow and groan."
"Guess I was up later than I thought."
"I force myself to sit up."
m "— Couldn't fall asleep."
j "— Yeah, I've been having trouble too. The beds are terrible."
"I look around."
m "— Where's Teej?"
j "— Hike."
m "— What?"
j "— He went on a hike."
"I sit there, frowning at Jenna."
"She types a while until she finally notices me staring and shakes her head."
j "— I don't know, he wanted to go alone."
m "— He's been asking us to go with him all week."
j "— I know. I think something's bothering him."
"Jenna pauses."
j "— Well, I know it's the scavenger hunt. Of course that's what's bothering him."
"I sit on the edge of the bed, rubbing my face with my paws."
m "— This was a bad idea."
"Jenna goes on typing."
j "— Maybe, maybe not. He really wanted to do it. I'm going to try to talk to him when he gets back, though."
"I stare at my feet for a moment, deciding on whether or not to just text him now."
m "— Jenna, do you think there's something weird about the treasure hunt?"
"Jenna doesn't even look up from her screen."
j "— Of course I do. I think everything about it is weird."
m "— I mean, I don't even know if Sydney put those there."
"Jenna finally looks up at me."
j "— Why not?"
m "— Just...just everything seems off."
j "— Who do you think put them there, then?"
"I shrug."
m "— I don't know."
"Jenna stares at the computer screen for a while, not typing anymore."
j "— Well, the whole reason we're doing this is because of TJ. This seems to be what he wants to do."
j "— And even if it was someone else that left them there, if it's going to help him then I'm going to help him with it."
"Jenna shrugs."
j "— And in the end all it is is a treasure hunt. I'm just hoping that it ends at the house."
m "— Yeah."
"Jenna goes on typing, apparently done with the conversation so I finally get up to go to the shower."
scene bg parkinglotday with dissolve
"Breakfast is long gone by the time I go to the lobby and what's left is a few dried biscuits."
"So I opt to go to the diner instead while Jenna opts to stay in the room to finish her paper."
scene bg diner with dissolve
"I sit at my usual booth in the corner of the diner, half-heartedly flipping through the menu."
"Janice comes over to take my order and my short answers to her pleasantries keep her from being too chatty."
"Once I'm done ordering, I sit back and look out the window, watching the bright sun bake the hot desert below."
"I imagine TJ out there on the trail, trudging along the path under the 100-plus degree heat."
"Aside from worrying about what he might be going through right now, I also worry that he might pass out in this kind of weather."
"I can only hope he had the right of mind to take along enough water and make sure to cool off, like he did to me."
"I look down at my phone on the table, again considering whether or not I should call him."
"Maybe a text at least..."
#"I tap out a quick one: Hey man :)"
call text_chase("tj") from _call_text_chase_12
$ renpy.pause(0.5, hard=False)
play sound "texting2.ogg"
$ renpy.pause(1, hard=False)
call text_0("m", "Hey man :)") from _call_text_0_11
""
call text_end from _call_text_end_12
"Then I set my phone back down and wait for a response, wondering if I might drive out to the trail myself if he doesn't."
"That's when I sense someone move up next to the table."
"I look up expecting to see Janice, but I'm met with the sight of a young, white deer, his clasped paws holding a folded, blue apron."
show Julian at center with dissolve
"I blank on his name for a few moments and I'm left with my mouth hanging open like an idiot."
"Then I remember."
m "— Oh, Julian. What's up?"
"Julian smiles."
ju "— Hey there...My shift just ended and saw you sitting here."
"I wait, but he doesn't go on."
m "— Oh, uhh..."
"I don't want to say it, but it looks like he's expecting it, and I can't really find a way out, so..."
m "— Wanna sit down?"
ju "— Yeah, sure."
show Julian at left with moveinleft
"Julian responds quickly and slides in the booth across from me, setting his folded apron down on the table."
ju "— Thanks."
m "— Yeah, no problem."
"I wonder if I sound a little annoyed."
"A part of me hopes that I do so that he might get the hint, like Janice did."
"But he goes on sitting there, interlocking his fingers and resting his forearms on the table."
ju "— How are you today?"
m "— Good. You?"
show Julian Rejected with dis
"Julian shrugs."
ju "— Eh, I've been better. This job is really starting to wear me out, ya know?"
m "— Yeah, I've had a few like that."
"While the buck seems nice enough, I don't think I've had more than five conversations with the guy in my entire life."
"He was just a regular face that I saw through middle and high school, a part of the background."
"It wasn't until the last few years of high school that I noticed him and TJ hanging out, and TJ was the only reason we ever briefly interacted."
"So I'm a bit confused now as to why he's suddenly taken an interest."
show Julian Confused with dis
ju "— Yeah? What sort of job do you have?"
m "— Uh, well, I'm between jobs right now. I'm going to school but I'll probably stock shelves over the summer, like I did last year."
ju "— So that job wore you out?"
m "— Well...no, but my fast food job did, the one I had in high school. I kind of like stacking boxes and putting stuff on shelves."
ju "— See, I think food service jobs are definitely the worst, so I can see why stocking might be a little better."
show Janice Happy at right with dissolve
"He breaks off as Janice comes back, setting down my chicken sandwich."
ja "— Oh! You know Chase, Julian?"
ju "— A little! I know him through TJ."
ja "— Ah! Well, if you see that boy again let him know that I'd like to chat with him!"
hide Janice with dissolve
"I look up and Janice gives me a wink before bustling off."
"I decide to definitely not let TJ know."
show Julian Rejected with dis
ju "— But anyway, I'm going to school too, over at Mesa, and this diner has some seriously flexible hours. Only reason why I'm still here."
m "— At least you guys don't seem very busy, even during the lunch hour."
"I nod at the two or three other occupied tables."
ju "— Heh, yeah, it's a wonder we're still in business. Probably gonna have to close down in a year or two."
"That idea actually makes me a little sad."
"I look down at my chicken sandwich, feeling a bit awkward at the idea of Julian just watching me eat, so I leave it on the plate for now."
"Julian leans back and looks out the window."
show Julian Confused with dis
ju "— So...where's Teej at? I thought you two were hanging out?"
"I get the feeling that this is the main reason why Julian is talking to me."
m "— Yeah, he went off on a hike earlier this morning. I slept in."
ju "— Ohh, I see. He still do that a lot?"
"I shrug."
m "— I don't know. We've only been here about a week. He does love going on hikes, though."
ju "— I mean, does he do that at CCU?"
"I stare at Julian for a second before I realize what he's talking about."
m "— Oh, no, I don't go to CCU. I'm at Pueblo."
ju "— Huh, so you guys met up here?"
m "— Well, I picked him up and brought him here, along with Jenna, but she goes to Pueblo too..."
"I grow a little frustrated at having to explain everything to this guy."
"All I want to do is eat, then go back to the motel and wait for TJ."
ju "— I see...well, TJ was my best friend during senior year, after you and Carl left. We hung out all the time. After he left for college we kind of lost touch."
m "— Hmm, yeah, he's not very active on social media."
"I'd only seen TJ post a few pictures since he started classes."
"A few were of him on the college soccer team, and one was of him standing in a prayer circle along with an inspirational quote."
"But Julian revealing that he was TJ's best friend toward the end of high school cools my exasperation."
"I suppose he does have a reason to know what TJ might be up to."
ju "— He was kind of depressed right after graduation, so I've been a little worried about him."
m "— Depressed?"
"That surprises me."
"I've never known TJ to be depressed."
"Sure, he's been sad before, but not outright depressed, as far as I know."
"Maybe I don't know much about him."
ju "— I thought it might have to do with graduation, but it went on all summer."
m "— Oh...well, if you want to talk to him I can definitely let him know."
"I gesture at my phone on the table."
"I also make a mental note to myself that I should talk to TJ, too...about everything."
show Julian with dis
"Julian smiles."
ju "— That would be great! Please do. I think he must have changed his number after leaving."
m "— Okay."
"I hesitate, then pick up the phone to type out the brief message."
hide Julian with dissolve
call text_chase("tj") from _call_text_chase_13
$ renpy.pause(0.5, hard=False)
play sound "texting2.ogg"
$ renpy.pause(1, hard=False)
call text_0("m", "I just met Julian at the diner. He'd like to talk to you :)") from _call_text_0_12
""
"TJ hasn't texted me back yet."
ju "— How long have you known TJ?"
call text_end from _call_text_end_13
show Julian at left with dissolve
"I set the phone back down and settle back into the booth."
m "— Since he got here in like 2001, so fourteen years ago?"
ju "— Wooow, that's a long time."
m "— Yeah, it really is."
ju "— You guys always been good friends?"
m "— For the most part...I had times where I was kind of a dick to him, but he's always been a good friend to me."
ju "— I see, I see...Yeah, we all went to the same elementary school, but it wasn't until junior high that I met him in bible study."
m "— Ah."
"Of course."
ju "— I always knew about you guys though, the Echo kids."
m "— Yep, that was us. The weirdos."
show Julian Depressed with dis
"Julian glances around before lowering his voice."
ju "— It was a mean thing to say, but this town IS kind of messed up. Lot of weird things happen here."
m "— I can't argue with that."
stop music fadeout 10.0
"Julian looks around again, biting his lip."
"Then he lowers his voice another notch."
ju "— Hey, so this is gonna be a bit weird, and I don't want to offend you, but it's something that's bothered me for a while."
"I eye Julian warily."
m "— Yeah?"
ju "— TJ told me what happened at Lake Emma a while back when we were talking about death and heaven."
"I feel a little chill go up my spine."
ju "— Well, he never actually told me about what {i}exactly{/i} happened, but I can tell it really affects him."
"Julian pauses, but I don't say anything, keeping my eyes fixed on the table."
ju "— Now, you don't have to tell me, and if it makes you uncomfortable please don't—"
ju "— —but I feel like if I have a better idea of what happened, I might understand {i}him{/i} a bit better."
"Julian brings his interlocked fingers up to his chin to rest it on."
ju "— I'm not going to ask HIM to tell me, of course. I know it was a long time ago, but I know you can carry stuff like that around for a long time."
ju "— So if you're not okay with it then please just let me know and I'll change the subject."
"I contemplate it for a moment, wondering if the buck is out of line to be asking about such a thing."
"I decide he isn't."
"He's one of TJ's best friends, so in a way he's sort of connected to it."
"So I guess he does have a reason to know."
m "— Okay, but please don't bring it up with TJ. Like you said, it still really affects him."
show Julian Confused with dis
ju "— Never."
"Julian looks at me solemnly."
"I think for a moment, gathering my thoughts."
"It's been a long time since I thought of the story from beginning to end."
play music "when_your_arms_were_around_me.ogg" fadein 3.0
m "— It was around August I think, 2003. It's a little bit hard to remember."
m "— What I do remember is that we'd all gone down to the lake to swim like we did almost every week."
m "— There's this little spot where the beach kind of curves in and it's mostly sand and shallow water. That's where we'd usually hang out and swim."
m "— Even though the water was always sort of stagnant there, it was at least safe and warm compared to the rest of the lake."
m "— I think at some point one of us wanted to go and skip rocks."
m "— We had to go further up the shore to do that, and TJ was more interested in building sandcastles."
m "— So he stayed behind while the rest of us went up the beach to find the rocks."
m "— When you go up that far you can't really see that spot anymore, so I'm not completely sure what happened."
"I vaguely remember looking back at TJ as we went up the beach."
"The lynx bending over his castle, the back of his wet swim trunks covered in sand from when he'd sat down."
m "— Sydney went with us, I at least remember that, but while we were skipping rocks he just sort of disappeared."
"I glance up at Julian for a moment and see him listening attentively before I look back down at the table."
m "— Anyway, we heard some splashing and some shouting from TJ and we all ran up the beach to see Sydney floating out in the lake..."
m "— I swam out there and got him. Too late, though."
"I don't mention the part where TJ was crouched in three feet of water, staring at Sydney's body floating twenty feet away from him."
"I don't tell him that TJ's explanation for what happened always amounted to Sydney stepping out too far into the water."
"That maybe the current knocked him off balance and pulled him in."
"How he'd even said that it almost looked like an invisible shark had grabbed Syd and pulled him out."
"How none of it makes any sense at all."
m "— None of us are sure what happened."
stop music fadeout 15.0
show Julian Depressed with dis
"It seems to be enough for Julian though, as he shakes his head."
ju "— I'm very, very sorry to hear that, but thank you for telling me. All I knew was that a friend of his drowned in the lake."
ju "— He didn't tell me how close he was to it. It makes sense why that would still deeply affect him."
m "— No problem."
play music "neutraldiner.ogg" fadein 3.0
"I realize that Julian is probably the first person that I've ever told the story to outside of Echo."
"I also realize that it wasn't hard at all to do."
"I suppose it's easier to tell someone who wasn't related to the incident, someone that has no connection to the raw horror of that day."
"That, and a lot of time has passed."
"Maybe I just got over it without even knowing."
show Julian Confused with dis
ju "— But yeah, Echo is a crazy place. You know about that mass hysteria thing that happened a hundred years ago? This place is kind of famous for that."
ju "— Almost all of the paranormal podcasts I listen to have an episode on it."
"My heart skips a beat as I suddenly remember my project."
"I cover my face with my paws."
m "— Shit..."
ju "— What's wrong? Did I say something...?"
"I uncover my face to see Julian looking at me with some concern."
m "— No, I...I just forgot some school work that I need to get done, a project."
"The excitement around the scavenger hunt completely wiped the the thought of it from my mind."
ju "— Oh? What kind of project?"
m "— A news report on Echo and that mass hysteria incident. I've barely done anything on it since I first got here."
ju "— Hey, that's so cool! Do you need help?"
"I blink, the buck's eagerness surprising me."
show Julian Sheepish with dis
"For the first time I see him become embarassed, the skin on the inside of his ears turning a dark red."
ju "— Sorry, it's something that's always interested me so I got a little excited, hehe."
"I glance down at my phone and see that I still haven't gotten a response from TJ, so I get an idea."
"Despite my initial annoyance, I like how considerate Julian was about the whole lake incident."
"I also want to give him a chance to see TJ before the end of our trip."
m "— Well, actually I've been meaning to get some footage of the mine, or at least the opening since it's sealed up."
m "— If you want, we can head up there to get some shots and at the same time look for TJ. The trail is in that area."
show Julian with dis
"Julian perks up."
ju "— Hey, that would be really awesome. Thanks! Do you want to eat that first?"
"I look down at my sandwich, then shake my head."
m "— I'll just eat on the way to the motel."
stop music fadeout 5.0
ju "— Oh, I got my truck! I can drive you over, and there's a bunch of room if you need it for your equipment."
m "— Oh, okay. Yeah, thanks. Just let me get a to-go box and we can leave."

scene bg dirtroad with fade
play background "highway.ogg" fadein 5.0
"Twenty minutes later and we're heading up the narrow canyon road toward the mine."
"I haven't been there in years, but the dirt road leads straight to it, so I don't even have to look up instructions."
"Julian chats away while I eat my lukewarm sandwich out of a foam to-go box."
"While there's an almost robotic quality to the buck with how articulate he is, he's also really nice."
"I can certainly see why TJ would call him a friend."
stop background fadeout 3.0
play loop "engine.ogg" fadein 3.0
"The bumpy road curves upward and finally we get to the mine."
scene bg echomine with dissolve
"There's a wide-open dirt space for parking, along with some concrete barriers along the edge of the drop-off."
"There are a few sign posts, probably giving a brief history on the mine and then there's—"
"There's TJ."
"The lynx is sitting at the opening of the mine, right at the entrance."
"He's leaning back against the rebar grid that's sealed the entrance."
m "— What the..."
"Julian stops talking and looks over at me, then in the direction I'm looking."
ju "— Whoa, is that Teej?"
"I don't say anything because I realize now how limp the lynx looks, his head tipped back, his paws limply laying on the ground."
stop loop fadeout 5.0
play sound "cardoor.mp3"
"I'm out of the truck before Julian can even park, my to-go box spilling out onto the gravel as I jog toward TJ."
m "— TJ! Hey, what's wrong!? You okay?"
"The lynx doesn't respond and when I get to him I see that his eyes are open, but they're rolled back to the point where I can only see white."
"I bend over him, trying to help him sit up better made more difficult by his bulky backpack getting in the way."
play background "whispers.ogg" fadein 5.0
"As I'm doing this, I feel a rush of cold air from the mine, blowing out through the rebar."
"I ignore it at first, focused on trying to get TJ to respond to me, but then I realize there's a hissing sound to go with it, like someone exhaling."
#"I glance to my left, through the grid, and I come face to face with a blood-red visage of rage."
#"I see piercing yellow eyes, and a row of white, blocky teeth...and then all of the blackness that extends beyond it..."
#unk "\"How long do you think you can keep it hidden? You know someone's onto you.\""
#"A clawed and withered hand sticks out through the bars, resting on TJ's head, ruffing his ears almost affectionately."
#unk "\"How could he ever forgive you?\""
#"I stare back at a different face - increasingly empty eyes, pools of bottomless silence..."
stop background fadeout 5.0
play loop "reststop.ogg" fadein 3.0
"I glance up through the grid, but I don't see anything."
"Still, I get the unnerving feeling that the opening is breathing somehow."
show Julian Depressed at right with dissolve
ju "— Is he alright!?"
"Julian's shouting and running up next to me turns my attention back to TJ."
"I look down at the lynx and see his ears twitching around."
show TJ Neutral at left with dissolve
t "— Huh, whu—?"
"I crouch down next to him, putting a paw behind his head to give him some support."
m "— TJ, what happened? Are you okay?"
"TJ turns to me, blinking in confusion."
t "— Okay? What's wrong?"
"He rubs at his eyes with the back of his paw before adjusting himself so that he can sit up straight."
ju "— You were just sitting there. You almost looked—"
"Julian pauses."
m "— It looked like you were passed out, or something."
"TJ finally seems to focus on us, the dazed look in his eyes disappearing."
t "— Passed out? Oh! No, I was just taking a quick nap, haha."
"TJ let's out a short laugh and leans his head back against his backpack."
m "— What? Here?"
"I look back at the sealed mine, the ominous blackness still seeming to yawn open at us."
m "— Why?"
t "— Well, it's hotter than usual today, so I started to feel like I was gonna pass out. Thought that might be a bad sign, so I decided to rest once I got here."
m "— You came here on purpose?"
t "— Yeah, I saw the canyon with you last time, so I decided to take a trip to the mine this time."
"TJ smiles lazily up at me as he continues to lounge against his backpack."
t "— Sorry I worried you and—Oh, Julian!"
"TJ seems to suddenly realize that the stag is here."
t "— What are you doing here!?"
"TJ quickly gets to his feet, sliding his arms out of the straps of his backpack."
play music "comeover.ogg" fadein 3.0
stop loop fadeout 3.0
show Julian with dis
"He hugs Julian, the stag hugging back just as enthusiastically."
"TJ doesn't even greet me so.. intimately."
"I guess they have more of a history than I thought..."
ju "— Hey Teej. Yeah, I met Chase at the diner."
ju "— You weren't answering your texts so we both decided to come up and find you...that, and Chase needs to get some footage for his project."
show TJ with dis
t "— Oh cool! Do you need help with that, Chase?"
"TJ turns to me with a grin."
"I don't know what it is, but TJ's acting a lot more chipper than he was yesterday."
"That almost dark broodiness is gone, replaced by his usual cheer."
"I have to smile because of it, despite the situation just a few minutes ago."
m "— Sure."
"Another breeze of cool air seems to whoosh softly through the rebar."
"I look back at it."
m "— TJ, why the hell would you sleep here next to the creepy mine?"
show TJ Rejected with dis
"TJ frowns."
t "— It was really cool."
t "— Like, cold. I was laying in the opening and felt some cool air blow out, so I decided to lean against it. It feels really nice."
"TJ walks up to the metal grid and spreads his arms out, clutching onto bars as he presses his face against it."
t "— Ahhhhh...ergh."
"He leans his head back, pulling a face."
t "— Well, it smells really musty, but it feels good!"
m "— Hmm..."
"I look back at the opening, the blackness inside sending chills up my spine."
"I think back to when a body was found in there over a hundred years ago."
"Even though I know there aren't any dead bodies in there now, it still creeps me the fuck out."
"I try to hide my shudder as I turn away, looking back at the truck."
show TJ Neutral with dis
t "— Hey, so are we going to Sydney's old house now? Is that why you guys came to find me?"
"TJ's trying to hide it, but I can hear the eagerness in his voice."
"I turn back to look at him, the lynx now with his back to the mine, pressed up against it."
"I want to tell him to move away from the opening, but I wouldn't be able to explain to him why."
m "— Well, let me get some filming done first. I can do the voice over later, so it'll be quick."
"I hold back a wince as I realize how much time that's also going to take."
"My project is going to be shit at this point, can't avoid that."
"I just need to make it the least shit as I can."
show TJ with dis
t "— Oh yeah, sorry, hehe."
"TJ laughs nervously, then looks away."
t "— Sorry, I'm just a little loopy from my nap. You guys really surprised me."
m "— It's okay. I'm gonna go get my equipment really quick, alright?"
"TJ nods at me and I jog off to the parked truck to grab my camera."
hide TJ
hide Julian
with dissolve
"So TJ might still be acting a little weird, but I'm just glad he seems happy again."
"Seeing him the way that he was last night was...a little unnerving to say the least."
"I scoop up my camera bag from the bed of the truck and head back, slowing down to a walk as the heat is already starting to catch up with me."
"How TJ was able to go on a several-hour-long hike is absurd to me."
"It almost seems foolish."
"Especially for someone like TJ who knows about how dangerous that can be."
show TJ at left with dissolve
show Julian at right with dissolve
"When I get back to the mine entrance I see Julian and TJ sitting with their backs to either side of the opening, chatting with each other."
"They're eating granola bars and TJ holds one out to me as I approach."
m "— Thanks.. Hey, TJ?"
t "— Huh?"
"TJ looks up at me innocently."
m "— If you go on a hike again, be sure to bring me next time, okay? I don't think you should be alone out here."
show TJ Sheepish with dis
t "— Oh.. Yeah, sure."
"His ears droop a little, a small frown on his face."
m "— I just don't want you to get hurt, ya know? It's really hot today and it would have been really terrible if you'd passed out alone."
t "— Yeah, sorry."
"I drop my bag gently on the ground before leaning back against the wall next to the lynx."
m "— It's all good. I just wanna make sure you're okay."
t "— Heh, thanks. I just didn't want to wake you up this morning."
m "— Jenna offered to go with you, didn't she?"
"TJ sighs quietly, looking away into the mine."
t "— Yeah, but I can tell you guys don't want to go. I just don't want to ruin this trip for you more than I already have."
m "— What!? TJ what are you talking about?"
"TJ goes quiet, then just shrugs his shoulders."
"Maybe he isn't back to his old self after all..."
ju "— I wouldn't mind going with you, TJ. I love hiking."
"Julian smiles gently at the lynx."
"For some reason I feel a tiny tug of annoyance in my chest."
"It's stupid, but I was the one who offered first, and I'm the one that took TJ out the first time."
m "— Yeah, we could both go. The point is you don't go out alone next time, alright Teej?"
t "— Yeah, okay. Thanks guys."
ju "— No problem."
"A short silence stretches out between the three of us before Julian speaks up again."
ju "— We were just talking about our old bible study group."
show TJ Neutral with dis
t "— Ugh."
"TJ leans his head back against the wall, rolling his eyes."
"It's an expression I don't see from him very often."
m "— What about it?"
show Julian Happy with dis
ju "— Oh, just the way that TJ would always take it so seriously, and no one else would, haha."
"TJ shakes his head in exasperation."
t "— Yeah, I never had any control in that club."
m "— Oh really? Were you in charge?"
"It's a little odd to think of TJ in a leadership position like that."
"I just never knew him to put himself out there in high school."
t "— Yeah, I revived it after it sort of went defunct for a few years. Wasn't all that popular."
"TJ smiles with some embarrassment."
ju "— Yeah, we had like, three other members not including you or me."
t "— Yeah, then one dropped out after like, two meetings."
show Julian Wry with dis
"Julian clicks his tongue."
ju "— What a godless school we went to."
show TJ Surprised with dis
t "— Hey!"
ju "— You know I'm kidding...mostly."
show TJ Neutral with dis
t "— Well, I did want atheists to join too, as long as they weren't disruptive. I just wanted to show everyone what a nice experience it could be—"
t "— —even if you didn't believe."
"I very vaguely remember TJ inviting me to the club and me saying that I'd think about it."
"I never went, of course."
t "— Wasn't all that spiritual in the end, though."
ju "— Yeah, mostly we just talked and brought snacks. It took TJ a while to realize no one wanted another Sunday school session at actual school."
t "— Yep. Hours of planning out the window."
ju "— It was still a great time. I think the four of us were happier for it."
t "— Yeah, I guess."
"TJ seems to suddenly notice me."
t "— Ah, sorry Chase, you wouldn't know much about this stuff."
m "— It's okay. It's interesting to hear about."
"Again, I get that little twinge of jealousy, even though I know it's not fair."
"I'd chosen not to show up, probably using that time to go home and...hang out with Leo."
ju "— You didn't miss much. Just discussions about movies and...watching movies too."
t "— Ugh, they couldn't even be religiously themed."
ju "— Thank God."
t "— Hey!"
"I laugh at how indignant TJ is."
t "— Well, I'm glad you had a good time at least. I came away thinking the whole thing was a failure."
ju "— I think I remember you mentioning that you wished your friend here would have shown up."
show TJ Sheepish with dis
t "— Er...I don't really remember."
ju "— Of course you do, you said it all the time."
"TJ's ears flatten and turn red."
m "— Who, me?"
ju "— Yep!"
"Julian grins as TJ tries to look away."
"While the situation is kind of funny, now I feel even worse about not ever showing up."
m "— Ugh, sorry Teej. You know, it was high school and all..."
t "— Yeah, I understand. Don't worry about it."
ju "— So did you start another club at your new school?"
show TJ with dis
"TJ smirks."
t "— It's a Christian school, so there's like, fifty clubs about religion."
ju "— Oh? Are you a member of any of them?"
t "— Uh, a few."
m "— Which ones?"
t "— Uh...a singles club."
m "— Singles?"
ju "— As in finding a date?"
t "— Sure."
"He looks away again."
"It's hilarious how bashful he is about this stuff."
"He's in college; all of this should be natural to talk about, but not with TJ."
m "— You meet anyone?"
show TJ Neutral with dis
t "— Hey Chase, don't you have to film some stuff?"
"He looks back at me with a frown."
m "— Whooah, just askin'."
show Julian Happy with dis
"Julian chuckles quietly."
"I bend down and start pulling out my equipment, deciding that a few long shots with the tripod should be enough."
"As I'm extending out the legs, Julian asks TJ about the hike."
show Julian with dis
ju "— Was it fun?"
"TJ shrugs, finishing the last of his granola bar and brushing his paws together to get rid of the crumbs."
t "— It was okay, was really quiet."
"I wince as one of my pads gets pinched between metal."
t "— Kinda creepy to be honest. I would like it if you two went along sometime, if I do it again."
ju "— Of course."
m "— Yeah, definitely."
stop music fadeout 5.0
play background "reststop.ogg" fadein 3.0
"Over the next 20 minutes I set up the camera in three different spots, getting about one minute of film for each."
"TJ and Julian sit in the truck while I do, and whenever I glance at them they seem to be animatedly chatting and laughing."
"Once I'm done I sigh and quickly snap the legs back down into the bag along with camera."
"I see my to-go box in the dirt and consider picking it up...but I don't."
"I drop the bag into the truck again before hopping into the passenger seat, leaving TJ to sit between the two of us."
stop background fadeout 3.0
"They go quiet as we start pulling out onto the dirt road."
scene bg dirtroad with fade
play background "highway.ogg" fadein 5.0
m "— What were you guys talking about?"
ju "— Not much. Just about high school."
"TJ nods."
"Again I'm starting to feel a little left out between these two, kind of like a third wheel..."
m "— So...what's the plan now?"
t "— Well, we thought we'd go to the house now, after we pick up Jenna and Carl."
m "— Alright."
"We drive in silence a little while and for some reason I start to wish that I was sitting in the middle."
"The way Julian keeps turning the wheel forces his elbow to brush up against TJ's side and—"
"I force myself to look away, wondering what the fuck I'm thinking."
"I'm treating TJ like he's something that belongs to me."
"We've only hung out recently over the course of this week."
"I'd barely talked to him the past two years."
"I force myself to look ahead, out the windshield."
play sound "phonebuzz.ogg"
"Then TJ's phone buzzes and my eyes naturally go to the screen as the lynx whips it out."
"I see the name \"Flynn\", then the message underneath it."
"I only have time to see a few words:"
"\"You know\" \"his\" \"FUCKING\" \"tell me\""
"TJ jerks his phone back down and I look away just as I feel the Lynx's eyes on my face."
"I wonder if he saw me looking, I'm sure he did."
"That doesn't really matter though, because now I'm wondering what the fuck Flynn thinks he's doing."
"They've been staying away from each other the past few days obviously, but I guess Flynn found another way to get to TJ."
"What the fuck does he think he's doing?"
"I feel myself getting angry."
"I don't exactly know what the lizard is saying to TJ, but judging by what I saw it's definitely not good."
"I make a mental note to ask TJ about it tonight."
stop background fadeout 3.0
"If he won't tell me then I'll let Leo know."
"He'll do something about it."

scene bg sydneyhouse with dissolve
play background "reststop.ogg" fadein 3.0
"We all walk up the sidewalk to the old ranch-style house."
"It's been a long, long time since I've seen this place."
"Even longer since I've walked on this path."
"Sydney's house is up the gravel road behind the \"forest\"."
"It's a bit of an odd spot, secluded from the rest of the town."
"It was all the better for us, I guess."
"It's nice not to be reminded of what happened."
show Carl Rejected at right with dissolve
c "— Guys.. I dunno about this. You think he's just gonna let us in?"
show TJ Neutral at center with dissolve
t "— What else can we do?"
c "— Uhhh, maybe Sydney didn't mean his room?"
t "— Where else would he sleep?"
c "— I.. don't know."
m "— I mean, he'd nap in random places, if I remember right. Like, he's slept on my couch, even."
show TJ Annoyed with dis
t "— Stop it, Chase. You know that's not what he meant."
m "— Well, who knows?"
t "— I do. I know where it is."
"That dark edge to TJ's voice is creeping in again."
show Julian Confused at farright
show TJ Neutral
with dissolve
ju "— I suppose there's no harm in asking."
show Jenna Neutralhips at farright with dissolve
j "— You can't deny that it's a little weird for five young adults to just show up on your door step asking to be let in."
t "— We don't have much of a choice though, do we?"
show Carl Depressed with dis
"TJ's walking ahead of all of us, marching up the concrete steps without hesitation before immediately ringing the bell."
m "— Whoah, wait! We didn't even think of what we're going to say."
t "— I already know what I'm going to say."
show Jenna Rejectedhips with dis
"We stand there in stunned silence for a bit and I look around at the others."
"Carl looks completely uncomfortable, almost nauseous, his paws shoved deep into his pockets as he stares hard at the ground."
"Jenna is staring at TJ, her brown furrowed, clearly worried."
"Julian just stands there, as if the situation doesn't bother him at all."
"The door finally opens, revealing a young red panda, not much older than ourselves."
"He blinks at us, then fixes a smile on his face."
unk "— Hello...can I help you?"
"I see TJ's ears flatten down for a moment, his originally tough resolve clearly faltering."
t "— Uh, umm, hello..."
"The red panda stares down at TJ for a moment, waiting expectantly."
"I don't recognize him, and I'm sure I would have seen him around town if he'd moved in after Sydney's parents moved out."
"It must have been sometime recently, a few years ago."
"I decide then that I should step in to let TJ try and gather his wits."
m "— Hi! I'm Chase, this is TJ...and Carl, Jenna, and Julian."
"I point to everyone, feeling my cheeks grow hot."
show Injy at farleft with dissolve
inj "— Hi.. everyone. I'm.. Injy."
"Another moment of awkward silence before I try to think of something else to say."
"How the hell do you bring up wanting to search someone's house because it belonged to your dead friend?"
"As I'm trying to figure that out, TJ speaks up again."
t "— M—my.. our friend used to live here, about twelve years ago?"
inj "— Oh really?"
"The panda seems to think."
inj "— Are you talking about.. Cindy?"
t "— Sydney, yeah, he was our friend."
inj "— Oh! Sorry, I couldn't remember the name. I think his aunt told me about what happened."
t "— Yes, and uh, he left something behind for us, in his room. Is it alright if we come in and look for it?"
"Injy's originally inquisitive look is replaced by one of confusion and definitely a little bit of suspicion."
inj "— Oh, all of you?"
show Carl Depressed with dis
"I notice Carl still staring down hard at the floor, his paws twisting in his pockets."
t "— If that's alright with you."
"Injy stares at us all for a good ten seconds, causing even me to glance down at the floor, realizing how stupid all of this is."
"Finally, he starts to step back, closing the door a little bit as he does."
inj "— Um, I'm sorry, but I don't think that's a good idea—"
t "— Wait!"
"TJ steps forward, his fur bristling."
"The panda jumps a little, closing the door further until it's at the point where I can only see one of his eyes."
t "— S—sorry. It's just...maybe I could come in and the rest of my friends can wait outside? This will be really quick. I know exactly where to look."
"The panda's one eye looks back at us."
"TJ turns around and makes a shooing gesture with both paws."
"There's a pause, then we stumble back a little, down the steps onto the sidewalk."
"My face burns again in embarrassment, realizing what a bunch of crazy people we look like right now."
"I look back and see TJ standing alone on the porch, looking back at the panda, his paws clasped together."
"Again, what feels like a very long silence seems to drag on until—"
"Injy opens the door slightly."
inj "— You know what...why don't you just tell me where it is and I'll have a look?"
t "— Oh! Oh, yeah, um..."
"TJ seems surprised, as if only now considering that idea."
t "— It's the room on the left, down that hallway."
"TJ points at the door at an angle."
t "— In the closet, in the back corner. It might be in a box."
"Injy's facial expression mirrors mine as I frown."
"A box in a closet, sitting there for over a decade?"
inj "— Alright, I'll have a look."
hide Injy with dissolve 
"Injy disappears behind the door and I hear a deadbolt slide into place."
"We stand there in silence for a while before Carl breaks it."
show Carl Rejected with dis
c "— Dude, he's calling the police."
t "— No he's not."
c "— We look like a bunch of crazy people! We should leave."
t "— Not until he comes back out."
c "— I think I'm gonna be sick."
ju "— I think it's technically okay unless he tells us to leave."
j "— He did say he's going to look for it. No harm in just waiting for his answer."
"I see Carl scuff his hooves against the pavement, looking around nervously."
"I wonder if he's had too much weed, or something."
m "— Why do you think it's in the closet?"
t "— He used a shoebox in there as a spot for his treasure hunts before. You remember."
"I vaguely do, now that he mentions it, but I'm surprised TJ does."
"He was even younger."
show Injy at farleft with dissolve
"Then the door opens and Injy comes back out."
"His facial expression is completely different now."
"It's one of amazement, and disbelief, but it's what's in his paws that catches my attention."
play music "loneliness.ogg" fadein 5.0
show Carl Surprised with dis
show Jenna Surprisedhips with dis
"It's a teal-colored shoe box, old and worn and torn through the corners."
"My mouth drops."
"Injy stands there for a moment, holding the box out."
inj "— Is...this it? It's not mine, and there's a piece of paper inside."
"TJ's paws shake as he reaches out to take the box, lifting the lid to look inside."
inj "— It was in the spot that you said. I've never seen that before."
"I feel my stomach twist, more dismayed than anything that he found something."
m "— Do you not use that closet?"
"It's a bit of an odd question, but I want to know how the hell he might have missed it."
"Injy shakes his head."
inj "— No, not really. It's mostly a storage room right now. I think I've opened it a few times to put some boxes on the shelf, but I can't really remember..."
m "— Did you not look inside when you first moved in?"
"Injy looks at me, and so does TJ, over his shoulder."
"I guess now I'm sounding like the crazy person."
inj "— Well, I can't really remember. It was a couple years ago."
inj "— I had family help me move them in, so maybe they just thought it was mine if they saw it?"
"I want to ask more, but I bite my lip, not wanting to seem as frustrated and suspicious as I am."
inj "— It's definitely something I could have missed. I've found a few things in the crawlspace from the last family."
j "— Who lived here before you, if you don't mind me asking?"
"Injy leans against the doorway, his arms folded, looking a lot more relaxed now."
inj "— It was the family you're talking about, I think? The Bronsons?"
t "— Yes."
"TJ's still looking down at the box, having not taken out the note."
inj "— Yep, the woman who lived here moved out right after what happened, but then her sister moved in."
inj "— She told me about what happened when I bought the place."
"Injy looks down at the box that TJ's still holding."
inj "— Do you know what he left you? How did you know to find it?"
t "— It's a...an old scavenger hunt that we found. It told us to come here."
inj "— Like, something he left behind?"
t "— Yeah."
inj "— Wow...well I'm sorry about what happened to your friend. You must have been children at the time?"
"No one says anything, so I nod for him."
inj "— I'm sorry...also sorry for being so suspicious when you guys showed up. Thought I caught someone trying to break in a few days back."
inj "— Can't be too careful."
show Julian with dis
ju "— Don't worry about it, that's completely understandable."
"Injy nods, then shifts around."
inj "— I don't want to pry but...what does it say? I didn't read it since I don't wanna intrude or anything."
t "— Um."
"TJ lifts the lid again, then reaches in to pull out the piece of paper."
"It's identical to the others that we've seen."
"Injy takes the box from the lynx so he can use both paws to unfold the note."
stop music fadeout 5.0
"Then he starts reading."
hide Injy
hide Jenna
hide TJ
hide Julian
hide Carl
with dissolve
"\"I hope that you're all having fun,\""
"\"Soon you'll know what Chase has done,\""
"\"Figure it out, it's a piece of cake,\""
"\"If you can't, look by Carl's drawing at the lake.\""
"It goes quiet for a while, the only the sound is the wind rustling through the trees."
"Then I hear a gagging sound and look back just in time to see Carl hurling into some bushes."
stop background fadeout 3.0

scene bg motelfull with fade
"TJ is strangely calm as we sit in the motel room."
"It's been about half an hour since we found the last note."
"After Carl lost his lunch in the bushes, Julian drove him back home and we had to put the scavenger hunt on hold."
"TJ wants us all to be there for it."
"Julian is still with us and I keep wondering when the hell he's going to go home."
"He just joined our little group today and TJ acts like he needs to be part of this for some reason."
"He barely even knew Sydney."
"But that doesn't really matter."
"This whole thing is so ridiculous."
"It's so obvious that Sydney had nothing to do with this \"scavenger hunt\"."
"Someone's planting these damn notes, and they have it out for me."
"I sit with my back against the headboard of the bed, staring at my legs as TJ tries to defend this whole thing."
play music "quiet.ogg" fadein 3.0
show TJ Neutral at center with dissolve
t "— If it's really bothering you Chase then you don't have to come..."
"I bristle a bit."
m "— You're insisting everyone else go, why not me?"
"I force myself not to look over at Julian."
t "— I do want you to come, but you're so angry...I've never seen you like this."
show Jenna at left with dissolve
j "— Oh I have, we all have. Chase is just acting like his old self now."
"Jenna sits in the corner on her laptop as usual, smirking."
"It pisses me the fuck off."
m "— Listen, whoever's writing these has it out for me. Look at what the last one said!"
t "— Sydney wrote them and he always kind of teased you. It's just like him."
"I go quiet, looking away with a glare."
j "— What do you think the clues are implying about you, Chase?"
"I think for a moment, but it's hard with all the anger that keeps threatening to bubble to the surface."
m "— I—I don't know. I just don't like the sound of it and honestly..."
"I try to think of the right way to word what I'm going to say."
m "— If you respect me you'd see that and stop this stupid hunt."
"It goes quiet for a moment, then Julian stands up."
show Julian Confused at right behind TJ with dissolve
ju "— Hey, I'm gonna head out."
ju "— Let me know what you guys decide to do tomorrow. I've got the whole day off."
show TJ with dis
t "— Oh! Okay, man. Thanks so much for coming with us!"
"TJ gives the stag a side hug and I try to keep myself from bristling."
hide Julian with dissolve
show TJ Neutral with dis
"Once Julian leaves out the door, TJ sits on the foot of the bed, looking at me."
t "— I completely respect you Chase, but I really think these are from Sydney. He's just teasing you."
"I don't say anything, choosing to look at the wall, feeling more unnerved by my own emotions than anything else."
"I don't feel like myself at all."
j "— I know I asked you this morning, but if you think this is someone else's doing, who could it be?"
"Jenna crosses her arms, looking at me earnestly."
"I sit there quietly for a moment, debating on whether or not I should tell them."
"I decide I have to, since neither of the others seem to see it."
m "— I think it's Flynn."
show Jenna Annoyed with dis
j "— What?"
m "— I think it's Flynn.. and Carl. They're doing this whole thing."
j "— You can't be serious."
m "— Who else!? Carl's the one that found the first note. I think Flynn gave it to him."
"The looks on Jenna and TJ's faces makes me look away again."
"Am I going crazy?"
t "— Chase, that's..."
m "— Crazy, I know. But you saw how Carl was acting today, how nervous he was. He even threw up!"
j "— Carl does that sometimes."
m "— Ugh."
"I slide my legs off the bed and let them hang over the side, fully facing the wall now."
t "— I know how Flynn was back at the river, but even he wouldn't do that."
"I look back at TJ with a glare."
m "— What about those texts he's sending you?"
t "— Wha—"
show TJ Surprised with dis
"TJ's paw flies to his pocket, a shocked look on his face."
"Jenna looks between us."
j "— What?"
m "— Flynn sent TJ a text swearing at him. I think he's been messaging you this whole time."
"TJ's quiet, just staring at me."
j "— TJ, is that true?"
show TJ Neutral with dis
"TJ stares at the floor for a moment before finally looking up, his voice oddly calm."
t "— Yeah, well, he's angry. Of course he would be. But he has no reason to be writing this scavenger hunt. Flynn would never do that."
m "— You sure about that?"
"TJ glares back at me, and now I can tell I've made him angry."
t "— Yes."
j "— Why would he do it in the first place?"
"I don't have to think hard on that one."
m "— To hurt TJ, to ruin our friendship by making up lies about me, to just be a complete dick - take your pick."
t "— That's absolutely ridiculous."
"I don't say anything, choosing to glare at the wall."
"Jenna looks between us again and shakes her head."
j "— Alright, that's enough of this. Neither of you are acting like yourselves so I think it's best we head to bed. Alright?"
stop music fadeout 5.0
m "— ...Whatever."
"I slide into the bed on my side, still staring at the wall, listening as TJ gets up and goes into the bathroom."
"Jenna goes on typing on her computer."
"I lay there quietly, deciding that I'm going to have to do something to stop this."

scene bg black with slow_dissolve
"Sneaking out of the motel room is probably the hardest part."
"I know that if they catch me at any point, it's over."
"At about 3 A.M. I slide out of the bed, listening to TJ's snores and watching Jenna's unmoving form curled up on the bed in front of me."
"Quietly, I dig around in my bag for my keys, then slip out the door into the night."
scene bg parkinglotnight with dissolve
play background "crickets.ogg" fadein 5.0
"I grit my teeth as my car starts up, imagining TJ or Jenna pulling back the curtains and seeing me sitting in the car."
"I've got excuses; I'm sick, I had to drive to the emergency room, or even that I just couldn't sleep and wanted to get a snack somewhere."
"They're all suspicious, but should be enough to cover my ass if things go south."
stop background fadeout 3.0
scene bg highwaynight with dissolve
play music "reckoning.ogg" fadein 1.0
"I drive along the quiet road, my surroundings almost black since the moon has set."
"It takes me a moment to find the side road that will take me to the shore."
scene bg lakeemmanight with dissolve
"Once I do, I see one, lonely orange light glaring in the middle of the parking lot."
"I park away from it at the edge of the lot. It's dark here."
"I sit in the car for a while, wondering what I'm doing, wondering what the fuck I'm going to do."
"But something drives me, a feeling that if I don't do this, then the rest of my life is going to be ruined."
"I can't let that happen."
"I open the door and quickly get out."
"I pull out my phone and turn on the light, finding the small, dirt trail that leads out into the inky blackness."
"The air is cool and I can smell the lake."
play background "lakesounds.ogg" fadein 3.0
"Pretty soon I can hear it too, the soft, desolate sounds of the waves running against the thin strip of shore."
"It's peaceful, but at the same time it terrifies me, and for a moment I feel like the lake is one giant living thing."
"It dwarfs me with its presence; a giant, all-knowing thing."
"It knows I'm here."
"I shudder and force myself to continue."
"I find the shoreline and the dry sand shifts under my feet as I take a right and follow the shore."
"I try to ignore the sounds of the lake, the feeling that it's watching me, beckoning me towards it."
stop background fadeout 5.0
"Finally, I come across the boulder that I'm looking for."
"The one that Carl used to carve his drawings into."
"Of course it would be something Carl used."
"That fat piece of shit."
"I kneel down beside it, moving the light of my phone around until I find the drawings."
"I look at the Super Wolf etched into the rock, glaring...then I see a glint of light above it."
"I shift the phone light up to see what it is—"
"I gasp and I can't help a ragged scream from escaping my throat."
"A tarantula sits there, staring back at me, its cluster of eyes shining back in the darkness."
"I stumble back in the sand and fall, sitting down hard and causing my teeth to clack together."
"I scramble back up."
"I look around for a rock and quickly find one."
"When I turn back around and lift the light, the spider is gone."
"I look around for a while, in case it just moved around, maybe on the ground closer to me."
"I don't see anything though, and I throw the rock at the lake, cursing the damn thing."
"Then I kneel down and look at the spot between the rocky ground and the boulder."
"It takes a few moments and I have to get real close, looking deeper into the crevice and then—"
"There's a glint of what looks like metal."
"I start to dig, first with my bare hands, then with the help of a flat rock laying nearby."
"I'm sweating and gasping by the time I pull the thing free."
"It looks like an old lunch box."
"I shine a light on it and can barely make out what looks like a cartoon dragon."
"I open it and pull out the note."
"I read it."
"In a fit of rage I tear the stupid thing in half, throwing it on the ground."
m "— You fucker!"
"I hiss it out through my teeth, then pull out the piece of paper that I'd taken out of one of Jenna's notebooks, along with a pen."
"I write for a moment, using the old lunch box as a flat surface."
"When I'm done, I drop it into the box, then wedge the box into the crevice, covering it up with the loose dirt I'd moved."
"I pack it down, then stand back up."
"Thinking twice, I pick up the shredded note and stuff it into my pocket."
"Then I walk back up the shore and up the trail, ignoring what looks like the eye shine of tarantulas all around me...maybe it's just the stars."
scene bg black with dissolve
stop music fadeout 15.0
"I don't remember much of the drive back, or the parking lot of the motel."
"The next thing I know, I'm standing next to the bed, glaring down at TJ, watching him sleep."
window hide
scene bg black with slow_dissolve

jump tjsaturday