label tjthursday:
stop music fadeout 3.0
window hide
scene bg TJThursday0 with transition_fade
$ renpy.pause(1.0, hard=False)
scene bg TJThursday with slow_dissolve
$ renpy.pause(2.0, hard=False)
scene bg motelfull
with slow_dissolve
window show
play music "neutral.ogg" fadein 3.
"Há uma pulsação insuportável na mimha cabeça quando acordo, um resquício da dor de cabeça extrema que eu estava ontem."
"Eu tomo um pouco de Paracetamol quando o TJ entra no banheiro para que ele não veja."
"Não quero deixar ele preocupado."
"Enquanto ele está tomando um dos seus banhos insanamente longos, eu vou até a recepção para pegar um pouco de café da manhã."
"Quando volto ao quarto, balançando dois pratos cheios de bagels, bacon, e ovos, fico surpreso que o TJ já terminou."
"Ele está ocupado penteando seu pelo no espelho, tentando arrumar sua aparência cômica e afofada."
show TJ at farright with dissolve
t "— Não acredito que eu esqueci meu shampoo... olha o quão ridículo eu tô!"
"Ele estende os braços para mim e a Jenna."
"Jenna grunhe, sem prestar muita atenção emquanto digita furiosamente em seu notebook."
m "— Eu acho meio fofo."
"TJ sorri."
t "— Você quer dizer engraçado."
m "— Não, cê só parece meio gordinho."
show TJ Surprised with dis
"Dou um sorrisinho para o olhar mortificado do TJ enquanto ponho os dois pratos na mesa o que força a Jenna a afastar seu notebook por um momento."
show TJ Sheepish with dis
"TJ abre um pacote de geleia e manteiga amtes de colocá-los perfeitamente sobre o bagel cortado no meio."
"Eu observo enquanto um pouquinho gruda no longo pelo por volta de sua boca quando ele dá uma beliscada."
"Ele se limpa com um guardanapo, apenas para fazer a mesma coisa de novo"
t "— É bem triste que você vai passar todo seu tempo fazendo trabalho escolar, Jenna."
show Jenna at farleft with dissolve
j "— Eu vou ter duas provas na Segunda que voltarmos, então é bastante necessário, TJ."
"A Jenna nem tira o olhar do seu notebook quando responde, focada apenas mo que quer que ela esteja digitando."
"Eu tenho bastante certeza de que ela só enfiou metade de um bagel em sua boca amtes de começar a trabalhar."
"TJ senta alí quieto por um momento, dando outra mordida."
t "— Você acha que vai ter tempo pra fazer alguma outra coisa hoje?"
"Jenna não responde por alguns segundos, o único som sendo os leves toques do teclado."
"Finalmente, ela para e levanta seu olhar para nós pela primeira vez em provavelmente uma hora."
j "— Eu acho que não. Eu tenho muita coisa pra fazer. Por que vocês dois não saem e fazem algo?"
t "— A gente vai! É só que seria legal se você viesse com a gente."
"Eu expiro."
m "— É, se você viesse com a gente pra fazer MAIS trabalho na casa da Janice DE NOVO."
"TJ abaixa as orelhas."
j "— De novo?"
"TJ dá outra mordida em seu bagel e não parece que ele vai dizer alguma coisa."
"Eu suspiro."
m "— É, ela meio que encurralou ele e fez com que ele dissesse que faria mais trabalho."
"Jenna revira os olhos e retorna sua atenção para o notebook."
show Jenna Annoyed with dis
j "— Janice tirando vantagem das pessoas? Chocada."
t "— Jenna..."
"TJ protesta quietamente."
j "— Sabia que ela costumava me contar uma historinha triste na lanchonete pra me fazer dar mais gorjeta?"
"TJ franze a testa."
t "— Bem, ela realmente tem uma vida difícil, Jenna."
"Mesmo estando incomodado por ter que voltar para a casa da Janice, eu me encontro concordando com o TJ."
m "— Eu acho que cê faz o que quer que você consiga aqui pra fazer dimheiro. Provavelmente é difícil ter uma casa só como garçonete."
j "— É, bem, talvez não seja uma garçonete em uma cidade fu–de merda. Ela poderia pelo menos TENTAR achar outra coisa se é tão difícil assim."
"TJ ainda está franzindo a testa, suas orelhas abaixadas."
"Eu percebo que ele quer falar mais alguma coisa, mas a Jenna é uma figura intimidadora para tentar se discutir."
"Fica um silêncio por outro minuto antes da Jenna suspirar bem alto."
show Jenna Depressed with dis
j "— Desculpa, eu só tô um pouquinho estressada agora. Eu tenho um montão de coisa pra terminar."
t "— Tudo bem. Eu queria que a gente pudesse te ajudar nessa."
"Jenna ri sem graça."
j "— Eu também queria."
"TJ fica quieto, olhando para o pequeno pedaço de bagel segurado entre seus dedos."
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"Meu celular vibra no meu bolso e eu pego-o, surpreso em ver uma mensagem do Carl."
call text_chase("carl") from _call_text_chase_1
call text_0("", "Eiiiii") from _call_text_0_1
""
#c "\"Yooooo\""
"Eu fico olhando para ela por um momento."
m "— Uhm."
play sound "texting2.ogg"
$ renpy.pause(1, hard=False)
call text("m", "oi") from _call_text_4
#"I type a quick \"hi\" back."
""
show TJ with dis
t "— Quem é?"
call text_end from _call_text_end_1
"TJ pergunta por volta de sua última mordida no bagel, segurando delicadamente um guardanapo na frente da boca enquanto mastiga."
m "— O Carl."
"A digitação da Jenna para novamente."
show Jenna with dis
j "— Sério? Como ele tá?"
m "— Sei lá. Acho que tá bem."
"Foi então que percebi que não tinha tido a chance de perguntar à Jenna, ou a qualquer outra pessoa o que tinha acontecido com o Carl ontem."
t "— Aonde ele tava? O Leo disse que vocês acharam ele."
j "— É."
"Jenna pausa, olhando para a tela de seu notebook."
m "— O que rolou?"
j "— Eu realmente não sei. Flynn found him in the crawl space, apparently."
t "— The crawl space?"
"For some reason I get chills running up my arms."
t "— What in the world was he doing down there?"
"Jenna shakes her head."
j "— When I went down there he was just sitting on the ground and Flynn told me to leave."
"I raise my brows and TJ gives me a confused look."
j "— He was standing in front of him so I couldn't see him, like, if he was upset or something."
m "— What was he doing?"
"Jenna shrugs."
j "— Flynn took him upstairs and we left after that."
t "— Was he like, drunk, or something?"
"TJ seems to try and word it delicately."
"Jenna shrugs again, then turns back to her writing."
j "— He's always high, isn't he?"
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"I look back down at my phone."
call text_chase("carl") from _call_text_chase_2
call text_0("", "Wnna hng out,") from _call_text_0_2
#c "\"Wnna hng out,\""
""
"Is he THAT high right now?"
"It takes a second to figure it out."
"When I do, I look back up at TJ."
m "— What time does Janice want us over?"
t "— We'll go in the evening, when it's not so hot."
"TJ looks down and lowers his ears again."
"Because I don't want TJ to get all apologetic again, I keep talking."
m "— Do you want to go hang out with Carl?"
"TJ smiles."
t "— Yeah! That could be a lot of fun."
m "— Alright, then."
play sound "texting2.ogg"
$ renpy.pause(1, hard=False)
call text("m", "Sure. TJ is also coming with me.") from _call_text_5
#"I type a reply back to Carl, telling him I'd be bringing TJ over."
""
"For some reason, though, I can't shake the feeling that something is off..."
call text_end from _call_text_end_2

scene bg parkinglotday with fade
play background "reststop.ogg" fadein 3.0
"Stepping out into the parking lot, TJ immediately starts heading for the road while I pause by the car, holding my keys."
m "— Um."
"TJ turns around."
show TJ at center with dissolve
t "— Hm?"
m "— Are we...are we walking?"
"I look up the road toward the foothills of the mountains, Carl's house an intimidating speck in the distance, barely visible through the heat haze."
t "— Oh, did you want to drive?"
"I shield my eyes against the sun, only just over the mountains, but still promising a hellscape by noon."
m "— I mean, did you want to walk?"
"I can see TJ's demeanor deflate a little bit as he starts walking back towards me and the car."
t "— We can drive!"
"He smiles at me, but I sigh and shove my keys back into my pocket."
m "— Naw, we can go for a walk. It'll give us more time to talk, anyway."
t "— Oh, okay!"
"TJ smiles and waits for me to catch up to him before we start up the road."
"While I'm not looking forward to trekking back to Janice's house in the heat, I'd rather TJ be in an upbeat mood."

scene echoroad with dissolve
stop music fadeout 3.0
"We're pretty quiet on the way up."
"It isn't until we're passing Janice's house that I finally break the silence."
m "— Man, why did you have to say yes?"
"I groan half-teasingly, shoving my shoulder into his, sending him stumbling a little ways into the road."
show TJ Sheepish at center with dissolve
t "— I'm sorry!"
m "— Is it so hard to say 'no'?"
t "— Well, yeah. It definitely is."
"I sigh."
m "— It would be fine if we weren't on vacation with friends we might never see again."
"TJ sulks a bit."
t "— Don't say that."
m "— It's kinda true."
"I remember that the trip is already sort of ruined because of Flynn."
t "— Anyway, it's not that easy, Chase, especially when she's all smiling and expectant like that."
m "— You should stop letting people take advantage of you."
"TJ stares at the ground."
t "— Sorry."
m "— And stop apologizing!"
"TJ flattens his ears and I realize that my tone might have been a bit too harsh."
m "— Okay, now I'M sorry. I was mostly joking, but it's frustrating to see you get pushed around—"
t "— I don't really get pushed around."
"I ignore him."
m "— —and get taken advantage of."
t "— She doesn't take advantage of me."
m "— Why do you think she only asks you for these things?"
"He opens his mouth, but I don't let him answer."
m "— Because she knows you'll say yes. That's basically the definition of taking advantage of someone."
"I nudge him again with my shoulder, but he manages not to fall into the road this time."
m "— You gotta be a little more assertive. Stand up for yourself more often."
"TJ shoves his hands in his pockets."
t "— So just say no to people?"
m "— Not just when it comes to saying 'no'. Stand up to people being mean to you, too."
"I don't mention Flynn, but I'm pretty sure he knows what I'm getting at."
"I try to give him an encouraging smile, but he doesn't look at me."
m "— It feels great, man. Once you do it once, you can't stop."
"TJ looks away, out into the desert."
t "— It sounds like you just want me to be mean to people."
"I shake my head."
m "— You can be nice and assertive at the same time. It's a good combination."
scene bg flashback1 with dissolve
"TJ's quiet for a few minutes as we start the painful, uphill portion of the trek towards Carl's mansion."
show TJ Neutral at center with dissolve
t "— I do it because I like to do it, you know."
m "— Hm?"
"I'm starting to pant a little, my short, stubby legs already burning."
t "— I like to help her out. It feels good."
m "— Like, it makes you feel better about yourself?"
t "— It makes me feel better about a lot of things."
"There's a sudden shift in his tone that cuts me off from saying anything else."
"It's a tone I'm not used to hearing from him and I wonder if I went too far with the whole \"being assertive\" thing."
"I feel like there's a whole lot more going on under the surface, but now doesn't feel like the time to delve into it."
"I try to think of something else to talk about, to change the subject."
m "— Anyway, maybe the apologizing thing is just part of your heritage?"
show TJ with dis
"TJ laughs, dispelling the tension easily."
t "— Maybe."
m "— Well, if you do go back at least you'll fit in with all the nice people."
t "— It's just a stereotype, and not all that true. There were mean people in Wasatchua."
m "— Not like here, though."
"TJ nods."
t "— Yeah, not like here."
"We're quiet for a few more minutes, Carl's house promisingly close now."
"I'm distracted, looking up at it when suddenly TJ shoulder checks me right off the road, tripping me over my own feet and into the sage brush."
play sound "thud.ogg"
with vpunch
m "— What the hell!?"
"I shout as I lay in the dirt, the dust cloud clearing to reveal a mortified TJ still standing on the side of the road."
show TJ Surprised with dis
t "— Oh my gosh, I didn't mean to knock you over, I'm so—"
"He catches himself, though the horrified look is still on his face."
"I stare up at him for a while, then burst out laughing."
"I see his tail and ears relax, his floofed out fur laying back down."
"He smiles, seemingly relieved."
m "— You're learning!"
show TJ Sheepish with dis
"He rubs his shoulder sheepishly."
t "— I guess so."

scene bg mansion with fade
play music "neutral.ogg" fadein 3.0
"We stand a good couple of minutes on Carl's doorstep, ringing the doorbell over and over."
"I can hear the heavy beat of some hip hop song through the door...and ground."
"I swear the windows look like they're about to bust out with how much they're shaking."
"Finally, I send him a text and that's when the music finally stops and the door swings open."
"As it does, TJ and I are blasted with a wave of pot with just a touch of booze lingering underneath."
"Carl grins at us, his eyes bloodshot and fur mussed up."
show Carl at center with dissolve
c "— What the fuuuuuuuck took you guys so long to get here?"
"TJ frowns, rubbing his nose inconspicuously."
"I don't think I've ever seen Carl this far gone."
"I stare at him as he stares back at us, his grin never wavering."
"I finally break the silence."
m "— Are you okay?"
show Carl Neutral with dis
"Carl suddenly gets a very serious look on his face."
c "— Chase."
"Gravely, he reaches out to put both his paws on my shoulders."
c "— I have—"
"He smirks, then sets his face sternly again."
c "— —never felt better."
"He brings me into a hug and whispers fiercely into my ear."
c "— I'm so glad you're here."
"He suddenly shoves me back and whirls on TJ, who cringes."
"Carl goes after him, sweeping him off his feet like the lynx is his brand new bride."
show TJ Surprised at right
show Carl

with dissolve
t "— Carl!"
c "— Get inside before you get a heat stroke, fluffcheeks!"
"I stand there on the doorstep as Carl takes the cat inside, TJ throwing me a wide-eyed look over the ram's broad shoulder."
hide Carl
hide TJ
with dissolve
"I stare back, wondering if this was such a good idea before stepping in."
stop background fadeout 3.0
scene bg livingroom with dissolve
"Pot smell aside, the coolness of the mansion is a welcome relief to the quickly rising heat behind me."
"I'm just in time to see Carl toss TJ onto a two-cushion couch before flopping onto a bigger one across from it."
"He smiles at me and pats the cushion next to him."
"I sit down on the last cushion, leaving a space between the two of us."
"I'm just a little worried about how handsy he's being right now."
"Carl shrugs and kicks up his feet on the cushion between us, tapping me with his hooves."
"We sit there for an agonizingly awkward ten seconds before TJ clears his throat."
show TJ Sheepish at left with dissolve
t "— So, Carl. How have you been?"
"Carl rolls his head on his shoulders to snap his gaze in the direction of TJ, who gulps."
show Carl at right with dissolve
c "— Teej-y, I've been just peachy. Ya get me?"
"TJ's ears twitch."
t "— Yes?"
c "— Super.. super-y."
"Carl giggles quietly to himself."
"He stares at the ceiling for a while, continuing to tap me with his hooves."
"I look down and see that they're leaving hoof-shaped prints of white dust on my pants."
c "— Man, I'm glad you guys are here. I thought I was gonna go crazy."
t "— How come?"
"Carl interlocks his fingers behind his head."
c "— This house, man. You go crazy in it when no one's around. Flynn spent the night but then he had to go to work."
show TJ Neutral with dis
t "— Ah."
"TJ seems to have run out of things to say, leaning back on the couch as his tail twitches around nervously."
"Carl doesn't seem to mind though, staring peacefully at the ceiling."
"I exchange glances with TJ who shrugs worriedly at me."
"I look at the massive flat screen."
m "— You wanna watch something?"
"Carl flicks his eyes to the TV."
c "— Uuuuhhh.. have you seen the new Luche Lobo movie?"
"I have to think about that."
m "— Not since last summer, I think."
t "— I haven't."
c "— It's the fuckin' shit, dudes!"
"Carl sticks his legs in the air, swiveling on his butt before launching himself off the couch to land on his hooves awkwardly."
"He stumbles, falling into TJ's couch."
"The lynx tries to steady him, but the ram is off before he can, grabbing the remote."
"Suddenly, he spins around and tosses his phone at me and I have to lunge to catch it."
c "— Chase! Puh-lease order us a goddamn pizza. I'm starving!"
m "— Uh, what?"
"I stare at his phone."
"He sighs loudly at me."
c "— The Giano's app. Duh!"
"It takes me a second to find it in the sea of random game apps."
m "— Oh. So, uh, what do you guys want?"
c "— I'll shove anything from Giano's into my fat face."
"I stare at him."
c "— So order anything."
m "— Okay..."
"I end up letting TJ pick the toppings since he's got that special dietary where he can't eat gluten."
"Once I've ordered the extra-large pizza, Carl's already started up the movie."
m "— I didn't know anyone delivered out here."
"Carl sits down with a beer in his hand and I wonder if I should tell him not to drink anymore."
"Honestly, I don't know if the way he's acting is more due to the pot or the drink."
"He grins."
c "— That's what's so great about Giano's. They'll deliver anywhere if you pay."
"He takes a swig and belches."
c "— Price of delivery is the same as the fucking pizza, though."
"He stares at me before pointing at his beer."
c "— You want one?"
"I glance at TJ who's staring hard at the screen."
m "— Maybe I'll have one with the pizza. Me and Teej have some yard work to do for Janice."
show Carl Annoyed with dis
"Carl wrinkles his nose."
c "— Laaame."
t "— Do you want to go with us, Carl?"
"Carl thinks then gives a massive shrug."
show Carl Neutral with dis
c "— I can tag along. Might not be able to do any real work though."
"He pats his stomach."
c "— Swear to God, I'll hurl."
t "— That's fine."
"TJ smiles, but Carl seems to be watching the movie now which is already a few minutes into the intro."
stop music fadeout 5.0
hide Carl
hide TJ
with dissolve
"The pizza doesn't arrive for another hour and when it finally does the slices are almost room temperature."
"Still, with the pizza, beer, and a movie, I start to kind of enjoy myself."
"By the end of it, Carl seems to have sobered up a little bit."
"Not a whole bunch, but to the point where he's at least coherent."
"He turns off the TV and sighs, flat on his back on the couch at this point, his fetlocks across my lap."
show Carl Neutral at right with dissolve
c "— I'm fucking stuffed."
"I agree and now I'm feeling even less inclined to go over to Janice's place."
"TJ's pulled out his phone and now he's staring at it with his ears lowered."
"I'm about to ask him what's wrong, but that's when Carl nudges me with his leg."
c "— Hey, you guys wanna play a game?"
"I look at him cautiously."
m "— What kind of game?"
c "— Um."
"Carl looks around, then finds the row of three bottles on the ground next to the couch, two of them empty, one half empty."
show Carl with dis
play music "comeover.ogg" fadein 3.0
c "— Never have I ever!"
show TJ at left with dissolve
"TJ gives a nervous laugh."
t "— But Carl, I don't drink."
c "— Give it a try."
"I frown, giving Carl a look."
m "— Or we could just do Ten Fingers. You don't have to drink for that one."
"Carl pouts."
c "— Wow, you're boring as hell today, Chase. Alright, we'll do both. You guys can do the Ten Fingers bullshit."
"He struggles to sit up, burping again while he does."
"He leans over with a groan and picks up his beer."
c "— Okay, I'll go first!"
"I hold up ten fingers and TJ does the same, somewhat reluctantly."
c "— Never have I ever..."
"Carl seems to think hard, then grins."
show Carl Teasing with dis
c "— Had sex!"
show TJ Sheepish with dis
"TJ's ears flatten and I glare at Carl."
m "— Really? We're going there already?"
"Carl shrugs."
c "— What!? That's the first question everyone asks."
"I lower a finger, still glaring."
m "— Isn't this game about getting to know things about people that you don't already know about?"
"I look over at TJ, not surprised to see all of his fingers still up, though he's still blushing."
m "— I'm surprised you haven't, though. You've had girlfriends."
show Carl Annoyed with dis
"Carl sneers at me."
c "— Turns out having to lift up my own gut so they can suck me off turns them off. Never gone past that."
m "— So they still sucked you off."
c "— Blow jobs don't count."
m "— Uh, yeah they do. It's called oral SEX."
c "— Naw man."
"I suddenly become very aware of a beet-red lynx sitting across from us."
"I cough loudly and sit up straight, trying to think of something that's interesting, but still G-rated for TJ."
m "— Never have I ever.. been in a fight, a physical fight, I mean."
show Carl Neutral with dis
"Carl takes a drink, TJ's fingers stay up."
m "— Who did you fight?"
c "— The fuck have you been? Remember Clint?"
m "— Oh yeah..."
"TJ starts to lower his finger, too, then stops."
t "— Well, he mostly attacked us. We didn't really fight back, so it's not really a fight?"

play loop "hysteria.ogg" fadein 3.0
menu:
    "Grab him by the neck.":
        "Carl shrugs."
    "Throw him to the ground.":
        "Carl shrugs."
    "Kick him if he tries to get back up.":
        "Carl shrugs."
stop loop fadeout 5.0

c "— Me and Flynn have gotten into it before."
m "— Well, you already took a drink, so..."
"I look over at TJ."
m "— Your turn!"
"TJ looks off to the side, seeming to think hard."
t "— Never have I ever failed a test."
show TJ with dis
"TJ grins."
"I lower a finger, smirking, but Carl lets out a snort."
show Carl with dis
c "— Cute."
"The amount of disdain in his voice has me looking over at him, but he's already chugging down his beer."
"His burp seems to shake the couch."
c "— Alright. Never have I ever kissed a dude."
m "— Carl!"
c "— What? I've never actually seen you kiss Leo, so.. oh wait, maybe I have. Meh."
"He shrugs again."
"I lower a finger, rolling my eyes."
"TJ, of course, doesn't."
"As I'm trying to think of my own question, I suddenly feel something warm press against the side of my face."
show Carl Teasing with dis
"I blanch away out of instinct and turn to find Carl with his eyes closed and lips puckered."
show TJ Surprised with dis
t "— Carl!"
"TJ sits on the couch, his face a portrait of comically cartoonish shock."
c "— Alright, now I have!"
"Carl takes a big gulp of beer."
"I'm not sure how to react, but TJ's reaction is enough to make the whole thing seem funny.. instead of like sexual harassment."
show TJ Sheepish with dis
m "— I mean, you can't do it after the question's been asked, right?"
"Carl puts his chin on a fist, fluttering his eyes in a way he probably thinks is seductive."
c "— You can look it up if you want."
"I shake my head, wiping the side of my face as I try to think."
m "— ...Never have I ever flown in an airplane."
"Carl and TJ both lower a finger."
t "— Really? That's crazy!"
"I shrug."
m "— Hardly ever been out of the state in my life."
show Carl Neutral with dis
c "— That's tragic."
m "— It kind of is."
"And so it goes."
show TJ with dis
"The game continues for another twenty minutes, most of the questions innocent enough."
"Still, I notice that every time TJ takes his turn, Carl gets more and more agitated."
"Never have I ever done drugs. Never have I ever been late to class. Never have I ever gotten less than an A- in a class."
"Still, I can tell that TJ's directing it mostly at me."
"Partly because he's being mischievous, and partly because I think he's genuinely trying to figure me out."
"Carl's mood continues to sour though and it all seems to build until the sixth round."
t "— Never have I ever been in a car accident."
"I lower a finger."
t "— You've crashed before?"
"I mock glare at him."
m "— Why do you automatically assume it was my fault?"
t "— Oh, sor—I mean, uh."
m "— My dad was driving and we got rear-ended."
t "— Ohhh."
stop music fadeout 5.0
"That's when I notice that Carl hasn't spoken at all since the question was asked."
"I look over at him and see that he's got the bottle resting on his knee as he watches TJ."
"I lean over to poke at him."
m "— You okay?"
"He glances at me before turning back to TJ."
c "— You knew I'd been in an accident."
show TJ Neutral with dis
"TJ looks at Carl, confused."
t "— I did?"
c "— Yeah, I told you at the motel when you first got here."
t "— Oh! Yeah, sorry. I forgot about that."
c "— Yeah, okay."
"TJ continues to look confused."
"Carl stares at his lap for a while and I start to wonder if the game is over."
"Then he looks up and stares at TJ, rubbing his chin."
c "— Hmmm..."
"He seems to be thinking hard."
c "— Hmmm, never have I ever..."
"We wait."
show Carl with dis
"Carl smiles."
c "— Never have I ever killed someone."
play music "quiet.ogg" fadein 5.0
"What follows is dead silence."
"Carl stares straight at TJ, still with a smile on his face."
"TJ still looks confused."
t "— That's a weird thing to say..."
c "— Is it?"
"TJ freezes up, as if ice cold water had been dumped over his head."
"I look at Carl slowly, but he's not looking at me at all."
"TJ's clenched paws rest in his lap, his face expressionless, almost, as we both realize what Carl's getting at."
"We sit in that silence for what feels like almost a minute."
"Carl finally breaks the frozen portrait that we're all in, leaning back into the back of the couch."
c "— You know, my life has been going downhill since that happened?"
"TJ and I don't say anything, both of us watching Carl."
c "— School, grades, drugs, whatever. I dunno, seems like it all started after whatever it was that happened."
"Carl looks pointedly at TJ again."
m "— Carl..."
"My voice comes out shocked and bewildered."
"That seems to get through to him a little bit, his long ears flicking down briefly."
"TJ continues to stare back at him and I'm reminded of how he looked when Flynn was having a go at him."
"Carl finally looks down, away from TJ."
c "— So I was in the crawl space the other day and I found an old letter from Sydney."
"I don't say anything, neither does TJ."
"Carl waits a while, then goes on."
c "— I haven't opened it. It said it was a treasure hunt on the front."
"A treasure hunt."
"Sydney absolutely loved treasure hunts."
"He was always making them in his spare time."
"They were usually pretty bad and the \"prizes\" at the end were always pretty awful."
"It would always take some convincing on his part to get us to go on one."
c "— I don't know why I have it, but it's made me..."
"Carl stops talking and closes his eyes, pressing himself deeper into the soft cushions of the couch."
c "— Maybe if we knew what happened we could fix some of our problems..."
"TJ finally stands up and Carl's eyes snap open when he does."
"I watch him, too, having no idea what he's about to do."
"Because of the look on his face, I wonder if he's about to actually do something violent, attack Carl, or something."
"His expression is dark, not like I've ever seen him, even when Flynn was yelling at him."
"Instead, though, he just stands there for a few moments, staring at Carl."
stop music fadeout 5.0
show Carl Depressed with dis
"Carl looks away again, his ears lowered."
t "— Self-improvement starts with realizing what the actual problem is, Carl."
"That.. that didn't sound like TJ at all, not even the voice."
show Carl Rejected with dis
"Carl seems shocked as well as he finally looks up at the lynx."
t "— Stop blaming others and start blaming yourself."
"His voice is calm and smooth, but ice cold."
"TJ turns on his heel and stalks toward the door, his fur fluffed out."
"I finally snap out of it and stand up as TJ opens the door."
"I take one last look at Carl as he's slumped on the couch, his head down."
m "— I'll—I'll call you later, okay, Carl?"
"Carl doesn't say anything."
"So with that, I hurry out the door that TJ left open."

scene bg mansion with dissolve
play loop "reststop.ogg" fadein 3.0
"I catch up to the lynx about a hundred yards down the road, trying to match his brisk pace."
"It's late afternoon at this point and the heat hits me like a ton of bricks."
"Sweat already threatens to drip off my chin as I approach TJ."
"He slows down when he hears me panting, letting me catch up."
scene bg flashback1 with dissolve
"We walk in silence for a good fifteen minutes and I almost jump when TJ finally speaks up."
show TJ Annoyed at center with dissolve
t "— Can you believe he did that?"
"I take a few deep breaths, gathering the time I need to form a response."
m "— I.. I think he was just really high and drunk..."
"TJ shakes his head."
t "— He knew what he was saying."
m "— Sure, but...but his inhibitions are down."
"TJ isn't as upset as I thought he would be, at least not in the way I thought he would be."
"Instead, he seems more angry than anything."
t "— I think it's because he's been talking to—talking to Flynn...who knows what he's been saying to him."
"That could definitely be the case."
"TJ finally sighs and stares at the ground, his ears falling."
"I can tell he's about to finally start crying so I quickly put my arm around his shoulders."
m "— Hey, it's okay. He was seriously drunker than I've ever seen him. He's not gonna remember any of this."
"He doesn't look up."
m "— TJ, you are a HUGE reason why we've all stuck together at this point."
"TJ doesn't say anything and I see his eyes watering up."
"I could be making it worse, but I give his shoulder another squeeze."
m "— You're the glue. And like you said, Carl's blaming his own problems on everyone else. This has nothing to do with you."
show TJ Neutral with dis
"TJ sighs, leaning against me a little."
"I take this as a good sign and nudge him."
m "— Listen, let's get to Janice's place and get those chores out of the way. After that we can get some ice cream at Ray's okay?"
t "— Alright."
"TJ lets out a small laugh and we continue down the road for another ten feet like that."
"Then he suddenly pulls away from me, faces me, and hugs me tight."
"He buries his face in my chest as I feel his fingers clench into the back of my shirt."
"He holds me like that for a long time."

scene bg janicehouse with fade
"We get to Janice's house a good half an hour later, me covered in sweat, TJ airing out his shirt."
"It's five at this point, but the sun is still pounding down on the back of my head like a lead weight."
"Janice opens the door almost the second we knock and I can tell immediately that something's off."
"First of all, she's got no pants on."
"I catch a glimpse of her large, white panties before I snap my eyes back up, staring hard at the coyote's face."
"I can't see TJ, but by the funny way he's breathing, I'm pretty sure he's noticed as well."
"Janice spreads out her hands, grinning."
play music "neutral.ogg" fadein 3.0
ja "— Well I'll be. You made it!"
"We gawk at her for another few seconds before TJ finally squeaks out."
show TJ Sheepish at left with dissolve
t "— Y—Yeah, of course! Um..."
"Janice suddenly steps forward, towards the lynx, and cups his face in her hands."
"I keep my eyes up, trying to focus on her face."
"She squishes TJ's face to the point where his lips purse out a little bit."
ja "— You, TJ, are a lifesaver. You know that?"
"She says it sincerely and I can see TJ trying to pull back."
"Unfortunately, it also looks like the coyote has a good grip on his face because everything but his head moves back."
t "— Er...thankoo Danice..."
"TJ tries to speak from his squashed face."
m "— Um, Janice, what did you want us to do today?"
"I break in, hoping to move her attention away from ripping TJ's cheeks off."
"She seems to really be enjoying the tufts of fur there."
ja "— Oh, Chase, you're here too?"
m "— Yeah, we're gonna work on it together."
ja "— Well alright. How about I head out there and show you two?"
"My eyes flick down to her bottom half for just a second and I immediately regret it."
m "— You...You uh—"
"There's no way around it."
m "— You wanna get dressed first?"
ja "— Hm?"
"Janice looks down."
ja "— Oh that! Well I've just got to apologize now. I was in the middle of gettin' ready for work. I just forgot what I was doin'!"
"I glance at TJ, then quickly back to the coyote."
m "— Oh, well, we can wait—"
ja "— Nonsense! It'll only take a sec!"
hide TJ with dissolve
"I'm left open-mouthed, following the coyote automatically as TJ follows closely behind me."
"A quick glance around reassures me that there isn't anyone around at the moment, but if someone does come around..."
"Janice marches us out to the back, to the few wooden remnants of the shed we'd moved earlier."
"She points at the ground."
ja "— I want you two to dig a hole right here!"
"TJ stays just slightly behind me, as if using me as a shield to Janice's shameless immodesty."
m "— A hole?"
ja "— Yep! In a rectangle, from here...to here."
"Janice marks a line in the dirt with her foot before walking about five feet in the other direction and marking another line."
ja "— And three feet wide, at least three feet deep, if not more."
"I nod through her instructions, just trying to get through this as quickly as possible."
m "— Okay, what are we doing this for?"
"Janice stops, scratching the back of her head."
ja "— Hmm...a pool. Gonna have a pool back here."
show TJ Sheepish at center with dissolve
t "— A pool?"
ja "— Yeah, a nice little pool."
"She grins at us and I quickly nod at her."
m "— Okay, we'll get right to work. Shovels in the garage, right?"
"I'm doing everything I can to get her back inside."
ja "— Yep! Need anything else? I can make you lemonade before I leave."
m "— Naw, we'll just get water if we need it."
ja "— Well, alright. No need to finish it today if you can't. I know how hot it is."
"Janice turns to leave, but not before reaching out and pinching TJ's cheek almost viciously."
"He squints his eyes, ears flattening as he just stands there and takes it."
stop music fadeout 5.0
"And with that, she hums her way back to the house."
"I wait until I hear the door close."
m "— Oh my God, she's gone insane."
"TJ stays quiet, staring at the spot on the ground that Janice marked out."
m "— Seriously, maybe we should go."
t "— No...no. She's probably just having another off day, or something."
"I shake my head."
m "— And this is definitely not a pool."
"TJ kicks at the dirt and I shiver as I see a small spider skitter across the ground."
m "— Either she's lost it and we're doing nothing here.. or we're digging a grave!"
show TJ Neutral with dis
t "— Oh, come on, Chase."
m "— This was a bad idea."
"I hear the garage door opening and shut my mouth."
"A car engine starts up and then I see an old, rusty, white sedan pull out of the driveway."
"Janice waves at us and blows a kiss which I'm pretty sure is directed at TJ."
play sound "driveby.mp3"
"Then she peels off like she's drag racing to the diner that's less than a mile away."
m "— So who do you think she's on her way to murder?"
t "— Stop."
"I look back at TJ."
m "— You think she even put her pants on?"
"TJ shudders and looks back at the ground."
t "— Let's...let's just get this done, then I promise I won't do any more chores for her, okay?"
"I sigh."
m "— Alright. Just remember whose fault this is if this ends up being OUR grave."

scene janicehouseafternoon with fade
"The work is tougher than I thought it would be."
"We both start at opposite ends of the little...trench thing we're making."
"Janice said we should do more than three feet if we could, but if this whole thing is bullshit—"
"(which I'm sure it is)"
"—then I'm not doing any more than the minimum."
"I'm at least glad to see TJ returning back to his cheerful, bubbly self."
"We even almost get into a dirt clod war, but that comes to a quick end when I hit TJ in the thigh with a rock-filled one."
"About two hours later, the sun is comfortably low and we're a little over halfway done."
"It's at that point that I get a text message from Carl."
"I take a quick glance at my phone, seeing a one word apology of 'sorry'."
"I look at it for a while until TJ finally peers up."
show TJ at center with dissolve
t "— Everything okay?"
"I debate whether or not to tell him, now that he's in such a good mood."
"It's hard to tell exactly what will make TJ feel better or worse, I've come to realize."
"Still, I think he can tell who it's probably from already, judging by how slanted back his ears are."
m "— It's from Carl. Just says sorry."
show TJ Neutral with dis
t "— Ah."
"TJ stops digging, pressing his shovel into the darker, moist dirt at the bottom of the trench."
t "— That's it?"
m "— That's it."
t "— Are you going to respond?"
m "— I don't know. Should I?"
"TJ starts digging again."
t "— Yeah."
stop loop fadeout 5.0
play music "intimate.ogg" fadein 10.0
"TJ tilts his head down."
t "— I need to apologize, too."
"Now that seems more like TJ."
m "— Well, what should I say?"
"TJ stops digging again and looks up at me."
t "— Um..."
"I look up at him expectantly."
t "— Okay, so I'm trying to be more assertive, like you said."
m "— O—Oh?"
"I didn't expect him to say that."
m "— Is that why..."
"TJ looks down, so I stop myself."
"Is that why he'd acted so strange at Carl's mansion?"
m "— Sorry, never mind. What were you saying?"
t "— So I'm just going to say this. I was thinking about that treasure hunt Carl found."
"For a moment I don't know what he's talking about."
m "— Oh, the thing he found in the crawl space?"
t "— I was thinking..."
"TJ leans on the shovel's handle, looking away."
t "— Thinking that we should open it...together."
m "— ...Oookay."
"I say it slowly, realizing how delicate of a topic this is."
m "— Is there a reason why you want to open it?"
show TJ Rejected with dis
"TJ sighs deeply, looking up at the deep, red and orange sky."
t "— I feel like.. I always feel like things happen for a reason and we were just talking about finding closure yesterday."
m "— Okay."
t "— So—I feel like this might be a way to do it, maybe? Read what h—he had to say. Maybe go on one of his last hunts."
"TJ swallows hard."
"I can sort of see where he's coming from."
"Sydney always wrote stupid riddles and stories with his treasure hunts. It might mean something to read something he wrote so long ago."
m "— Okay."
"I keep coming up short with what I want to say."
"Again, I can see why TJ might think this is the answer, but I'm not so sure."
m "— Well, um, I guess I can ask Carl about it...did you want everyone there?"
t "— Maybe...maybe just us. We can let the others read it later if they want. I don't think Flynn..."
"I nod quickly."
m "— Yeah, that makes sense. So you, uh, wanna do that tomorrow?"
t "— Um, see if we can do it tonight. We've only got a few days left and this is making me nervous."
show TJ Sheepish with dis
"TJ gives a tight laugh."
m "— Yeah, Sydney's treasure hunts could be pretty elaborate."
t "— Oh yeah, definitely."
"Are we starting to be able to talk about him normally again?"
"Maybe TJ is right about this."
m "— Okay, I'll text him back and ask if I can call him."
t "— Okay."
#"It takes me a little bit to figure out how to word TJ's request, so I just decide to ask if we can come over and talk."
"It takes me a little bit to figure out how to word TJ's request."
call text_chase("carl") from _call_text_chase_3
$ renpy.pause(0.5, hard=False)
play sound "texting2.ogg"
$ renpy.pause(1, hard=False)
call text_0("m", "Hey man. Can TJ and I come over and talk?") from _call_text_0_3
""
call text_end from _call_text_end_3
"While we wait for Carl's response, TJ abruptly looks back up at me."
t "— Are you and Carl, um, friendly with each other?"
m "— Huh?"
t "— I mean, how he kissed you..."
m "— What!? No!"
"I laugh."
m "— That was just Carl being drunk."
t "— Okay."
"TJ goes back to digging, his ears twitching around."
"I grin."
m "— What, are you jealous?"
show TJ Surprised with dis
t "— No!"
"He says it way too fast and loud."
m "— Hey, if you wanna give me a kiss I don't mind."
"TJ doesn't respond, instead focusing hard on the ground he's digging up."
m "— Aww, if you're shy I can do it instead."
"I see his eyes widen but he still doesn't say anything."
"I make kissy sounds at him and that's when he flings some dirt up at me, smattering my pants with dark brown spots."
m "— Aww, come on!"
show TJ Teasing2 with dis
"I see TJ smirk as he goes right back to work."
stop music fadeout 10.0
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"I'm thinking about picking up another dirt clod, but that's when my phone buzzes again."
call text_chase("carl") from _call_text_chase_4
call text_0("", "Okay.") from _call_text_0_4
""
#c "\"Okay.\""
call text_end from _call_text_end_4



scene bg mansion with fade
play music "neutral.ogg" fadein 3.0
"We walk slowly up the length of Carl's driveway, our shadows covering its entire length in the light of the sunset."
"TJ's starting to drag his feet again as we get closer to the door and I stop to look back at him."
m "— You okay?"
show TJ at center with dissolve
t "— Yeah, I'm good!"
m "— You sure? We don't have to do this today. We can come by tomorrow."
"TJ shakes his head, taking a swig of water from a water bottle we'd bought from the convenience store on the way here."
t "— No, I'm just a little tired. It's been a long day."
m "— Yeah..."
"I wait for TJ to catch up, then match his stride as we make our way up the sidewalk, then up the steps to the door."
"TJ doesn't do anything, instead just gripping into his water bottle, making the plastic creak."
"I wait another second, then reach out across TJ to press the doorbell."
"The faint, fancy chime emanates from behind the door for a few seconds, followed by the clopping of Carl's hooves on the wooden floor."
"There's a pause once he reaches the door, and I imagine him hesitating as he reaches for the door handle."
"A second later, though, it swings open, revealing a very bleary, red-eyed ram."
show Carl Rejected at right behind TJ with dissolve
"Carl blinks at us a few times through the bright orange sun behind us."
"Finally, he steps aside, opening the door wider."
c "— Hey guys..."
"There's a pause as I wait to see if TJ will say anything."
"When he doesn't, I clear my throat and step forward through the door."
stop background fadeout 5.0
scene bg livingroom with dissolve
m "— Hey, man. You okay?"
show Carl Rejected at center behind TJ with dissolve
c "— Not really."
"I don't say anything in return, instead spreading my arms out in the cool air of the mansion."
"I turn around and wait as TJ steps through the doorway, the lynx framed by the golden sunlight, the fine hairs of his fur lit up like white-hot wires."
"I see Carl's hand that's not on the door sort of twitch, like he's grabbing something in the air."
c "— Hey..."
"TJ stands next to me, looking back at Carl."
show TJ Neutral at farleft with dissolve
t "— Hello."
"Carl rubs vigorously rubs at his arm."
c "— Listen..."
"Carl pauses."
"I get the idea that he's wanting TJ to tell him that everything's okay so that he doesn't have to explain anything."
"That would definitely make things easier."
"But he doesn't say anything, just watches the ram."
"Carl rubs behind his head for a second, looking back out the door."
"I'm not sure why it's so hard for him to apologize to TJ."
"I had thought it was weird that Carl had apologized to me instead of the lynx in the first place."
c "— Listen..."
"Carl takes in a big, shuddery breath, blowing it out loudly."
c "— I was really, really fu—messed up earlier. I wasn't thinking right."
"TJ continues to watch Carl silently."
"His ears are up, at least."
"Carl stutters and stumbles over a few more syllables before he continues."
c "— A—and I just wasn't thinking straight."
"He scuffs the hardwood floor loudly with a hoof."
c "— And I don't think you did anything like that. I was just pissed off..."
"TJ is quiet for a few more seconds, but Carl doesn't offer anything more."
t "— So.. why were you angry?"
"Carl sighs, then leans his head back against the door, his horns knocking loudly against it."
c "— You said some shit that I'm asshurt about, okay? It wasn't your fault."
"TJ folds his arms, looking down."
t "— Well, wha—what was it I said?"
"Carl shakes his head."
c "— Stupid shit, I mean stupid because of me. Stuff about school, car accidents, just brought old stuff up for me."
t "— Oh..."
c "— But I don't think you ever did anything like I said...I was just being a huge dick. Sorry."
"His voice breaks a little at the end and he quickly looks at the floor, his ears down."
"TJ is again quiet. I think about changing the subject now that the apology is out of the way, but TJ speaks first."
t "— Thanks, Carl...and I'm sorry I brought stuff up like that. I'll try to remember in the future."
"Carl shakes his head, looking back up."
c "— Not your fault."
"We stand there awkwardly for a few more seconds."
t "— I guess...I thought maybe Flynn had been saying stuff to you, that was why you said it..."
c "— Huh? Oh..."
"Carl's non-denial hangs heavy in the air."
"I haven't seen Flynn in days and I am wondering what he's been up to in that time."
"I'll have to ask Carl when TJ isn't around."
"As of now, though, I want to change the subject because things are getting awkward."
m "— So, uh, TJ had an idea about the scavenger hunt thing."
"Carl looks at me as if just now realizing that I'm there."
c "— Scavenger hunt?"
t "— Oh, yeah, the treasure hunt."
show TJ Sheepish with dis
"TJ scratches his arm, looking embarrassed."
show Carl Neutral with dis
c "— Sydney's treasure hunt?"
"TJ scratches harder at his arm, looking more and more flustered, so I jump in."
m "— Yeah, we were thinking about actually doing it to...maybe find some closure?"
"Carl frowns."
c "— Really?"
show TJ Neutral with dis
"TJ stops scratching at his arm, his ears coming back up."
t "— Yeah...yeah, I—I believe things happen for a reason. That you found it now while we're all here means something, I think."
c "— Man...I mean, it's really old. You even think any of that stuff would be out there right now?"
t "— Maybe, but I guess I'm not really looking to find anything. It's like a thing we can do while we...remember him."
m "— I think it's a good way to find closure."
"I try to back TJ up under Carl's somewhat bewildered stare."
"The ram strokes his chin."
c "— I guess that sort of makes sense. I mean, if you're okay with doing it."
"TJ squares his stance, looking up."
t "— I am...it's been so long feeling this way. I feel like this might be my...our last chance to do...something."
"Carl looks over at me."
"I nod, indicating I feel the same way."
"I don't fully understand this new direction in TJ either, but I sure as hell supported him."
stop music fadeout 10.0
c "— Well, okay then. I'll go grab it. You wanna just open it now?"
t "— Let's...let's go to the motel, or something, with Jenna there, too."
c "— Okay."
"Carl finally shuts the door before making his way to the stairs."
hide Carl with dissolve
"TJ seems to deflate then, his shoulders hunching back in."
m "— That wasn't so bad."
"I mumble to him once I think Carl's out of earshot."
show TJ Neutral at left with moveinright
t "— Yeah, it was okay."
"We stand there awkwardly as we wait."
"The whole situation is so strange."
"Carl comes back with a crumpled-looking white envelope in his hands."
"TJ eyes it, the fur standing up on the back of his neck."
c "— So, uh, you dudes wanna drive back to the motel or—"
m "— Actually, we didn't drive."
"Carl drops his hands to his sides."
c "— Are you fu—reaking serious? I can't walk in that heat."
m "— TJ did."
"I tug up some of the fur on the lynx's neck to show Carl."
"TJ actually jumps a bit and I quickly let go. I want to ask him what's wrong, but Carl keeps talking."
c "— Man, I'm gonna smell like shit once we get there."
m "— The sun's almost gone anyway."
show TJ Neutral at farleft with moveinleft
show Carl with dissolve
"Carl smirks at me."
c "— I sweat walking in the winter time."
m "— You can take a shower at the motel."
"Carl blows his breath out loudly, frowning."
c "— Okay, but I'm gonna put on more deodorant before we go."

scene sunset with fade
"The walk back isn't so bad."
"Carl makes it out to be a lot worse than it is with all his gasping and wiping his face constantly."
"TJ gets a text from Jenna to meet at the diner instead of the motel since she's going there for dinner anyway."
scene bg diner with dissolve
play music "neutraldiner.ogg" fadein 5.0
"Once we walk in, Carl lets out a gasping groan of relief that turns a few heads."
"Jenna looks up from a corner booth and waves at us."
"I wave back and start making my way over."
c "— Goin' to the bathroom; gotta wipe my pits."
"TJ makes a sour face as he follows me to the table."
"Jenna scoots in so we can slide in next to her."
show Jenna at right with dissolve
j "— So what's this all about?"
m "— Carl found a treasure hunt that Sydney made."
"Jenna toys with her brown, leather purse, staring at it."
j "— Oookay. Like, a map, or something?"
m "— A letter."
j "— What are you going to do with it?"
m "— Well..."
"I look over at TJ, but he doesn't say anything, instead looking out the window at the sunset."
m "— We're thinking about doing it."
j "— You're thinking about going on the treasure hunt?"
m "— Yeah."
j "— I mean—"
"Jenna pauses, clearly trying to choose her words carefully."
j "— I mean, would there be anything left of it at this point? It would have to be at least eleven years old by now."
"Jenna looks over at TJ, studying his reaction."
show TJ Neutral at center behind Jenna with dissolve
"He doesn't give her anything, though, still staring out the window."
"I spread my hands out on the table, instantly regretting it as I feel the grease slide around under the pads."
m "— We're seeing it more as a closure sort of thing...a send off. We're not really expecting to find something."
"TJ finally looks back at us."
t "— He made it for us, so I feel like we should do it...for him."
j "— Hmmm..."
"Jenna stares back down at her purse."
j "— I guess Flynn won't be involved?"
m "— No."
j "— And Leo?"
t "— He's going to be busy for most of the week. I don't think he'd really want to anyway."
j "— Why not?"
"Now TJ looks like he's trying to choose his words carefully."
t "— He pretends like it never happened. I don't want to bring it back up for him."
"No one says anything else until Carl shows back up, the fur on his head and face a little wet."
show Carl at left with dissolve
c "— Hey, Jenna."
j "— Carl."
"Jenna nods at him as he sits across from me."
"He reaches across the table, snatching up a menu from the metal holder in the center."
c "— I'll pay if anyone wants something."
"Jenna curls a lip in disgust, but I'm starving so I start browsing the menu as well."
"TJ goes back to staring out the window and I can see his ears twitching around."
j "— Sooo, where's this treasure hunt thing?"
"Carl looks up and sees that Jenna's staring at him."
c "— Huh? Oh I have it. I'm gonna order real quick though if Chase is ready."
"I nod and Carl waves his menu at Janice who quickly bustles our way with a tray of glasses of water."
"She's wearing pants now, but there's definitely still something off about her."
"Her eyes are wide, her smile more like a grimace as she sets down our glasses and straws."
"She takes our orders well enough, though, and Jenna waits patiently as Carl and I order a meal and TJ gets a smoothie."
"Carl methodically tears off one end of the wrapper off his straw before he blows on the other end, shooting the rest of the wrapper at me."
"I flinch and try to catch it, failing as it falls to the floor."
"Jenna clears her throat loudly."
j "— So, where is it?"
"Carl looks at her, the straw still in his mouth."
c "— Huh? Oh right."
"Carl reaches into his pocket then pulls out the envelope."
"He pushes it onto the table, face-up."
"There's writing in black marker on the front;"
"\"Tresure Hunt Number 7!"
"We all stare at it."
c "— Uh, should I read it?"
"Carl sets a hand down on the letter."
c "— Or...someone else?"
"Carl's eyes briefly flick over to TJ, then quickly look back down at the letter."
"TJ's hand comes up, then surreptitiously scratches at an ear before letting it fall back into his lap."
"It does seem appropriate that TJ open it, but if he doesn't want to..."
"Carl looks just as hesitant, so I finally reach out and gently slide it out from under his hand."
stop music fadeout 3.0
m "— I can read it."
"No one objects, so I open it carefully, not wanting to rip anything as I pry the adhesive apart."
play sound "creepyswell.ogg"
"A chill goes up my spine for some reason."
"A strange, surreal vision comes to my mind's eye of inky blackness leaking out of the envelope, spilling slowly across the table."
"I can feel it, too, like a cold draft is wafting from inside."
"I pause, feeling an emptiness in my chest."
"What the hell?"
"I give my head a small shake, breaking out of the trance."
"I guess it's only natural I feel this way."
"That's Sydney's handwriting on a letter sealed after he licked it."
"He loved making these treasure hunts."
"It's really sad, so it makes sense that I'd feel this sudden drop in mood."
"I swallow as I continue to pry it open, the feeling getting worse and worse as I do."
"When it's finally fully opened the feeling slowly subsides."
"Tension in the air seems to melt away, too, like the whole town just let out a sigh of relief."
"I look up for a moment at the others, wondering if they're feeling the same way."
"It's hard to tell as they're all looking intently down at my hands."
"I quickly look down again and stick my fingers inside, feeling a piece of paper catch on a pad."
"Gently, I press down on it and slowly slide it from the envelope."
play music "loneliness.ogg" fadein 3.0
"It's bright white copy paper, folded once in half."
"It's been creased so long that it's starting to part at the fold, in the middle part so that the edges are barely holding it together."
"Black blotches bleed through the paper, probably written with the same thick marker that was used for the envelope."
"I gently unfold it, not wanting to rip it apart more than it already has been been."
"The big, blocky black letters are sloppy and childish."
"Even though it's only a few sentences, it covers the entire page."
"The last few words trail off into a tiny, almost illegible scrawl."
"It droops off down the side of the paper as Sydney realized he'd ran out of room at the end."
m "— Okay...um..."
"I clear my throat, then start reading aloud."
"\"Welcome to tresure hunt number 7! This is the biggest one so far and it took a long time!\""
"\"So no cheating this time (I'm talking about you Carl and Chase no skipping steps!)\""
"\"First clue: These things fly really high, its in there home with my comb.\""
"\"(Chase you dont have to do this one i know you hate it! you'll see if you figure it out.)\""
"\"Good luck guys!\""
"\"-Syd\""
stop music fadeout 10.0
show Carl Neutral
show Jenna Depressed
with dis
"I feel my throat close up just a little as I stare down at his name."
"He always wanted to go by Syd, but it never stuck so none of us ever did."
"It just didn't suit him."
"I look back up at the others."
"Carl is still staring at the paper and TJ's looking out the window again."
"Jenna has a hand up to her mouth, staring as well."
j "— Wow..."
"Then she wipes at her eyes and I look away."
"I guess I never really thought about how this might affect Jenna."
"She and Sydney never really got along because of the way he treated TJ."
"But still, he was just a kid, like the rest of us."
"Carl lets out a ragged cough."
c "— Uh, that whole cheating thing was totally you, Chase, not me."
play music "neutraldiner.ogg" fadein 5.0
"I look up at Carl, raising a brow."
m "— You're the one that told me to do it."
"Carl smirks."
c "— And you're the one that did it."
t "— What did you do?"
"TJ asks quietly from his corner, finally looking away from the window."
m "— Well, Sydney liked to reuse certain hiding spots. I mean, there were only so many places he could use."
c "— Yeah, and Chase went straight to Sydney's mailbox and ruined the whole thing like a boss."
m "— I was like, eight!"
c "— Turns out it was the last spot and he got the 'prize'."
"Carl makes finger quotes around the last word."
m "— Yeah, one of those plastic clapper things we used to get in elementary school for reading a lot."
c "— He was so mad."
m "— Yeah..."
"I remember dropping it on the ground because of how lame it was."
"I also remember Sydney crying, but I'm not gonna bring that up."
"Carl seems to have at least lightened the mood, though, and Jenna's stopped wiping at her eyes."
"I'm starting to think TJ was right about this whole closure thing."
m "— I know where he's talking about for this one, though."
"I tap the paper with a finger."
c "— Yeah, it's the birdhouse."
j "— Birdhouse? Where is that?"
t "— The forest."
"TJ sits up straighter, ears up as well."
t "— The birdhouse is on one of the trees close to the road."
j "— Oh, well, I never went in there because of all the shit—sorry, stuff that would get in my fur."
"TJ looks back out the window, the sun gone now, though the clouds in the sky are still tinged red."
t "— You guys want to do it tonight?"
c "— Really? It's getting kinda late and we still gotta eat."
"Carl looks eagerly over at the front counter, through the small rectangle that lead to the kitchen."
t "— We can use Chase's car. Besides, it might be kinda fun in the dark..."
"TJ adds the last bit meekly."
show Carl Annoyed with dis
c "— Uh, hell no?"
j "— As long as you guys know where it is it shouldn't be a problem."
"I gently fold the letter back up and start tucking it back into the envelope."
t "— Um, what was...what did he mean by saying you didn't have to do that one, Chase?"
"I look up at TJ, then back down at the letter as I gently press the lid of the envelope closed."
m "— I thought I saw something and got scared one time. Was a long time ago, though."
m "— At least that's what I think he was talking about."
show Jenna with dis
"Jenna clears her throat, seeming to have collected herself."
j "— I think I remember that. My parents told me about it."
"I frown."
m "— Really?"
"I didn't like the idea of that."
t "— What did you see?"
"I shrug."
m "— A person in the trees."
"A hanging person."
t "— Oh."
"TJ shudders."
c "— So hell fuckin' no to going there tonight, then? Sorry for the F-word, Teej."
m "— It's fine, I saw a lot of things as a kid."
"I'm not going to tell them how I'm definitely still scared of that place."
"Besides, TJ looks really eager to start this so I'm not gonna ruin it for him."
"But really, that's not what's bothering me right now."
"I look down at my hands as I try to work out a time line in my head."
"When was it that that incident happened in the forest?"
"I thought I'd been ten at the time since that was when I'd started going to a psychiatrist."
"And I'd started going because of that."
"But that would be impossible, because..."
show Janice Happy at farright
show Carl Neutral
with dissolve
ja "— Here we are!"
"A plate with a massive burger and steak fries lands in front of my face."
"The big coyote sets a smoothie down for TJ and an even bigger veggie burger down for Carl."
t "— Hey, Janice. Is Julian working today?"
"Janice smiles at TJ."
ja "— No, dear. He's only here when I'm not. He'll be in tomorrow if you're looking to find him."
t "— Okay, thanks."
"Janice then clutches her tray to her chest and watches us for a moment."
ja "— Listen, Chase and TJ, why don't you come by my house again when you get the chance?"
"I look up at Janice and see that she's got a strange look on her face, confused and worried looking."
t "— What's wrong, Janice?"
"TJ's voice is full of concern."
t "— Did we do something wrong?"
ja "— No, no! You did everything wonderfully! I just want to have a talk about the way I acted the past few days."
"Janice lets out an exasperated-sounding laugh."
ja "— Not really sure what came over me. Just now realizing how strange it all was."
"She glances at Carl."
ja "— But we can talk about it later, in person. Enjoy your dinner!"
hide Janice with dissolve
"She bustles off, tray still held against her body."
"Carl watches her go, stuffing a few fries into his mouth."
c "— What was that about?"
m "— Um..."
"The way Janice had looked at Carl makes me think she doesn't want him knowing about what had happened."
m "— I think she just feels bad for making us work so much."
"I look over meaningfully at TJ."
t "— Oh! Uh, yeah, maybe..."
"TJ quickly starts sucking on his straw."
j "— Well, she should."
"Jenna's sitting back in the booth, having taken out her brush to start grooming the fur on her face and head."
"I inconspicuously slide my plate a little further away from her."
m "— Well, once we finish we can go get my car and head to the forest."
stop music fadeout 5.0
"As I lift my burger and take a bite, I look over at the counter where I see Janice leaning over her notepad."
"Her shoulders are shaking and it takes me a moment to realize that she's crying..."

scene bg forestnight
show nightoverlay
with fade
"The \"forest\" is really just a patch of trees on the side of the road near Leo's house."
"While it's technically small, it still covers several acres which is enough to get lost in."
"The sky is a soft blue now, just enough light to see by."
"It won't be long before that won't be the case, though."
play sound "engineoff.mp3"
"I pull off to the side of the road in the spot where I think the birdhouse might be."
play music "quiet.ogg" fadein 5.0
"It's been well over a decade since the last time I've seen it."
"This is probably where the treasure hunt is going to end considering the time that's passed."
"The birdhouse probably isn't even there anymore."
"We all step out of the car into the warm, evening air."
show Carl at center behind nightoverlay with dissolve
"Carl folds his arms on the hood of the car and grins at me."
c "— See? Even with the sun gone it's roasting. 'Least you can drive me home now."
m "— Yeah."
"I look over at Leo's house, but his truck is gone."
"TJ catches my glance."
show TJ Neutral at left behind nightoverlay with dissolve
t "— I might tell him what's going on if we find something and you want him to join us."
"TJ picks at his claws."
m "— It's alright."
"I give him a quick side hug as we step up to the edge of the trees."
"I can see why TJ doesn't want to tell Leo about this."
"He was right about Leo pretending it didn't happen."
"I can't imagine it would go well if we told him about drudging up old Sydney scavenger hunts."
show Jenna at right behind nightoverlay with dissolve
j "— So, where is it?"
"Jenna looks into the empty ditch between us and the forest, wrinkling her nose at the old scraps of garbage inside."
c "— Well..."
"Carl looks up and down the tree line, squinting."
c "— It kinda looks different now, but I think it's about here. It's only like, ten feet in, right?"
"Carl looks at me."
m "— That sounds about right."
t "— We can fan out and check all the trees that close to the road."
hide TJ with dissolve
"TJ jumps across the ditch lightly, much more lightly than the clumsy hop I execute right after."
hide Carl
hide Jenna
with dissolve
"I land unevenly on the opposite incline and windmill my arms as I lean back."
"Carl starts laughing before I even fall, but TJ reaches out and grabs me by the shirt, yanking me back up from the ditch."
show TJ Neutral at center behind nightoverlay with dissolve
"I fall into him awkwardly and quickly step back, brushing myself off, even though there isn't anything on me."
t "— Are you okay?"
m "— I'm fine, thanks."
"I glare over at Carl who's still laughing."
c "— Did you even try, man?"
"He leaps over easily, clearing the ditch along with a few more feet."
m "— That's not fair, I'm an otter."
show Carl at right behind nightoverlay with dissolve
c "— Don't let that hold you back from achieving your dreams."
"Jenna elects to delicately step around the garbage before climbing up the other side."
t "— It's okay, you swim better than any of us, Chase."
"I sigh."
m "— Thanks, TJ."
"I turn back to the forest which is much darker as the light struggles to filter through the branches and leaves."
m "— Well, let's start before it gets too dark."
scene bg forestnight
show nightoverlay
with dissolve
"As we spread out amongst the trees, I'm struck with how quiet it is."
"The only sound is the crunch of our feet on the dead vegetation and that starts to fade as the others move further away from me."
"I zigzag through the trees, trying to get a look at their full circumferences."
"From what I remember, the birdhouse was a plain old wooden thing that hardly stood out from the trunk that it was attached to."
"We might not see it even if we were looking right at it."
"While it's been a long time, walking between these trees does bring back some memories."
"We stopped coming here after what happened to Sydney, mainly because this was his favorite place to hang out."
"He liked to play capture the flag here."
"I can still remember how fast he was, how I'd only catch glimpses of his tail between the trees before he disappeared with the flag."
"His team won almost every time."
"The summer of 2002 was the last time we played."
"Sydney had even been getting along better with TJ then."
"That might have been the best summer of my life until it happened."
"It was almost like Echo saw us having too much fun and wanted to end it..."
"...for good."
"Sydney had still been a dick, though."
"The image of Sydney whipping TJ mercilessly with the towel we used as a flag comes to mind."
"I move closer to the edge of the tree line before slanting back in again."
"Looking up between the branches, I see that the sky is a darker blue now."
"Pretty soon it'll be pitch black."
"It was about this light the last time I was here."
"I'd come alone and I was ten, maybe 9?"
"It's hard to remember now, but I think I'd gone there because I was sad."
stop music fadeout 5.0
"I'd had good memories of the forest, so I thought going there might make me feel better."
"I was standing in the forest, waiting to see if I did feel better."
"It didn't happen, so I'd sat down in the leaves and started crying."
"I was there for maybe five minutes before I heard some branches creaking above me."
play music "atmosphere.ogg"
"I'd looked and saw feet swinging around."
"This confused me, so I stood up and backed away, staring up as I slowly realized I was seeing a fox being hung by its neck."
"Even now I can remember the way he looked, his overalls and his white shirt."
"His head had been tilted down toward me, his tongue lulling out of his muzzle, his eyes blank."
"I can even remember what looked like pinkish red blood on the white fur of his chin."
"Then I tripped over a branch and when I looked back up, he was gone."
"I can't remember much after that except that I'd gone home and told my parents."
"That ended up with me seeing a doctor."
"They never found anything wrong with me, at least anything that might relate to seeing things."
"In the end we were told that sometimes kids hallucinate, that it would stop happening as I got older."
"I hug myself, feeling cold and a little scared now that I've brought up that old memory."
"While I know that I was at the age where kids hallucinate most often, I still can't get out of my mind how real it had been."
"Still, that's not exactly what's giving me the chills right now."
"Because I just realized that that had been the summer after Sydney passed."
"That's why I was sad, because I remembered how happy the summer before that had been."
"So what Sydney wrote doesn't make any sense."
"Unless I'm going crazy..."
"A creak behind me makes me jump and I whirl around, eyes scanning the branches, terrified of what I might find."
"But there's nothing there, just branches creaking in the wind."
stop music fadeout 10.0
"I stare for a while longer before a shout from far down the line of trees makes me jump."
t "— I found it!"
"It's TJ's voice, high-pitched and excited."
"I shake myself out of my trance and start jogging towards where the lynx's voice came from."
"Maybe I've confused things and I'm just remembering things incorrectly."
"It's the only thing that makes sense."
"As I come up on the lynx, Carl and Jenna are already there, standing around a tree trunk."
"Sure enough, a little wooden birdhouse is tied to the trunk with rusty wires."
play music "banter.ogg" fadein 5.0
show Carl at left behind nightoverlay with dissolve
c "— I can't believe it's still here."
show TJ Neutral at center behind nightoverlay with dissolve
t "— It does look pretty beat up."
show Jenna Neutralhips at right behind nightoverlay with dissolve
"Jenna points to a little wooden plug in the opening."
j "— It's closed up."
m "— Think it's been closed this whole time?"
t "— I dunno, maybe..."
"TJ pokes at the plug with a claw, then grips around the edges with all his claws before gently pulling the wooden, cork-like thing out."
"A thick, sticky looking trail of cobwebs follows it."
"We all stare into the dark hole that's revealed."
c "— Chase, wanna reach in there? I'm sure there aren't any spiders."
"I shiver involuntarily."
t "— Uh, I don't really want to either."
"Jenna sighs before pushing past TJ."
"Bending over, she picks up a twig and sticks it into the hole before swirling it around."
"When she pulls it back out it's like she's made a cotton candy cone of spider webs."
"She drops that then takes out her phone, turning on the flash before holding it up to the opening."
j "— Well..."
"We all wait anxiously for her to say something."
j "— There is something here."
"With that, she reaches in with just her fingers."
"After a few crinkling sounds, she pulls out a zip lock bag and inside is a folded up piece of paper and a blue comb."
c "— Ho—lee shit, no way..."
t "— Well, no one ever comes back here, so I guess it makes sense."
c "— He actually put a comb in there to make it rhyme, haha."
"Jenna makes a few jerking motions away from the birdhouse to get rid of the cobwebs."
"She looks around, then sticks it out to me."
j "— Since you read the last one."
m "— Okay."
"I glance at TJ, but he doesn't make any indication that he might want it."
"The bag is covered in what looks like dirt and cobwebs, a few clumps of both dangle from the bottom."
"I open it carefully and when I pull out the paper I can tell that it's been wet a few times."
"It's a little crumpled, but when I unfold it the water damage isn't bad enough that I can't read it."
"Still, the paper immediately splits in two this time and I have to hold them up together as I read it."
"It's dark to the point where I have to have Carl hold up his phone to give me some light."
"\"Good job! but that was a little easy right?\""
"\"Next we will find out how brave you are (I know this was already a scary test for Chase but that doesn't count).\""
"{cps=22}{font=ui/belligerent.ttf}Do you really remember?"
"\"get a flashlight and make sure leo is with you!\""
"\"Here it is!\""
"\"Stay in school, it will be cool.\""
"\"We'll have fun in 301.\""
"\"I hope you don't die!\""
"\"-Syd\""
show TJ with dis
"We're all quiet for a moment, then TJ giggles."
"I look at him, but he's covering his mouth with a hand so I can't see him smiling."
t "— That's not really a riddle, is it?"
"I smile."
m "— Go easy on him; he was a kid."
t "— Sorry."
j "— So the old school, in room 301? I assume that's what he meant by a test of courage."
c "— Shi—shoot, he went in there all by himself? I wouldn't even do that now."
m "— Yeah, that is a little weird..."
"The feeling that something isn't right grows inside my chest."
j "— Well, we have to break the law to get in there. We'd be trespassing."
"Jenna glances at TJ because we all know the lynx wouldn't dare break the law."
j "— Besides, it's getting late. Maybe we can go check it out tomorrow. One of us can go in for you, TJ."
"TJ looks up at the sky where stars are starting to twinkle through the branches."
t "— Well, if we're going to trespass, we should do it at night, right?"
show Jenna Surprisedhips with dis
"Jenna's mouth falls open."
show TJ Sheepish with dis
j "— What?"
"TJ looks flustered."
t "— I mean, we don't have all that much time left here so we should probably get as much of it done as we can."
m "— So...you're okay with breaking the law?"
t "— Well...yeah, if it means we can finish this."
"We all stare at him."
t "— I—I don't know what else to say. I just really want to get this done...It feels right."
"We're quiet for a moment before Carl claps his hands together."
c "— Well, alright then, let's go! We've still got a few hours before I'm going to bed."
show Jenna Neutralhips with dis
"Jenna sighs loudly."
j "— Alright, but I wanna get back before 10 so that I can finish my papers."
c "— Yeah, yeah, don't worry. Onward!"
stop music fadeout 10.0
"Carl marches ahead of us, taking a running leap to cross the ditch."
"I look at TJ who's still looking fidgety again."
m "— Hey, we'll finish this before we have to leave, okay?"
"TJ gives me a small smile."
t "— Okay."

scene bg schoolnight
show nightoverlay
with fade
play loop "crickets.ogg" fadein 3.0
"Carl says that a cop still patrols Echo randomly at least once a night."
"Because of that, we let Jenna sit out in the car and keep watch."
"If someone shows up she'll text us, which should give us time to get out the back of the school."
"It'll still look suspicious as hell, but as long as we're not caught on the property and have some sort of excuse we should be fine."
"...At least that's what Carl says."
"We stand there in front of the door and I notice that a couple chains hang loosely off the door, no lock to be found."
m "— Well, at least that hasn't changed."
"Carl shrugs."
show Carl Neutral at right behind nightoverlay with dissolve
c "— Teenagers break in all the time. No point in putting a lock back on every time."
play sound "doorsqueak.ogg"
"Carl gives the door a shove and it slides open very slowly, letting out an unearthly squeal as it does."
"The three of us stand there, staring into the darkness."
"TJ fidgets next to me."
m "— Having second thoughts?"
show TJ Sheepish at left behind nightoverlay with dissolve
t "— No!"
"His voice comes out in a crackly squeak that Carl snorts at."
t "— Just...just so dark."
c "— Night time has a way of doing that, my man. Good thing I charged my phone before we left."
"Carl takes out his phone from his pocket and holds it up before turning on the light."
t "— Uh, mine's almost dead."
m "— We can share."
scene bg schoolintnight
show nightoverlay
with dissolve
"Carl sweeps the light inside revealing graffiti covered walls and dirt covered floors."
c "— Nice."
"I look back and see Jenna staring at us from the car."
"She gives me a thumbs up."
"I inhale deeply."
m "— Well...let's go."
"I take out my own phone and step inside and TJ follows me."
stop loop fadeout 3.0
play music "neutral.ogg" fadein 5.0
"Carl stands next to us, spinning in a circle."
show Carl Neutral at right behind nightoverlay with dissolve
c "— Well...it's not THAT creepy."
show TJ Neutral at left behind nightoverlay with dissolve
t "— Okay, so the rooms here are the 200s."
"TJ points up at a doorway next to us, a small label above it reading \"203\""
t "— So that means that we have to go up one floor."
"Carl sweeps his light around and points to the staircase."
c "— Shall we?"
m "— Those things better be stable."
"Carl points his light up the stair case."
c "— I can see some graffiti up there. It's probably fine."
"The ram leads the way, at first tentatively setting a hoof on the first step before testing the next."
c "— Yeah, it's good."
"And with that he strides up the stairs while TJ and I following a little more hesitantly."
t "— Why don't they just demolish this place?"
c "— Heard they wanted to turn it into a museum...can't see why, though."
"Carl shines his light on the railing, the wood rotted and broken."
c "— Hey, do you guys remember when Chase saw someone staring out from one of the windows up here?"
t "— Oh my gosh, pleeease don't talk about this right now."
c "— Do you even remember that, Chase?"
m "— Uh, yeah, actually...that was a long time ago."
"I hardly remembered it, but I do remember seeing a dark form in one of the windows."
"I'd been positive it was just an object sitting in the room, but I'd wanted to tell my friend that I'd seen a ghost."
"It was nothing like what I saw in the trees."
"Thinking about it is creeping me out though."
t "— Stooop."
"TJ whines as we reach the top of the stairs then, clearly trying to change the subject, points up at the door."
t "— Alright, 305, so maybe this way.. Chase, let me see your phone."
"TJ takes it from me and points it up at the next door over."
t "— Yeah, 304, so the last one down."
"He hands me back my phone and stands there a moment."
show Carl with dis
"Carl chuckles."
c "— Want me to go first? You scared?"
"TJ glares at him."
m "— Come on, guys. I wanna get out of here, too."
c "— Okay, okay."
"Carl leads the way again, down the hall to the very end."
"There's more stuff in the way on this floor with a lot of desks and chairs."
"Carl keeps his light up, counting down the doors."
show Carl Surprised with dis
c "— 303...and 302...Ah! 30—FUCK!"
show TJ Surprised with dis
"TJ jumps a foot into the air and I point my light at Carl."
m "— What!?"
"Carl turns around sheepishly, rubbing his hip."
c "— Ran into this stupid desk. Hurt like a mother."
show TJ Annoyed with dis
t "— Really, Carl?"
"TJ clings to me, taking a deep breath."
show TJ Neutral
show Carl Neutral
with dis
c "— But here's the door."
"Carl points the light back up above the door and sure enough there's a 301 up there."
"TJ and I stand next to him, both staring into the dark room."
c "— Hey, I think this might actually be the room you saw the thing staring at you from."
t "— Carl."
"There's a warning tone in TJ's voice."
"I rub my chin."
m "— Actually, yeah, I think it is."
"TJ sighs loudly and closes his eyes."
t "— Guys, please, can we just—"
show Carl with dis
c "— YAH!"
with vpunch
show TJ Surprised with dis
t "— AAAAHH!"
"Carl thrusts his hands into TJ's side as he yells, sending TJ into a hysteric fit of screaming and grabbing on to me."
"I stumble as I try to keep the lynx from rending my flesh with his claws."
show Carl Surprised with dis
c "— Oh shit, sorry, I—OW!"
show TJ Annoyed with dis
"Carl reaches out to, I assume, comfort TJ, but gets a backhand across the face in response."
t "— YOU ASS!"
"I watch the two of them with wide eyes, never having seen TJ so indignant."
"Carl stares back, a hand up to his cheek."
c "— Whoa."
t "— Alright, let's start looking."
hide TJ with dissolve
"As if nothing had happened TJ takes my phone and strides into the room, his tail twitching in irritation."
c "— I can't believe you slapped me."
"Carl calls after him, but gets no response."
"I smile, trying not to laugh as I walk past the ram."
c "— Can you?"
"He asks me, rubbing his cheek as he follows me in."
m "— Hey, you asked for it. Probably not the best time to be scaring him."
show Carl Neutral with dis
c "— Yeah, whatever. What the hell are we looking for anyway?"
"I look around."
"From what I can see, there's not much left in the room."
"A few desks are pushed up against the wall and aside from a chalkboard and map at one end of the room, there's nothing else."
hide Carl with dissolve
"I go over to stand by TJ at the other end of the room, looking at the desks."
m "— There's not much in here, is there?"
"TJ sweeps the light around the room, frowning."
show TJ Neutral at center behind nightoverlay with dissolve
t "— Not really."
"He points the light at Carl who's at the other end of the room by the chalkboard."
t "— Anything written on the chalkboard, Carl?"
"Carl shines his light on the board, then gasps."
m "— What?"
c "— There is. It's.. a whole lot of dick!"
"Carl steps to the side, pointing his light at the board and, sure enough, it's covered in countless drawings of dicks."
"TJ sighs."
m "— I mean, we were bound to hit a roadblock eventu—"
stop music fadeout 5.0
"I trail off, staring at the window at the far end of the room where I see a small-looking box on the ledge."
m "— What's that?"
"I point and TJ shines the light over at it."
"A metal toolbox glints back at us."
hide TJ with dissolve
"TJ immediately walks over to it and I follow him."
"Carl joins us as TJ fiddles with the latches, popping them open."
"There's a soft creak as he lifts the lid, a tray extending out as he does."
"And there, sitting in the tray, is another folded piece of paper."
m "— There's no way."
show Carl Neutral at left behind nightoverlay with dissolve
c "— Yeah, that makes no sense."
show TJ Neutral at right behind nightoverlay with dissolve
t "— Why not?"
"TJ gently picks up the note, handing me back my phone."
t "— Shine that on this for me please."
m "— Someone would have taken it by now."
t "— Well they didn't, see?"
"TJ had unfolded it and he shows me the handwriting, the exact same we'd seen on the other two notes."
"I frown, but I don't say anything more."
"Maybe it did just sit here for the past ten years, no one wanting to bother with an old-looking toolbox."
"But this place is broken into regularly with the whole point being to tag or take stuff."
"Someone definitely should have taken it by now."
"This was all on top of the idea that Sydney came in here as a little kid just to hide a note."
"Something isn't right, and I'm starting to feel uneasy."
"I don't have time to dwell on that, though, as TJ begins to read..."

"\"So you went to the school!\""
"\"You found it with some tools.\""
"\"Next go to where I sleep.\""
"\"It's where I keep my secrets, something Chase can't keep!\""
"\"-Syd\""

"It's silent for a moment as we all take that in."
"I feel my face flush and my fur prickle as I wonder what the hell that last line is supposed to mean."
"Carl and TJ don't look at me, but I can sense that they want to."
"Carl is the first one to make a sound, clearing his throat."
c "— Soooo, Sydney's bedroom, maybe?"
t "— That's what I'm thinking. This is a kid writing this stuff, so it should be pretty straightforward."
"I shake my head."
m "— Really guys?"
"TJ finally looks over at me."
t "— What?"
"There's a defensive tone in TJ's voice, and I know he knows what I'm about to say."
m "— This—this is way too much."
"TJ frowns at me."
t "— Too much what?"
m "— Y—you know..."
"I trail off, not used to TJ looking at me this way."
"He lets the silence drag on and I look over to Carl for help."
"He clears his throat again."
c "— You know, Teej, this IS pretty weird. Like, someone would have probably taken it by now."
t "— Why does that have to be the case? People could have just missed it. We almost did."
"TJ looks back down at the note, holding it in both paws."
"I reach out for it, but TJ pulls it back, like I'm going to try and steal it from him."
m "— Um.. can I look at it for a sec?"
"TJ hesitates, then holds it out to me slowly."
play music "quiet.ogg" fadein 5.0
"I eye the lynx as I reach out, taking the note from him gently."
"TJ's behavior alone has me deciding that this whole thing is definitely a bad idea."
"The note looks old just like the first two we found."
"The writing looks the same, too."
"Maybe it is possible that Sydney came in here to hide the note, wanting to make this scavenger hunt especially scary for us."
"But still, I can't shake the feeling that something is off about it."
"I need to find time to really think about this."
"For now though, I hand the paper back to TJ who takes it from me gingerly, as if worried it'll fall apart."
t "— Carl, do you know who lives in Sydney's old house now?"
"Carl tips his head back as if thinking."
c "— Huh, I can't remember his name, but he's a red panda, I think."
t "— Well, let's go then."
"I give a start."
m "— To the house!?"
m "— His family moved out right after...it happened. There's no way it's still there, TJ."
t "— The other two were."
m "— This is different, though."
t "— Might as well try."
"I can't imagine going up to the new homeowner and telling him about Sydney and this posthumous scavenger hunt, and him just letting us in."
"But the determined look on TJ's face tells me right away that I won't be able to talk him out of it."
"I sigh."
m "— Well...can we at least do it tomorrow?"
"I look at my phone."
m "— It's almost 10."
"TJ doesn't say anything as he looks out the window, his face barely visible in the darkness."
"Carl shifts around next to me."
c "— Yeeeah, I'm gettin' pretty tired. We'll have all day tomorrow."
hide TJ with dissolve
"TJ suddenly turns around and heads for the door."
t "— Fine, but we are going. I am, at least."
"Carl glances at me, probably feeling as uneasy as I am."
c "— Hey, I'm comin' too. Just think it'll be easier."
"TJ doesn't respond and we make the rest of the treacherous journey out of the school in silence."
scene bg schoolnight
show nightoverlay
with dissolve
play background "crickets.ogg" fadein 3.0
"Jenna looks up from her phone as I slide into the driver's seat."
j "— Find anything?"
m "— Yeah."
j "— Another note?"
m "— Yeah."
j "— Well, what did it say?"
"I busy myself with searching my pockets for the keys, so Jenna turns in her seat to look back at Carl and TJ."
j "— Well?"
t "— Next one is at Sydney's old house."
j "— What? Really?"
t "— Yes, we're going there tomorrow."
"TJ doesn't offer anything more, so Jenna turns back around in her seat and gives me a look."
"She seems to sense the mood though, and doesn't question any further."
"As I stick the key into the ignition, TJ speaks up again."
t "— Chase, what did he mean by you not keeping secrets?"
"A moment of silence goes by before I answer."
m "— I don't know, or I don't remember. It's been a long time."

scene bg moteltablen with fade
stop music fadeout 5.0
"I lay awake next to TJ, listening to the lynx's steady breathing."
"I've been tossing and turning for the past three hours, trying to get some sleep, but my mind won't settle."
"This whole scavenger hunt has left me with such a bad taste in my mouth."
"Something about it is especially unsettling and I've turned it over and over in my mind, examining it from every angle and now I'm sure of it."
"I saw that fox hanging in the forest AFTER Sydney died."
"That's why I was there in the first place, that's why I'd been so sad."
"I turn over on my side, gripping my pillow in both paws as I stare at the wall, still listening to TJ's soft snoring behind me."
"So how the hell is any of this happening?"
"It's scary, but not because I think Sydney's ghost is writing scavenger hunts, or some stupid shit like that."
"No, someone wrote the notes pretending to be Sydney, then planted them around the town for us to find."
"And that someone is likely one of us; Leo, Carl, Jenna, Flynn...or even TJ."
"Are any of us sick enough to do something like that?"
"And if so, who?"
"I try to remember if I'd told anyone about that incident in the forest before today, but I honestly can't remember."
"Apparently my mom had told some people about it.. Jenna's parents for one."
"But I really can't imagine Jenna being among the aforementioned."
"Whoever's writing them seems to like singling me out too, mentioning the forest and how I told \"secrets\"."
"I roll back to stare at the ceiling and start wondering about TJ."
"He's been acting really strange the past few days, his bright, cheerful demeanor almost completely gone after we started the treasure hunt."
"I guess it's possible that he's upset enough to do something that's as crazy as this."
"Maybe it could make him feel like he's connecting to the person he'd watched die over a decade ago."
"Maybe he did it a long time ago and it's only now that we've come across them?"
"Maybe he can't remember because he buried those memories?"
"Those papers do seem pretty old."
"But I can't shake the feeling that this person has it out for me in some way."
"I think about how Carl was the one to find the first letter."
"But I almost immediately dismiss the idea that Carl might be involved."
"He would have no reason to do it..."
"...Unless."
"The only other person I can even imagine doing this is Flynn."
"He was the one most upset about Sydney's death, aside from TJ."
"Carl and Flynn seem to have grown pretty close over the past year or so."
"Could the two of them be involved somehow?"
"It's pretty suspicious that it would just show up in Carl's basement."
"I roll back to my side, preferring to stare at the wall."
"I don't like suspecting my friends like this, but this whole thing is messed up on so many levels, and I'm really worried about TJ."
"Depending on how this all ends, it could make things even worse for him."
"Considering how Flynn treated TJ at the river, I wouldn't be surprised if it's leading up to something terrible."
"And on top of all of that, there's the insidious way that these rhymes refer to me..."
"I decide that I'm going to have to do something after we find the next note, depending on what it says."
"If we even find it at all."
stop background fadeout 5.0
"I'm hoping that we don't..."

scene bg black with slow_dissolve
scene bg fb5dream
show nightoverlayred
with fade
play music "eveningcall.ogg" fadein 5.0
c "— If you go in I'll give you a dollar."
show Young_TJ Sad at farleft behind nightoverlayred with dissolve
t "— No."
show Young_Carl at right behind nightoverlayred with dissolve
c "— Five bucks."
t "— Noo."
c "— Ten."
t "— Nooooo."
c "— You could buy like, twenty candy bars with that money."
t "— I'm not going in!"
show Young_Carl Sad with dis
c "— Alright, alright. Quit yelling."
hide Young_Carl
hide Young_TJ
with dissolve
"Carl and I swing side by side, synchronizing our legs so that we swing back and forth at the same time."
"As always, it doesn't work because Carl's so much heavier than I am."
"The wind feels good on my fur, finally cooling me down after being out in the heat all day."
"Toby sits on top of the slide next to us, watching with a bored look on his face."
t "— It's my turn, Chase."
m "— In a minute."
t "— It's been like, fifteen minutes!"
m "— Nuh-uh."
"Toby sighs and sits back, pouting."
"I look back over at the old school and smile."
m "— But if you go inside I'll let you."
t "— NO!"
"Toby's shout seems to echo around us and I giggle."
m "— Fine, fine..."
"We swing a little longer, the rhythmic squeaking of the chains being the only sound."
c "— When's Sydney coming back with the popsicles? He's taking forever."
m "— Maybe his mom caught him and made him stay home?"
c "— Uggghhh..."
"Carl leans far back in the swing and I feel the entire thing shift around."
"I wonder if it's going to collapse."
c "— We should go to your house, Chase. It's too hot."
t "— I wanna swing."
"I lower my feet and let them kick through the dirt as I slow myself down, sending a cloud of dust in the air."
"This talk about Sydney reminds me of something, something I'd been told about yesterday, and now that he isn't here..."
m "— Hey guys, my mom told me something about Syd yesterday."
show Young_TJ Sad behind nightoverlayred
with dissolve
"Toby's already slid down the slide and walked up next to me, holding one of the chains on the swing as he tries to push me out of the seat."
m "— Don't push me, Toby! Don't you wanna hear it? It's a secret."
"I move to stand between the two swings as Carl kicks his hooves into the dirt next to us."
t "— Keep swinging, Carl. I wanna swing with you!"
c "— Wait, what's the secret?"
t "— Swing, Carl!"
m "— Wait a minute! It's really weird."
"That seems to finally catch Toby's attention and he settles down."
t "— What?"
"Carl and Toby stare at me and for the first time I feel a little worried about telling them, but having their full attention like this is kinda cool."
m "— You know what happened to Syd's dad a while ago when school started, right?"
c "— Yeah."
show Young_Carl at farright behind nightoverlayred
with dissolve
"Carl's completely stopped on the swing now, staring at me."
m "— Well.. my mom says the cops think it's really weird what happened."
t "— Sydney's dad died. He's in heaven now."
"Toby says it matter-of-factly and starts to swing a little again."
t "— Even if you're a Mormon you can go to heaven. My dad said so."
m "— Yeah, but do you know how he died?"
"I start whispering and look over my shoulder at the dirt road to see if Syd is coming."
"It's empty for now."
show Young_Carl Sad with dis
c "— He accidentally got shot when he was hunting with Syd."
"That's what the adults told us, that he was \"accidentally shot\", maybe while he was loading his gun."
m "— My mom said they aren't sure if that really happened, though."
c "— Whaddaya mean?"
"Toby seems to have taken interest again and stops swinging, staring at me."
m "— Well.. maybe Syd did something."
"Carl frowns."
c "— Like, Sydney did it?"
m "— I mean, I don't know, but my mom said to be careful around him, just in case."
"Toby's eyes suddenly widen even more as he suddenly understands."
t "— Sydney killed his dad!?"
m "— SHHH!"
"Toby flinches as I grab his muzzle with one paw, squeezing it shut."
m "— You have to keep it a secret!"
"Toby just sits there, staring at me."
"Carl does the same."
"Now I kind of wish that I hadn't told them."
m "— They don't know, though. My mom just said to be careful. That's it. It might have been an accident."
"I talk kinda fast, like I'm trying to take back what I'd just said."
"I let go of Toby, but he just sits there and doesn't swing."
"Carl just stares at the ground, then his ears flick up."
"A few seconds later I hear scuffing footsteps making their way up the dirt road and I turn around to see Sydney jogging toward us."
"His arms are filled with colorful ice pops wrapped in plastic."
sy "— Hey, sorry, I had to go into the basement freezer to find some. They're Super Wolf pops."
show Young_Sydney_casual Worried_arm at farleft behind nightoverlayred with dissolve
"He stumbles up next to us, kicking up another cloud of dust."
"He stands there for a second, breathing heavy, sweating through his thick fur."
sy "— Uh, grab one?"
"The three of us reach out automatically and take one of our own."
"Mine is partially melted already, blue liquid pooling at one end of the plastic."
show Young_Sydney_casual Sad with dis
"Sydney frowns at us."
sy "— What were you guys talking about?"
show Young_Carl with dis
c "— Nothing."
"Carl says it almost before Sydney can finish his sentence."
"Sydney glares."
show Young_Sydney_casual Arm
show Young_Carl Sad
with dis
sy "— Yeah right, what were you saying about me?"
"Sydney turns on me and I just shake my head, busying myself with opening the plastic."
"Then Sydney turns to Toby, his glare turning into a smirk."
sy "— Alright, Tobias, you'd better tell me what you were talking about!"
"I feel my stomach turn even as I open the package and turn it upside down to pour the sweet blue juice into my mouth."
sy "— Tell me or I'm gonna wrestle ya!"
"Sydney goes at Toby with his paws up, baring his blunt claws."
"Toby eyes him for a moment, but once Sydney gets close the lynx twists out of the way like only a cat can."
show Young_TJ Scared at right with easeoutright
t "— Don't touch me!"
"Toby hides behind Carl and I as Sydney turns to watch him, lowering his paws slowly."
show Young_Sydney_casual Sad with dis
sy "— What's wrong?"
"Toby doesn't say anything, standing behind me quietly."
"I can feel his cold ice pop pressing against my back."
"We stand in silence for a while, and I can see Sydney trying to figure out what's going on."
"I try to think of something fast."
m "— Hey, lets go to my house and play on the trampoline!"
show Young_Carl with dis
c "— Yeah!"
hide Young_Carl with easeoutright
"Carl hops out of the swing and starts walking toward the road."
hide Young_Sydney_casual
hide Young_TJ
with dissolve
"I follow him as Toby clings to my side."
"Sydney doesn't follow and, after a moment I turn back to look at him."
"He's glaring at me."
m "— What?"
"He goes on glaring before throwing his ice pop into the dirt and running past us."
sy "— You guys suck!"
stop music fadeout 10.0
"He runs up the road and back toward town, disappearing into the bright sunset."

jump tjfriday