label tjwednesday:
window hide
stop music fadeout 3.0
scene bg AllWednesday
with transition_fade
$ renpy.pause(3.0, hard=True)
scene bg motelfull
with dissolve
show Jenna at center with dissolve
play loop "shower.ogg" fadein 3.0
window show
j "— Aparentemente ninguém tá conseguindo entrar em contato com ele."
"Jenna se encosta na cômoda, passando uma escova nos pelos do pescoço e da cabeça, ainda um pouco úmidos do banho."
m "— Já tentaram ligar pro telefone fixo dele? Talvez ele tenha silenciado o celular. Tipo, ele dorme o dia inteiro." # "He sleeps in like, everyday."?
"Jenna levanta os ombros."
j "— Eu presumo que sim."
m "— Então ninguém falou pra ele que íamos ter uma festa pra ele?"
"Jenna se vira e se inclina em direção ao espelho acima da cômoda, escovando os pelos caídos."
j "— É uma festa \"surpresa\", né?"
m "— Eu acho. É só que não é realmente o aniversário dele."
"Jenna suspira."
j "— É só uma desculpinha pra fazer alguma coisa nessa cidade de merda."
"Eu vejo a Jenna olhar para a porta do banheiro, como se estivesse preocupada que o TJ pudesse ouvi-la xingar, mesmo com o chuveiro ligado."
"Eu dou meu próprio suspiro."
m "— Bem, desculpa por ter te arrastado pra cá, Jenna. Pensei que seria divertido, só isso."
stop loop fadeout 3.0
"Jenna termina de fazer o que quer que estivesse fazendo no espelho e se vira para mim."
play loop "showerfan.ogg" fadein 3.0
j "— Ei, não é a cidade que vim ver. Era vocês."
m "— É, bem, cê também não parece muito feliz com isso."
"Jenna franze a testa."
j "— Se eu não quisesse ficar aqui com vocês eu já teria ido embora. Eu tenho amigos em Payton que poderiam me levar até o ponto de ônibus."
"Eu não digo nada, escolhendo me deitar na cama e fechar os olhos, ainda cansado dos sonhos fodidos que tive na noite passada."
show Jenna Depressedhips with dis
j "— Mals, vou parar de reclamar."
"Eu massageio minha testa com uma das mãos."
m "— Ainda é o começo da semana. Temos tempo pra mudar isso."
j "— É realmente só o Flynn."
"Eu olho para ela."
m "— Ele vem?"
show Jenna Neutralhips with dis
j "— Uhum. O Leo falou que eles tiveram uma conversa, então..."
m "— Quer dizer, o Flynn supera as coisas bem rápido. Eu acho que não vai ser constrangedor se não deixarmos que seja."
"Jenna olha para a porta do chuveiro, com o som do secador soprando alto atrás dela."
j "— Não é realmente com o Flynn que eu tô preocupada. As coisas que ele falou pro TJ–"
"Eu esfrego os olhos."
m "— Se chegar a esse ponto, eu e o Tejinho vamos sair mais cedo e iremos pra outro lugar, talvez a casa da Janice."
"Abro os olhos para olhar para Jenna."
m "— Cê vem com a gente?"
show Jenna Smilinghips with dis
"Jenna dá uma risadinha para mim."
j "— Acho que preciso estudar um pouquinho."
m "— Ah, qual foi."
j "— Enfim, e se o Flynn tiver outra–"
"Ela imediatamente se interrompe quando a porta se abre repentinamente."
"Eu vejo um dos olhos azuis do TJ olhando através da abertura."
"O olho se arregala e a porta fecha rapidamente de novo."
"De repente a porta se abre novamente e o lince sai apressado apenas com suas calças."
show TJ-noshirt-n at right with dissolve
t "— Com licença, Jenna."
"Jenna se afasta e o TJ vai em uma das gavetas para pegar uma camisa polo."
t "— Esqueci minha camisa."
"Ele murmura antes de se virar e ir depressa para o banheiro."
hide TJ-noshirt-n with dissolve
"Eu percebo por poucos segundos que a parte interna de suas orelhas estão bastante vermelhas."
"A porta fecha novamente."
"Nós dois ficamos encarando a porta por um tempo antes da Jenna falar novamente."
stop loop fadeout 5.0
j "— Se o Flynn conseguir manter a boca fechada até o fim da semana, então talvez consigamos passar por isso."

scene echoroad
with fade
play background "highway.ogg" fadein 3.0
"Eu fico olhando pela janela enquanto descemos as ruas empoeiradas de Echo."
"Honestamente, não parece muito pior do que quando eu fui embora."
"As estradas podem estar um pouco piores, mas eu presumo que isso se deva ao fato de não terem feito nenhuma manutenção desde o inverno."
f "— Eu tô me arrependendo de não ter avisado que estávamos vindo. Sabe? Tu vai ter sorte se ele sequer levantar a bunda da cama."
l "— A gente liga pra ele, então."
f "— E se ele não atender?"
"Leo não diz nada, ao invés disso, volta a se concentrar na estrada. TJ acaba com o silêncio depois de um tempo."
t "— Bem, eu não acho que seja muito estranho. É meio como se estivéssemos saindo juntos de novo. Não tem nada de errado nisso."
f "— Claro, mas botar o foco no Carl é meio... estranho. Talvez se o aniversário dele fosse tipo, na próxima semana? Duas semanas no máximo."
j "— Ai para, Flynn. Vai ser igualzinho como se estivéssemos saindo juntos. Você agir de forma estranha em relação a isso não vai ajudar em nada."
"O carro começa a desacelerar e eu saio do meu devaneio para olhar o que está acontecendo, sabendo que definitivamente ainda não estamos na casa do Carl."
stop background fadeout 5.0
play loop "engine.ogg" fadein 3.0
"É então que vejo uma figura canina redonda parada mais à frente na beira da estrada."
"Ela está parada na terra que separa a estrada do campo em frente de uma cerca de arame farpado quebrada e enferrujada."
l "— Acho que é a Janice."
"Eu olho para o Leo e ele parece preocupado, suas sobrancelhas franzidas enquanto ele cuidadosamente dirige o carro bem ao lado da coiote."
"Eu percebo o porquê; ela está agachada, com os cotovelos nos joelhos, olhando para o chão."
l "— Abaixa sua janela, Chase."
"Eu abaixo quando ele fala, tendo um pouco de dificuldade com a manivela antiga."
f "— Que merda ela tá fazendo aqui?"
"Paramos ao lado da coiote, soltando um pouco de poeira."
l "— Sei lá... EI!"
"Leo se inclina sobre mim e sorri para Janice que ainda está olhando para o chão."
l "— Tá tu–"
"A voz do Leo é cortada em um estranho som de engasgo."
"Eu olho para ele, confuso, e então olho para fora pela janela e não consigo evitar, mas eu fico espantado."
"Era difícil perceber pelo ângulo, e por toda a poeira levantada pela van, mas agora eu consigo ver que a Janice está com suas calças abaixadas até as coxas..."
"... Eu também consigo ver todo o resto."
"Eu volto a me sentar depressa e desvio os olhos, começando a olhar para o para-brisas."
f "— Que porra."
j "— Ai meu Deus. Leo, acelera."
"Jenna sussurra, sua voz tensa."
l "— Ah! Hum, desculpa, uh–"
"Leo para de falar e dou uma olhada pela janela de novo."
"A Janice está olhando para nós agora, e está sorrindo."
"É um sorriso estranho porque seus olhos continuam arregalados."
"É bizarro."
"Leo olha de volta."
m "— Leo, vai."
"Eu murmuro pelo lado da boca, voltando a olhar para o para-brisas. No entanto, ele parece relutante, como se estivesse preocupado."
l "— Janice, você precisa de ajuda?"
"Seu tom é um que você talvez use com um neném... ou com uma pessoa doida."
"Eu não escuto ela dizer nada, talvez com a exceção de um grunhido. No entanto, o Leo bravamente continua tentando."
l "— Podemos te dar uma ca–"
"O Leo para de falar bem na hora para mim ouvir um som de algo derramando."
"É um som que reconheço bem da época em que eu mijava nas estradas de terra de Echo quando não havia ninguém por perto."
"A van avança para frente, depois volta a acelerar suavemente para a estrada vazia."
f "— Cacete! Que porra foi essa!?"
l "— Eu não..."
"Leo está franzindo, parecendo mais confuso que nunca."
l "— Eu de–Eu deveria voltar?"
t "— Não!"
"Eu olho para trás e vejo o TJ cobrindo o rosto."
j "— Talvez. Ela poderia estar tendo um tipo de episódio psicótico."
f "— Ou talvez ela só precisasse mijar."
l "— Eu não acho. Você viu o jeito que ela tava me olhando?"
m "— Ela provavelmente só tá usando algo. Igual todo mundo?"
l "— Não, ela não usa esse tipo de coisa."
m "— Bem, talvez use sim? Você nunca realmente comhece as pessoas."
"Novamente, o Leo não diz nada e ninguém também."
"Eu dou uma olhada no TJ que está sentado no assento de trás junto com a Jenna."
"Suas orelhas abaixadas, olhando para seu colo onde está mexendo inquietamente as mãos."
"Eu sei que ele provavelmente está pensando a mesma coisa que eu, que deveríamos ajudar a Janice com sua limpeza de primavera, ou algo assim."
"Eu quero perguntar a ele sobre isso, mas a van completamente calada está me fazendo sentir que agora não é a melhor hora."

stop loop fadeout 3.0
scene bg mansion with fade
show Flynn Annoyed at left with dissolve
play background "reststop.ogg" fadein 3.0
f "— Eu te disse caralho!"
"Leo aperta a campainha de novo, com frustação estampada em seu rosto."
m "— Dá pra você parar de xingar só um pouquinho?"
"Eu não consigo evitar de perceber o TJ se retraindo toda vez que o Flynn acaba de falar."
"Ele está ficando longe do Flynn, sempre estando do lado oposto do nosso grupinho."
"Eu movo a mochila que estou carregando em minhas mãos, tentando olhar através do vidro fosco nas laterais da porta." # mochila ou bolsa?
m "— Talvez ele tá se drogando?"
show Jenna at right with dissolve
j "— Ele ainda deveria conseguir ouvir."
m "— Quer dizer, talvez ele só não queira?"
"TJ mostra seu celular."
show TJ Neutral at center with dissolve
t "— Ele também não tá atendendo o celular."
play sound "knock.ogg"
"Leo bate na porta com força, seu bíceps se expandindo."
j "— Bem, acho que a gente consegue entrar se a porta estiver quebrada."
"Leo se afasta, com as patas na cintura enquanto respira fundo."
"Ele tá determinado."
"E eu acho que ele deveria estar considerando que foi ele que planejou isso tudo."
hide Jenna
hide TJ
with dissolve
show Flynn Annoyed at center with moveinright
f "— A gente só deveria ter falado pra ele nos encontrar na lanchonete, ou algo assim."
show Leo Questioning at farright with dissolve
l "— Eles trancam as janelas?"
show TJ Surprised at left with dissolve
t "— Quê!?"
show Leo Annoyed with dis
"Leo rosna." # rosna ou ruge?
l "— Não é como se estivéssemos invadindo!"
show TJ Rejected with dis
"As orelhas do TJ se contraem, seu rosto sem expressão." # "TJ's ears pin back"?
"O lobo coloca uma pata na testa, fechando os olhos."
show Leo Neutral with dis
l "— Desculpa, mas eu acho que ele tá só dormindo e não deve ser muito difícil de só entrar e acordá-lo."
"Eu olho para o lado da casa e vejo uma janela para o porão."
"Aponto para ela."
m "— Que tal aquela?"
l "— Pequena demais."
show Jenna at farright with dissolve
j "— Eu provavelmente caibo."
hide Jenna with dissolve
"Ela sai da varanda da frente e se agacha ao lado da janela, empurrando-a."
j "— Espera, tem um adesivo de alarme aqui."
f "— Bem é preciso armar o alarme primeiro e o Carl é preguiçoso pra caramba que eu sei que ele não armou."
f "— E tipo, se ele disparar a gente só corre. Não é como se eles fossem aparecer tão cedo."
"Jenna hesita, então empurra a janela novamente, mas ela não se move."
j "— Trancado."
l "— Vamos tentar na da de cima."
j "— É alta demais."
l "— Eu te apoio."
t "— Eu acho que vocês tão indo longe demais."
"Leo ignora ele e fica ao lado da janela antes de fazer uma plataforma para o pé da Jenna com suas patas."
"Apoiando-se com as patas na parede da casa, Leo levanta a Jenna com facilidade e ela consegue agarrar a borda."
f "— Que cacete, isso é burrice pra caralho."
"Flynn murmura ao meu lado, mas eu o ignoro."
"Jenna empurra a janela e ela se abre facilmente."
l "— Isso! Agora eu vou te empurrar o máximo que consigo. Calma aí."
j "— Cuidado!"
"Como se fossem um tipo de dupla de líderes de torcida, o Leo empurra a Jenna para cima com uma pata e ela desaparece pela janela."
"Sua cauda ondulada é a última coisa que vemos... até que sua cabeça aparece de novo." # cauda ondulada?
j "— Cozinha; Eu cai na pia."
l "— Boa! Agora destranca a porta."
"Ela desaparece de novo e nós voltamos até a porta da frente."
f "— Leo, tu é doido pra caralho."
l "— Se tu não calar a porra da tua boca Flynn eu vou dar um chutão bem na tua buceta, tá legal?"
f "— Jesus, se acal–"
"Leo se vira para ele, com um pé na frente do outro."
"Flynn fica calado."
"Os olhos do TJ estão arregalados, embora ele esteja olhando para os degraus da escada na porta."
"Eu quero colocar meu braço em volta dele."
hide Flynn
hide Leo
hide TJ
with dissolve
"Finalmente, ouvimos o barulho da porta e ela abre."
play sound "dooropen.ogg"
show Jenna Neutralhips at center with dissolve
j "— Chamei ele mas ele não respondeu..."
f "— Bem ele tem que tá aqui. Não é como se ele pudesse ir pra outro lugar... ou quisesse."
scene bg kitchen with dissolve
stop background fadeout 3.0
play music "quiet.ogg" fadein 3.0
"A casa do Carl é tão grande e imaculada quanto eu me lembrava."
"É uma mansão, afinal."
"Bem, talvez menos imaculada do que me lembro."
"Há algumas embalagens e caixas de pizza no balcão de mármore."
"Presumo que isso se deva ao fato dos pais do Carl não estarem aqui para lhe mandar não ser um vagabundo."
"O Flynn imediatamente sobe as escadas."
f "— Ei, Carl!"
"Eu coloco a mochila sobre a mesa e o TJ coloca o bolo nela também."
"Eu olho para ele."
m "— Cê tá bem?"
show TJ Neutral at center with dissolve
t "— Eu tô bem! Por quê?"
m "— Só perguntando. Então..."
"Eu esfrego a parte de trás da minha cabeça, tentando pensar em como falar sobre isso."
t "— Que foi?"
m "— Hum, a Janice."
t "— Ah, é."
"TJ imita minha pose, esfregando atrás da própria cabeça."
t "— Na verdade, eu tô muito preocupado com ela."
m "— Quer dizer, ainda deveríamos ir?"
"TJ olha para mim, surpreso."
t "— É claro! Especialmente agora. Precisamos ter certeza que ela tá bem."
m "— Ah, sim, talvez deveriamos."
"Na verdade, eu não sinto que precisamos fazer isso considerando que ela provavelmente só tá muito, muito drogada."
"Eu ia sugerir que pelo menos adiássemos a visita para amanhã para que ela tivesse tempo de se recuperar."
"Mas o choque do TJ com minha sugestão me fez segurar a língua por enquanto."
show Leo Annoyed at left behind TJ with dissolve
l "— Chase, dá uma olhada lá atrás! TJ, porão."
"Leo late para nós antes de passar com rapidez em direção ao corredor."
hide Leo with dissolve
"Nós dois olhamos um para o outro antes de eu levantar os ombros e ir para a porta dos fundos."
hide TJ with dissolve
"Eu fico olhando para a janela de vidro da porta por um tempo, me perguntando por que o Carl estaria lá fora afinal."
"O velho parquinho com os balanços se foi, assim como a casa na árvore que ficava em uma das duas árvores."
"O galho próximo à base da árvore que usávamos como degrau também foi cortado." # AS A STEP = COMO DEGRAU???
"O Carl e eu costumávamos brincar naquela casa na árvore toda hora quando éramos mais jovens."
"Eu abro a porta e saio pisando nos degraus de concreto."
scene bg backyard with dissolve
play loop "reststop.ogg" fadein 3.0
"Eu sinto a saudade ao não vê-la aqui. Eu tinha muitas memórias nela."
"Eu consigo me lembrar do dia que começamos a construí-la."
"Quer dizer, o pai do Carl construiu toda a base dela, mas deixou o resto por nossa conta."
"Duke, o velho doninha, tinha uma pilha de lixo de coisas aleatórias em seu quintal e nos deu permissão para pegar coisas dela contanto que nós limpassemos tudo."
"Eu contei pro TJ que se nós limpássemos a pilha, meu pai iria nos levar no cinema aquela noite."
"Nós dois fingimos ajudar a limpar, embora tivéssemos só pegando o que queríamos pra casa na árvore."
"Nós levamos tudo em uma carroça, falando pro TJ que a gente tava levando pro canto pra reciclar, ou algo assim, e que ele deveria continuar."
"É claro, nós não voltamos."
"Eu não sei porquê eu pensei que iríamos nos safar assim."
"Aparentemente o TJ ficou lá por mais três horas antes do Duke vir e descobrir o que aconteceu."
"Eu fiquei de castigo por mais tempo do que eu já tinha ficado."
"Eu me retraio e fecho os olhos, meu rosto esquentando com a memória de ser forçado a pedir desculpas ao TJ."
m "— Cuzão fodido."
"Eu murmuro para mim mesmo."
"Éramos extremamente cruéis com o TJ naqueles anos."
"Era provavelmente por causa da diferença de idade."
"Eu e o Carl tínhamos 10, o TJ tinha 8."
"Por algum motivo, dois anos parecem duas décadas quando se tem essa idade."
"Mesmo assim, não há desculpa para o quão arrombado eu era com ele."
"Mesmo depois que isso aconteceu, nós nunca o deixamos subir na casa na árvore."
"Eu era um moleque bem arrombado, mas eu sei que o TJ não tem nenhuma mágoa de mim."
"Mesmo assim, a ideia de tirar vantagem do TJ por causa de sua natureza em confiar nas pessoas só é tão... terrível."
"Eu suspiro, dando uma olhada rápida no resto do quintal mesmo sabendo que o Carl não está aqui fora."
"Estou um pouco preocupado, mas tenho certeza de que há algum tipo de explicação para onde ele foi."
scene bg kitchen with dissolve
stop music fadeout 5.0
stop loop fadeout 5.0
"Eu me viro para trás, decidindo ajudar com a busca dentro da casa."
"É então que vejo rapidamente uma cauda gorda, laranja e cinza desaparecendo pela escada do andar de baixo."
"Eu pisco."
"Jenna passa por mim."
show Jenna at center with dissolve
j "— Eu vou olhar na garagem. Mas eu acho que ele nem tá nessa casa."
m "— Ok."
hide Jenna with dissolve
"Enquanto a Jenna se dirige para a porta da garagem, eu me dirijo para as escadas."
scene bg basement with dissolve
"O ar frio que surge do corredor escuro à minha frente é um contraste nítido com o calor do lado de fora."
"Abro um pouco minha camisa enquanto olho para as várias portas ao longo do corredor."
"Entretanto, a única aberta fica no final do corredor, e consigo ouvir uma voz baixa vindo dela."
"É o Flynn, com certeza."
"Ao chegar silenciosamente à abertura, eu consigo começar a entender o que ele está dizendo."
f "— –mas eu só queria que tu soubesse que não tô bravo contigo... Belê?"
"Eu não escuto uma resposta enquanto estou parado do lado de fora da porta."
"A partir daqui, tudo o que eu consigo ver são algumas caixas de papelão e uma cama bem arrumada que provavelmente não foi tocada há anos."
"Um quarto de hóspedes e, ou armazém?"
f "— Qual foi, cara. Eu tô tentando. Eu tava puto ontem e eu não deveria ter enviado aquela porra."
"A voz do Flynn vem de mais fundo do quarto, à minha esquerda."
"Eu ranjo os dentes, hesitando entre entrar agora, ou apenas esperar pelo melhor e deixar as coisas acontecerem."
t "— Eu tenho que ir..."
f "— Eu só tava tentando entender–"
t "— Não–"
"Eu escuto alguns barulhos no quarto e é aí que percebo que preciso intervir."
"Eu me seguro na batente da porta enquanto inclino minha cabeça para dentro."
show TJ Depressed1 at left
show Flynn Annoyed at right
with dissolve
play music "loneliness.ogg"
"O Flynn colocou o TJ contra o que parece ser a porta de um armário."
"O TJ está encolhido no canto enquanto o Flynn está com uma mão no ombro do lince, segurando o tecido de sua camisa."
"As orelhas do TJ estão apertadas contra sua cabeça e ele está olhando para o Flynn com uma expressão de desconforto."
"Então seus olhos se voltam para os meus quando ele me percebe."
f "— Me deixa falar por um segun–"
"Flynn percebe que o TJ está olhando por cima do seu ombro e vira sua cabeça em minha direção."
"Assim que ele me vê, sua mão se solta do ombro do TJ."
"Ficamos nos encarando por alguns segundos e eu engulo em seco bem alto." # tá certo essa expressão? 
m "— Vocês acharam o Carl?"
"Minha pergunta parece ainda mais ridícula no silêncio mortal que se seguiu."
"O olhar do Flynn se volta para a parede sobre a cabeça do TJ onde ele a encara friamente por alguns segundos, sua mandíbula se mexendo furiosamente."
"Eu começo a me preocupar que ele esteja invocando mais um de seus ataques de raiva."
"Porém, depois de cerca de cinco segundos, ele imediatamente se vira e sai do quarto furiosamente."
"Eu tenho que sair do caminho quando ele passa rapidamente por mim."
hide Flynn with dissolve
"Quando olho de volta para a sala, o TJ já estava em frente a um espelho na parede."
show TJ Depressed1 at center with  moveinright
"Ele endireita a camisa, e então penteia vigorosamente os pelos do rosto."
"Ele faz um movimento estranho para frente e para trás em suas bochechas com uma das mãos, embora elas pareçam boas para mim." # cheek ruffs...
m "— TJ?"
t "— Hm!?"
"TJ vira sua cabeça em minha direção, com uma de suas orelhas se contorcendo." # contorcendo? (dnv)
m "— Você tá... bem?"
t "— Tô bem!"
"TJ fala rápido e alto, dando em sua camisa um último puxão."
t "— Vamos continuar procurando o Carl."
"Ele faz questão de olhar ao redor da sala."
t "— Eu não acho que ele tá aqui!"
"Quando ele passa por mim para sair do quarto, eu agarro seu braço."
"Ele dá um pulo e olha de volta para mim, com os olhos arregalados."
"Eu o solto rapidamente, percebendo o quão parecido estou agindo como o Flynn estava alguns minutos atrás."
m "— Você quer fa–"
t "— Não!"
"Eu pisco surpreso."
t "— Não, eu não quero falar sobre isso... desculpa."
"Suas orelhas estão abaixadas de novo e ele está olhando para o chão."
t "— Vamos... vamos só continuar procurando."
"Ele se vira novamente, mas eu sinto que deveria falar algo mais."
"Eu quero fazer com que ele se sinta melhor, tirar ele de perto do Flynn."
stop music fadeout 10.0
m "— Cê quer dar uma volta, ou algo assim?"
"TJ vira e me olha se questionando."
m "— Quer dizer, pra continuar procurando o Carl. Ele não tá na casa, então talvez ele tenha saído pra algum lugar pela cidade?"
"TJ concorda com a cabeça, a expressão de angústia desaparece do seu rosto."
show TJ Sheepish with dis
t "— Ahh, isso pode ser uma boa ideia. Deveríamos falar pro Leo."
"Sinto uma onda de alívio por ter conseguido distrair o TJ, e agora eu quero continuar com isso."
scene bg kitchen with dissolve
"Felizmente, não vemos o Flynn pela saída."
"Um Leo distraído e frustrado rapidamente nos dá tchau enquanto ele continua sua procura nos quartos do andar térreo."
l "— Provavelmente se drogou e desmaiou em algum lugar."
"Ele murmura distraidamente enquanto saímos pela porta."
scene bg flashback1 with dissolve
play music "oldwinds.ogg"
"Eu imediatamente percebo o quanto isso é uma má ideia quando sou atingido pelo sol."
"TJ, por outro lado, se anima no segundo em que saímos da mansão."
"Isso, pelo menos, me faz sentir um pouquinho melhor."
stop music fadeout 5.0
"Andamos em silêncio pelos primeiros minutinhos, observando as colinas e montanhas, cactos, e arbustos."
"É um daqueles dias em que eu não tenho certeza se o calor é pior vindo do sol acima de mim, ou do escaldante asfalto preto sob meus pés."
stop music fadeout 5.0
play loop "reststop.ogg" fadein 3.0
show TJ at center with dissolve
play music "banter.ogg" fadein 3.0
t "— Como andam as coisas na faculdade?"
"Eu pisco para sair do meu transe-queimando-vivo e tento me concentrar na pergunta."
m "— Ah, tá indo bem. Só um pouco chato, tá ligado? "
"Ao mesmo tempo, eu sinto uma sensação de pânico ao perceber o quanto de trabalho ainda precisava ser feito no meu projeto."
"Eu consigo me convencer de que ainda tenho metade da semana... Eu vou dar um jeito."
m "— E você?"
t "— Tá ótimo!"
m "— Treinamento esportivo, né?"
t "— Uhum!"
m "— Então o que exatamente cê faz, treina as pessoas pra esportes?"
"TJ ri."
t "— Bem, tem mais a ver com lesões, reconhecê-las, preveni-las, tratá-las se possível."
m "— Eu não sabia que era isso que você fazia. Então cê é tipo um doutor, ou algo assim?"
"Ele ri de novo, mas como sempre, o TJ consegue fazer isso de uma forma que você sabe que ele não está rindo de você."
t "— Definitivamente não, isso seria muito difícil. Acho que você pode dizer que um treinador esportivo é um profissional da saúde."
m "— Daora, daora."
"Eu tento não ficar ofegante."
m "— Eu achava... Eu achava que você taria mais interessado em ser tipo, um coach, ou algo assim. Cê gosta de esportes."
"TJ discorda com a cabeça."
t "— Não, eu seria horrível nisso. Eu não consigo gritar com as pessoas o dia inteiro."
t "— E tipo, sequer tem diploma pra coach?"
m "— Eu acho que a maioria das pessoas que querem ser coach só pegam uma licenciatura em história pra conseguirem \"dar aula\" —"
"Eu faço um gesto de aspas."
m "— no ensino médio enquanto fazem coach. Eles \"dão aula de como ser um coach\"."
t "— Ah é, era assim que era na nossa escola." # escola ou faculdade?
"Eu piso em uma pedra especialmente afiada e mordo o lábio para não gritar."
t "— Eu realmente só queria fazer algo que envolvesse esportes."
m "— Cê gosta disso, dessa parada de treinamento esportivo?"
t "— Sim! Bem, é o meu primeiro ano, então quem sabe, mas acho que sim."
m "— Então cê só gosta de ajudar as pessoas?"
t "— Isso, e eu só gosto de esportes."
"TJ fica quieto por um segundo."
t "— Provavelmente parece bobo, mas é como se isso fizesse a vida parecer mais simples?"
m "— Esportes?"
t "— É, ou se exercitar. Tem um objetivo e algo em seu caminho, tipo a outra equipe, ou uma grande colina —"
"TJ chuta uma pedrinha do chão e a pega na parte superior do pé antes de jogá-la na estrada."
t "—, e o seu único trabalho é superar isso pra chegar no seu objetivo."
"O lince ri."
t "— Não sei se isso faz sentido."
m "— Eu acho que faz. Eu sou meio assim com videogames, eu acho."
t "— Entendo."
"Eu tento chutar uma pedrinha para a parte superior do meu pé igual o TJ fez, mas eu acabo chutando-a para a beira fora da estrada."
m "— Como cê fez isso?"
t "— Ah, eu só tive sorte dessa vez; na maioria das vezes não dá certo. Mas eu tô no time de futebol."
"Penso em como nem me dei ao trabalho de tentar entrar para a equipe de natação para lontras da minha escola."
"Eu já sabia o quão medíocre eu era."
t "— Mas eu também gosto de estar do lado do campo com toda a torcida e as luzes. É divertido."
"Ao continuarmos pela estrada passamos pelas fundações carbonizadas de um velho trailer."
"Embora a maioria dos arbustos tenha voltado a crescer, ainda restam esqueletos da terra queimada e dos arbustos pretos."
stop music fadeout 5.0
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"Naquele momento meu celular acende e eu o pego, tendo que colocar minha mão por cima para conseguir ver a tela sob o sol forte."
"É uma mensagem do Leo."
call text_chase("leo") from _call_text_chase_6
call text_0("", "Achei ele") from _call_text_0_6
#"\"Found him\""
""
m "— Ei, eles acharam o Carl."
t "— Ah! Onde?"
m "— Ele não falou, só falou que acharam."
t "— Bem que bom!"
m "— É."
"Eu sorrio quando uma pequena bola de tensão em meu peito que eu nem sabia que estava lá se dissipa."
call text("m", "Ótimo! Aonde ele tava?") from _call_text_8
""
#"I send Leo a response asking where Carl was."
call text_end from _call_text_end_6
"Olho para trás por cima do ombro para a mansão que fica na base das montanhas, a distância e o calor a tornam turva."
"Eu realmente não quero andar tudo de volta."
t "— Talvez ele só tenha dado uma volta como nós e acabou de voltar?"
m "— Talvez."
play sound "phonebuzz.ogg"
$ renpy.pause(1, hard=False)
"Meu celular vibra na minha mão quando recebo outra resposta do Leo."
call text_chase("leo") from _call_text_chase_7
call text_0("", "sem festa o carl n tá mt bem") from _call_text_0_7
#"\"no party carl isnt feelin good\""
""
"Eu franzo a testa."
call text_end from _call_text_end_7
t "— O quê?"
m "— Falou que o Carl não tá se sentindo bem então não vai ter festa?"
show TJ Neutral with dis
t "— Ah."
"TJ olha para a mansão comigo, arejando a camisa com as duas mãos enquanto isso."
"Por mais que seja uma merda pra mim estar sob esse sol, é sempre pior para o TJ com aquele pelo grosso."
"Eu faço a mesma coisa, arejando minha própria camisa, começando a me sentir envergonhado de novo por causa do meu fedor."
t "— Deveríamos voltar? Espero que ele esteja bem."
"Eu penso em toda a tensão de merda que tava rolando lá atrás e faço uma expressão de desconforto."
m "— Sei lá. Poderíamos fazer outra coisa?"
"TJ parece pensar, com as mãos nos quadris."
"Então seu rosto se anima."
show TJ with dis
t "— Ei! A casa da Janice fica bem no final da rua. Podemos começar o trabalho mais cedo."
m "— Ah."
"Eu quase tinha me esquecido disso."
"Embora eu tivesse planejado ir, eu não queria ir agora, nesse calor."
"TJ pula no mesmo lugar, como se estivesse se aquecendo para um jogo."
t "— Vai ser bom fazer alguma coisa depois de ficar parado o dia todo."
"Eu fico olhando para o TJ, completamente chocado com seu entusiasmo."
show TJ Sheepish with dis
t "— Que foi?"
m "— Quer dizer... bem primeiramente, é trabalho. Segundo, cê não tá preocupado em como ela vai tá quando chegarmos lá?"
"Fico olhando para a estrada no local aproximado onde a vimos há apenas uma hora."
"Ela não está mais lá, obviamente, mas a memória ainda me dá calafrios."
t "— Bem, eu também quero ter certeza de que ela tá bem."
m "— Sei lá, deveríamos dar a ela pelo menos algumas horas pra... se recuperar."
"TJ para de pular e esfrega o braço."
t "— Desculpa, hum, se você não quiser eu posso só ir..."
"Eu o encaro."
m "— Ah, nem vem me culpar."
t "— Eu não tô! Eu só não quero que você fique bravo comigo."
"Eu me espreguiço, sentindo o suor escorrer pelas laterais do meu rosto."
m "— Poderíamos esperar até o fim da tarde, pelo menos."
t "— Ah, sim, acho que podemos."
"A decepção no rosto do TJ é tão óbvia que é impossível que ele não esteja fazendo isso de propósito."
m "— Beleza, e se ela abrir a porta e ainda estiver com as calças abaixadas?"
"TJ fica boquiaberto."
t "— Chase!"
m "— Só tô falando, isso é o que poderia acontecer. Não tem como saber o que ela tá usando."
t "— A Janice não é assim."
m "— Então talvez ela só tivesse tendo algum tipo de episódio? Todo mundo é doido aqui."
t "— Mais um motivo pra ir ver como ela tá."
"Eu esfrego meu rosto."
m "— Pela mooooor."
t "— Tudo bem! Eu posso só ir sozinho."
"TJ cruza os braços e se inclina para mais perto de mim."
t "— Ou talvez, sabe, ela só precisava fazer xixi."
"Ele cochicha as últimas palavras como se elas fossem os piores palavrões do mundo."
"Eu expiro e fecho os olhos." # expiro? (snort)
m "— Tá."
"Eu passo as costas da mão pela testa."
m "— Mas se eu tiver uma insolação, a culpa é toda sua."
t "— Meu Deus, não fala isso. Se você se sentir tonto ou mal, você vai pra dentro."
"Pensar em ficar sentado dentro da casa com a Janice enquanto me resfrio é quase tão insuportável quanto pensar em trabalho braçal."
"Mesmo assim, o TJ parece feliz, o que vale a pena, eu acho."
scene bg janicehouse with fade
play music "neutral.ogg" fadein 3.0
show Janice Happy at right with dissolve
ja "— Bem, tenho que admitir, eu não esperava que vocês dois viessem aqui tão cedo!"
"Seguimos a velha coiote pelo lado da casa, passando por arbustos e bolas de feno." # bola de feno?
ja "— Tá meio quente agora, mas se vocês acham que aguentam!"
show TJ at left with dissolve
t "— É, a gente meio que não tinha muito mais o que fazer hoje."
"A Janice, pelo que posso dizer, tem agido completamente normal."
"Eu pelo menos esperava que ela ficasse constrangida sabendo o que tinha feito na nossa frente."
"Supondo que ela sequer se lembre disso."
"Contudo, estou bem em nunca mais tocar nesse assunto, e tenho certeza de que o TJ pensa a mesma coisa."
"Quando chegamos à parte de trás da casa da Janice, eu fico espantado ao ver uma pilha de bolas de feno com cerca de talvez três metros de altura contra a casa."
"A pilha se sobressai mais um metro e meio da parede."
m "— Eita."
"Janice coloca as mãos nos quadris, olhando para a bagunça."
ja "— Eita mesmo. Já faz alguns anos que eu não fiz isso. Não tô mais conseguindo olhar pela janela de trás!"
"Janice dá uma risadinha."
"TJ bate as mãos e sorri."
t "— Isso não vai ser tão difícil!"
"Eu sinto que ele está dizendo isso para o meu bem."
"Tá tão quente, eu só quero me deitar e morrer aqui mesmo na terra."
ja "— Deve ser bem rápido! Foi por isso que eu arranjei outro trabalho..."
"O canto do meu olho se contorce." # contorce? (twitches)
"Janice se vira para apontar para seu quintal."
"Ou pelo menos o que seria seu quintal se tivesse uma cerca ou algo para separá-lo da natureza ao redor."
ja "— Tá vendo aquela pilha de tábuas ali?"
"Ela aponta para o que de fato é uma pilha de tábuas velhas e deterioradas."
ja "— Antigamente tinha um depósito lá. Tava lá só Deus sabe quanto tempo. Vocês dois se importam de guardar as boas pra uma lenha?"
"Janice se volta para a pequena residência semelhante a uma cabana que é a sua casa."
ja "— Vocês podem empilhar elas no lado da casa."
"Eu dou ao TJ o olhar mais sujo que consigo enquanto ele impotentemente tenta manter um sorriso para a Janice."
"Ela protege seus olhos do sol."
ja "— Nossa, tá escaldante hoje. Eu vou preparar uma limonada pra vocês daqui a pouco."
hide Janice with dissolve
"E com isso, a Janice volta para a casa, seus passos pesados esmagando através do mato."
"Ficamos em silêncio por alguns minutos, ambos olhando para a pilha de bolas de feno."
show TJ at center with moveinright
t "— Parece que ela tá bem!"
"Eu me agacho na terra, colocando a cabeça nas mãos."
t "— Acho que ela só teve um momento constrangedor e ficou sem jeito. Eu sou assim o toda hora!"
"Eu não digo nada."
show TJ Neutral with dis
t "— Chase, você tá bem?"
"Eu discordo em silêncio com a cabeça."
t "— Não é tão ruim assim, a gente consegue!"
"Suspiro, decidindo se eu vou ou não realmente deixar o TJ e depois voltar quando não estiver tão quente."
play sound "pour2.mp3"
"É aí que ouço água fluindo."
show TJ with dis
"Olho para cima e vejo um TJ sorridente parado no canto da casa, segurando uma mangueira verde."
"A água goteja pela extremidade da tampa de metal."
t "— Pensou que eu tinha esquecido de você e da água? Lembra, a cada quinze minutos pelo menos!"
"Apesar do meu mau humor, eu não consigo evitar de sorrir um pouco diante seu entusiasmo contínuo."
"Eu me levanto e vou até a mangueira, a pegando do TJ e deixando a água gelada correr sobre minha cabeça enquanto ele olha com aprovação."
"Eu tenho que me conter para não gemer de tão gostoso que isso é."
"Quando acabo, eu olho para trás para a pilha de bolas de feno."
stop music fadeout 5.0
m "— Então o que a gente deveria fazer com tudo isso? Ela não nos disse pra onde colocar."
t "— Vamos só jogar pro lado. O vento vai tomar conta do resto."
play music "comeover.ogg"
"Então começamos a trabalhar."
"A Janice pelo menos deixou algumas luvas para nós para que não precisássemos nos preocupar com alguma coisa pontiaguda passando pelas nossas mãos."
"Eu ainda sou espetado através da minha camisa ou até mesmo no rosto se eu puxar sem jeito."
"TJ, não posso deixar de notar, é muito mais rápido do que eu."
"Ele está trabalhando em um ritmo rápido e constante, não se importando nem um pouco quando uma bola de feno o atinge no rosto."
"Eu recebo mais algumas mensagens do Leo perguntando onde estamos."
"Quando eu lhe falo, ele não responde."
"Não demora muito, estou suando pra caramba, com círculos escuros se formando sob meus braços e ao redor do meu pescoço."
"Dez minutos depois eu preciso tirar a camisa, deixando-a pendurada em um suporte de metal enferrujado sob a janela."
"Percebo que o TJ me olhando de lado depois que faço isso." # I notice TJ giving me sidelong glances after I do.
"Eu sorrio para ele."
m "— Que foi, tá gostando?"
show TJ Surprised with dis
"TJ pula."
t "— Quê–Não!"
show TJ Sheepish with dis
"TJ desvia o olhar depressa de novo, trabalhando mais rápido do que nunca nas bolas de feno que já estão quase desfeitas a esse ponto."
"Percebo que ele está com a mesma mancha de suor que eu estava."
m "— Ei, cê pode tirar a sua também. É muito melhor assim!"
"TJ para e ofega por um momento, olhando para o resto de bolas de feno."
m "— Tipo, se for é melhor tirar agora. Ainda temos um monte de tábuas pra mover depois disso."
"Ele inclina as orelhas e consigo vê-lo corar." # inclina? (flicks)
m "— Cê tá com vergonha!? Cê não toma banho pelado com outros caras na faculdade?"
t "— Bem sim, mas–"
m "— Mas o quê?"
"TJ suspira e finalmente tira a camisa, forçando um sorriso enquanto ele a pendura ao lado da minha."
"Eu percebo que ele faz isso com os braços cruzados, como as meninas fazem."
hide TJ with dissolve
show TJn at center with dissolve
t "— Pronto, feliz?"
m "— Por que cê fica todo estranho por tirar a camisa? Cê tava agindo do mesmo jeito hoje mais cedo."
"TJ suspira."
t "— Eu tava tentando não parecer estranho, mas vocês dois ficaram me encarando quando eu abri a porta."
"Eu rio e o TJ coloca as mãos nos quadris"
t "— Só lembra de que quando terminarmos vamos ter que olhar se tem carrapatos em nossos torsos também."
m "— Ah, pior..."
"Isso abala meu humor."
m "— Cara, que merda."
"TJ ofega quieto por alguns segundos."
t "— Realmente tá um pouquinho quente..."
m "— Então cê admite que isso foi uma ideia ruim!"
t "— Não! Quer dizer, talvez? Mas pelo menos teremos a noite pra fazer alguma coisa quando terminarmos, não é?"
"Ele sorri para mim esperançoso."
"Isso realmente melhora um pouco meu humor."
m "— Quer ir na lanchonete?"
"TJ sorri antes de se abaixar em direção às bolas de feno novamente."
t "— Sim, claro, eu tava querendo experimentar–AAAAAAAGGH!"
show TJn Surprised with dis
with vpunch
stop music fadeout 5.0
"Dou um pulo enorme no ar, quase caindo nas bolas de feno."
t "— Sai, sai, sai!"
hide TJn with dissolve
"TJ sai como um tiro, correndo para longe da pilha em minha direção."
"Confuso, eu saio do seu caminho, e o sigo pelo lado da casa enquanto olho para o lugar onde ele estava."
"Eu não vejo nada, mas a reação dele é suficiente para me deixar com os pelos arrepiados na nuca."
"TJ para na frente da casa."
m "— Que porra!? O que rolou?"
"Finalmente o alcanço, ofegando sob o calor."
"TJ também está ofegante, mas provavelmente mais por medo."
show TJn Surprised with dissolve
t "— Uma... tarântula."
"Um arrepio por reflexo sobe pelo meu corpo e eu começo a tentar controlar minhas mãos tremendo." # "wring my hands out"?
m "— Não!"
"De repente estou muito consciente de tudo ao meu redor, todos as pequenos pontas e galhos do arbusto parecendo aranhas."
m "— Cê tem certeza!?"
t "— Sim!"
"A voz do TJ é aguda e chiada enquanto ele agita suas mãos." # agita? (shakes)
"Ele está rindo para si mesmo nervosamente."
t "— Eu ia pegar outra e quando eu toquei nela ela se mexeu e era uma aranha gigantesca pra caramba!"
"TJ deve estar realmente apavorado porque eu raramente escuto ele usar uma palavra dessas."
"Nós dois ficamos ali parados por um minuto e o TJ olha para trás da casa de novo, mordendo o lábio."
"Mas tem algo meio estranho na forma como ele está agindo. Talvez um pouquinho exagerada demais?"
"Eu estreito meus olhos." # estreio = narrow?
m "— Isso é uma outra trolagem?"
t "— Ha! Não!"
"TJ olha de volta para mim e discorda com a cabeça, seus olhos arregalados."
t "— Ela tava bem ali... provavelmente ainda tá lá agora."
m "— Cara, é melhor que você não esteja me zoando com isso, vai fazer o resto do dia ficar tããão pior."
"Ele se arrepia de novo, mas ainda estou desconfiado. O TJ consegue ser um bom ator quando quer."
t "— Realmente era uma tarântula."
"A porta da frente se abre repentinamente e a Janice espreita com a cabeça para fora."
ja "— Ai minha nossa! Quem são esses belos rapazes que estão no meu quintal?" # quintal? (mas é na frente...)
show TJn Surprised at left with easeoutleft
show Janice at farright with dissolve
"A velha coiote sai, olhando para nós de cima a baixo, especialmente o TJ."
show TJn Sheepish with dis
"O lince percebe e segura um braço com uma das mãos, como se estivesse tentando se cobrir sob o seu olhar."
ja "— Mmh-mh! E por que essa gritaria toda?"
"Eu fico sem reação diante o quão direta a velha coiote foi."
m "— Hum–"
"Olho para o TJ, mas ele não diz nada."
m "— O TJ disse que viu uma tarântula..."
"Janice coloca uma pata ao lado do rosto."
ja "— Ai que horror. Uma loira?"
t "— Ta–talvez? Eu nunca vi uma antes."
ja "— Bem, elas tão por toda parte aqui, vocês só nuncam vêm elas porque elas só saem à noite."
"Janice protege seus olhos do sol novamente."
ja "— Numa hora dessas do dia é quente demais pra elas. Provavelmente era uma caranguejeira."
"Todo esse papinho sobre aranhas tá me dando vontade de só voltar andando agora mesmo pro hotel igual um arrombado."
t "— Não era."
"TJ murmura ao meu lado, mas eu não acho que a Janice ouviu ele."
ja "— Só queria deixar vocês sabendo que eu fiz uma limonada e também tô com alguns cookies no forno!"
"TJ força um sorriso em seu rosto."
t "— Aw, obrigado, Janice!"
"Ela dá um sorrisinho para ele."
ja "— Você é simplesmente a coisinha mais fofa!"
"Ela se aproxima para beliscar suas bochechas e de alguma forma ele consegue continuar sorrindo enquanto ela belisca."
hide Janice with dissolve
"Finalmente, a Janice volta para dentro e eu dou uma longa olhada para o TJ."
show TJn Surprised with dis
"Ele levanta as mãos para o alto."
t "— Eu não tô mentindo!"
"Consigo ver ele ficando avermelhado sob o pelo, então eu deixo para lá por agora."

scene bg janicehouse with dissolve
"Damos uma olhada por um tempo mas não conseguimos encontrar nenhum rastro da aranha."
"Voltar ao trabalho é difícil, e eu fico pulando ao ver qualquer coisa longa e estreita."
"Que, quando se está limpando bolas de feno, é tudo."
"Além disso, eu vejo várias aranhas pequenas e, sempre que vejo, eu pulo e corro um pouco para longe antes de tentar espantá-las."
"No entanto, o TJ se recupera muito mais rápido, e em pouco tempo ele está jogando as bolas de feno no mesmo ritmo de antes." # jogando? (tossing out)
"Isso me deixa ainda mais desconfiado."
"Enfim, não é tão ruim de se olhar."
"O TJ tá muito mais sheipado do que eu, os músculos firmes de suas costas se destacam facilmente e deslizam sob o pelo." # sheipado? (manter só "em forma"?)
"Eu me pego olhando várias vezes e tenho certeza de que ele também."
"Quando estamos quase terminando, tenho que me endireitar, pressionando as mãos na minha lombar para fazê-la estalar."
show TJ-noshirt-n with dissolve
play music "neutral.ogg" fadein 3.0
t "— Tá com dor?"
m "— Um pouquinho."
"TJ joga fora uma das últimas bolas de feno antes de vir para o meu lado."
t "— Ela sempre dói?"
"Ele coloca a mão na minha lombar e começa a passar a mão por ela."
m "— Hum, não tanto? Só quando eu tô me abaixando e tal."
"Ele fica quieto por um momento, passando a mão no pelo em minhas costas."
"Eu começo a corar, mas é aí que ele aplica um pouco de pressão em um músculo."
"Eu faço uma expressão de dor e fico todo erguido."
t "— Nossa, que duro!"
"Solto um som chiado e tento me virar, mas ele coloca uma mão no meu ombro para me manter no lugar."
"Ele dá uma risadinha."
t "— Fica parado por um segundo."
m "— Bem, quando cê tá enfiando tudo assim–" # muito sexual?...
t "— É porque você tá todo tenso. Só relaxa."
"Eu tento relaxar como ele diz, embora seja extremamente desconfortável."
t "— Tipo, as lontras são conhecidas por terem costas ruins."
m "— Tô ligado. Meu pai mal consegue se mover hoje em dia."
t "— Que horrível."
"Eu levanto os ombros."
m "— Ele ainda consegue dar um jeito. Só precisa tomar analgésicos."
t "— O que você não quer ter que depender."
"Meu ombro encosta no peitoral do TJ e seus longos bigodes passam pela minha orelha."
t "— São as perninhas e as costonas."
m "— Grosso."
t "— Você tem que se curvar mais do que a maioria de nós. Mantenha uma boa postura, e levante objetos pesados com os joelhos."
"Seus dedos deslizam um pouco mais para baixo antes de se afastarem."
t "— Você vai se agradecer daqui a vinte anos quando não tiver sentindo uma dor constante."
"Ponho as duas mãos nas costas, me sentindo quente e muito mais solto."
m "— Ei, eu realmente tô me sentindo um pouco melhor."
t "— Ótimo!"
"Estou impressionado com o quanto o TJ sabe sobre lontras. Ele provavelmente sabe a mesma quantidade sobre todas as outras espécies também."
m "— Sabe, cê é muito inteligente."
"TJ abaixa a cabeça modestamente."
t "— Ah, eu só tô repetindo o que aprendi."
m "— Tipo, eu esqueço tudo o que eu aprendo dentro de uma semana."
t "— Eu também esqueço, às vezes. Você só precisa continuar estudando até colar."
"TJ olha em volta."
t "— Na verdade, eu realmente queria que você pudesse se deitar em algum lugar. Daí eu poderia te dar uma massagem de verdade."
m "— Isso seria incrível."
t "— Eu poderia te dar uma hoje à noite quando voltarmos pro hotel!"
m "— Certeza?"
"Só de pensar nisso já me sinto quentinho, e não só nas costas."
t "— É claro! Tipo, eu meio que te arrastei pra cá..."
m "— Não se preocupa com isso! Na real até que é bem legal. Não tenho feito um trabalho desses faz alguns anos."
"TJ sorri de volta para mim."
t "— Não é?"
"Ele se inclina para trás e se estica e eu tenho que me forçar a não ficar olhando para seu torso se destacando."
t "— Mas eu acho que já acabamos com as bolas de feno."
"Olho um pouco desanimado para a pilha de tábuas."
"TJ segue meu olhar e me dá um sorriso solidário."
t "— Lembra, com os joelhos!"
"TJ diz com alegria enquanto marcha até a pilha."
hide TJ-noshirt-n with dissolve
stop music fadeout 3.0
"Descobrimos rapidamente que, embora não haja nenhuma tarântula, as ruínas do depósito estão infestadas com aranhas."
"Várias delas são viúvas negras."
"Como elas são realmente perigosas comparadas às loiras, o TJ entra para pedir a Janice um inseticida."
"Eu volto para me molhar de novo com a mangueira, deixando a água gelada escorrer pelas laterais da minha cabeça e pelo meu focinho."
m "— Aranhas fudidas. Em todo lugar nessa porra."
"Eu me arrepio de novo."
"Eu ando nervoso desde que o TJ – fingiu que? – viu aquela tarântula."
"Me levanto, deixando a água correr pelas costas e pela frente, suspirando com o quão gostoso é."
"Ouço a porta da frente abrir e fechar e o som dos passos do TJ vindo pelo lado da casa."
"Olhando para baixo para a mangueira ainda-ligada em minha mão, eu dou um sorrisinho."
"O TJ foi quem começou essa guerrinha de trolagens, então eu não me sinto tão ruim pelo que estou prestes a fazer."
"Eu me pressiono contra a lateral da casa – me certificando de que não há nenhuma aranha primeiro –."
"No segundo que vejo o pé do lince surgindo da lateral eu levanto a mangueira."
"Minha intenção original era molhar a frente das calças dele para que parecesse que ele tinha se mijado."
"Infelizmente, ele está longe demais da casa e ao invés disso ele fica olhando para mim enquanto um arco de água cai a um metro de distância dele."
"Ele está segurando alguma coisa, mas eu não tive tempo de ver o que era antes de pressionar o polegar na abertura da mangueira e mandar uma jatada direto para o rosto do TJ."
play sound "pour.mp3"
"TJ fica boquiaberto como se tivesse caído em água gelada e dá uma topada para trás, quase tropeçando."
"Eu rio."
stop loop fadeout 5.0
play music "TJtheme.ogg"
t "— Chase! Que que é isso!?"
"Eu por fim paro o fluxo de água, revelando um lince piscando furiosamente e encharcado."
"Em uma de suas mãos há uma vassoura e na outra um prato com o que provavelmente eram cookies."
"Eles parecem meio moles agora."
m "— Ai, merda."
"TJ larga a vassoura para examinar seu prato de cookies."
"Ele a inclina para o lado e deixa um fluxo de água escura e cheio de farelos escorrer do prato."
t "— Eles também tavam com um cheiro tão bom..."
"Eu vou até ele e pego o prato."
m "— Bem, os de cima não tão muito ruins, só um pouquinho mole."
"TJ franze o nariz."
t "— Só joga eles no deserto. Eu me sentiria mal se a Janice visse."
"Eu pego um cookie e dou uma mordida. Está um pouco mole na superfície, mas está quente e grudento no centro."
m "— Mmmmh."
"TJ olha para mim horrorizado."
t "— Chase!"
m "— Quê? Tá gostoso pra caramba. Para de frescura e come um."
"Eu pego outro."
t "— Para! E se essa água estiver toda suja?"
"Isso me faz pausar por um segundo, mas eu levanto os ombros."
m "— Eu engolia água toda hora quando nadava no lago."
"Me pergunto logo depois de dizer isso se não deveria estar mencionando qualquer coisa relacionada ao lago perto do TJ, mas ele apenas discorda com a cabeça, passando por mim."
show TJn Rejected with dissolve
t "— Se você começar a vomitar hoje à noite saberemos o porquê."
m "— Mas eu terei você para cuidar de mim, doutor."
t "— Eu realmente não sei muito sobre estar doente."
"Ele me observa ansioso enquanto dou outra mordida."
m "— Mesmo assim, tá muito bom."
"Aponto para a vassoura na terra."
m "— Pra que essa vasoura?"
"TJ se abaixa para pegá-la."
t "— A Janice não tinha nenhum inseticida, então ela disse pra passar a vasoura nas tábuas."
"Faço um som de desconforto." # groan = som de desconforto?
t "— Eu tava pensando que você poderia passar ela e eu levantaria já que suas costas tão doendo."
"Faço um som de desconforto."
t "— Não se preocupa. A Janice disse que se elas nos morderem a gente avisa pra ela nos levar no hospital."
m "— Perfeito."
t "— É... escuta, desculpa por tudo isso. Eu não sabia que seria tão pesado pra você."
"Eu engulo culpado."
m "— Eu tô zoando. É realmente só a quantidade de aranhas que é a pior parte."
t "— Eu vou pagar na lanchonete quando terminarmos, tá?"
"Eu sorrio para ele."
"Não estou sofrendo por dinheiro nem um pouco, mas eu sei que o TJ se sentirá melhor se eu o deixar."
m "— Beleza, fechado."
scene bg janicehouseafternoon with dissolve
"É o fim da tarde a esse ponto, o sol está baixo o suficiente para que a casa da Janice esteja projetando uma sombra no quintal."
"E claro, essa sombra está a alguns metros de distância de onde estamos trabalhando."
"Começo a trabalhar tentando varrer as aranhas, seus ovos, e todos os outros tipos de insetos enquanto o TJ pega as tábuas grandes e as arrasta pelo quintal."
"Eu sou péssimo nisso, tentando não gritar enquanto balanço a ponta da vassoura para frente e para trás como um idiota."
"TJ me diz várias vezes que posso só esperar, mas eu me sentiria culpado demais se eu saísse."
"Em um determinado ponto, eu quase jogo uma aranha no TJ o que o faz gritar."
"Mas depois de vários pedidos de desculpas e risadas nervosas, voltamos ao trabalho."
"Demora muito mais do que deveria, principalmente por causa de toda a varredura que estou fazendo, mas algumas horas depois estamos nas últimas tábuas."
"A maior parte do que restou são tábuas apodrecendo e deterioradas."
"TJ passa a mão pela testa."
show TJ Neutral at center with dissolve
t "— Bem, eu diria que essa é a última."
"Eu dou uma varrida rápida na tábua, feliz por não ver nenhuma aranha nessa."
m "— Ei, eu tava pensando; cê quer ir numa outra trilha amanhã? A gente poderia convidar os outros pra vir com a gente."
"TJ olha para mim."
t "— Você tem certeza? Eu achei que você não tinha gostado."
m "— De novo, eu reclamo muito. Eu me diverti."
show TJ with dis
"TJ sorri."
t "— Bem tá legal, isso seria incrível!"
"Ele está com um sorrisinho agora, e isso me faz sentir ainda melhor."
t "— Certo, vamos terminar isso e podemos ir na lanchonete e planejar tudo."
m "— Fechado."
"Com isso, o TJ vira a tábua e revela uma tarântula enorme."
stop music fadeout 2.0
"Oito olhos pretos e lustrosos refletem o sol e logo sou quase cegado por eles."
"Eles me penetram e a aranha se vira lentamente, como um caranguejo em suas pernas, para que fique de frente para mim."
"Meu estômago se retorce e o chão se inclina."
"Sinto que estou caindo da beira do mundo."
"Eu me agarro em alguma coisa, qualquer coisa, mas tudo o que há é o ar ao meu redor, e eu caio na escuridão."
scene bg black with dissolve
unk "— Só conta quando os ombros tiverem abaixados, tá?"
scene bg fb5 with slow_dissolve
play music "eveningcall.ogg" fadein 3.0
"Sinto como se água estivesse correndo pelos meus ouvidos e tenho que manter uma postura com minhas pernas distantes para não cair."
unk "— Tu tá ouvindo?"
m "— Ahn?"
unk "— Chaaaaaase."
m "— Quê?"
"Tento focar no garoto na minha frente."
show Young_Sydney_casual Worried_arm with dissolve
sy "— Tu morreu, ou algo assim?"
m "— Sei lá, só tava pensando em outra coisa."
show Young_Sydney_casual with dis
sy "— Ha, tu é idiota."
m "— Tu é idiota."
t "— Não tô me sentindo bem."
show Young_Sydney_casual at right with easeoutright
show Young_TJ Sad at left with dissolve
"Toby fica parado com os braços em volta do estômago, suas orelhas abaixadas."
sy "— Para de ser um bebêzão, Toby. Só mais um round!"
t "— Eu não quero–"
sy "— Já!"
hide Young_Sydney_casual
hide Young_TJ
with dissolve
"Sydney pega Toby pelos ombros e coloca uma perna por trás de suas pernas."
play sound "bodyfall.ogg"
scene bg fb5 with hpunch
"TJ é facilmente derrubado e cai de costas na terra."
"Tenho a impressão de que o lince está propositalmente perdendo para que acabe logo."
"Sydney não gosta disso e tenta puxar o TJ para que ele levante antes de ir pra cima do lince sobre seu estômago."
"Ele dá um puxão nas orelhas do Toby."
t "— AI!"
"Eu dou um passo à frente."
m "— Ok! Sydney ganhou!"
"Levanto a mão e aponto para o Sydney, apenas querendo que isso pare."
"Sydney continua e pega sua camisa que havia jogado no chão mais cedo e a amarra no pescoço do Toby."
m "— Sydney!"
sy "— Regras pesadonas! Vale tudo!"
m "— Sério..."
"Toby segura seu pescoço e seus olhos se arregalam quando o Sydney recua, puxando a cabeça do Toby junto com ele."
"Os braços do lince se debatem descontroladamente, sua boca completamente aberta."
"Fico ali parado, confuso. Tá tudo bem se não for contra as regras?"
"Sydney ri e se recua ainda mais, parecendo empolgado e feliz."
"Toby me encara com olhos arregalados e grandes."
stop music

scene bg janicehouseafternoon
show TJ Surprised at center
play loop "reststop.ogg"
m "— PARA!"
"Eu vou em frente e seguro o TJ."
t "— Chase! Chase, você tá me ouvindo!?"
"TJ está olhando para baixo para mim com seus olhos azuis arregalados."
m "— Toby?"
t "— Eu–Quê?"
"Eu pisco para ele, me sentindo mal."
"TJ sente minha cabeça, depois se levanta e começa a me puxar pelo chão."
m "— Que... O que tu tá–"
t "— Tenho que... te levar... pra dentro."
"Ele grunhe enquanto me puxa e é aí que meu estômago embrulha e eu rolo e vomito os cookies."
t "— Merda... merda!"
"Consigo ouvir o TJ começando a entrar em pânico, então o seguro."
"Tenho que tossir e cuspir várias vezes antes de conseguir falar."
m "— Não, eu tô bem. Não entra em pânico."
t "— Não você não tá! Você consegue se levantar?"
m "— Sim, sim, eu tô bem."
"Eu me levanto com minhas pernas trêmulas mas estáveis o suficiente."
"TJ coloca um braço em volta de mim."
t "— Vamos chamar uma ambulância assim que entrarmos."
m "— Não, eu tô bem."
t "— Não! Você não tá bem. Isso é sério."
"Ele começa a me apoiar em direção à frente da casa."
t "— Eu deveria ter ficado de olho em você."
"A voz do TJ falha e eu o interrompo."
m "— Ei, olha pra mim. Eu tô bem."
"Eu olho para ele nos olhos e vejo lágrimas prestes a derramarem."
m "— Eu só tô com muita fome e me levantei rápido demais... então fiquei tonto."
"TJ olha de volta para mim, estudando meu rosto."
m "— Só não chama uma ambulância pra mim, por enquanto pelo menos."
"Eu forço uma risada."
m "— Definitivamente não tenho grana pra isso agora."
show TJ Rejected with dis
"TJ fica em silêncio por um momento, então começa a me puxar para frente de novo."
t "— Vamos ir pra dentro pelo menos. Eu nunca deveria ter feito você trabalhar nesse calor."
m "— Eu só tô cansado. É melhor irmos pro hotel."
t "— Pra dentro, agora. Só pra garantir."
stop loop fadeout 3.0

scene bg janicehouseafternoon with dissolve
"Janice fica feliz em nos deixar sentar no sofá por um tempo, bebendo limonada."
"O TJ não conta a ela o que aconteceu, mas fica olhando para mim de vez em quando, como se estivesse preocupado que eu caísse de cara para fora do sofá."
"Me sinto um pouquinho tonto, mas fora isso estou bem."
"Continuo pensando naquela tarântula, mas o TJ não disse nada sobre isso então eu decido não tocar no assunto, ainda."
"Enquanto isso, o TJ está tendo uma conversa constrangedora com a Janice."
"Eu inclino minha cabeça para trás, com fome e cansado."
show Janice at right with dissolve
ja "— Basicamente cortar as tábuas é o que vai ser a parte mais difícil. Minhas costas já não são tão boas como eram."
show TJ Sheepish at left with dissolve
t "— Ah sim, é entendível."
ja "— Acho que eu estava esperando conseguir só mais um pouquinho de ajuda..."
t "— Ah!"
ja "— Se vocês não se importarem, é claro."
"Eu levanto minha cabeça do sofá para olhar para o TJ."
ja "— Eu também estou de folga amanhã e estarei livre para mostrar o que precisa ser feito se vocês quiserem."
"TJ fica com a boca aberta, depois sorri."
t "— É claro!"
"Eu franzo a testa."
"Janice dá um grande sorriso para ele."
ja "— Você é um anjinho perfeito, Tobias!"
show TJ with dis
t "— Sem problemas, senhora."
ja "— E muito educado, também!"
"TJ evita fazer contato visual comigo, com um sorriso estampado no rosto o tempo todo."
"A Janice de repente vira seu olhar para mim e sou forçado a tirar o olhar do meu rosto."
ja "— Como tavam os cookies?"
m "— Ah! Ótimos, eles tavam ótimos, hum TJ?"
"TJ, ainda sorrindo, apenas concorda com a cabeça."
ja "— Ótimo, ótimo. Minha receita secreta."
"Ela pisca para mim, e eu me sinto um pouco desconfortável porque ela sorri com os olhos arregalados."

scene sunset with fade
"É uma caminhada curta até a lanchonete e eu fico criticando o TJ durante todo o caminho."
t "— Me desculpa! Ela meio que tava empurrando pra mim."
m "— Cê sempre pode dizer não."
t "— Eu não posso só dizer não!"
m "— Ou pelo menos que você tinha outros planos."
"TJ fica quieto enquanto eu abro a porta da lanchonete."
scene bg diner with dissolve
play music "neutraldiner.ogg"
m "— Eu tava meio animado pra sair de novo."
"TJ fica quieto enquanto nos sentamos, então eu desisto e apenas inclino a cabeça para trás de novo, com os olhos fechados."
"Fica um silêncio por alguns minutos até que o TJ finalmente fala."
show TJ Neutral at left with dissolve
t "— Como você tá?"
"Esfrego os olhos gentilmente, com uma dor de cabeça substituindo a tontura que senti antes."
m "— Cansado, minha cabeça tá doendo."
t "— Eu realmente não deveria ter feito isso. Realmente me des–"
m "— Para... de se desculpar, por favor. Tá de boa. Não foi o calor."
"TJ fica sem expressão e se senta, olhando o pôr do sol pela janela."
m "— Desculpa, eu não tô bravo. Eu só não quero ver você se culpando por isso, sabe?"
"Eu não falo para ele que suas constantes lamentações e desculpas estão irritando minha dor de cabeça."
t "— Bem, não se esquece de tentar comer. Talvez você só precise de energia."
m "— Espero que sim."
"Naquele momento um jovem cervo que eu reconheço vagamente vem até a nossa mesa."
"É estranho ver alguém tão jovem e novo no lugar da Janice."
"No entanto, quando ele chega em nossa mesa, seus olhos se iluminam."
unk "— Tejinho!?"
show TJ with dis
"TJ se ergue de repente, com um grande sorriso estampado no rosto."
t "— Julian!"
m "— Julian?"
show Julian at right with dissolve
"Já faz um tempo que eu não vejo ele."
"Ele tá maior, assim como seus chifres. Eu mal o reconheço."
ju "— E o Chase, também!? Que que cês dois tão fazendo aqui?"
t "— De visita! Eu não sabia que você tava trabalhando aqui. Que legal!"
show Julian Happy with dis
"Julian dá um sorrisinho."
ju "— Não muito, mas ele paga parte das minhas contas."
"Nesse momento eu me desligo da conversa, deixando os dois colocarem conversa em dia."
"O TJ tinha muitos amigos no ensino médio. Ele era tecnicamente popular."
hide Julian with dissolve
"Passam alguns minutos até que o cervo finalmente anote nossos pedidos."
"Quando o Julian se dirige a outra mesa, o TJ dá um sorrisinho para mim."
t "— Ai cara, é bom ver ele de novo."
m "— É, é legal."
"Quando o cervo se foi, o silêncio constrangedor rapidamente nos consome novamente."
"Porém, eu tô muito cansado pra fazer algo a respeito."
"Eu inclino minha cabeça para trás de novo, fechando os olhos, sentindo que poderia dormir ali mesmo."
show TJ Neutral with dis
t "— Então..."
"Eu abro eles e vejo o TJ olhando para mim antes dele rapidamente desviar o olhar de novo."
m "— Quê?"
t "— Hum..."
"Ele fica mexendo com a pilha de guardanapos."
t "— Você me chamou de Toby mais cedo."
m "— Chamei?"
"Mas eu me lembro mesmo quando digo."
t "— Aham."
show TJ Sheepish with dis
"TJ força uma risada."
t "— Faz anos que você não me chama assim."
m "— Uhum..."
stop music fadeout 10.0
"Ficamos em silêncio por um momento."
show TJ Neutral with dis
t "— Então... por que você me chamou assim?"
m "— Sei lá. Acho que eu tava um pouco confuso depois de desmaiar."
t "— Ah."
"Eu o olho com atenção."
m "— Cê se incomoda se eu te chamar assim?"
t "— Hum, pode ser TJ."
"Então se incomoda."
play music "bittersweet.ogg" fadein 15.0
"Eu estudo o TJ, a forma que ele está meio encolhido, suas orelhas se contraindo." 
m "— VOCÊ tá bem?"
t "— Sim, eu tô bem."
"Eu fico oscilando decidindo se devo mencionar todo o incidente com o Flynn ou não."
"Apesar de seus melhores esforços, o TJ não está enganando ninguém dizendo que não está incomodado com o que aconteceu."
"É claro que ele estaria."
m "— Cê quer–Cê quer falar sobre o que aconteceu Segunda?"
"O TJ está quieto e eu me sinto culpado."
"Tenho um pouco mais de tempo para pensar no que vou dizer em seguida quando o Julian traz nossa comida e começa outra conversa."
show TJ with dis
"TJ, mais uma vez, é capaz de facilmente esboçar um sorriso e conversar com o cervo."
"O cheiro do hambúrguer me deixa com água na boca e é incrível quando dou uma mordida."
"É impressionante o quão fácil é para o TJ simplesmente colocar um sorriso e agir com alegria."
"Isso me faz perguntar o quanto disso é realmente genuíno."
"Estou quase na metade do meu hambúrguer quando o Julian é chamado com raiva de volta à cozinha pelo cozinheiro."
"TJ fica quieto de novo e começa a beliscar sua salada."
"Eu engulo e baixo o hambúrguer, meu estômago embrulhando um pouco com o que estou planejando dizer."
m "— Eu tava pensando nisso antes de chegarmos aqui."
t "— Sobre?"
m "— Que talvez pudéssemos usar o tempo que temos aqui para lembrar do que aconteceu, para darmos..."
show TJ Rejected with dis
"TJ finalmente olha para mim e a tristeza que vejo em seus olhos faz meu coração desabar."
m "— ... darmos uma conclusão?"
"TJ está quieto, olhando para sua salada."
m "— Eu não sei, cara. Eu só sei o quão ruim ainda é pra você, e eu só quero descobrir um jeito pra gente..."
"Eu procuro as palavras corretas."
m "— ... entrar em paz com isso."
"TJ ainda está quieto."
m "— Eu não sei, cara."
"Eu finalmente falo e me afundo no assento, sentindo que arruinei a noite."
t "— Como nós faríamos isso?"
"Seu tom é trêmulo, mas genuinamente curioso."
m "— Eu não sei. Falando sobre, falando sobre com os outros? Sem o Flynn, só os outros."
"TJ olha pela janela novamente."
m "— Talvez até ir no lago, falar sobre lá... sei lá."
"Quase engasgo na palavra \"lago\", ainda preocupado em dizê-la na frente do TJ."
t "— Talvez."
m "— Talvez?"
"TJ suspira e finalmente olha para mim com um sorrisinho."
show TJ Neutral with dis
t "— Talvez, mas agora eu só quero passar o tempo com você e me divertir, tá?"
m "— Tá."
t "— Então para de ser tão bravo. Tá me deixando triste."
"Pego meu hambúrguer, meu estômago se solta o suficiente para que eu sinta que consigo comer de novo."
m "— Desculpa, eu só tava ansioso pra–"
t "— E para de se desculpar."
"Ele diz isso com um sorrisinho, então quase imediatamente fica sem expressão."
t "— Quer dizer–desculpa, isso foi grosso."
show TJ Teasing2 with dis
"Eu rio para ele, e ele sorri de volta."
"Dou outra mordida e olho pela janela."
"Me sinto muito melhor agora e tenho certeza de que eu só desmaiei porque não tinha comido nada."
m "— Aliás, cê chegou a ver aquela tarântula de novo, depois da primeira vez que cê viu?"
show TJ Sheepish with dis
"TJ se arrepia."
t "— Ugh, não, graças a Deus."
"Olho pela janela para o brilhante pôr do sol."
m "— Ah, que bom..."

stop music fadeout 3.0
stop loop fadeout 3.0
scene bg black with slow_dissolve
scene bg fb5
show nightoverlayred
with dissolve
play music "eveningcall.ogg" fadein 3.0

"Ele tenta se afastar de mim, mas eu lhe chuto na lombar e ele cai de joelhos."
"Ele permanece ali, sem se preocupar em se mover."
"Olho fixamente para sua nuca, respirando pesado."
m "— Como é quando fazem contigo?"
"Minha voz treme quando grito com ele."
"Não estou acostumado a fazer algo assim."
"Parece tão... grosso."
"Mas ao mesmo tempo sinto que finalmente estou lhe ensinando uma lição."
"Ele já se safou por tempo demais."
m "— Por que tu é tão mau com ele?"
show Young_Sydney_casual behind nightoverlayred with dissolve
"Ele não responde, ao invés disso levanta-se lentamente, limpando o rosto com as costas da mão."
"Eu falei pra ele vir até aqui pra fazer uma de suas caça ao tesouro, só pra mim poder confrontá-lo assim."
"Entretanto, não está indo como eu imaginava."
"Ele apenas fica parado ali, sem dizer nada."
"Por fim ele começa a se afastar novamente, os ombros caídos, as orelhas e a cauda abaixadas."
"Sinto outra explosão de raiva, seguindo-o."
hide Young_Sydney_casual with dissolve
play sound "bodyfall.ogg"
scene bg fb5
show nightoverlayred
with vpunch
"Rapidamente ultrapasso seu ritmo lento e o empurro com toda força que consigo nas costas."
"Sua cabeça estala para trás antes de cair de barriga no chão." # head snaps back = cabeça estala para trás (?)
"Ele permanece ali por um longo, longo tempo enquanto eu o encaro."
"Eu não consigo me lembrar do que aconteceu depois disso..."
stop music fadeout 3.0



jump tjthursday