label carlthursday:
window hide
stop music fadeout 3.0
stop loop fadeout 3.0
scene bg thursday
with transition_fade
$ renpy.pause(3.0, hard=True)
scene carlsroom
show Carl Neutral at center with dissolve
play music "banter.ogg"
window show
m "\"Are you sure you don't wanna come down?\""
"Carl lays spread out on  his bed, game controller clutched in both of the paws that are thrown over his head against the pillow."
"He offers me a glance, but returns back to his game."
"This time it's a new-looking open-world fantasy and, honestly, I'd much rather be watching him play it than doing homework."
c "\"I just don't wanna distract ya, man, and you know how much help I am.\""
"I frown."
m "\"Well, it'd be more for the company than anything. Don't you wanna look through the stuff, too?\""
"Carl screws up his muzzle, as if contemplating."
c "\"I've seen most of it, dude. I wrapped up half the stuff in there.\""
m "\"Well, alright...\""
"I pause, but he doesn't say anything."
"It's clear he's not interested, so I have no reason to nag him."
"Still, it sort of hurts my feelings..."
stop music fadeout 5.0
scene bg basement with fade
"As I make my way into the basement alone, I realize another reason why I would have appreciated Carl's company."
"The house IS as creepy as fuck."
"I've always been a bit of a pussy when it comes to scary things."
"I mean, once, after I'd seen a scary movie about possession, I'd been afraid to go to sleep for weeks, mainly because my nightmares can seem so real."
"It took almost a month for me to manage it without the lights on and I was eighteen at the time."
"And now I mentally kick myself for remembering that movie while I'm down in Carl's creepy basement, alone."
scene bg black with dissolve
"Once I get to the crawlspace I do an awkward, half-run to the flood lamp that probably would have made Carl laugh his ass off."
scene bg crawlspace
play sound "switch.ogg"
play loop "floodlight.ogg"
play music "neutral.ogg" fadein 3.0
"The crawlspace really is fucking creepy."
"I imagine Carl sleep walking down here (which I'm pretty sure is what happened last night) then waking up alone in the dark."
"I can understand why he was so freaked out."
"The sight of the plastic tarp at the bottom of the steps brings back memories of the tarantula as well."
m "\"Shit...\""
"Now I have good reason not to go down there at all."
"I still don't know if what I saw was real, or was some kind hypnagogic hallucination that my mind always seems so keen to throw at me."
"I scan the tarp, it's white and clean surface free of any insects, as far as I can tell."
"I shudder again before making my way slowly down the steps, eyes still darting around."
m "\"Come on you idiot, this is ridiculous...\""
"When I was younger I used to have a problem where I'd wake up in the middle of the night and see spiders crawling up my walls."
"I'd scream and one of my parents would come running in to tell me nothing was there."
"My dad talked to his psychologist friend who told him it was normal, so we didn't do anything about it."
"Over time, the hallucinations stopped."
"They didn't come back until I took the night shift near my university's campus."
"After that, I started to get sleep paralysis and, about half the time, spiders are involved."
"My feet crunch their way across the tarp, back toward the tubs that I know are marked \"History\"."
"I stare at them for a second, remembering that two days ago the tubs had been turned to have their sides facing the entrance to the crawlspace."
"I clearly remember seeing them that way over Carl's shoulder, right before I saw the tarantula."
"Now they're turned so that their ends are pointing to the front."
"I frown, but the prickling feeling on my neck doesn't feel good, especially with me being alone down here..."
"So I shove that to the back of my mind and grab the end of the bottom tub so I can start dragging it back toward the stairs."
"Sitting down and taking the lids off, I start sifting through the contents."
"Again, something isn't right."
"There are a few empty wrappers lying around among the artifacts, as if someone had unwrapped a few trinkets before taking them."
"I wonder if Carl decided to take a few things? God knows why he would."
"I remove those wrappers, three in all, and set them to the side before digging further in."
"This particular tub has a divider in it."
"As I start unwrapping things, I realize that one side is for the harder artifacts, like keys, or knitting needles."
"The other has mostly paper items, like photos, and documents."
"On the paper side, I see a thick folder labeled \"Biography of James Hendricks\"."
"My eyes widen."
"Now THAT would come in handy."
"Is this a book, or..."
"As I open it up I find a bunch of loose papers inside. While it's clearly copy paper, it's old enough in its own right."
"I move back down to the tarp so I can start spreading the documents out, not wanting to lose anything."
"I'm breathing heavily at this point, hardly believing my luck."
"There are hundreds of pages and I hardly know where to start."
"After a while I begin to deduce what this is."
"Someone's been trying to write a book on James Hendricks. From what I can tell it was Carl's mother, Trisha."
"Some of the documents were typed out on a typewriter, so this might have been started as far back as the 80s."
"Getting married, having kids, and running a company probably slowed things down just a little bit."
"I grin."
"While it's too bad that this might never see publication, Carl's mom has no idea how much she's saved my ass."
"On top of that, she's got it all organized."
"One divider indicates \"James Hendricks\" while another marks \"Emma Hendricks\" who I assume is James' wife."
"A few of them are filled with several names; \"Marilyn Smith/John Begay/Yanaha Begay/Christopher Leeway\"."
"Finally, the last section of the binder is filled with dividers indicating dates \"1825-1852\", \"1852-1875\", \"1875-1878\", and \"1878-1891\"."
stop music fadeout 3.0
"I start with that, my fingers shaking a bit with excitement as I start pouring over Trisha's meticulous time line, using my phone to take notes."
play music "mitt.ogg" fadein 5.0
"James was born in 1825 to an immigrant family from Eire."
"His family faced oppressive prejudice from the day they arrived in the country."
"Despite this, they managed to make a living with James' father becoming a plumber, a profession that mainly dealt with lead."
"His father, Martin, was abusive, even more so than was acceptable for the time and James suffered greatly for it."
"The mysterious death of his five year old sister, Martha, lead many of the townspeople to suspect murder on the father's part—"
"—but this was never proven."
"James left home at the age of fifteen."
"He told his remaining sibling, Jane, that if he were able, he'd find a place for both of them to stay to escape their father."
"Not much is known about James Hendricks between 1840 and 1849, with Trisha assuming that he simply job hopped around the Tri-State area."
"What IS known is that James set out West in 1850 during the gold rush."
"Luck struck quick with James finding gold in a quartz deposit in 1852."
"The first person James confided in about the find was his only friend, John Begay."
"John was a Native desert fox, and would go on to become James' business partner."
"This comes as a bit of a surprise due to John's many recorded instances of prejudice against the Natives."
"With John's help, James officially laid claim to the mine before turning it into a business."
"While Echo was originally a small camp of less than twenty people, it became a mini boomtown."
"Over two thousand people arrived within the next three years."
"Things went well for James after that."
"He became rich, built a mansion in Echo, and lived off the mine's seemingly endless flow of gold."
"He sent Jane, who was married with a large family at that point, a yearly sum of money."
"Meanwhile, no money was sent to his parents who were living in deep poverty."
"He married Emma, a girl half his age, in 1860."
"They had five children; James, Thomas, Genevieve, Carol, and Martha."
"Things changed for James in 1875, though, when he was accused of sodomy with John Begay."
"The land being lawless at the time, John Begay was hanged by the locals."
"James was never convicted of the crime, likely because of his strong influence in the town."
"However, the ostracism grew to be too much and, in 1878, he left his family to live in solitude on the West Coast."
"He quietly started a moderately successful ice cream business in the 1880s."
"It didn't grow into the regional juggernaut it is today until it was taken over by his grandson, Peter."
stop music fadeout 5.0
"He died there in his villa in 1891 from an unusual insect bite."
"I rub my eyes and check the time; three hours have passed already and it's late in the afternoon."
"Apparently Carl's game is so good he hasn't even bothered to come down and check on me."
"I sigh and gather up a few of the items; a pocket watch, what looks like a nugget of gold, and what I think is a stamp with a crest on it."
"I'll need to take the pictures outside considering how dim it is down here."
scene bg mansion with fade
stop loop fadeout 2.0
play music "reststop.ogg" fadein 3.0
"I lay the items down on the adobe sidewalk that leads up to Carl's house."
"Deciding that will make a suitable background, I start taking pictures."
"Hours after the discovery of the binder I'm still relieved."
"I was really starting to worry with how little time I had left, but Trisha's research has saved me hours of time."
"In fact, she'd pretty much laid everything out for me."
play sound "windowknock.ogg"
"I nearly jump out of my skin and spin around, still clutching my camera."
"Behind me, I can see the window still rattling from the force of whatever had knocked on it."
"It's a basement window, in a window well, though I can't see anything through it. It's too dark."
"I stare for a while, frowning."
"What the fuck was Carl doing? Did he go back downstairs and somehow see me through the window and decide to scare me?"
"I slowly gather the artifacts back up and place them in my bag, keeping an eye on the window as I do."
"If he wanted to pull that shit then I could play at that game, too."
stop music fadeout 3.0
scene bg basement with fade
"The only problem is that Carl isn't in the basement."
"From what I can gather it was the window next to the crawl space that was hit."
"Looking out, I can see the spot where I must have been standing."
"The chills return and I shiver as I move back to the crawl space."
scene bg crawlspace with fade
play loop "floodlight.ogg" fadein 3.0
"It had to have been Carl, though I don't get why he wouldn't have stayed down here until I came back."
"I gather everything back up and start to place them back into the tub in the same order I had taken them out."
"And that's when I notice something; at the very bottom of the tub a plastic baggy has been opened with its contents spilled out."
"I set down the binder which I had been about to put away and reach in, sifting through the spilled papers."
"They're newspaper clippings from the town of Payton."
"They're incredibly old, and I can't imagine this is the best way to preserve them."
"Either way, the fashion in which they're carelessly spread out across the bottom of the tub makes me wince."
"I don't remember leaving it this way and it makes me feel sick that I could have damaged any of it."
"Slowly, I push all of the clippings back into the baggie, making sure to seal it tight after I do."
"From what I can see, nothing's been visibly damaged."
"I sigh before putting everything back in the tub and shutting it with the lid, making sure it's sealed tight."
"It's a shame that it's been so difficult for Carl's family to set up the museum."
"From the looks of it some of this stuff isn't going to last much longer without proper preservation."
"Finally, I drag the tubs back and subconsciously take note of exactly how I left them before heading back upstairs."
scene bg carlsroom with dissolve
stop loop fadeout 3.0
play music "neutral.ogg" fadein 3.0
"When I get upstairs, though, Carl is asleep."
"His controller is still above his head, clutched in his paws, as if he'd fallen asleep the moment I'd left."
"On the screen his character is immobile, standing in the middle of some hut."
"A single NPC stands in front of him, walking back and forth."
"Every now and then it stops in front of him, exclaiming \"what are you doing in my hut!?\"."
"I reach out and place a paw on his shoulder and he immediately opens his eyes, snorting loudly."
"He sits up and rubs at his face, snorting again as he breaths deeply."
m "\"Did you go downstairs?\""
show Carl Rejected at center with dissolve
c "\"Huh? what happened?\""
"It's almost funny how utterly confused he looks. If he's acting he's doing a damn good job of it."
m "\"I heard some noises downstairs. I thought it was you.\""
c "\"No...I don't think so.\""
m "\"Things were moved around, too.\""
"He takes in a deep breath before blowing it out."
c "\"I told you, man, this place is haunted. I wasn't joking.\""
"We both look at each other for a moment."
"Finally, Carl breaks the awkward silence."
show Carl Neutral with dis
c "\"So how'd it go, aside from the ghosts?\""
m "\"It went alright. Just three hours and a bunch of research.\""
"He looks at me blearily."
c "\"Aww, shit, seriously? I was gonna come down after a while, I just...\""
m "\"Fell asleep, yeah. Anyway, we were supposed to go out today.\""
c "\"Really?\""
m "\"Yeah, remember? You said so a few days ago.\""
"Carl looks around."
c "\"Well, what'd you wanna do?\""
"I think."
m "\"Don't you have an interview tomorrow?\""
c "\"Don't remind me.\""
"Carl picks up his controller again and I frown."
m "\"Welll, I was thinking we could go out and maybe give you a new look?\""
"Now Carl frowns, clicking away at the controller."
c "\"Like what?\""
m "\"Well, your clothes, for one. Do you have any dress clothes?\""
c "\"Uhhh...\""
m "\"You don't, seriously? Have you ever had an interview before?\""
c "\"Well yeah, it's just that I've, uh, grown out of them.\""
m "\"Uh-huh. Well, we'll definitely need you to get some of those.\""
"I look at his beard thoughtfully."
m "\"Maybe we should give you a more...clean cut look?\""
"Carl doesn't say anything and instead goes on frowning."
"I put a paw down on his controller, forcing him to pause."
m "\"Come on, it could be fun. You can't stay in this house - in this room - forever."
show Carl Rejected with dis
"He finally does look at a me, then, his expression kind of sad."
m "\"What's wrong?\""
"Carl looks away, then stands up slowly, his joints popping."
c "\"Nothing. If it makes you happy then why not?\""
m "\"Great!\""
c "\"Just so you know I'd rather just play some video games with you...\""
"It's tempting; just watching Carl play is a lot of fun what with his style and commentary, but this is more important."
"I really want to help him out."
stop music fadeout 3.0
m "\"Maybe later tonight. Let's get this done first!\""
scene bg route93 with dissolve
play loop "highway.ogg" fadein 3.0
m "\"So apparently your great-great-great-great grandfather was accused of sodomy.\""
c "\"What!?\""
"Carl looks up from his phone, his muzzle wrinkling."
m "\"Yep, with John Begay, who I'm almost positive is related to Jenna, but I'll have to ask her.\""
c "\"Are you serious? How did you find that out?\""
"He pauses."
c "\"And maybe don't ask Jenna about that.\""
m "\"From what I can tell your mom's trying to write a book.\""
"Carl strokes his beard."
c "\"Oh yeah, she is, isn't she?...well, WAS, more like. I don't think she's worked on it in years.\""
m "\"From the looks of it she started it in college.\""
c "\"Damn.. well, I do remember her saying it stressed her out a lot, or that something happened to make her stop...\""
"Carl seems to be thinking."
c "\"Actually, I think I remember her talking to my dad about how those old things freaked her out, or something.\""
"He shrugs."
c "\"But we've always said the house is haunted."
"Carl's phone starts buzzing."
c "\"And speaking of Jenna...she's calling me.\""
"Carl looks a bit perturbed, but he puts on a cheerful voice as he answers it."
c "\"Yo, whale-ears!\""
"Ah, that old name."
"As he listens to her response I see his smile slowly slide off his face."
"I can hear the sharp, muffled tones of Jenna's voice, even though he's holding the phone on the other side of his face."
c "\"I don't—\""
"I guess she cuts him off because he doesn't finish."
"I glare."
m "\"Here, let me talk to her.\""
"The way Jenna acted yesterday (which isn't like her at all) is giving me a pretty good idea of what she's going off about right now."
"Carl doesn't give me the phone though, instead just staring out the windshield as we continue on the highway."
"Finally, he lower the phone from his ear, then stares at the the screen for a while."
m "\"She hang up?\""
c "\"Yeah...Said something about how Leo's depressed now, and how us hanging out by ourselves isn't helping things.\""
"I roll my eyes."
m "\"You know what? Fuck Jenna. She's been on one since Leo's day didn't go the way he wanted it to.\""
m "\"For some reason she just wants to blame you.\""
c "\"Yeah...\""
"Carl looks out his window, so I can't really gage the mood he's in."
m "\"Listen, let's get something to eat first. I'll buy.\""
c "\"No. My parents are rich. I'll pay.\""
"I can't exactly argue with that, so I don't."
"I also don't feel like I can leave it at that so, hesitantly, I reach out with a paw and place it on Carl's shoulder."
m "\"Seriously. Let's have fun today, okay? Forget Jenna.\""
"He looks over at me and gives me a sad smile."
c "\"I'm fine, Chase. I just wanna get this over with so we can go back and play some games.\""
"I sigh."
m "\"Is that all you think about these days?\""
c "\"Hey, lots of people play games for a living.\""
m "\"Name one.\""
c "\"Rob Lowe.\""
m "\"That's a sport.\""
c "\"Still a game.\""
"I grin as I hear that jokey playfulness back in his voice, glad I'm able to take his mind off of Jenna for the moment."
m "\"Well, at least that keeps them active. Playing games all day will get you...unhealthy.\""
c "\"Fat? If you didn't notice I'm already there.\""
m "\"You're not that bad. I swear you're mostly muscle.\""
c "\"Then I guess I've got nothing to worry about.\""
m "\"But you should get out more.\""
c "\"Why? I've got entire worlds in my game.\""
m "\"I don't know...what about girls?\""
c "\"They're in games, too.\""
m "\"Well, you can't exactly touch a boob with your actual paws in a game.\""
c "\"I dunno, I swear they've got those in anime land.\""
m "\"You know what I mean.\""
c "\"Already done it. Not that great.\""
m "\"You a queer, or something?\""
"I say it with a southern accent."
c "\"Let's just say I don't label my sexuality.\""
"I let that sit for a second."
m "\"That's a pretty queer thing to say.\""
c "\"Guess I'm a pretty queer dude, then.\""
m "\"Is that so?\""
c "\"'Sides, until I'm able to see my hooves again I don't think any girls are gonna be after me.\""
m "\"Well, that's what we're doing right now; trying to give you a new look, a fresh start.\""
m "\"It'll boost your confidence AND your appeal. You'll have girls AND boys after you.\""
"Again, Carl doesn't act very enthused about that."
"I tell myself it's only because he has to go out. Once we get there I'm sure he'll cheer up..."
stop loop fadeout 3.0
scene bg mallinterior with fade
play music "payton.ogg"
"I swear, every store in the Payton mall is dark and covered in neon."
show Carl Rejected at center with dissolve
"Carl stands there awkwardly, looking around as if unsure about what to do."
m "\"So what kind of look do you wanna go for?\""
"Carl looks at me like I'm crazy."
c "\"Seriously, dude? I have no idea. You brought me here.\""
m "\"Just work with this for the next hour and I promise we can go to the game store next.\""
show Carl Sad with dis
"Carl makes a big show of sighing but I assume the twitch in his ears indicates he'd like that a lot."
show Carl Rejected with dis
c "\"Well, it's just dress clothes, so it shouldn't be that big a deal.\""
"Carl's getting all insecure the way he did during the \"surprise\" birthday party."
"It's kinda cute."
unk "Carl?...Chase?\""
show Carl with dis
"The voice comes from behind me and Carl smiles over my shoulder before I turn around."
m "\"Raven!?\""
show Raven Happy at right behind Carl with dissolve
show Carl at left with moveinleft
"The black and white two-toned husky is just a few feet behind me, grinning."
ra "\"How long has it been?\""
c "\"Too long, man. What are you doing here?\""
ra "\"Family moved back after dad got fired...now I work here. I could ask the same about you, Chase.\""
m "\"Oh, uh, just on spring break right now. You work in a clothing store now?\""
"Raven laughs."
ra "\"No, I'm a store down. I work at Game Central.\""
"Carl perks up at that."
ra "\"So you're still in school, huh? Well it's great to see you!\""
"Raven's accent is only slightly detectable now, the only noticeably foreign thing about him being his name."
ra "\"So what are you guys doing here? Getting clothes?\""
m "\"Yeah! For Carl, actually. He has an interview tomorrow.\""
show Carl Sad with dis
"For some reason Carl ducks his head at that and, through his ears, I can see him blush deeply."
ra "\"Oh really? It's about time!\""
c "\"I mean, I HAVE had a job before...\""
ra "\"So what kind of look are you going for?\""
"When Carl doesn't answer I speak up."
m "\"That's what we were trying to figure out just now, actually.\""
show Raven Confused with dis
ra "\"Hmm...\""
show Carl Depressed with dis
"Carl shrinks further into himself, his hat seeming to fall further over his eyes."
c "\"Dude, It's just dress clothes, really...\""
ra "\"Well, I think you should get a red tie, at least, might go good with your eyes. And maybe trim that beard?\""
show Carl Rejected with dis
c "\"Since when are you a fashionista?\""
m "\"Come on Carl, let's at least try it out.\""
"Carl sighs, rubbing his forehead."
c "\"Okay, fine, but only as long as we're outta here in the next hour...\""
show Raven Happy with dis
ra "\"Hey, I gotta get back to work, but I'll be free in about an hour. Let's catch up!\""
hide Raven with dissolve
"I wave at Raven, then turn to Carl."
m "\"Well that was nice. Didn't think I'd ever see him again.\""
show Carl Neutral with dis
c "\"Me neither, actually. I'll have to hang out with him more.\""
c "\"I mean, I like Flynn, but having to put up with him just to get a ride to the store isn't always worth it.\""
m "\"Well anyway, if you're wanting to get out of here in an hour then we should probably get started.\""
hide Carl with dissolve
"The process is a lot less painful than Carl makes it out to be."
"Soon enough, we're on our way to the food court, Carl carrying a bag way too big for the contents inside."
"We meet Raven again and, once we get our food, he suggests we eat outside."
scene bg mall with dissolve
"I look from my full combo meal to Carl's small, tiny container of tater tots."
m "\"You not hungry?\""
"Carl just shrugs and grins at me."
show Carl Teasing at left with dissolve
c "\"You just don't know the ways of the fatty.\""
m "\"Huh?\""
c "\"We're judged all the time, especially when we're eating.\""
"He delicately bites a tater tot in half before adopting a sarcastic tone."
c "\"'Ew gross, of course he's eating.'\""
m "\"That seems kind of unfair.\""
c "\"See, Raven thinks so, too.\""
"The husky is in the middle of a huge bite of his subway sandwich, his eyes on Carl. He swallows before speaking."
show Raven Wry at right with dissolve
ra "\"I can see that you're self-deprecating as ever.\""
c "\"You know me.\""
show Raven with dis
ra "\"So Chase, are you still dating that wolf...uh, Leon?\""
show Carl Neutral with dis
m "\"Leo, and no.\""
"I ignore the sidelong glance I get from Carl."
ra "\"Ah, sorry about that. You two were really cute together.\""
"It's hard to know what to say when people comment on your relationship."
"If someone isn't homophobic, gay relationships are usually \"cute\" or \"adorable\"."
"OR maybe it was just the size difference."
ra "\"But seriously, I've always wanted to date an otter.\""
m "\"Oh really?\""
ra "\"Yeah, they're adorable.\""
"{i}Swimming clowns.{/i}"
m "\"Do tell.\""
show Raven Wry with dis
"Raven picks up on my sarcastic tone right away, but it doesn't seem to phase him."
ra "\"Well, yeah. You know what they say about otters and blow jobs.\""
show Carl Surprised with dis
"Carl almost chokes on his last tater tot."
show Carl with dis
c "\"The hell, Raven? You barely know him and you're saying that shit!\""
"Carl's laughing, though."
"I'm sure to keep my face passive."
m "\"Oh? What do they say about otters and blow jobs?\""
"Raven laughs."
ra "\"You know. They never have to come up for air. Ten minutes, non stop!\""
"Raven giggles, then makes a visible effort to keep a straight face."
show Raven with dis
ra "\"Sorry, I don't mean to make you uncomfortable. It's just one of those jokes I always hear.\""
m "\"You can imagine I do, too, and it's eight minutes, by the way.\""
show Raven Wry with dis
ra "\"Psh, I'd take that, too.\""
"Carl crumples up a straw wrapper and flicks it off Raven's blue-ish looking nose, to which he simply smiles."
"Carl stands up."
c "\"Hey, I'm going to the bathroom. Raven, don't be a dick.\""
ra "\"I'm not!\""
hide Carl with dissolve
"We both watch Carl amble off before Raven turns back to me, that dopey smile back on his face."
show Raven Happy with dis
ra "\"So how long are you gonna be here, Chase? We need to catch up!\""
"I wonder what catching up means when our biggest interaction up until this point was dissecting a shark in high school biology."
m "\"Sunday. School starts up again on Monday.\""
"Despite having a head start on the project thanks to Carl's mom, I still get a nervous twinge in my stomach."
"I still have a lot left to do."
"Voice overs, b-rolls, and oh God, editing."
ra "\"We should hang out!\""
"His adorable excitement is barely contained and I'm pretty sure I can hear the thumping of his tail against the curb we're sitting on."
"Despite my earlier offense at his stereotyping of otters, I'm reminded at how much worse dogs get it."
"They're not common in Echo, or this side of the world, for that matter."
"While otters are thought of as entertainers, I feel like it's better than dealing with being seen as a simpleton."
m "\"So the main reason I'm here is to do a news segment on Echo, for class.\""
ra "\"Ooh! Is it gonna be on TV?\""
"I laugh."
m "\"No, I mean, maybe I could get it into rotation on the college TV station, but otherwise no.\""
ra "\"Well that's still pretty cool!\""
m "\"But my point is that it's kinda boring...\""
ra "\"What? Is it just a bunch of writing, or...?\""
m "\"Mostly going through old stuff. Carl's family saved a bunch of artifacts from the old days.\""
ra "\"Whoa, so you're like, actually touching the old stuff?\""
m "\"Uh, yeah. That's kind of a weird way to put it, but yeah.\""
ra "\"That sounds awesome!\""
"His outgoing nature is kind of infectious. I smile."
m "\"Well, if you're really interested I wouldn't mind having some help.\""
ra "\"That's great! I have the next two days off.\""
m "\"Cool! We'll ask Carl when he gets back.\""
stop music fadeout 5.0
"It takes a while for the ram to return, but when he does he seems a bit reluctant to agree to the idea, which kind of surprises me."
"But eventually we convince him and we make plans for Raven to come over the next day."
hide Raven with dissolve
play music "intimate.ogg" fadein 5.0
"As we're heading back out to the car I nudge Carl, forcing him into a slight stumble."
show Carl Neutral at center with dissolve
c "\"Hm?\""
m "\"What's up?\""
c "\"What do you mean?\""
"I try to keep my tone light."
m "\"You seem a bit down. Actually, you have all day.\""
"Carl shrugs."
"I nudge him again and he giggles."
show Carl with dis
c "\"I dunno. It's just awkward coming out here and having you two just examine me like that.\""
m "\"Oh...yeah?\""
c "\"Yeah dude. It just feels kinda weird, is all.\""
"I stay silent for a moment, wondering if I'd made the right decision in doing all this."
m "\"Well, I'm just trying to help you out, you know?\""
c "\"I know, bro. It's cool.\""
m "\"Seriously. I've been thinking..\""
c "\"Oh no."
m "\"Your main problem is worrying about going out in public, like a social anxiety.\""
c "\"Whoa, now you're sounding like Jenna.\""
"We get to my car and he smiles at me over the roof while I unlock the doors."
m "\"I feel like if we can break through that, it'll help you out a bunch.\""
"I break eye contact as we both slide into our respective seats."
hide Carl with dissolve
m "\"And I think this job will be a huge part of that, so I really want you to get it.\""
"As I lean to the side to pull out my seatbelt, I feel something soft and warm press to my cheek."
"It only lasts for a second, then it's gone."
"I look over at Carl, but he's looking out the window."
m "\"Did you just kiss me?\""
c "\"Yeah bro.\""
m "\"Are you high?\""
c "\"No, I mean...maybe?\""
"He giggles."
m "\"So yes.\""
"Slowly, I pull out of the parking space."
scene bg route93 with dissolve
"If he hadn't made a move on me last night I might have been a little more shocked."
m "\"Where the hell did you get high anyway?\""
c "\"Alley behind the mall.\""
m "\"Charming.\""
c "\"Yeah, pretty sure I've got a few needles stuck in my hooves.\""
"We drive in silence for a while, Carl looking out at the desert scenery while I squint out the windshield, trying to see through the hazy orange sunset."
c "\"I did mean that, by the way.\""
m "\"What?\""
c "\"Just...thanks.\""
m "\"Sure.\""
"I don't know what else to say, so I leave it at that and we drive along in pleasant silence."
"Carl still seems a little sad, and I can't pinpoint why."
"I'm hoping that it's just a phase—"
"—that by the time this interview is over he'll be able to get past his anxiety and finally be done feeling like a failure at everything."
stop music fadeout 3.0
stop loop fadeout 3.0
scene bg black
with transition_fade
$ renpy.pause(5.0, hard=True)

#nightmare
scene bg black with fade
play music "creep.ogg"
"I wake up to the feeling of a familiar, numbing heaviness in my body."
"I try to move, tugging at what feels like a massive weight on my arms and legs, but all I can manage is to wiggle my fingers."
"It feels like someone's pressing down on my chest, trying to suffocate me."
"And something's in the room with me."
"I can't help myself; I open my eyes."
scene bg carlsroomred with dissolve
"A blood red glow fills Carl's room, as if from a night light covered in blood."
"The sight would have made me whimper if I was able to make any kind of sound."
"My eyes flick around the room."
"It looks strangely empty, a lot more empty than I remember it, as if Carl is in the middle of a move and he'd packed up all of his toys and decorations."
"In fact, the only thing I recognize in his room is his bed, the blankets tossed back and empty."
"I'm alone."
play sound "chuckle.ogg"
"..."
"I hear a chuckle, right next to my ear, and it's straight out of a horror movie."
"Whatever it is, it's right out of my line of sight and I can't turn my head to see what it is."
"My heartbeat picks up and I decide to close my eyes, knowing that nothing good will come out of opening them."
scene bg black with dissolve
"It breathes heavily in my ear for a while, then stops."
stop music fadeout 5.0
"The weight lifts off of my body and I feel its presence leave."
scene bg carlsroomnight with dissolve
"I sit up, open my eyes again, and sigh with relief."
"But then I realize the room is still empty, and so is Carl's bed."
play music "horrorbeat.ogg"
"???" "\"DIE!\""
"Something yanks me out of bed and suddenly I'm being pulled by both feet down the hallway—"
scene bg kitchennight with dissolve
"Down the stairs—"
scene bg basement with dissolve
"Down the basement—"
scene bg black with dissolve
"Towards the crawl space—"
"Into darkness—"
"Furry legs crawl all over my body and pin pricks pierce ever inch of my flesh."
"I'd give anything to be able to scream right now."
stop music
scene bg carlsroomnight
"I gasp and jolt out of the paralysis."
"I wait a good ten seconds before I'm convinced that I'm really out of it."
"Carl's snoring loudly in his bed, one arm dangling over the side while his belly rises and falls."
"I sit up and rub my face, wondering how the hell I'm gonna get back to sleep after that."

jump carlfriday