label mansion1:
scene stars
with slow_dissolve

play music "transition.ogg"
window show
"Wind blows pleasantly through my fur, seeping underneath and cooling my sweating skin."
"The smells of the desert, sage brush and dirt, overwhelm my senses."
"Everything is black around me, but there are a million stars above me."
"I hear the smattering of small feet running circles around my body, snuffling of noses up against my sides and neck."
"Mixed into the sounds of the wild are words; languages I don't understand, chanting and singing, the sounds of dancing."
"Then another language."
"I hear a word or two that I learned from Leo years ago."
"And then my own language."
play sound "cackle2.ogg"
"And above it all is a maniacal cackling, one that builds and fades before choking off into a sob..."
stop music fadeout 5.0

scene bg black with slow_dissolve
"The first feeling I have is one of confusion."
"I feel stiff and cold and I'm lying back on something hard."
"I expect to see stars above me when I open my eyes, but instead all I see is blackness..."
"Panic starts to well up inside me."
"My breathing quickens and, though it's hard and painful, I manage to push myself up into a sitting position."
"That's when I see a gentle glow coming from an opening about thirty feet away from me."
"Where am I?"
"The last thing I remember was the lake."
"Wait, no, Carl's house is the last thing I remember."
"We went back to his house after the lake."
"Did I fall asleep in his house somewhere?"
"I feel around on the floor with my hands and can feel wood underneath me."
"It creaks as I shift around."
m "\"Carl?\""
"My voice comes out hard and crackly."
"I have to lick my lips several times to keep them from sticking together."
"I call out again, but more softly this time because now I'm starting to wonder if someone else brought me here." 
"When I don't hear anything I start to crawl forward, towards the light."
play loop "atticshuffle.ogg" fadein 3.0
"My head throbs a little and there's a coppery taste in my mouth."
"Probing my tongue around, I taste the sour of bites along my cheeks."
"I start to run through a list of things that could have happened...I was in Carl's basement, then I just sort of seized up."
"Did someone hit me over the head?"
stop loop fadeout 3.0
"I stop crawling and start moving my hands around my body and over my head."
"No. No sign of any injuries."
"Aside from the cheek bites, it's really just the inside of my head that hurts."
"While I do this, lucidity starts to return in waves as if a dam has broken and all of my senses are falling back into place."
"At the same time the panic starts to return as I realize how much this doesn't make sense."
"Someone had to have brought me here, wherever \"here\" is."
play loop "atticshuffle.ogg" fadein 3.0
"I start crawling again, trying to keep my panic under control."
"I'm almost to the glow, but it's weird because it's coming from the ground."
play sound "rustle.ogg"
"As I get closer I hear a soft brushing behind my head."
"I tense and look over my shoulder."
"I'm greeted by the sight of inky blackness, so dark that it almost feels alive and I get the impression of a giant mouth opening up in front of my face."
"The imagery gives me a jolt and I lunge forward, deciding to get up on my feet so I can move fast—"
stop loop
scene glow
"And then I'm falling, but not for long."
"My senses are full of light now and I throw my hands forward to catch myself—"
"—but I keep falling and the split second before I hit I realize there's a ladder."
"I instinctively grab at it but my head hits the rungs first and I flip forward before landing on my feet."
play sound "bodyfall.ogg"
queue sound "anklebreak.ogg"
"It happens on weak ankles, though, and my right foot gives out and my ankle rolls."
"I hear a series of pops before the rest of my body hits the floor."
scene hall1 with slow_dissolve
"I lay there for a moment, the sudden noise and violence of the fall stunning me."
"In my stupor I feel a cold spiderweb of electricity pulsing from my ankle and that's what spurs me to move."
"I pull myself into a sitting position to clutch at it."
m "\"Fuck...\""
"The pain isn't really bad, but something is definitely wrong and I'm not sure if I can just walk it off."
"That's when I notice my surroundings."
"A long hallway stretches out to either side of me lit by decorative chandeliers."
"Looking up I see that I've fallen down a drop-down ladder from a small square in the ceiling."
m "\"What the hell...?\""
"I look back down at my ankle."
"I wiggle it around and immediately feel another pulse of electricity that feels much more painful this time around."
"I grit my teeth as I spread my hands out against the wall behind me, pushing myself up slowly, making sure not to put any weight on my injured ankle."
play loop "carpetwalk.ogg"
"As I'm doing this, I hear a soft clopping sound coming from my right."
"At the end of the hall it looks like it takes a sharp right, and it sounds like the noises are coming from that turn."
"My throat tightens and I press myself harder up against the wall."
"I see a shadow slide up the carpet at the end of the hallway and I hold my breath."
stop loop fadeout 3.0
"The shadow stops too, and I get the feeling that whatever it is might be holding its own breath."
"Finally, the tension gets to me and I clear my throat nervously."
m "\"Carl?\""
c "\"Chase?\""
m "\"Carl!\""
play music "quiet.ogg" fadein 5.0
"I let out a gasp of relief and almost sag down the wall."
"More clopping of footsteps and Carl appears around the corner."
show Carlalt Surprised at center with dissolve
"His eyes are wide and his nostrils flare. He stumbles up to me, his hands clasped together nervously."
c "\"Holy shit, dude, it's so fucking good to see you!\""
"I press up harder against the wall, taking more weight off of my foot."
m "\"What the hell is going on?\""
c "\"I—I don't know, I just woke up...you okay?\""
"He looks at me, then down at my foot."
c "\"Are you hurt?\""
"I gesture up at the ladder."
m "\"I fell down that thing.\""
"Carl looks up at the ladder and the dark hole it leads up to."
c "\"What were you doing up there?\""
m "\"I don't know...I just woke up in the dark and tried to crawl out.\""
c "\"Shit...\""
"Carl bends down to look at my ankle which is clearly starting to swell."
c "\"Can you walk?\""
m "\"I think so...kind of.\""
"He stands back up and looks around."
c "\"Chase, I don't know what's going on. I just woke up in a bedroom up the hall like 20 minutes ago.\""
m "\"Is this...is this not part of your house?\""
"Carl lets out a breathy, incredulous laugh."
c "\"No, definitely not. I was trying to find a window, but I can't.\""
m "\"Maybe we're in a basement, or something? The last thing I remember is your crawl space.\""
c "\"Why would they have an attic in a basement?\""
"I look back up at the dark hole in the ceiling."
m "\"Maybe it's not an attic.\""
c "\"Chase, I'm freaking out.\""
"And it shows, too. His breathing is picking up, his wide nostrils flaring again."
"I reach out and put a hand on his shoulder, giving some reassuring squeezes."
m "\"No, no it's okay. Maybe we got really high, or drunk, or something...what's the last thing you remember?\""
show Carlalt Rejected with dis
"Carl starts clicking his fingers together again, looking away, up the hall."
c "\"Uh...um, the lake?\""
m "\"Yeah? I remember we went back to your house, then down to the basement, and then...\""
"Carl frowns."
c "\"I don't remember.\""
"I watch him carefully."
m "\"But then I remember looking behind the plastic bins and there was this—\""
stop music fadeout 5.0
unk "\"HELP!\""
show Carlalt Surprised with dis
"We both jump as the scream comes from right down the hall."
"Carl and I both look at each other, wide-eyed."
c "\"What the hell?\""
unk "\"Hello!? Is someone out there?\""
c "\"That sounds like Raven...\""
hide Carlalt with dissolve
"Carl starts to hesitantly walk up the hallway and I move to follow...and immediately regret it as I put weight on my ankle."
"It's completely stiff now and pain shoots up into my shin like lightning."
show Carlalt Surprised at center with dissolve
"My gasping causes Carl to turn around in confusion, then his eyes light up when he sees my leg."
c "\"Aw shit—Here.\""
"He reaches out and I wrap an arm around his neck."
"He's sturdy and strong, easy to lean against and I sigh with relief as I take the weight off my injured ankle."
ra "\"Somebody!?\""
hide Carlalt with dissolve
"We hobble our way down the hall, following the sound of Raven's panicked voice."
"We take a left at the end of the hall and are confronted with an almost identical hallway to the last."
"That's when I start to smell smoke."
m "\"Do you smell that?\""
"Carl puts his nose up."
c "\"Something burning?\""
ra "\"Heeeelp me!\""
play music "meeting1.mp3" fadein 3.0
"I almost jump again as the sound comes from right on our left, the only door on the left side of the hallway"
"We both look at the door for a moment, Carl's ears perked straight up."
play sound "heavyknocks.ogg"
"And we both jump again as the door shakes from several heavy bashes that rattle the frame."
ra "\"Heeeeelp.\""
"The cry is mournful, like he's given up."
show Carlalt Surprised at center with dissolve
c "\"Raven?\""
"The shaking and pounding stops."
ra "\"Carl? Carl!\""
"The voice instantly turns hopeful and the voice grows muffled, as if Raven is pressing his muzzle right up against the door."
ra "\"I'm—I'm stuck, the door won't open...and there's a fire!\""
m "\"What!?\""
ra "\"Chase? There's something burning on the stove, or something...I can't see it!\""
"Me and Carl look at each other in bewilderment."
ra "\"Guys? It's getting really smoky in here. I can't really see anything.\""
"He gives a cough."
ra "\"And it's really hard to breathe!\""
c "\"Alright, hold on a sec man, we'll get you out.\""
"Carl shifts me to the wall so I can lean against it, then tries the door knob."
"The knob barely turns, clearly locked."
c "\"Shit...\""
ra "\"Yeah, it's locked...it's getting really hot in here.\""
c "\"Hold on.\""
"Carl shoves his shoulder up against the door. It gives a few creaks, but otherwise stays solid."
ra "\"Please help...\""
"His plaintive whimpering is barely audible through the thick wood."
m "\"What kind of lock is it? Maybe we could pick it?\""
show Carlalt Rejected with dis
"Carl studies the knob."
c "\"Uh, I don't think a paper clip is going to work.\""
"I lean in to look and find myself staring at an old-fashioned keyhole."
m "\"The hell?\""
c "\"Raven, can't you unlock it from that side?\""
ra "\"No, there's nothing there! Guys I can't breathe!\""
"His voice is getting desperate again."
m "\"There's no other way out? No other door in there?\""
stop music fadeout 3.0
"Raven doesn't answer and Carl and I both wait for a good ten seconds."
m "\"Raven?\""
ra "\"AAAAAH!\""
play music "meeting2.ogg"
show Carlalt Surprised with dis
"We both jump for the third time before Carl presses his face up to the door."
c "\"Raven!? Raven, what happened?\""
"For a few seconds all we hear is coughs, then Raven's voice is lower, up against the bottom of the door as if he's laying down."
ra "\"Something...something in the smoke! Help!\""
m "\"What!? What's in the smoke?\""
"My mind flashes back to what I heard in the attic."
ra "\"Something...can't see. Open the door!\""
c "\"Fuck...alright, man, stand back!\""
"I don't know if he's talking to me, or Raven, but I take a step back anyway."
show Carlalt Neutral with dis
$ renpy.pause(0.1, hard=False)
hide Carlalt with dissolve
"Carl takes a few steps back, then throws his body forward, smashing up against the door."
play sound "doorbreak.ogg"
"It shudders a little bit and I hear a crack, or two, but otherwise there's no change."
play sound "doorbreak.ogg"
"He tries it again with the same result."
m "\"Carl, I don't think that's gonna work!\""
"Carl doesn't say anything, instead backing up until his back touches the opposite wall."
"He takes a deep breath, then charges forward, his head down this time."
"Instinctively I close my eyes, imagining Carl snapping his neck right in front of me."
stop music fadeout 2.0
play sound "doorbreak2.ogg"
"The impact is much louder this time and it's accompanied by a crunch."
"When I open my eyes it's not Carl's neck that's broken, but rather the wooden door."
"Carl's head has completely busted through the door so that his head is poking in to the other side."
"I stare, expecting to see the tendrils of black smoke snaking out of the broken door...but there's nothing."
"Carl sets his hands on either side of the door, apparently taking a look around."
c "\"Raven...you okay?\""
"I walk up to Carl's side to put a hand on his back."
m "\"Carl...what is it? Is there a fire?\""
"Carl braces himself up against the door before pushing back, yanking his head out of the opening."
"He comes up with a bunch of wooden splinters clinging to his head fur and beard and sweatshirt."
show Carlalt Surprised at center with dissolve
c "\"Nothing.\""
"I duck down and look through the opening as well, taking care to keep weight off my injured foot."
scene mansionkitchen with dissolve
"I'm greeted to the sight of a brightly lit dining room and kitchen...but it's clear, no smoke in sight."
ra "\"It was...it was completely black in here a second ago.\""
"I look down at the trembling voice of Raven below me and see the husky curled up, his head poking up from his fetal position."
ra "\"Hey, Chase.\""
m "\"Uh, hi...\""
ra "\"I don't know what happened. There was smoke everywhere. It's like when you opened the door it all got sucked out.\""
"I sniff and now I can't even get a whiff of smoke aside from the residual taste I still have of it in the back of my throat."
play music "quiet.ogg" fadein 10.0
"I hear a click next to my head and look over to see the doorknob twist. I pull my head out of the hole and Carl pulls the door open."
c "\"Are you kidding me? It was locked, right?\""
m "\"It was definitely locked...\""
"Raven gets up, brushing shaky hands down his shirt."
show Carlalt Rejected at left with dissolve
c "\"You okay, man?\""
show Raven Depressed at right behind Carlalt with dissolve
ra "\"Yeah, yeah, just thought I was going to die for a second haha...\""
"I watch as Raven struggles to keep his ears perked."
m "\"What happened?\""
"Raven takes a deep breath."
ra "\"I don't know. I just woke up in here and smoke just started coming out from the stove, or oven, or something.\""
m "\"You said you saw something?\""
ra "\"Y—yeah, something in the smoke, it looked like arms, or something...\""
"Carl and I look at each other."
ra "\"But it might have just been the smoke!\""
"I look around the room, scanning it for any sign of the black smoke that Raven was so adamant about having seen."
"I don't think he was just seeing things because I'm pretty sure I hadn't imagined the smell."
ra "\"I promise I'm not lying. It's just what I saw...\""
m "\"I think the bigger issue here is that we're here at all. I mean, where the hell is here?\""
"I spread my hands out, giving an incredulous laugh."
show Raven Confused with dis
ra "\"I—I thought maybe it was just another part of your house?\""
"Raven looks at Carl."
ra "\"I mean, I went downstairs after you guys and found this hole. Then everything went dark.\""
show Carlalt Depressed with dis
"Carl looks down."
m "\"Same here. I followed Carl.\""
"We both look at Carl, but he doesn't say anything, instead just moving past Raven into the large kitchen next to the dining room."
hide Raven
hide Carlalt
with dissolve
"I hobble after him, then reach out to lean against the counter."
"I try to gather my thoughts."
"Everything still feels dreamlike, surreal, and my thoughts are sluggish."
m "\"Carl, do you have any idea what happened? I mean, that hole. Did you go there too?\""
"Carl sets his hands on his hips, eyes wandering around the room."
show Carlalt Rejected at left with dissolve
c "\"Honestly, I can't remember anything that happened after the lake, man.\""
"Raven casts a sidelong look at me before moving next to Carl."
show Raven Confused at center behind Carlalt with dissolve
ra "\"Well...maybe it will just take you a second before you can remember.\""
ra "\"I was really confused when I woke up here. I was curled up over there on that counter.\""
"Raven points to a marble-top counter, under a row of over a dozen pans hanging from a fixture attached to the ceiling."
"We stand there in silence as, I imagine, we individually absorb the situation we're in."
m "\"Carl, are you sure this isn't some extension of your house? Maybe something that leads out of the crawlspace?\""
show Carlalt with dis
"The ram laughs, but it definitely isn't genuine."
c "\"Dude, I think I'd know if this was some part of my house...\""
show Carlalt Neutral with dis
c "\"...unless my parents have just been building this secret kitchen underground for who knows how long.\""
"I glance at the lighting, which is definitely electric, then over at what looks like an electric stove."
"While everything sort of looked old fashioned, there was a mixture of modernity to it as well."
m "\"Where else could we be?\""
m "\"Raven and I remember going to the crawlspace, then losing consciousness after we found that hole, which is where you went, Carl.\""
show Carlalt Rejected with dis
"Carl finally does turn to me at that point, his brow furrowed."
c "\"Do you think I had something to do with this?\""
"Even though I was implying that he might know more, Carl's sudden jump to being defensive catches me by surprise."
m "\"No! I just wonder if you might have any more ideas since it's your house, you know?\""
show Carlalt with dis
"Carl laughs again."
"I'm struck by the fullness of it. Usually when Carl laughed it was crackly and half-hearted."
"Now it's loud and a little abrasive."
show Carlalt Neutral with dis
c "\"Think I just waited in the shadows and drugged you all up with acid, or some shit?\""
"I don't respond, just watching Carl as he stares back at me, breathing hard."
"Raven coughs loudly."
show Raven with dis
ra "\"Hey guys, let's calm down. You know, I'm kinda hungry...why don't we make some food!\""
"That seems to break Carl out of his stare-down with me as he looks over at Raven and huffs out one of his more characteristic chuckles."
show Carlalt with dis
c "\"Really, Raven?\""
show Raven Happy with dis
ra "\"Yeah! That always makes me feel better.\""
hide Raven with dissolve
"Raven starts opening cupboards, but each one is empty."
show Carlalt Rejected with dis
"Carl turns back to me, frowning."
c "\"Sorry Chase, I'm just fucking freaked out, too. Thing is, I don't think we're in my house anymore.\""
"He chuckles again."
c "\"I mean, are we even in Echo? What time is it, anyway?\""
"I reach in my pocket to check my phone and that's when I remember I have a fucking phone."
"I almost jump with the realization and shove a hand into my pocket to pull it out."
"Why didn't I think of that before?"
c "\"What?\""
m "\"Phone!\""
call phone_terror from _call_phone_terror_1
"I pull it out excitedly and hit the button to turn the screen on—"
"—And am met with a black screen."
"My phone's dead."
m "\"Are you kidding me?\""
"I hold the power button down, but nothing happens."
call terror_end from _call_terror_end
"I look up to see Raven and Carl getting similar results, Raven shaking his as if that's going to help."
"Carl shakes his head."
c "\"Were we out that long? This is crazy.\""
"I press a hand to my face for a moment, the idea that this could still be some sort of dream coming to mind."
"I remember after taking an overnight job back when I was a freshman and how that had fucked up my sleeping schedule."
"That in turn gave me all kinds of fucked up, realistic dreams."
"Sleep paralysis plagued me to the ends of my wits and I remember one time I thought I'd never be able to get up."
"I was stuck in bed, but each time I sat up and thought it was over I'd end up sort of waking up again, still lying down, stuck in my paralysis."
"Dreams within dreams within dreams—"
ra "\"No food, either...\""
"My scattered thoughts collect together long enough for me to decide on the next course of action we should take."
m "\"Alright, this is stupid. We should go out and look around. We'll find the way out eventually.\""
c "\"Yeah...yeah, we need to do that. I looked around a little but didn't find anything.\""
"I grip the counter a little more tightly as I feel a slight wave of dizziness come over me, making everything feel even less real."
"But the pain that's shooting up from my ankle is very real and just a glance down at the ever-growing swelling confirms it."
"The suspicion that we'd somehow been drugged grows, but I don't want to upset Carl again, so I don't mention it."
c "\"Okay, yeah. Let's uh, let's just stick together and go. We'll find the way out.\""
show Raven Depressed at right with dissolve
ra "\"Aww, I am hungry...\""
m "\"We can eat when we get out. There's no food here anyway.\""
"I turn and, even though I do it as lightly as possible, the moment I set my right foot down feels like a hundred needles press into my ankle."
m "\"Oh fuck!\""
hide Raven with dissolve
show Carlalt Rejected at center with moveinright
"Carl's at my side instantly, reaching out a hand to steady me."
c "\"Dude, you alright?\""
ra "\"What happened?\""
"I lean all my weight on the counter at that point. Just letting my foot dangle as I hold it off the ground is painful."
c "\"He fell down a ladder and landed on his foot wrong."
show Raven Depressed at right behind Carlalt with dissolve
ra "\"What!?\""
m "\"But it's only now that it's really starting to hurt.\""
"I say it through gritted teeth."
"The pain is actually making me sweat and I'm realizing that I might have done more than just sprain it."
m "\"I don't think I can walk like this.\""
ra "\"How did you fall down a ladder?\""
c "\"He woke up in an attic...here—\""
show Carlalt Neutral with dis
"Carl hunches down in front of me."
"My stupefied brain thinks up a butt sex joke, but I manage to keep it canned."
m "\"You sure? I could just lean against you.\""
c "\"That'll take too long. Besides, it looks like you can't walk at all right now.\""
"Hesitantly, I let go of the counter and let myself sort of fall forward onto the ram's back."
"He's sturdy and barely budges as I lean all my weight onto him."
"Carl reaches back with both hands and hitches my legs off the ground as he stands and I feel all the muscles in his back flex as he does."
m "\"Damn Carl. You work out?\""
"Carl grunts."
c "\"Little bit.\""
"I move my head to the side to keep from knocking my nose against his horns."
"It's a smart move because just then Carl nods his head in Raven's direction."
c "\"Hey, I know this is kinda fucked up, but maybe grab a kitchen knife?\""
show Raven Confused with dis
"Raven raises an eyebrow at Carl."
ra "\"Why?\""
"I immediately see what Carl's getting at."
m "\"We have no idea where we are...or who put us here. Might be safe to be ready to defend ourselves, you know?\""
c "\"And you said you saw something in the smoke.\""
"Raven's eyes widen, but he reaches out to slowly pull a knife from a silver-looking knife block."
show Raven Depressed with dis
"The husky frowns at the \"shing\" sound it makes."
"His ears down and elbows in, it's clear he's never used anything as a weapon before."
"But I can't blame him; neither have I."
ra "\"I don't know if I should be the one to do it, though...\""
c "\"Well, you're not strong enough to hold Chase, so I've got my hands tied.\""
"He looks back at me."
c "\"If anything happens, though, I'll have to drop you and help him out, okay man?\""
"I chuckle softly."
m "\"Yeah, no problem. Let's just hope that doesn't have to happen.\""
stop music fadeout 3.0
"And with the shaky husky in the lead, we set off back into the hallway."
scene hall1 with dissolve
play music "mitt.ogg" fadein 5.0
"Immediately it's clear that wherever we are isn't very large."
"Four identical hallways lead us around in a perfect square"
"Each hallway has three doors on the right, one on the left, and a hatch in the ceiling that leads to the attic."
"What also becomes immediately clear is that the door on the left leads into the kitchen, but from the kitchen there's only that one door out."
"Each time we open the door to the kitchen we come to realize that the angle in which we enter it is the same."
"The first time this happens we're mostly just confused, wondering if maybe we backtracked somehow."
"After the second time, though, Raven laughs."
ra "\"This isn't real! Haha! We're on drugs, or something.\""
m "\"But we're all seeing the same thing?\""
ra "\"Or I'm just having this dream and none of you are real, eh?\""
"The husky's voice is bordering on crazy."
"That paired with his grin, paired with him holding a knife is slightly disconcerting."
"Carl huffs, hitching me up higher on his shoulders."
c "\"Alright, calm down. Just don't think about it. let's try the other doors.\""
"I'm a little surprised at how well Carl is taking all of this."
"I wonder if part of it has to do with any of the weed that might still be in his system."
"We start trying the doors on the right and this time things are different."
"The first door opens up to a wall, just an extension of the beige color of the wall surrounding it."
"We stare at it for a few moments and for the first time I get a deep, unsettling terror in the pit of my stomach."
"I manage to keep it from rising to the surface, but all of this bizarre imagery combined with the surreal haze is making me feel sick and claustrophobic."
c "\"Bummer, that's definitely not the way out. On to the next door!\""
"Carl chuckles again and I feel myself clinging to his attempt at humor just to keep myself sane."
"The next door opens up to what looks like a bathroom."
"It's definitely not a modern one, though, since it's complete with a pull chain from the high tank."
c "\"Well, at least we've got all the essentials, right?\""
"The next door reveals a room full of tools and chains hanging from the ceiling, along with a sawhorse."
"The walls, though, are lined with wooden planks, and Carl gently sets me against the hallway wall before hurrying in and peering at the wood."
c "\"Fuck, it's just concrete behind it.\""
"I don't bother to ask what the hell is going on again."
"I'm just starting to accept that where we are can't be explained."
"More doors are opened, 12 in all. One is completely white and empty, another contains a frilly bedroom which is where Carl says he woke up."
"Further along we come across what looks like an office, along with a room decorated with sofas and a chandelier."
stop music fadeout 5.0
"When we reach one of the doors in the last hall, though, something is different."
"The first thing I notice is the smell."
"Though it's faint, I can tell it's sweet in the most disgusting way possible."
show Raven Rejected at left with dissolve
ra "\"Ugh, what is that?\""
"Raven holds a hand up to his nose as we approach the second to last door in the last hall."
"This one is clearly damaged. The wood is splintered in the middle, bulging out slightly as if it had been punched from the other side."
"We all stare it for a moment, the smell growing stronger."
"Then it hits me."
play music "bent.ogg"
m "\"Oh God, do you think...?\""
"I can't finish, covering my muzzle with both hands."
show Raven Depressed with dis
"Raven, who had been right up next to the door, steps back with an arm up around his face, looking like he's about to throw up."
"I imagine the smell is a lot worse for him."
m "\"M—maybe we should skip this one...for now.\""
"Carl hesitates, then gently sets me down against the wall again."
c "\"We need to check every door. This could be the way out, you know?\""
"He looks back at me, but I don't say anything, just grimacing at the door."
"He holds out a hand to Raven."
c "\"Knife.\""
#locked branching doors
"After handing it over, Raven takes several more steps back, further up the hall."
"I press my hands to my muzzle, readying myself to shut my eyes."
hide Raven with dissolve
"As Carl turns the knob I grit my teeth."
stop music fadeout 3.0
"This room has no illumination, therefore we have to rely on the light from the hallway to see inside."
"As the light from the opening door spreads across the room I see that it's rather simple."
"the walls are concrete, peppered with craters and rocks. The floor is smoother, but with webs of cracks in its surface."
"I can't see the ceiling, but I do see what's hanging from it."
"Once the door opens completely there's enough light to fully take in exactly what it is."
"A noose, frayed and old looking, but unmistakably a noose."
"Carl stares at it, then sticks his head in further to look back and forth before stepping back to close the door."
ra "\"What was it?\""
"Raven calls from up the hall, his hands clasped nervously together."
"I notice then that the rotting smell is completely gone now, instead of getting stronger when Carl opened the door."
c "\"Nothing...empty room.\""
"I see Carl visibly trying to keep his breathing under control as he holds the knife out to Raven before bending down in front of me again."
ra "\"Really? Oh thank God.\""
"Carl trembles as he stands up with me in tow."
"As the husky moves on to the final door, I lean in next to Carl's cheek."
m "\"You okay? Did you see anything?\""
"He turns his head towards mine, touching his cheek to mine."
c "\"Aside from the rope?...no.\""
"It's hard to say whether or not I believe him, or if he's just trying to protect me from whatever else he saw in there."
"Either way, I don't press for it."
"The last door is locked."
"It's big and made of small logs. Its deep brown color contrasts with all of the others."
"Raven jiggles the handle a few times and Carl tries to look into the cracks between the logs, but it's complete black."
m "\"So that's it. That's all the doors...\""
"I'm starting to feel a certain level of panic again now that we know that we're stuck."
"Carl, I think, picks up on that and comes over to where I'm leaning against the wall to set a hand on my shoulder."
c "\"It's alright, man. We haven't checked the attic either.\""
c "\"I mean, there aren't any windows so like you said, we're probably in a basement, or something, right?\""
"The reassuring hand feels good, but it's not exactly enough to keep me from feeling a certain level of despair."
m "\"Honestly? I think I'm still dreaming right now...\""
"Carl doesn't say anything to that."
"Raven sidles up next to us."
ra "\"Well, dream or not I'm still pretty hungry.\""
"We both glance at Raven and I can't help but give a little laugh at the grin on his face."
"I guess, at least for now, it's best to just not think about it."

scene mansionkitchen with fade
play music "neutral.ogg"
"We head back to the kitchen which doesn't take very long because every door on the left leads to it."
"We all split up to search the many cupboards and drawers of the kitchen for food."
"We come up mostly empty, only finding silverware and cooking utensils here and there."
"Because of my injury I cover a lot less ground, only able to hobble around along the counter, using it as a crutch as I move down a line of cupboards."
"Even if we were able to find any food there's no way I'd be able to cook it."
"The only thing I'd ever been able to make on my own was a grilled cheese sandwich back when I was in high school."
"Even then I'd almost burned down the house when I dropped a piece of bread on the gas stove."
"In a panic, I threw the flaming bread across the kitchen into the living room."
"I smile at the memory as I open the last cupboard along the wall and right in front of me is a block of cheese on a glass plate."
"Next to it is a loaf of bread in plastic bagging, and a small square of butter wrapped in wax paper."
"I stare for a moment, waiting for the food in front of me to disappear. I even blink a few times to be sure."
m "\"Uh, guys?\""
c "\"What's up?\""
m "\"You seeing this?\""
ra "\"What?\""
m "\"Cheese, bread...and butter.\""
"I stand to the side and Raven perks up."
show Raven Happy at center with dissolve
ra "\"Oooh! You found food! I swear I already checked that cupboard.\""
"Raven is next to me a few seconds later, reaching in to take out the food."
"For a moment I swear the bread blurs as he pulls it out and I have to shut my eyes for a moment to keep from feeling sick."
"I feel Carl support me from behind with his hands on my shoulders."
show Carlalt Neutral at left behind Raven with dissolve
c "\"Whoa, dude. You alright, Chase?\""
"I grab on to the counter again."
m "\"Y—yeah. It's just...\""
"Carl waits for a moment."
c "\"What?\""
m "\"I just...I was thinking about grilled cheese before I opened the cupboard.\""
show Raven Confused with dis
ra "\"Liiike, you just wanted a grilled cheese sandwich really badly and it popped up?\""
m "\"Sort of...\""
ra "\"Huh...\""
show Carlalt Neutral with dis
"Carl walks up to the bread and bends over, observing it closely."
c "\"It looks real.\""
show Raven Happy with dis
ra "\"It is real!\""
"Raven walks up to the cupboard where he had pulled the food from and closes it."
ra "\"Alright, I'm wishing for...a steak!\""
"He closes his eyes for a moment, then reaches out to pull the cupboard back open, smiling expectantly."
"It's empty."
show Raven Confused with dis
ra "\"Well, grilled cheese isn't bad.\""
hide Raven with dissolve
show Carlalt Neutral at center with moveinright
"Raven moves down the counter to grab one of the pans hanging from the rack."
"Carl moves over to my side as Raven turns the gas stove on with a {i}click click click{/i} of the igniter."
c "\"Dude, I think one of the important things to do right now is to stop questioning this place.\""
c "\"We just can't make sense of it.\""
"I fold my arms."
m "\"It has to be a dream.\""
"Carl puts an arm around me."
show Carlalt with dis
c "\"Maybe...but dude, I'm just glad I'm not here alone.\""
"I nod in agreement."
m "\"Yeah, I don't think I'd be able to deal with that.\""
c "\"Let's just take it one step at a time for now, man.\""
"I manage a small smile."
m "\"Are you high right now?\""
"Carl laughs."
c "\"Man, I wish.\""
"I hear the sizzling of the melting butter as Raven plops it in the pan."
scene mansionkitchen with dissolve
"Carl and I go about setting slices of cheese in the bread as Raven starts searing them."
"The action of making food is enough to calm me down at least a little and the other two keeping high spirits lifts mine."
"Before long there are six grilled cheese sandwiches stacked on a plate."
"They look good, but after the first bite I almost let the food fall back out of my mouth."
m "\"What the fuck?\""
"I look over to see Carl and Raven pulling similar faces."
show Raven Depressed at right with dissolve
ra "\"Ugh, it kind of tastes like chalk.\""
show Carlalt Rejected at left with dissolve
c "\"You know what chalk tastes like?\""
ra "\"Yeah, I ate some when I was a kid.\""
"He has a point; It's dry and crumbly, almost inedible."
c "\"Well, it still sort of tastes like grilled cheese...sort of."
m "\"I don't think this is food.\""
ra "\"It's not THAT bad. Besides, it's all we've got.\""
"Raven forces another bite and so does Carl."
"I can't bring myself to do it."
"My ankle, the smoke, the dead body smell and noose; it's all too much for me to deal with right now."
"I watch Carl and Raven talk back and forth and I'm again struck by how surreal this all feels."
"I think back to the time I first got stoned from a stupid pot muffin, how nothing felt real, how I felt like I wasn't in control."
"It's like that only ten times worse. I wonder if the others feel the same."
"Something ebbs to the surface of my mind, trying to break through the veil of fog shrouding my mind."
"{i}What are we doing!? Why are we sitting here eating when we should be trying to figure out a way to get the fuck out!?{/i}"
play loop "hysteria.ogg" fadein 5.0
"I open my mouth."
menu:
    "Everything is fine.":
        "I struggle to keep my food down and instead choose to look hard at the table cloth."
    "Everything is fine.":
        "I struggle to keep my food down and instead choose to look hard at the table cloth."
    "Everything is fine.":
        "I struggle to keep my food down and instead choose to look hard at the table cloth."
stop loop fadeout 5.0
show Raven with dis
ra "\"You not hungry?\""
"Raven is looking intently at my half finished sandwich."
m "\"Naw, you can have it.\""
show Raven Happy with dis
"I slide my glass plate across the table to Raven."
show Carlalt Neutral with dis
"Carl watches me but doesn't say anything, slowly chewing."
"I subconsciously note that he'd eaten around the crust, leaving those on his plate."
#decision?
"We start discussing what else we might be able to do here, other possibilities on how we could get out."
"The attic is really the only place we haven't been, yet, but because it's so dark we're not so sure about going."
c "\"Well, Why don't we sleep on it and figure out what we'll do when we wake up?\""
"Raven yawns widely."
ra "\"That sounds good to me! Feels like it's been hours.\""
"It does feel that way, but without our phones it's really impossible to tell."
scene hall1 with dissolve
"Leaving our plates where they are on the table, Raven leads us back out into the hallway."
"It takes us a few minutes to find the right door, considering everything looks identical, though we take special care to avoid the damaged door."
"As Raven moves into the bedroom Carl leans against the wall, turning his head to talk back to me."
show Carlalt at center with dissolve
c "\"Hey, we're gonna be alright, okay?\""
"I look back at the one green eye I can see and will myself to squash the boiling pit of dread in my stomach."
m "\"Okay...it's just that I can't believe this is happening, you know?\""
c "\"I gotcha...I just want you to know I'll be here for ya, okay?\""
"I look back at his gaze for a while, to the point where I think he's getting uncomfortable."
"I sigh."
m "\"You guys are just acting really weird about all of this.\""
c "\"Yeah?\""
m "\"Well, I guess Raven is being Raven. But you're acting.. different.\""
show Carlalt Neutral with dis
c "\"Really? How?\""
"I swallow."
m "\"Just yesterday you were throwing up over a job interview. Now you're the level-headed one while I'm freaking out.\""
"I laugh a little."
m "\"I just don't understand what's going on is all.\""
"Carl sets me down against the wall, then turns to me with a hug."
show Carlalt with dis
c "\"Hey man, I don't know either. I'm just trying to keep it together, too.\""
"The hug surprises me, but I take it gratefully."
"I stare over his shoulder at the uniform hallway."
"Despite Carl's efforts, the worrying feeling returns."
"Raven pokes his head around the doorway."
ra "\"Hey guys? That little sofa thing is awesome. I'll sleep there, you two can have the bed.\""

label carlsunday:
stop music fadeout 3.0
play loop "drone.ogg" fadein 1.0
window hide
scene bg SundayCarl
with slow_dissolve
$ renpy.pause(1.0, hard=True)
scene bg SundayCarl2 with slow_dissolve
$ renpy.pause(1.5, hard=True)
stop loop fadeout 3.0

scene bg black with slow_dissolve
window show
"And, of course, I dream."
play music "meeting1.mp3" fadein 3.0
"I'm running through endless hallways."
"All kinds of hallways, including one that looks like a space station and another that looks like a medieval castle."
"In each one I run into locked doors. Because of this, I can only move through the halls never knowing what's behind those doors."
"Eventually I wake up, but my dead limbs and heavy head tell me I'm not awake, not fully."
"I brace myself and shut my eyes again."
"My heart thumps and stomach churns with the disappointment of knowing I'm still in that fucking bedroom."
"The one that tells me I'm still stuck in a nightmare that's beyond the one I'm currently in."
"I feel things move about the room, hear things that sound like whining, crying, and screaming. Then I hear something in the ceiling, moving above me."
"It has many legs, like a spider that weighs hundreds of pounds."
stop music fadeout 3.0
"And then I'm free."

scene mansionbedroom with slow_dissolve
"I hold still as the gradual release of the paralysis seeps through my muscles and joints."
"At this point I feel like I've mostly learned how to cope with the nightmares."
"That thought would make me happy if I wasn't so crushed that I'm still here in this actual nightmare."
"Immediately anxiety rises back up in my chest as I realize how fucked up this actually is, how much sense this doesn't actually make."
"As far as I can tell, we've been drugged, somehow, and moved to this underground hellhole as an experiment of some kind."
"Someone in Echo had to have done this. One of the crazy old people. Maybe Duke."
"He probably built this underground maze just to watch us lose our minds, probably getting off to it at the same time."
"I grip the bedsheets and grit my teeth, grimacing at the ceiling as I try not to cry."
"That had to be it. This isn't some kind of supernatural alternate dimension; this is real and someone's fucking with us."
"We're probably being watched by cameras that are set up in corners and peepholes right now."
"That idea sends a shiver down my spine and I glance to my left, scanning the wall for any inconsistencies."
"We need to get out of here as soon as we can and the sooner we start moving the better."
"I hear a small whining grunt to my left at that moment and I look over...only to find that Carl isn't in the bed next to me."
"I stare for a moment at the tangled mess of sheets on his side of the bed, trailing off the side."
m "\"Carl?\""
"Another grunt, then I hear Carl. At least, I think it's Carl."
"His voice is deep, raspy, and it sounds like he's trying on some sort of weird accent that I've never heard him use."
c "\"My name.. mh.. soiled...\""
play music "creep.ogg" fadein 3.0
"Slowly, I sit up, and that's when I see something white sitting next to the bed."
scene sheets with slow_dissolve
m "\"Jesus!\""
"I jump and slide back on my ass away from it, almost falling off the other side of the bed."
"Staring at it a few seconds longer allows me to make out the clear shape of horns under a bed sheet..."
"Carl is sitting next to the bed with a white sheet over his head, swaying back and forth gently."
m "\"What the FUCK, Carl!\""
"I shout-whisper to him, my earlier exclamation sounding way too loud in this quiet room."
"I look over at Raven, but somehow he's still curled up on the sofa, fast asleep."
"Returning my attention to Carl, I jump again as I see that he's staring straight at me...or would be staring at me if there wasn't a sheet in the way."
m "\"Carl, what are you doing? That isn't fucking funny at all!\""
"I push myself off the bed, leaning against it to take the weight off my swollen ankle (now to twice its original size) as I stand in front of Carl."
"I reach out to take the sheet off of his head, but I hesitate."
"The horns.. they look bigger than they should be, and the voice is so different."
"???" "\"Dining.. love...\""
m "\"Carl? Carl, you're scaring the shit out of me...\""
"My voice is weak and it cracks at the end as I lose my nerve."
"Had this place been getting to Carl more than he'd been letting on?"
"But then maybe he was just sleep walking? I remember him doing that when he slept over at my house years ago."
"I reach out again more slowly this time, but again I hesitate."
"I can't shake the feeling that if I pull it off, it won't be Carl."
"Suddenly, the horned head shakes back and forth violently, the grunting reaching a fever pitch."
"Shocked, I fall back on my rear, yelping as my ankle is jolted. I lean back on my hands, watching with wide eyes."
"The shaking is so wild the sheet starts to slip off of the head as if whatever is under the sheet is trying to shake it off."
"I brace myself, watching as the sheet slides slowly from the horns to reveal..."
scene mansionbedroom with dissolve
show Carlalt Neutral at center with dissolve
stop music fadeout 1.0
"Carl."
"Of course it's Carl. He stares back at me with bleary eyes like he's just woken up."
"I swallow hard."
m "\"Carl? Carl, what are you doing?\""
"He's silent for a moment, then finally speaks;"
c "\"I know what to do.\""

scene mansionkitchen with fade
play music "quiet.ogg" fadein 3.0
ra "\"Where are we supposed to be looking?\""
c "\"Anywhere. but I know it's here.\""
"I lean uselessly against the dining room table again, watching them."
"I'm biting my lip, trying not to lose my cool, trying to absorb everything Carl had just told me."
m "\"You said James Hendricks himself came to you in your dream, right?\""
"Carl huffs but doesn't look at me."
show Carlalt Neutral at center with dissolve
c "\"Yup.\""
m "\"And he told you that you had to find...something?\""
"Carl gets down on his hands and knees and looks under the stove."
c "\"I know it sounds stupid, but that's what happened.\""
"I frown."
m "\"You know, I had a dream about a giant spider crawling through the ceiling but...\""
m "\"...but that doesn't mean that I'm going to be searching around for a spider in the ceiling.\""
c "\"No, this was different. I've never had a dream like that before.\""
"He stands back up and looks right at me."
c "\"It felt like he was actually in my brain, telling me.\""
"I look back at him for a while, not wanting to tell him he's going crazy just like I am."
m "\"Well, it's kind of vague to just tell you that you need to find 'something', isn't it?\""
c "\"He told me other stuff.\""
"Carl moves closer to me, starting to look through the various decorum of the dining room."
m "\"Like what?\""
"Carl lifts up a vase, then looks inside."
c "\"Said this place is chaos, a leftover memory from the old house.\""
m "\"That still doesn't really make any sense.\""
c "\"And that he organized it for us, into separate sections, to help us figure this out and clear his name so we can get out of here.\""
m "\"How is clearing James Hendrick's name going to end...this?\""
"I throw my hands in the air to gesture at everything that \"this\" is."
"Carl bends down to look under the dining room table, then stands up right in front of me."
c "\"What else do we have to go off on?\""
show Raven at right behind Carlalt with dissolve
ra "\"Hey, I found something weird!\""
"We both look over at Raven who holds up a corkscrew."
"Carl turns back to me, ignoring the husky."
hide Raven with dissolve
c "\"If we find it, that locked door will open and we'll be able to get out.\""
m "\"If he's here why doesn't he just show up himself and do this for us?\""
c "\"He said he's weak, that there are other forces in this house that have more control than he does. He can only do so much.\""
"I gape at him."
m "\"Do you hear yourself right now?\""
show Carlalt Rejected with dis
"Carl frowns, then moves past me."
m "\"What does his name even need to be cleared of?\""
"I feel tears starting to sting my eyes again because now I think I'm the only one here who realizes how crazy this all is."
m "\"Don't you guys get what's actually going on here?\""
"Raven stops rustling through the drawers and looks up at me."
show Raven Confused at right behind Carlalt with dissolve
ra "\"You okay, Chase?\""
m "\"No! Because someone fucking kidnapped us and put us in this crazy maze dungeon and we should be trying to figure out how we can get out!\""
"It's quiet for a moment as Raven and Carl exchange glances."
ra "\"It's okay Chase. We're gonna get out of here.\""
hide Carlalt
hide Raven
with dissolve
"I lean my head back in despair, about to cover up my face with my hands when something catches my eye."
"In the chandelier, a small, white envelope is wedged between the glass ornaments."
"I squint to make sure it's not my watering eyes creating an illusion."
"Yes, there's definitely an envelope up there, diamond patterns from the crystal cast across its surface."
m "\"Guys?\""
"Carl ignores me as he continues to shuffle through things on the counter behind us."
m "\"Carl? I found something.\""
"I point straight up at the chandelier above me."
"Carl stops then, finally, and moves next to me, looking up."
show Carlalt Neutral at center with dissolve
c "\"Is that a letter?\""
m "\"Looks like it. Do you think...is that what you're looking for?\""
stop music fadeout 5.0
"Carl gets up on the table, wobbling slightly as he reaches up to pull the envelope from the crystals."
"With a heavy thump he drops back down to the floor."
"I'm still skeptical of everything right now, but as I get a closer look at the letter I think I start to recognize it."
m "\"That kind of looks like the same envelopes your mom collected...\""
"Carl picks up the envelope, turning it over."
show Carlalt Neutral at left with moveinleft
c "\"Kind of. It just says 'John' on the front.\""
"Carl opens the flap to empty out the contents."
c "\"Isn't that the guy that—Whoah!\""
show Carlalt Surprised with dis
play sound "match.ogg"
"The letter lights up and what sounds like a match being struck accompanies the flash."
"Carl gasps and drops the letter, shaking his hands."
ra "\"It's on fire!\""
c "\"Shit! Put it out!\""
"I stupidly wonder if the lights had somehow set the letter on fire as Carl starts trying to smother the letter with a sleeve."
play loop "horrorbeat.ogg"
"At that moment, a great moaning sounds shakes the walls, almost knocking me off my feet and sending plates crashing to the floor."
"I cling to the table as the plates fall from the counter and the chandelier swings above us."
"The deep groaning coalesces into a scream that makes me clap my hands over my ears."
"Carl is staring at the ceiling his eyes wide when we hear another hissing sound."
"I jerk my head to look back in time to see a gush of inky black smoke burst from the stove, another scream accompanying it."
"It rushes straight towards us and for just a moment I see the outline of what looks like a mouth and eyes in the smoke before it engulfs me."
scene bg black
"My senses are completely smothered."
"It feels like something is slamming up against my chest and all my air is gone to be replaced by the unbreathable smoke."
"Its consistency is like water, filling my ears and eyes."
"I scream into the emptiness, but I can't hear myself over the cacophony that sounds like rushing water mixed with muffled screams and explosions."
"I fall to my knees, then curl up on the ground into a ball, just praying that the savage thing killing me would stop."
"Just as I'm starting to give in something grabs the scruff of my neck hard and yanks me up so violently my teeth clack together."
"The fingers are unmistakably hooved."
unk "\"The letter you fucking idiot!\""
"Then I'm shoved forward and find myself laying flat against the dining room table."
"Completely blind, I feel around before finding the letter."
"I clumsily rip the envelope part, grabbing the letter inside."
stop loop fadeout 5.0
scene mansionkitchen
"Then, like a massive vacuum being turned on, the smoke is sucked out of the room along with the horrible screaming and roaring."
"In an instant the room is quiet again and I slump back to the floor, gasping for breath."
"Carl is right next to me, curled up in the same position that I was."
"Raven is whimpering, his face in his hands and his rear in the air."
"Carl coughs a few times, wheezing in air before he looks at me and the envelope clutched in my hands."
show Carlalt Surprised at center with dissolve
c "\"What the hell just happened? Are you okay?\""
"I can't respond."
"I lean back against one of the chairs tucked under the table for a moment, gathering my wits."
m "\"Carl?\""
c "\"Yeah?\""
m "\"If that James guy tells you anything else...just tell me and we'll do it.\""
"Carl breathes heavily in response."
m "\"Raven, you okay?\""
"Raven sits a few feet in front of us, on his knees, tongue hanging out as he gasps."
show Raven Depressed at right behind Carlalt with dissolve
ra "\"Good, good...You know that's what I saw yesterday.\""
m "\"Yeah, I gathered that.\""
"I give a short, humorless laugh."
m "\"That and also that I'm done asking questions. I just wanna get out of here.\""

scene mansionkitchen with fade
play music "daze.ogg" fadein 5.0
"After a few minutes of catching our breaths, I turn my attention back to the letter."
"Somehow, it's completely undamaged despite catching on fire. It feels crisp and new, and the ink almost looks fresh."
"It definitely looks like it came from one of the bins in the crawlspace—"
"—but if that were the case then there's no way it could be in the great condition it's in."
"The letter itself is short, and I start to read it aloud."
m "\"My dearest John. The militia grows more agitated by the hour and I fear that they will demand a search of this mansion.\""
m "\"If that does indeed occur, I will do everything in my utmost power—\""
show Carlalt Neutral at center with dissolve
c "\"To hold them off.\""
"I look over at Carl, wondering if he just wanted to read the letter instead...but he's looking right at me."
c "\"They will never find the room I've left you in, do not fear—\""
"Carl moves closer to me, his hand reaching out to grab my shoulder."
m "\"Uh, Carl?\""
c "\"But if they so much as try to lay a finger on your head, it will be the last thing they ever do...\""
"Before I can even move, Carl leans in and kisses me."
"I'm just able to get a glimpse of Raven's shocked face before I'm practically smothered by Carl's soft, warm nose and lips."
"I freeze, my shoulders tensing."
"It's not that I'm not enjoying it, it's just that the kiss was so unwarranted."
"I'm not sure how long it lasts, but I never make a move to stop it."
show Carlalt Rejected with dis
"When Carl does finally pull back, it's awkward and he's looking just as confused as I am."
"Raven sits there, openly staring at us."
"Carl lowers his ears, his nose growing pink."
c "\"Uh, sorry, I don't know why I just did that...\""
"I clear my throat."
m "\"Uh, don't worry about it...this place is doing weird things to me, too.\""
ra "\"Awww, that was cute!\""
m "\"Raven, could you help me up?\""
"I mostly ask him so he won't dwell on what just happened."
"Carl clears his throat."
c "\"Well, I uh, I think the door's open now. Let's go check."

scene hall1 with fade
"We make our way slowly down the hall, Raven just behind us."
"I lean in closer to Carl's ear so the husky can't hear."
m "\"Soooo, was that really you, Or did your great-great-whatever take control, again?\""
c "\"I...don't know. I think I was still in control. Just felt like the right thing to do, ya know?\""
m "\"It looked like you already knew what the letter said.\""
c "\"...Yeah.\""
"I wait for him to go on, but he doesn't."
m "\"Well, what does he need his name cleared for anyway? Being gay? I don't think people care about that stuff anymore.\""
c "\"No, we already sort of knew that. Besides, that was basically a love letter.\""
m "\"So what is it that he thinks has ruined his legacy?\""
"Carl thinks."
c "\"I guess the idea that he just allowed his lover to die.\""
c "\"I think people believe that he sort of just left John to die, didn't really try to save him.\""
m "\"Hmm...\""
"This whole mess seems like a pretty roundabout way to go about that, in my opinion, but like I said earlier; I'm done asking questions."
m "\"Well, it was kind of nice. The kiss, I mean.\""
"Carl looks back at me with one green eye."
c "\"Yeah?\""
"I smile a little."
"I guess the fact that something had been growing between us since the beginning of the week is pretty undeniable."
"And now we're here in this crazy, alternate dimension with smoke monsters."
"So...well, fuck it, I guess."
"I lean forward and kiss his big, soft cheek."
m "\"Yeah.\""
"Carl grins and is about to say something when I catch movement out of the corner of my eye."
stop music
play sound "thud5.ogg"
"Immediately afterwards I hear a dull thump and Carl grunts, his eyes bulging before he crumples, sending me to the floor with him."
ra "\"Oh my God!\""
"I yelp as my ankle bangs against the floor and I roll onto my back, teeth grit, straining to reach down to hold my foot."
"Whatever just hit us is standing over me now."
"I raise a hand feebly to hold off the next blow."
"When it doesn't come I lower it slowly and look up."

jump mansion2

return
