label mansion2:
window show
ra "\"Jenna?\""
show Jenna Neutralhips at center with dissolve
play music "quiet.ogg" fadein 3.0
"Jenna stands there stoically, holding what looks like a small, wooden stool."
m "\"Jenna!? What—how did you get here?\""
show Jenna Rejectedhips with dis
"Jenna slowly sets the stool down, slowly seeming to recognize me."
"I lean forward to feel my ankle, the pain radiating from it in hot pulses."
show Jenna Surprisedhips with dis
j "\"Chase? Are you okay? What happened to your leg?\""
m "\"I...sprained it.\""
show Raven Happy behind Jenna at left with dissolve
ra "\"Hey Jenna. It's been a while!\""
"I look over at Carl who's still curled up on his side, his arms wrapped around himself."
m "\"Carl! You okay?\""
"Then to Jenna;"
m "\"Did you hit him?\""
show Jenna Rejectedhips with dis
"Jenna walks past Carl and crouches down next to my leg."
j "\"This looks really bad.\""
m "\"Yeah...Carl, are you okay?\""
c "\"Mmmmgh....\""
"Carl grunts and turns over to face us, a hand to his chest."
c "\"Jenna? What the fuck was that?\""
"Jenna looks at my ankle a while longer before standing up and looking around."
"When it doesn't look like she's going to answer, Carl sits up."
show Carlalt Neutral at farright with dissolve
c "\"How did you find us here?\""
"Raven perks up."
ra "\"Yeah! Is there a way out?\""
show Jenna Neutralhips with dis
"Jenna finally looks down at Carl and I note the complete lack of concern in her eyes."
j "\"I came to your house looking for TJ and ended up going to the basement.\""
"She looks down the hall again."
j "\"And I ended up here somehow. I blacked out before I did, so I don't know how to get out.\""
"Carl finally stands up, wearily eying the stool held loosely in Jenna's hand before bending down to help me back up."
c "\"Your leg okay?\""
"He grunts into my ear as he slides my arm over his shoulder and slowly pulls me back up onto his back."
m "\"M—mostly. I think I kinda twisted it up again.\""
show Carlalt Annoyed with dis
"Carl grunts again and turns back to Jenna, now with me on his back."
c "\"Well, that's pretty fucked up just to blindly swing at someone around a corner.\""
show Jenna Annoyed with dis
j "\"No. What's fucked up is waking up in a place you have no memory of going to.\""
show Carlalt Rejected with dis
"Jenna's sharp muzzle points right at Carl, glaring."
"Carl stutters for a second, clearly not expecting to have Jenna snap back at him."
c "\"H—hey, this isn't my fault. We have no idea where we're at either.\""
show Raven with dis
ra "\"Why are you guys fighting?\""
"Raven looks innocently between the two of them, his ears perked."
"It's a good question and I watch Jenna closely from over Carl's shoulder."
"She just glares at Carl, arms folded."
"Did she blame him for this, somehow?"
#Jenna taking it all well
"After a few seconds of awkward silence, Carl speaks up."
show Carlalt Neutral with dis
c "\"Well, you hit me for one. I don't know why YOU are so mad at me.\""
show Jenna Rejected with dis
"Jenna looks back at Carl and I see the tenseness in her shoulders slowly loosen."
#Work on this shitty scene
j "\"I'm sorry...I'm just a little uptight after waking up here.\""
show Raven Happy with dis
ra "\"Hey, you're taking it better than us. Chase was freaking out for hours.\""
"I give Raven a side glance."
j "\"Well, things have been going crazy since you two left the lake."
m "\"Like us ending up in this fucking nightmare dimension?\""
j "\"Not just that.\""
show Jenna Rejectedhips with dis
"Jenna sets the stool down on the carpet before sticking out her forearm."
"That's when I see the crusted blood in her fur in the form of three long lines."
show Carlalt Surprised 
show Raven Depressed 
with dis
c "\"What the...\""
show Jenna Depressedhips with dis
j "\"TJ attacked me.\""
m "\"What!?\""
"That sentence doesn't seem to fit together. TJ attacked?"
show Carlalt Rejected with dis
c "\"Why?\""
j "\"I have no idea.\""
show Jenna Rejectedhips with dis
"The faraway, vacant look Jenna had in her eyes earlier is fading to be replaced by a more concerned expression I better know her for."
j "\"He's been losing it ever since Flynn tried to grab him at the lake.\""
"I start to feel a little sick to my stomach."
m "\"Why?\""
j "\"He wouldn't tell me. He was just acting anxious, kept looking over his shoulder.\""
m "\"But isn't he sort of like that most of the time?\""
show Jenna Rejected with dis
"Jenna folds her arms then shakes her head."
j "\"No. He kept looking around, kept saying he was seeing things...\""
"She stops short."
c "\"...Like what?\""
"Jenna looks up."
j "\"Sydney.\""
"We're quiet for a while."
ra "\"It seems all of the rumors about this town are true; everyone is crazy.\""
c "\"This isn't normal at all...even in Echo.\""
show Jenna with dis
"Jenna looks at Raven."
j "\"I'm sorry. Who are you?\""
show Raven Happy with dis
"Raven grins."
ra "\"No, I'm sorry. I'm Raven!\""
"He sticks out a hand."
"Jenna looks at it before turning to me."
show Jenna Rejected with dis
j "\"Chase. Something was going on with Leo, too. He kept asking around for you, then he ran off saying he had to take care of some things.\""
show Raven Confused with dis
m "\"Oh, I—I don't know why...\""
"I try to think of what Leo might have wanted from me, but I draw a blank; it could be anything."
j "\"Anyway, I'd been trying to find TJ for ages.. I don't even know what day it is anymore.\""
j "\"Tried Carl's house since I'd ran out of any other options.\""
"Jenna goes quiet, then reaches into her pocket and pulls out her phone, holding it up, clearly looking for a signal."
j "\"Just as I got to your house, Carl, I heard popping sounds.\""
"Jenna sighs and puts her phone away again."
j "\"Gunshots, I'm pretty sure, coming from Main Street. Something's been happening to everyone.\""
"Jenna slides her hands into her back pockets, looking around."
j "\"And now this...\""
m "\"Wow.\""
"So something fucked up is happening all over town."
"I think about Leo and TJ and my stomach twists at the thought of them being out there."
"I can only hope that they were able to get out somehow."
j "\"At this point I'm just waiting to wake up.\""
c "\"We all are.\""
show Raven Depressed with dis
ra "\"Yeah! Especially after a giant smoke monster chased us around the dining room.\""
show Jenna Surprised with dis
j "\"What?\""
"Jenna looks at me and Carl."
"Carl glances back at me, as if asking me to be the one to explain the impossibility that had just happened."
#how long has Jenna been there?
"I take a breath, trying to think of how I'm going to say this."
m "\"So...I think at this point you're going to have to just—just go with whatever this place throws at you, Jenna.\""
ra "\"Yeah, we've all just kind of accepted what's been happening.\""
m "\"Well, we have to. Otherwise it would just be us sitting around freaking out about how crazy this all is and not doing anything about it.\""
c "\"And so far it seems we've at least been moving things forward.\""
"Jenna stares at us."
j "\"What happened?\""
stop music fadeout 5.0

scene hall1 with slow_dissolve
"We all stand in front of the wooden door in a half circle, none of us wanting to open it."
show Jenna at center with dissolve
j "\"So...this is all to clear James' name?\""
c "\"Seems that way.\""
j "\"But why go through all of this trouble?\""
"I rest on my good foot on the carpeted floor while I lean on Carl's back, wanting to give him some relief from carrying me all the time."
m "\"Probably because of the smoke monster thing. It's trying to stop him. Maybe it's making all of these obstacles?\""
j "\"Hmm...\""
"Jenna had taken our whole description of what had happened in the dining room pretty well."
"She listened silently while I'd explained what had happened so far."
c "\"So, I guess if we can get his story straight, maybe get it out to the town about what really happened, we might be able to get out of here.\""
"Jenna eyes the door."
j "\"You think that there's maybe a reason why this monster doesn't want James to get this information out?\""
"We're quiet for a moment."
m "\"Well, we don't have much else to go on.\""
"Again, there's a long pause as we all contemplate what the hell might be behind the door."
"That pause is broken by a certain husky, though, as his white hand suddenly reaches out to grasp the handle."
ra "\"Maybe we've already done what needs to be done? I'll bet this gets us home!\""
c "\"Raven!\""
play sound "doorsqueak.ogg"
"The heavy door pulls open slowly with an unearthly squeal."
show Jenna Surprised with dis
scene bg black with dissolve
"For the brief moment that I'm conscious, I see a black square in front of me that grows in size until it takes up my entire vision."
"The muscles in my back and neck seize up and my teeth clench together as my head jerks back."
"And then I'm falling..."

scene bg black with slow_dissolve
play music "nativedrum.ogg" fadein 10.0
"There's a rhythmic throbbing in my head."
"But it's hard to decide if it's coming from inside my head, or outside."
"The next sense to come back to me is touch; I feel a cold hard hard surface under my back, probably wood judging by the way my claws sink into it."
"I shift around a little, but I don't feel like getting up just yet."
"The smell is musty and old."
"I'm reminded of my grandpa's woodshed, a place I'd often go when I played hide and seek."
"The drumming sound continues and the rhythm makes me think that it's definitely coming from outside my body."
"It sounds...tribal, in a way."
"Where am I?"
"On the edges of my memory are troubling images of endless halls and rooms, the smell of decay and a noose."
"But I feel like if I block it out and just go back to sleep, I can erase all of it."
"I almost succeed, but then something brings me right out of my reverie."
ra "\"Caaaarl?...Chaaaase?\""
"I grimace, the voice reminding me of something dark, cloudy..."
ra "\"Heeeelp!\""
"The much louder yelp that follows has me rolling to my side, cracking my eyes open blearily."
scene bg cabin1 
show nightoverlay
with slow_dissolve
"I'm in a dark room, very dark, the only source of light coming from what looks like a candle on a bedside table."
"A large bed sits next to it."
"I'm laying near the foot of this bed and, opposite me, I can barely make out a wall next to which is a wooden box."
ra "\"Heeeeeellp...\""
"Raven's plaintive moan forces me to my feet, my joints cracking uncomfortably."
"As I drag my right foot up to stand under me, a blinding pain flashes up my leg, sending bright white across my vision."
"I let out a muffled scream of pain behind my clenched teeth, closing my eyes as I wait for it to subside."
"Memories are starting to flow back to me."
"There's a doorway in front of me and I start to make my way towards it, hopping slowly on my left foot, holding the right off the ground."
"I come into a small hallway, one that branches to my left into a corridor of darkness."
"Right in front of me, however, is a set of stairs."
"Light glows at the bottom and I'm pretty sure that's where Raven's voice is coming from."
"In fact, I'm pretty sure I can hear other voices coming from there as well."
"I look down at my ankle, wincing as I see that it's gotten even bigger, more than twice it's original size."
"I'm starting to think that it's more than a sprain."
"As I make my way down the stairs, cringing with every light hop, my stomach starts to sink."
"I remember now, the weird mansion that we were just in, the doors and hallways and the smoke monster."
"And the door we just went through...whatever's happening to us isn't over yet."
scene bg cabin2
show nightoverlay
with dissolve
"When I reach the bottom of the stairs, I find Jenna and Carl standing around a tall, brown wardrobe."
"As I stand there, breathing heavily, Carl turns to see me."
show Carlalt Surprised behind nightoverlay at center with dissolve
c "\"Chase!\""
"He immediately rushes to my side, his hooves clopping loudly against the wooden floor."
"I think he's simply coming over to support me, but he wraps me up in a hug."
c "\"God, I keep worrying that one of us is gonna disappear...I'm glad you're here.\""
m "\"Y—yeah, I'm fine...I was upstairs in a bedroom, I think.\""
stop music fadeout 15.0
"The anxiety I'm feeling over the whole situation goes away just a little, absorbed into the soft warmth of Carl's body."
"Over Carl's shoulder I can see Jenna watching us, her eyes narrowed, expression dark."
"I'm about to ask her what's wrong when I hear a loud bang from inside the wardrobe."
ra "\"Guys!? Are you still there? I think something touched me!\""
show Carlalt Neutral behind nightoverlay with dis
"Jenna turns back to the wardrobe, silent for a moment, then bends down to look at something."
ra "\"Guys?\""
"I hear a metallic click, then Jenna jumps back as one of the doors swing open and a black and white blur falls out like a rock."
"Raven face plants neatly into the wooden floor."
"He stays there a moment, moaning into the planks before Jenna bends over to help him up."
j "\"Are you alright?\""
ra "\"Urgh....yeah...I just—I just felt like something grabbed me.\""
"I look back up into the wardrobe to find a very bare and empty wooden compartment."
"I'm inclined to believe him, though, after everything that's happened."
show Raven Depressed at left behind Carlalt with dissolve
ra "\"Wh—where are we?\""
"It's a good question and now with the excitement over I take the opportunity to look around as well."
"Everything is wooden; the walls, floor, ceiling."
"There's a large rug on the floor covered in colorful patterns and shapes."
"It reminds me of the art projects we'd do in elementary school when learning about the Natives."
"There's a big stone fireplace and two rug-covered chairs in front of it."
"Jenna gingerly shuts the wardrobe."
show Jenna at right behind nightoverlay with dissolve
j "\"So...a log cabin.\""
c "\"Does everyone remember where we were before?\""
m "\"Yeah, that mansion place...\""
ra "\"So we're still stuck in this...dimension, thing.\""
"I sigh, rubbing my face with one hand while I lean against Carl with the other."
play music "nativedrum.ogg" fadein 15.0
"I'd long ago given up on trying to figure out exactly what the hell is going on."
"Like Carl said earlier; we just have to keep moving and hope we get out of here."
show Raven Confused with dis
ra "\"What's that sound?\""
"The drumming that I had thought was coming from within my head has started up again."
c "\"Drums?\""
"The husky moves towards the wall which consists of several logs stacked horizontally on top of each other."
ra "\"I can't see anything...the cracks are filled in with stuff.\""
"I look around again, this time more carefully."
"Right in front of me is a large, log door, not unlike the one we initially came through."
"On my left side, separated by the stairs, is what looks like the kitchen side of the room."
"In it, there's a small table with two chairs on either side."
"There's also a big, black, wood-burning stove next to a few shelves which are full of pots and pans."
"Various tools and furniture clutter up the rooms."
"And there's a window."
"I point it out to Carl."
m "\"Look, let's try and see out through there.\""
"Carl pulls me into the familiar position on his back before clopping over to the window, the sounds a bit louder with my added weight."
"Jenna and Raven follow behind."
scene bg cabin3 
show nightoverlay
with dissolve
"There's a ledge next to the window, thankfully, and Carl lets me sit on it."
"I turn to look out the window while the others crowd around me, resting their hands on the wooden bench."
#fire cg
"The first thing I notice is a flickering light in the distance, about a hundred yards away."
"It casts out across the ground around it; shadows from rocks and bushes dance about with the movement of the illumination."
"It's definitely a fire. A large one, probably a bonfire."
"The blackness around the fire is unnatural, though, just like what I saw through the windows in the mansion."
"It's inky and thick, and has the oppressive air of almost being alive."
"No other light comes from what I presume to be the sky, that fire being the only signal that anything exists outside the cabin."
ra "\"A fire...\""
"Raven says redundantly."
j "\"The drumming, it's coming from it.\""
"Carl reaches out, but his hand looks to immediately press against something."
"I reach out too, and feel a solid flat surface where a pane of glass might be set up, but it's clear there's nothing visible there."
"Observe. Accept. Move on."
j "\"Hey, look.\""
"I look up in time to see something dark flash across the fire."
"It disappears into the darkness to the right of the flame, though."
ra "\"What was that?\""
c "\"Maybe it was a—a tumbleweed, or something?\""
j "\"No. It was jumping, whatever it was.\""
"I feel a prickling along my neck and now I'm not really into the idea of just staring out into the darkness."
"But then it happens again, and I see what Jenna's saying."
"The dark shape starts at the left side of the fire before passing in front of it."
"I get a brief impression of a tail and ears, legs and arms pumping as if jogging in place."
"It moves past the flames, then disappears into the darkness again."
stop music fadeout 15.0
m "\"Something's out there...\""
"We continue to watch, but the drumbeat dies down and, after about a minute, it's clear nothing's moving around out there anymore."
ra "\"What was that?\""
c "\"Well, uh...\""
"Carl glances at Jenna."
c "\"The drumbeat sounds kind of native...don't you think?\""
"He's clearly waiting for Jenna to confirm."
j "\"Maybe.\""
"There's an awkward silence before Carl coughs."
play music "neutral.ogg" fadein 3.0
c "\"Well, let's think. We weren't able to get out of the mansion until we found that letter, right?\""
"He looks at me."
m "\"Yeah.\""
"I respond automatically."
c "\"Well, if that's the case then maybe we have to find something in here, right?\""
ra "\"I guess that would make sense...but what are we supposed to find, another letter?\""
m "\"Yeah, didn't—didn't someone tell you about finding something, that it would open the door?\""
c "\"Yeah, and I think it makes sense that whoever set this up would do it in the same way, right?\""
"I sigh and stop staring at the window, my back sore from the twisting motion."
"I sit straight up on the bench and look back into the cabin."
m "\"Well, if we're supposed to find another letter there's a bunch of places to hide it.\""
show Jenna Neutralhips behind nightoverlay at center with dissolve
j "\"Maybe we should try the door first?\""
"Jenna walks over to the door and looks it up and down before reaching out to slide back a rusty bolt."
"To my surprise, it moves with only a little resistance."
show Raven Depressed at right behind nightoverlay with dissolve
ra "\"A—are we sure we wanna go out there? I mean, we don't know who that is running around.\""
"Jenna hesitates, then heaves back on the door...but it doesn't budge, not even an inch."
"Jenna sighs."
"Raven bounds up next to Jenna before enthusiastically yanking back on the handle as well."
"Again, the door holds fast."
c "\"Of course.\""
"Jenna stares at the door a moment before turning to us."
show Jenna Neutralhips at left behind nightoverlay with moveinleft
j "\"Let's take a look around upstairs. If we're supposed to find something then we should start from top to bottom.\""
show Raven at right behind nightoverlay with dissolve
ra "\"Agreed!\""
show Carlalt Neutral at center behind nightoverlay with dissolve
"Carl bends down to pick me up, but I rest a paw on his shoulder."
m "\"Wait, I don't want you to have to drag me everywhere, let alone up and down the stairs.\""
"He stops mid-stoop, his face level with mine as he looks at me."
c "\"You sure? I don't really wanna leave you alone down here.\""
show Jenna Annoyed with dis
"As I look back at him I can't help but note the differences that I'd noticed earlier."
"His face has harder lines, his fur duller, eyes somehow deeper...wiser?"
c "\"You alright?\""
"I break out of my trance and blink."
m "\"Y—yeah...yeah, I'll just stay down here and look around where I can.\""
hide Jenna
hide Raven
with dissolve
"Jenna and Raven are already making their way up the stairs, Raven going on about how his family used to have their own log cabin."
show Carlalt Rejected with dis
c "\"Alright, but shout if, uh, if you need anything.\""
"I smile. At least I feel like some parts of Carl are still familiar."
hide Carlalt with dissolve
"After the ram heads up the stairs, I lean back on my little bench, letting my head tilt back as I close my eyes."
"Even in this new environment everything is still feeling surreal."
"I've come to welcome the feeling, though."
"It's a nice little barrier to everything that's happening right now."
"In some ways I can still pretend that this is a dream."
"Hell, even now I'm thinking it's a dream; that I'm somehow stuck in one of my paralyses."
"Maybe I'm in a hospital right now and they're trying to figure out how to pull me out of it..."
stop music fadeout 5.0
"That thought has me feeling like I'm being watched and the fur prickles around my neck."
"I guess it would be kind of awkward if all of those doctors are watching me right now...maybe Carl and Jenna are there too, and Leo, and Flynn, and TJ..."
"The feeling gets stronger, so I turn back around to look out the window."
"It's still silent, and the lonely little flame in the distance continues to flicker around the rocks and sage brush."
"It makes me wonder how endless this world is."
"If we're in some type of ghost dimension being manipulated by what are basically ghost gods, then will this whole ordeal be never-ending?"
"The thought twists my stomach so I stop thinking about it."
"I turn back around and force my eyes to start scanning the kitchen from top to bottom, looking for something, anything that might stand out."
"I assume I'm looking for a letter..."
"...but again, if the rules are limitless in this world, then there's no telling what it might be that we're supposed to find next."
"I think about vocally asking James, or whoever the hell it is, for some help."
"Maybe some kind of hint at least, but there's no way I'm gonna do that without the others with me."
"I'm thinking about pushing off the bench to start limping around the kitchen when a small scratching sound catches my attention."
play music "bent.ogg" fadein 20.0
"I hold still, then lean back, tilting my ear towards the sound."
"It's muffled, and a bit distant, but it's coming from directly to my left."
"Is it happening on the outside of the cabin?"
"My fur prickles and I think about calling Carl."
"I can hear the three of them stomping around, talking to each other in muffled voices from upstairs."
"I turn around again, this time a little more tentatively."
"The dancing bonfire continues to glow quietly, no other movement aside from the shadows."
"This time a rustling sound comes from that same spot and I instinctively turn my eyes in its direction."
m "\"Carl?\""
"I raise my voice only a little bit, but their conversation carries on upstairs as if I hadn't said anything."
"I look up at the ceiling, then back out the window."
"The rustling sound continues, this time in earnest, as if something's twisting around in the brush."
"It's coming from just out of view of the window, right at the base of the house."
"I hold my breath and lean forward, stretching my neck up to get a better angle and peer down into the darkness."
"It's really too dark to see much, or at least that's what I was thinking."
"Almost as if it has it's own glow, a bright, white face stares back at me from the blackness."
"My mind blanks and my body seizes up."
"And just like that I'm in a paralysis, forced to stare down at the white face, the black eyes..."
"It's as if the thing is holding me with it's gaze, but as it does its features become more definable."
"I see tall ears, a long, pointy muzzle, a band of some type across the thing's forehead..."
"???" "\"Stop. It.\""
"Something says it very deliberately through their teeth right in my ear."
"At the same time the face flickers and fuzzes, like a TV picture with bad reception."
"The head twitches and shifts, then the muzzle opens and—"
play sound "cackleloud.ogg"
"The cackle that comes forth is all at once terrifying and familiar and at that moment I'm released."
stop music
"My vocal chords start working at the same time and I let out a scream as I fall backwards."
play sound "thud5.ogg"
with vpunch
"I land on the wooden floor with a loud thud that shakes the pots and pans on the shelves."
"The room spins and I feel like I'm coming right out of a dream, like I'd been sleeping for ages."
show Jenna Annoyed at right behind nightoverlay
show Raven Depressed at left behind nightoverlay
show Carlalt Surprised at center behind nightoverlay
with dissolve
"The next thing I know is that I'm surrounded by the three faces of my friends, all looking down at me."
"Carl grabs me under the arms and pulls me into a sitting position, his face worried, but there's something else, too...anger?"
c "\"What happened!?\""
"I'm startled by his abruptness and I stammer through an answer."
m "\"I—I, it was a face...out the window.\""
c "\"What did it say!?\""
ra "\"Carl...what are you doing?\""
"Raven reproaches the ram gently, his ears falling."
"Carl glances at the husky, then at Jenna who's been silent so far, then back at me, slowly letting go."
show Carlalt Neutral with dis
c "\"S—sorry, I was just worried about you. What did you see? Did it say anything?\""
"It takes me a moment to find my voice."
m "\"Uh, no, no it didn't say anything, just laughed.\""
c "\"What did it look like?\""
m "\"A—a fox, maybe? Had a band over his head.\""
"Carl's eyes narrow."
show Raven Confused with dis
ra "\"Hey, I found something!\""
"We all look up at Raven as he holds up a white piece of paper."
c "\"What is that?\""
"Carl stands up, staring hard at the paper in Raven's hand."
ra "\"I dunno, looks like a photocopy of a newspaper...let's see.\""
"Raven turns towards the candle sitting on the desk."
"Jenna stands behind him."
j "\"Meseta boy missing after...\""
play sound "catchfire.ogg"
show Jenna Surprised 
show Raven Depressed 
with dis
ra "\"Whoa!\""
"Raven flinches back as the paper catches fire, illuminating the entire cabin room."
"Our shadows dance across the log walls."
"The paper, which Raven had dropped, flutters to the floor, a tongue of angry flame eating it up completely before it hits the floor."
show Jenna Annoyed with dis
"We all stare at the smoldering flake of ash on the ground."
play music "quiet.ogg" fadein 3.0
show Carlalt Annoyed with dis
c "\"Raven! Are you kidding me!?\""
ra "\"Wha-I wasn't even that close to the candle!\""
c "\"That might have been what we needed.\""
ra "\"But I—\""
"Raven stares at his hands, looking forlornly between them and the candle which seems to flicker innocently on the table."
"I rest my face in my hands."
m "\"Well, what do we do n—\""
j "\"He wasn't near the candle.\""
show Carlalt Neutral with dis
"I pull my head out of my hands, not because of what Jenna said, but because of the way she said it."
show Raven Confused with dis
ra "\"Huh?\""
j "\"I've got a side angle here. You were at least two feet away.\""
"There's a brief silence."
c "\"Jenna, what are you talking about?\""
j "\"I don't know, Carl. What AM I talking about?\""
"Jenna turns to the ram, eyes narrowed, teeth just slightly bared."
show Carlalt Rejected behind nightoverlay with dis
"I look at Carl."
"He's frowning, a concerned look on his face."
c "\"Jenna, I don't know what you're talking about.\""
j "\"I'm saying there's no way that candle burned that paper.\""
"Carl's concerned expression deepens, but there's also a hint of condescension there."
c "\"What else could have done it, Jenna?\""
"This time the silence is heavy."
"I'm baffled by the interactions they've been having so far and, judging by the look on Raven's face, so is he."
ra "\"Hey guys, I'm sorry I burned it...but maybe we can figure something out from the title, uh, Meseta boy missing?\""
"I look at Jenna."
m "\"Oh yeah, Meseta, isn't that—that your tribe, or...\""
j "\"Yep.\""
"I feel my face flush as I wonder if I'm being insensitive, like I think she knows everyone from the tribe."
show Carlalt Neutral with dis
c "\"But what does that mean? A lot of people go missing out here.\""
ra "\"Well, it would have something to do with James, right?\""
c "\"How do we know that?\""
"I look at Carl."
m "\"Are you okay, man? You've been acting really weird ever since we got here.\""
c "\"I think we're all acting a little different after getting here, don't you think?\""
"Carl glances at Jenna."
ra "\"Are we fighting again?\""
"Staring at the ash on the ground, something I should have realized earlier suddenly hits me."
m "\"Wait a minute...that newspaper; it kind of looked like something that came out of the crawlspace tubs.\""
j "\"What do you mean?\""
m "\"I was looking through some artifacts that Carl's family saved from way back when, for that project I was doing.\""
"It seems like years ago at this point."
"I snap my fingers."
m "\"And some of the stuff was missing from it, like pages ripped out from Carl's mom's notes that had photocopies of old newspapers.\""
ra "\"So...so was that just a clipping from the notes?\""
m "\"Maybe? I dunno, but John was native, so maybe it has to do with him?\""
"I think back to the small fox I saw through the window, the band across his forehead."
"Was that John?"
j "\"So the ghost just ripped out the pages to show you in this nightmare world? Why didn't he just point them out to you in the real world?\""
"I don't really have an answer for that."
j "\"Then we wouldn't have to be going through this shit right now.\""
ra "\"Ghost rules?\""
"Raven shrugs."
j "\"And what if that was our key out of here?\""
ra "\"Well, they can't just leave us here, right?\""
m "\"We don't know anything about where we are, or what these things are capable of...\""
j "\"So what now, just sit around and wait for something else to happen?\""
show Carlalt Rejected behind nightoverlay with dis
"Carl suddenly sighs."
c "\"Well, I'm gonna look around some more. You guys do whatever you want.\""
"Again I'm taken aback by Carl's demeanor. I've never seen him act like this before."
"It's like he's a different person."
"Without another word, he turns on his hoof and walks away."
scene bg cabin2 
show nightoverlay
with slow_dissolve
"Over the next several hours we search the cabin from top to bottom."
"I hobble around the ground floor, careful not to look out the window, even when the drumming starts up again at a few points."
"I check all of the shelves, under the chairs and tables, in the stove, in the pantry, between the cracks in the floor and walls."
"We don't find anything."
"At some point I almost topple over from dozing off and that's when we call off the search."
"There's some discussion as to where we should sleep, if we should do it in shifts."
"Jenna suggests she stay up downstairs while the rest of us sleep, just in case something else happens."
"Carl suggests that I sleep in the bed upstairs because of my leg, and I have to agree with him."
"Raven stays downstairs with Jenna, making himself comfortable in one of the chairs."
"As Carl hobbles up the stairs with me on his back, Jenna watches us the whole way."
scene bg cabin1 
show nightoverlay 
with dissolve
"I sit on the bed, watching as Carl moves about the room, looking behind shelves and under the bed."
m "\"Carl, I hate to ask again, but are you okay?\""
show Carlalt Neutral at center behind nightoverlay with dissolve
c "\"Hmm?\""
"He looks back at me."
c "\"Yeah, I'm fine. I just want to make sure everything is safe for you.\""
m "\"Thanks...it's just—it's just that you seem...different, I guess.\""
"Carl looks at the ceiling, seemingly thinking."
"It's difficult to make him out in the darkness."
"Just like when he had a sheet over his head, I get the weird feeling that who I'm looking at might not be Carl."
c "\"I think it's just that this has made me grow up. I realize now how useless I've been.\""
c "\"This is sort of an opportunity for me to actually do something, help people. You know?\""
m "\"Yeah.\""
"It sounds nice, but I can't get rid of that nagging feeling that something is off."
"It's in the way he talks, the way he moves, right down to his facial expressions."
"I swing my legs gingerly onto the bed and lay back."
"Carl comes over to sit on the other side."
m "\"Gonna sleep here, too?\""
c "\"Yeah. You need me to get around, so I'm gonna be by your side as much as possible."
m "\"Alright...thanks.\""
"As we lay awkwardly on our backs for a moment, Carl suddenly turns on his side and pulls me into his chest."
"I'm surprised, and turn instinctively so that he's spooning me."
"I guess it makes sense after our semi-confession back in the mansion."
"He nuzzles my neck, but again, the action is weirdly unnatural."
stop music fadeout 5.0
"Even with his big, warm body next to mine, it takes me a long time to fall asleep."
scene bg black with slow_dissolve
"I open my eyes and blearily I can make out the dark cabin room."
scene bg cabin1 
show nightoverlay
with dissolve
"My heart sinks again at realizing where I'm at, but it's more subdued this time."
"Guess I'm getting used to my new life."
"My mouth is dry, very dry, and I feel like I need to find water or I'm not going back to sleep."
"I sit up."
"Carl's moved back to his side of the bed at this point, lying out on his back, snoring."
"Quietly, I get out of the bed, wincing at how creaky the floorboards are."
"I make my way down the stairs, eyes adjusted to the point where I can barely make out the ledges."
scene bg cabin2
show nightoverlay
with dissolve
"When I reach the ground level I see that Raven is splayed out on the carpet, snoring as well."
"I shake my head before moving to the kitchen."
scene bg cabin3 
show nightoverlay
with dissolve
"Jenna isn't there and I wonder where she might be at."
"Was she in that other room upstairs?"
"Maybe I just missed her when I was distracted by Raven."
"Looking around, I see a small cup sitting on the table."
"I'm almost positive it hasn't been there before, but maybe Raven, or Jenna had set it there."
"Walking over to it I'm relieved to see that it's filled with what looks like water."
"I pick it up and sniff at it, not really getting a hint of anything."
"Tentatively, I take a sip..."
"...and immediately spit it out."
"It's salty, putrid...it tastes like—"
play sound "thud.ogg"
"I jump and some of the liquid splashes to the floor."
"Gingerly, I set down the cup, looking into the opposite room."
scene bg cabin2 
show nightoverlay
with dissolve
"Everything is still in the other room. I can't even hear Raven snoring anymore."
play sound "thud2.ogg"
"This time I see the wardrobe move, the door specifically."
"I stare, wide-eyed."
"Everything falls still again, but I don't dare move."
m "\"Jenna?\""
"I whisper loudly."
"It wouldn't make any sense why she'd be in there, but who else would it be?\""
"...Ghosts, of course."
"I'm about to take a step forward, toward the stairs maybe, or to at least wake Raven up, but that's when the small door cracks open."
play sound "doorsqueak1.ogg"
"I freeze, all of the fur on my body standing up."
m "\"J—James...\""
"Words die on my tongue as something long and black slides out from behind the door."
"It dips down towards the ground and only then does it vaguely take the shape of a foot."
"Another long, black tendril follows, slightly ahead of the first one."
"When it touches the ground it takes the shape of a hand, resting flat on the wooden floor."
"I choke and start to try and back away, but then—"
play sound "smash.ogg"
play loop "horrorbeat.ogg"
"The door explodes open and I'm just barely able to make out a galloping black shape before it engulfs me."
"I collapse back onto the ground, twisting, trying to scream, but the thing is completely covering and smothering me."
"I choke, and gag, feeling like I'm being suffocated, my arms pinned to my sides, my legs rigid."
"As I try to yank away from the thing it feels like something is freed from my mouth and I'm able to scream;"
m "\"Help! Get it off me! Help!!!\""
stop loop fadeout 5.0
c "\"Chase!\""
"The surface underneath me becomes soft, the thing on top of me warm."
scene bg cabin1 
show nightoverlay
with dissolve
show Carlalt Neutral behind nightoverlay at center with dissolve
"Through bleary eyes, I look up at Carl, just able to make out the curve of his horns."
m "\"Carl?\""
"I hear movement at the doorway and I glance in that direction to find Jenna standing there, hackles raised, teeth bared."
play music "anger.ogg"
m "\"Jenna!?\""
"Before I know what exactly is going on, Jenna sprints across the room and jumps on the bed."
"Carl doesn't even have time to turn around before she snatches him up by the horns and yanks his head back violently."
show Carlalt Surprised with dis
$ renpy.pause(0.1, hard=False)
hide Carlalt with vpunch
play sound "thud.ogg"
"The ram lets out a choking sound as he's dragged back and thrown to the floor."
"Jenna jumps off the bed after him."
"From the sounds of it she lands on him."
"What follows is a series of thuds and smacks."
"Weakly, I pull myself to the foot of the bed, still completely disorientated."
j "\"I knew it you motherfucking piece of shit!\""
"What I see is Jenna sitting on Carl's back, swinging her fists into his head while the ram tries to cover up."
j "\"You haven't changed at all!\""
m "\"Jenna, stop!\""
"I roll of the bed, confused as to why I'm so weak."
"Pain shoots up my leg again, but this time I barely notice it."
"There's something around Jenna, something big and black, like a shadow, making her look much bigger than she actually is."
"Her fists swing and hit Carl with a force I didn't think she was capable of."
"Then she grabs Carl by the horns again and yanks back before slamming his face back into the floor."
m "\"JENNA!\""
"I lunge forward, trying to put myself between the two of them."
"Underneath me Carl has gone limp."
"Just like Jenna, there's something black and shadowy around him as well, but it's fading, moving away..."
"Jenna's still trying to get at Carl, reaching around me and snarling in my ear; a sound that makes my fur stand on end."
"Then she's gone."
"I look to my left and see Jenna being drawn back by Raven, his eyes wide with shock."
ra "\"What are you doing!?\""
"Jenna struggles in the husky's grasp."
j "\"I saw him! He was trying to fuck the otter!\""
"The otter?"
m "\"Jenna, stop! He was helping me!\""
"Raven continues to try and pull Jenna towards the door, but she continues to struggle."
m "\"I was having a nightmare!\""
stop music fadeout 20.0
"Jenna's struggling losing some of its vigor, but she continues to snarl in Carl's direction."
m "\"Raven, please get her out of here.\""
"The shadow around Jenna seems to shrink and her face shows some doubt as she stares at the crumpled form of Carl."
"After a moment, she seems to let the husky lead her from the room and I hear soothing tones from Raven as he leads her down the stairs."
"I turn back to Carl who has his arms around his head, face still buried in the ground."
"After a while, I see his shoulders heaving with sobs."
"Gently, I pull one of his arms back and he looks up at me."
"This time I recognize his face."
scene bg black with slow_dissolve
scene bg cabin1 
show nightoverlay
with dissolve
play music "neutral.ogg" fadein 5.0
"I sit next to Carl on the bed, mopping up his face with his bloodied button up shirt."
"He sits there silently, looking at his hands while I work."
m "\"At least nothing's broken.\""
show Carlalt2 Rejected behind nightoverlay with dissolve
c "\"Dude...what happened?\""
"I'm not sure if he's talking about what happened with Jenna, or just everything."
m "\"I've been asking that same question since we got here."
show Carlalt2 Depressed behind nightoverlay with dis
"He looks at his hands again."
c "\"I felt...I felt different.\""
"I sit back and look him over, satisfied with having cleaned up most of his face."
m "\"You were acting different, too.\""
c "\"Like, I felt like I knew everything. I knew what I was doing.\""
m "\"You were acting really confident.\""
"I agree and set his bloody shirt off to the side."
"When I look back at him he seems so sad and beaten down that I have to hug him."
c "\"Dude, you're gonna make me start crying again...\""
"His voice cracks, but he hugs back anyway."
m "\"I'm just glad you're back. I felt like I was talking to a stranger.\""
"Carl leans against me and sighs."
c "\"I don't know if I'm glad, though. It's like I just came down from a huge high.\""
"I rub his shoulder for a while before I venture forward with my guess."
m "\"Was it James?\""
c "\"I—I don't know. Maybe.\""
"Carl looks at his hands again, like he's questioning if they're even his."
c "\"I just felt like I knew what I wanted, and when things didn't go the way I thought they would I'd get really pissed.\""
"He's silent for a while, I imagine contemplating what he'd just gone through."
m "\"Jenna isn't really acting like herself either.\""
show Carlalt2 Rejected behind nightoverlay with dis
"Carl looks up at that."
c "\"Yeah, I felt like whatever was in me...whatever it is really hates what Jenna is doing, for some reason.\""
"Carl looks around at the room, scanning it with his dark, green eyes."
c "\"I feel like all of this is some kind of mental fight between James and whatever else is fighting against him.\""
show Carlalt2 Depressed behind nightoverlay with dis
"He looks back down at his hands."
c "\"That's why we have to do all of this.\""
stop music fadeout 5.0
"He falls back into silence and I don't ask anymore questions, wanting to let him rest a bit."
"There is one nagging thought that comes to my mind, though;"
m "\"This is kinda stupid, but what happened back in the mansion, you know, that thing between us...\""
show Carlalt2 Neutral behind nightoverlay with dis
"He looks up at me and I feel my face flush, looking away."
m "\"I guess I'm wondering if any of that was real. I mean, if it was really you feeling that way.\""
play music "intimate.ogg" fadein 10.0
"Carl doesn't say anything so I'm forced to look up at him. When I do he has a sad sort of smile on his face."
show Carlalt2 Sheepish behind nightoverlay with dis
c "\"Dude, I think that was the only part of me that was real.\""
"Despite where we are, despite everything that's happening, that somehow makes me incredibly happy."
"Happy enough to lean forward and kiss him."
"He kisses back and while it's barely more than a peck, it has my entire body feeling warm."
"He puts his own arm around me after I pull back and I rest my head on his shoulder."
show Carlalt2 Rejected behind nightoverlay with dis
c "\"I feel like it's gonna try to come back, though.\""
"I look at him."
m "\"What, James?\""
c "\"Whatever it is. I can already feel it, like it's on the edge of my mind...\""
m "\"Do you think you can fight it?\""
"Carl sighs, then looks at me."
c "\"Should I?\""
m "\"What do you mean?\""
c "\"I mean...it made me feel amazing, like I could do anything. Maybe we need that?\""
"I frown."
m "\"I dunno...\""
c "\"Not only that, but I felt like I knew what to do. It might save us.\""
"He stares back into my eyes."
c "\"I know it's not really me, but it'll probably only be for the time that we're here.\""
"I look away, thinking."
c "\"Then I'll be back to my old self.\""
"He squeezes my shoulder."
c "\"But it's important to me what you think. We're in this together.\""

menu:
    "Fight it.":
        "No, whether or not it made Carl feel good I can't shake the bad feeling it gives me."
        "I rest a hand on his."
        m "\"No, after everything that's happened I don't trust whatever it is.\""
        "Carl watches me closely."
        m "\"Seriously, we need to be more careful. Besides...\""
        "I lean my head against his shoulder again."
        m "\"We ARE in this together. We don't need that thing meddling with us to get through it.\""
        "I feel some of the tension go out of Carl's muscles and we wrap each other more tightly into our respective embraces."
        "We sit there for a while, Carl absorbing what I'd just said."
        "It's clear that whatever is influencing Carl and probably Jenna is powerful and we had to be careful."
        "Whatever he decides, I just pray it's the right decision."
        scene bg black 
        with slow_dissolve
        stop music fadeout 5.0
        jump carla
    "Let it help us.":
        "While I don't exactly like the idea of whatever it is changing Carl influencing him, it might be our only choice."
        m "\"I think—I think you should probably let it...\""
        c "\"Yeah?\""
        "Carl looks at me and I can tell he's a little surprised."
        m "\"Maybe. It's basically trying to help us, right? And if it's James he knows exactly what we need to do.\""
        c "\"Yeah...\""
        "Carl sounds a little reluctant, but I can tell he's starting to agree with me."
        m "\"And it'll only be for the time that we're here. He just wants to show us his story, then we can get out.\""
        "I don't mention that a more confident Carl will make everything easier as well."
        "I just had to make sure that he and Jenna were carefully kept separate."
        m "\"Either way, we ARE in this together. I'll make sure things don't get out of hand between you and...it.\""
        "We sit there for a while, Carl absorbing what I'd just said."
        "It's clear that whatever is influencing Carl and probably Jenna is powerful and we had to be careful."
        "Whatever he decides, I just pray it's the right decision."
        scene bg black 
        with slow_dissolve
        stop music fadeout 5.0
        jump carlb