label sitwithcarl:
stop music fadeout 3.0
play loop "reststop.ogg" fadein 3.0
"I'm tired, and I feel awful. I just don't have it in me to chase everyone down right now."
"Flynn's back off to Echo, and it looks like Leo went after TJ, but I can't imagine the lynx wants all of us crowding around him right now."
"I sigh, rubbing my face before I sit down in the lawn chair next to Carl."
show Carl Rejected at center with dissolve
"He looks over at me, slowly lowering what's definitely a joint from his mouth."
m "\"What? I don't mind.\""
"I make a \"go on\" gesture with my paw."
"Carl shakes his head though, pushing the disheveled tube back into his front pocket."
c "\"Nah, I always kinda feel like a dick when the other guy isn't into it.\""
m "\"Want me to leave?\""
"He shakes his head with a quick flick of his horns."
c "\"No man. I just do it when there's nothing else to do.\""
m "\"Ah.\""
"There's a moment of silence and I feel a little pressure to break it since I'm the one who interrupted his bake session."
m "\"I actually tried it a few years ago.\""
show Carl Neutral with dis
"Carl looks surprised."
c "\"Oh really? How was it?\""
"I shrug."
m "\"Pretty bad. Was in a muffin, I think.\""
show Carl Annoyed with dis
"Carl makes a face at that."
c "\"Edibles.\""
m "\"Yeah, well, I ended up eating one, didn't feel anything for a while. Next thing I know I'm face down on the floor and everyone's freaking out.\""
c "\"Shit, that sucks.\""
m "\"It was kinda funny, but I don't think I'll ever try it again.\""
"Carl pulls the joint back out of his pocket and holds it up."
c "\"That's why you should use one of these. It's easier on the brain.\""
m "\"Yeah, well, I guess I just don't like the idea of putting smoke in my lungs.\""
show Carl Rejected with dis
"Carl puts the joint back in his pocket."
c "\"I get that.\""
"Again, there's a few seconds of silence and I try to think of something to say, but Carl beats me to it."
play music "neutral.ogg"
show Carl Neutral with dis
c "\"Crazy shit, huh?\""
"I assume he's talking about what just happened."
m "\"Yeah, crazy.\""
c "\"But you know how he is. He's regretting everything right now.\""
m "\"Well, I guess I'd rather he just wouldn't say it in the first place.\""
m "\"What he said to TJ, man...He picks on him a lot, but that was crossing the line.\""
"Carl scratches behind one of his horns, then rubs his nose."
c "\"Well yeah, I guess I never understood that, either. Making fun of TJ is like...making fun of a cloud.\""
c "\"But Flynn doesn't mean it, usually. He likes TJ.\""
"I've noticed during the trip that Carl's been pretty defensive of Flynn, even though he's the butt of most of the lizard's jokes."
"I'd seen Flynn trip Carl up and put him in several headlocks since I got here."
"You'd think getting older would change that, but I swear they roughhouse even more than they did before."
m "\"So you and him still seem pretty close. You guys hang out a lot?\""
c "\"Yeah, a bit, mostly because there isn't much else to do. He's got a friend in Payton that he hangs out with sometimes, too.\""
m "\"So what do you guys do?\""
"I know Flynn isn't into video games at all, and Carl probably doesn't care to go clubbing every other night."
"He shrugs."
c "\"Sometimes we go fishing, maybe just drive around Payton.\""
c "\"Mostly I'm just hangin' out at home, though.\""
m "\"Playing video games?\""
c "\"Playing video games, watching movies, cybering with a chatbot—the usual.\""
"I grin."
m "\"That's sad, I would have cybered with you if I'd known you didn't have anyone.\""
show Carl with dis
c "\"I dunno man, that thing compiles all the fetishes of the people it's talked to. It's gotten my sexuality all kinds of fucked up.\""
m "\"Oh yeah?\""
c "\"Yeah, seems like no matter what I say to her she's tied up in some warehouse, blindfolded with a few missing limbs.\""
m "\"You underestimate my abilities.\""
c "\"Oh, and a gender swap that comes out of nowhere halfway through.\""
m "\"Well, while you're not sexing up a robot, you doing anything else?\""
"He chuckles."
c "\"I can't exactly get around myself anymore.\""
m "\"So I guess your parents decided against getting you a new car?\""
c "\"Yeah...Oh! Look at this.\""
"He leans over and pulls out his phone. I can't help but notice it's a top model brand, probably around $700."
"But he's not showing me the phone. Instead he presses at the screen a few times and swipes through some pictures."
"I swear I see an image of Flynn with his pants down mooning the camera."
"Carl swipes over it pretty quick, though, and now I'm looking at the image of a brand-new sedan—"
"—except the front is neatly folded up around the pole of a stop sign."
"I recognize the sign; I'd actually seen it right outside the convenience store, still bent at a ridiculous angle."
"Guess the town didn't care enough to get it fixed."
"The pole itself is almost embedded into the middle of the hood."
m "\"Holy shit.\""
"Carl chuckles and pinches the screen, zooming in."
c "\"Yeah. Dropped my phone and when I came back up this freakin' pole was right in front of me.\""
m "\"Really, Carl? Why were you on your phone?\""
c "\"I dunno. When I get to the town I don't really think anyone's gonna be on the road.\""
"I sigh, then notice a big, round, spot on the right side of the windshield, spiderwebbed and smashed white."
m "\"Whoah, is that—\""
c "\"Yup!\""
"Carl knocks on his head for effect, the hollow sound that it emits seeming rather appropriate."
m "\"You rely on that too much...and you really need to start wearing your seatbelt.\""
"He shrugs and puts the phone back in his pocket before leaning back in the chair and closing his eyes."
c "\"What's the point?\""
m "\"Uh, to not die?\""
c "\"Happens to everyone sooner or later. Why not get out early if you can?\""
"He keeps his voice light under the heavy statement."
"I have no idea what to say to that, so I don't, but he breaks the silence again soon enough."
c "\"So how's PU, you see Chelsea at all?\""
"Sometimes I forget Carl went to Pueblo with me. It was only one semester, but we had a lot of fun."
m "\"It's alright, haven't seen Chelsea at all though.\""
c "\"It is a big school. Anyway, what's that project thing you're doing?\""
m "\"Just a news packet about Echo, really. Kinda about how it's falling apart.\""
c "\"Huh.\""
"I've told him this already, but Carl never remembers much."
m "\"Might center it around the whole 'body in the mine' thing that happened way back.\""
"Carl opens his eyes and looks at me."
c "\"So do you need like, history stuff, like old books and records and stuff?\""
m "\"Uh, yeah. If it relates.\""
"Carl sits up straighter and grins."
c "\"Well, why didn't you say so! We've got a ton of stuff in the crawl space from way back when.\""
m "\"Yeah? What kind of stuff?\""
"Carl sets a hoof against one of the rocks circling the fire pit and starts rocking his chair back."
c "\"Well, whatever my family kept over the years. That one guy, um...\""
"Carl snaps his fingers a few times."
c "\"You know, the guy...founded this place, uh...\""
m "\"James?\""
c "\"Yeah, sure. He's like, my great-great-great grandfather, or something. I think we still have some of that stuff from back in the day.\""
c "\"My parents were thinking about setting up an Echo museum thing, but they never did.\""
"This might actually be useful to me."
"All I had planned was to maybe look over some old newspapers or town records and be done with it."
"Actually seeing some old stuff up close could be pretty cool."
m "\"That might be a good idea, actually.\""
"Carl grins."
c "\"Awesome. I always kinda wanted to look through that stuff, but the crawl space is damn creepy. You free tonight?\""
"For the first time Carl actually looks really excited."
c "\"Oh wait, nevermind. Flynn's taking me to a dentist appointment early in the morning. How about around 11 tomorrow?\""
"I smile."
m "\"Sounds like a plan.\""
c "\"Sweet! WHOAH!\""
show Carl Surprised with dis
$ renpy.pause(0.1, hard=False)
hide Carl with dissolve
play sound "fall.ogg"
with vpunch
"Carl gives an excited kick off the rock and, as the chair's tipping back, the back legs practically snap under his weight."
"He's sent slamming down on his rear, the chair a crumpled mess under his ass."
show Carl Sheepish with dissolve
"I laugh and of course I feel bad, but Carl just gets up with a sheepish smile, looking down at the broken pile."
stop music fadeout 3.0
stop loop fadeout 3.0
c "\"Welp, Leo's gonna be pissed.\""

scene bg creepylake
with opening_fade
play music "meeting1.mp3" fadein 10.0

"I'm driving down the road alongside the lake."
"Carl's sitting next to me."
"He's in the chair that he broke."
"I keep telling him to wear his seatbelt, but he won't."
"I turn down a road I don't remember."
"It goes straight down towards the lake."
"For some reason I can't stop."
"I brace myself for the impact, but I hardly feel anything."
"We just glide into the lake."
"I start trying to take off the seatbelt, but it's stuck."
"I look over at Carl and he smiles before opening his door."
"Water rushes in, and he starts to step out."
"Soon the water is over my head, and it doesn't matter that I'm an otter."

jump carltuesday