label jennatuesday:

stop music fadeout 3.0
scene bg tuesday
with transition_fade
$ renpy.pause(3.0, hard=True)

scene bg trail1
with slow_dissolve
play background "reststop.ogg" fadein 3.0
show Jenna Smilinghips at center with dissolve
window show
j "\"So where are we headed, TJ?\""
"Jenna sounds like she's in a much better mood than yesterday. We all are, really."
show TJ at right with dissolve
t "\"The canyon! Echo Canyon, more specifically. You ever been?\""
"He looks at both of us with a grin."
j "\"Nope.\""
m "\"Um, no, me neither.\""
"His ears fall a little."
t "\"Wha—You know the town is named after it, right? How have you not been there before?\""
"I shrug and Jenna laughs."
j "\"Because you have to walk through three miles of snake-infested desert to get there.\""
"That makes me bristle, because there definitely are snakes here. I can't help but scan the brush."
t "\"You really shouldn't worry about that. They're more afraid of you than you are of them AND they do have a rattle, so just listen for it.\""
"Jenna grins and looks straight at me."
j "\"Yeah, you're right. The most dangerous animal you'll find on these paths is the blonde.\""
"An involuntary shiver works itself up my spine."
m "\"Jenna!\""
"TJ frowns."
t "\"That's even less likely, Jenna...\""
m "\"Great, now that you said it I'm gonna be all uptight for the rest of the hike...\""
j "\"You're welcome! Alright, let's get going. We want to make it to the top by noon.\""
stop background fadeout 3.0

scene bg trail2
with fade

"A few hours in and TJ's quite a bit ahead of us."
"I feel a little bit bad about it, but I think he likes it that way, probably wants to think after yesterday."
"Jenna and I walk side by side and she's making sure that I drink water the entire time."
show Jenna at center with dissolve
j "\"You should be done with that by now.\""
"She gestures at my water bottle which is still half full."
m "\"Ugh, come on. I've had like, three already.\""
"I take a sip, then almost snort water as Jenna tips up the bottom of the bottle."
j "\"Hey, I made TJ a promise here. You're an otter, you need it.\""
play sound "pour.mp3"
m "\"Blagh! Stop!\""
"I cough a few times, water running down my chin and chest. Even though it feels good, I wipe it away with a forearm."
play music "quiet.ogg" fadein 5.0
show Jenna Smiling with dis
"Jenna chuckles before we start walking again."
hide Jenna with dissolve
play background "trailsteps.ogg"
j "\"Actually, you don't really need more water than me or TJ, as he could tell you.\""
j "\"The water thing is actually more of a psychological need as opposed to a physical one.\""
m "\"Oh yeah?\""
"I look over my wet camera bag, which definitely didn't need water."
j "\"Yeah, you know, back when there weren't really any ethics in research they separated an otter pup from water, never allowed to swim.\""
"That makes me pause. Technically, in this day and age, otters don't really need to swim. A trip to the supermarket gets all that done."
"But something about not being allowed to be in water, to feel the cool, isolated space that I so longed to be in..."
m "\"What happened?\""
j "\"Depressed, disengaged, neurotic in general. Then, when they were done, they just set him loose into the world. He killed himself a few years later.\""
m "\"Wow...\""
j "\"Yup. I mean, ethics are in place now, of course, not that the Psychological Association is any better.\""
j "\"You probably heard about their role in the whole advanced interrogations controversy.\""
m "\"Like the waterboarding stuff?\""
j "\"Yeah. But it really makes you realize how powerful the brain is. It's not all physical necessities.\""
m "\"Must have been pretty awful for him that he killed himself. I can't imagine.\""
"Talking about offing oneself, though, it's got me thinking about Jenna's brother."
m "\"So, uh...\""
j "\"You wanting to talk about Adam?\""
m "\"No!\""
"Well, I sort of did, but I don't think that would be appropriate at all."
m "\"I was just wondering...are you gonna go see your family sometime during the trip? We talked about it earlier, but I guess you didn't really give an answer.\""
"Jenna snorts loudly, tossing her head back."
j "\"You're kidding, right?\""
"I feel my cheeks flush, knowing that I might have said something really offensive. I'm not really in tune with how things are with Jenna's family."
"Leo, and sometimes even Flynn, dealt with most of that."
m "\"I mean, aren't you a little bit curious?\""
j "\"Curious is the wrong word.\""
m "\"Oh?\""
j "\"Maybe morbidly curious. Anyway, they haven't bothered contacting me since I left so, as far as I can tell, they're not missing me.\""
t "\"Guys, there's a giant dip over here, so watch your step!\""
"TJ's quite a bit ahead of us now. I don't even see him anymore around all the boulders and brush."
"I pick up the pace and Jenna follows."
m "\"Well...do YOU miss them?\""
"She doesn't say anything for awhile, which tells me she's really thinking about it."
j "\"No.\""
"She says it, finally, surprising me a little with her bluntness."
j "\"At least not my mom and dad. Not even Adam.\""
m "\"Really?\""
stop music fadeout 3.0
play loop "reststop.ogg" fadein 3.0
"Jenna shifts around as she grabs another water bottle out of the backpack and hands it to me."
j "\"Adam.. he had problems. Mom and Dad fucked him up, of course, but he took it out on me. He did some messed up stuff.\""
"I debate whether or not I should ask what exactly that messed up stuff was, but I'm way too scared of what it might be."
j "\"Jeremy, though...I guess I wouldn't mind seeing him again.\""
"I give her an incredulous look."
m "\"See, Jeremy's the one I would have thought you wouldn't have wanted to talk to...\""
j "\"Heh, yeah. Now Clint is the one that fucked up Jeremy. But he really was a good person before then.\"" 
"Jeremy was, for as along as I can remember, a royal dick. A bully to me, TJ, and Carl."
"Along with Clint, he terrorized our childhood."
"That is, until Leo showed up."
"I'll never forget the day Leo rammed Jeremy's head into a tree, and punched Clint so many times in the face his eyes almost swelled shut."
"Of course, Leo never got in trouble because neither of their parents gave a shit."
j "\"Environment is really important to how you develop as a person.\""
"I think for a second."
m "\"Well, you turned out alright.\""
j "\"Environment AND temperament make us who we are. Some people...some people can just take more.\""
"It's clear that her \"temperament\" was a lot stronger than mine, whatever that was. If I had parents like that...I don't know how I would have survived."
"I take another gulp of water and it's then that I realize how badly I need to pee."
stop background fadeout 3.0
"Looking off to the side, I spot a rather large boulder surrounded by sage brush."
m "\"Hey, you go ahead. I gotta take a piss.\""
"Jenna quirks her muzzle and folds her arms."
show Jenna at center with dissolve
j "\"Sure you don't want me to wait up for you?\""
m "\"Uh...\""
j "\"I'm kidding.\""
hide Jenna with dissolve
"She turns and starts walking up the trail."
j "\"Watch out for spiders.\""
m "\"Haha...\""
stop loop fadeout 3.0
"Sometimes Jenna's jokes were so dry that I had a hard time figuring out if she really was joking or not."
scene bg boulder with dissolve
play background "reststop.ogg" fadein 5.0
"I dodge my way around the sage brush and tumbleweeds towards the boulder and start to piss."
"Jenna really is an enigma. She's nice enough, and smart, but she has this edge about her that always has me on guard, for some reason."
"Fur prickles on the back of my neck."
"I'm not sure what it is, but something isn't right. I look left and right in the small chance that someone else is coming up the trail."
"It's weird feeling like this in broad daylight. Normally I don't get so uptight unless it's dark."
"I hear it's the opposite with species that can see better at night."
"{i}Something's watching you from the brush...{/i}"
"A shiver runs right up my spine and I tremble under its influence."
"As if of its own accord my head whips around, immediately focusing in on a clump of sage brush thirty feet away."
"And there, right in the middle, someone's face is staring at me."
"I can only call it a face because there are two eyes, and a mouth, but I've never seen anything like it."
"It's flat, wide, and stretched out; sagging where the chin should be."
"I can't help myself."
"I yelp loudly and stumble to the side as I whip my body around to defend myself, somehow conscious of the fact that my dick is still out."
"Then, it all comes together. I stare for a few seconds longer, then force out a tight, high-pitched laugh."
m "\"Are you fucking kidding me?\""
"It's a rock, a white rock, and the sage brush twigs have fallen over it perfectly to give it features similar to that of a face."
"I sigh and rub my own face with both my paws, feeling my heart hammering in my chest."
"I always did this shit to myself."
"As I lower my paws I notice a wet streak across the left side of my pants. I hadn't finished peeing, yet."
m "\"Fucking son of a bitch.\""
"I hiss and turn back to the boulder, trying to work myself into a peeing mood again."
"Finally, as I start finishing up, the prickling feeling on my neck starts up again."
stop background fadeout 10.0
"I try to ignore it, but it's getting worse and worse."
"I shake my hips around a few times, then zip up and start back around the boulder. It's at that point that I give a quick glance back at the brush."
"The rock isn't there anymore."
"I stare, one paw on the boulder, feeling my fur starting to bristle out all over my body."
m "\"What...?\""
"Maybe it's because I'm at a different angle now..."
"The feeling of being watched is overpowering, though, and it's coming from the other side of the boulder, where I was just at."
"I look up the trail, but I don't see TJ or Jenna at all."
"I can't even hear them. I look back towards the boulder, wondering if I'm losing my mind."
"Gritting my teeth, I turn away and start back up the trail at a brisk walk, knowing that I'm acting just like a little kid."
"Despite that, I feel myself start to panic a little and soon enough I'm running up the trail, and I'm not looking back."

#transition
scene bg trail3 with fade
show TJ at center with dissolve
play music "carefree.ogg"
t "\"We made it!\""
"He says it, even though he's already sitting down on what looks like a rock bench."
"He probably got there a good ten minutes before us."
"I'm sweating all over the place, but Jenna seems fine. It's embarrassing because it's only now that I realize she'd been hanging back because of me."
t "\"Group hug!\""
"TJ stands and holds his paws out."
"I wanna protest because of how gross I must look, but Jenna sort of forces me into it as TJ walks up to us."
t "\"This was a lot of fun guys. Thanks for coming!\""
show Jenna Smilinghips at right with dissolve
j "\"Well, we're glad you had fun, even if we weren't able to keep up.\""
"As we lean back from the hug, I see Jenna's nose wrinkle."
"I press my tail a little closer to my rear."
t "\"Alright, let's eat!\""
hide TJ 
hide Jenna
with dissolve
"We sit down on the rock bench and TJ starts pulling the sandwiches out of the soft cooler."
"He'd been so excited about our trip that he'd gone to the convenience store by himself at five in the morning and made all of our sandwiches."
"It's actually pretty good, too. There's even avocado on it, even if it's the packaged, mushy kind, according to him."
stop music fadeout 5.0
play background "reststop.ogg" fadein 3.0
"We eat in silence for a while, and looking over I can see that Jenna's deep in thought, chewing slowly."
m "\"What's up?\""
"She shrugs, then swallows."
show Jenna at right with dissolve
j "\"Just thinking about how this might be the last time we really get to hang out, is all.\""
show TJ at left with dissolve
t "\"That's kind of a sad thing to say...\""
j "\"Well, think about it. I graduate in a few months and then I'll be off to the other side of the country.\""
j "\"Then you'll graduate, Chase, and I don't think you'll be sticking around here.\""
m "\"Maybe...\""
j "\"And you, TJ. You might just leave the country.\""
"That would make sense. TJ's parents are back in his hometown."
t "\"I think we'll get together again. It's just a matter of planning it right.\""
t "\"It might be a while, but it'll happen and there's always the internet.\""
j "\"I'm just saying; I hope Flynn can get over himself before the end of our trip. I don't think this should be our big send off.\""
m "\"We've still got time.\""
hide Jenna
hide TJ
with dissolve
"I lean back and drape my arms over the back of the bench, closing my eyes."
"I really want to take my shirt off, though. The fabric is almost soaked through and it's clinging in a really gross way to my fur."
"The sun is beating down on me, shining bright red through my eyelids."
"If only there was a pond up here; I'd be able to sink to the bottom, the sun reduced to a shimmering silver."
"My type really isn't built for this kind of weather."
"I feel Jenna shift next to me and suddenly I feel her nose up against my ear and I shiver a little."
"What the hell was she doing?"
"I start to turn my head towards her."
show Jenna at center with dissolve
j "\"Um, Chase? Do you...do you need some Muskoff?\""
"I open my eyes, then squint against the brightness of the sun."
m "\"Wha—?\""
j "\"I said...\""
"She leans forward, obviously not wanting TJ to hear. She laughs a little before she starts again."
j "\"You're smelling a little strong.\""
"Instantly my ears burn and I scoot away instinctively, lowering my eyes."
m "\"Shit, sorry...\""
j "\"No, it's alright; you didn't know we were going on a hike before you packed, but I have some.\""
show TJ at right
with dissolve
"TJ's looking over at us curiously as he nibbles on his salad wrap, ears perked and I don't know why, but I glare at him, already humiliated enough."
"He frowns."
t "\"What?\""
m "\"Nothing, Jenna's just telling me I stink.\""
t "\"Oh.\""
show Jenna Smiling with dis
"Jenna laughs, then reaches over to her backpack and opens the top zipper, talking in a normal voice, now."
j "\"It's the female brand so it's not as strong, but it should get the job done.\""
m "\"Thanks.\""
"I grumble and snatch it from her paw, instantly feeling shitty about it because I know she's just trying to be nice."
"Even though TJ and Jenna are probably the nicest people in our little group it's still fucking embarrassing."
"I'd actually prefer Flynn's ribbing right now."
hide TJ
hide Jenna
with dissolve
"I stalk off around a rather large bush and pull down my pants."
"The can is pink and covered in flowers. Great."
"I grab my tail and yank it up before giving my ass a good, liberal dose of girl smells."
"Of course, if I'd known I'd be doing anything so sweat-inducing I would have brought my own boy-smelling brand."
"...But I'm stuck with this; smelling like a girl in front of Jenna."
"Guess it's better than nothing."
"As I come back around the bush I can tell something's off."
show TJ Sheepish at left with dissolve
"TJ meets eyes with me, then quickly looks down, frowning."
"I glare. I'd honestly be happier if he just joined in with Jenna and laughed at me instead."
"She's buried in her phone right now, which is annoying since she told us before the hike that phones weren't allowed."
show Jenna Smilinghips at right with dissolve
j "\"All done?\""
"She doesn't even look up, but points at the bag with a foot."
j "\"Go ahead and stick it back in the bag.\""
"I sigh and bend over to shove the can back in, then notice that it's been zipped closed again."
"Without thinking, I zip it back and widen the gap and immediately find a big, furry, orange and black spider glaring out at me from the bag."
"I scream like a fucking girl and jump, dropping the can, stumbling back, and falling flat on my ass as I trip over some rocks."
"I land on my tail wrong and it sends a jolt of pain up my back."
show Jenna Teasing
show TJ Teasing2
with dis
"Jenna, who already started laughing the moment I screamed, puts a paw to her muzzle."
stop background fadeout 3.0
play music "comeover.ogg" fadein 5.0
"Only one, though, because the other is holding her camera phone and she's filming the whole fucking thing."
show Jenna Sheepish
show TJ Surprised
with dis
j "\"Oh God, are you okay?\""
"She's still smiling behind her paw."
m "\"Fine.\"" 
"I guess I have a decision to make; whether to get mad, or to just shrug it off and laugh with them."
"I go with the latter and grin sheepishly."
m "\"Wow, I'd expect that from you Jenna, but TJ, what the hell man!?\""
"TJ flinches, a sad look on his face."
t "\"She told me she'd throw me off the cliff if I said anything!\""
"Jenna laughs again and puts her phone away before picking up the can and shoving it into the bag."
show Jenna Smilinghips with dis
j "\"Success!\""
m "\"Where the hell did you even get that from?\""
j "\"That one rest stop with the souvenir shop.\""
j "\"Alright, everyone done? I know you need to get some shots of the canyon, Chase. Let's go do that!\""
stop music fadeout 3.0

scene bg canyon with fade
play background "reststop.ogg" fadein 5.0
"I sit cross-legged next to Jenna, a bit further back than she is with her legs dangling over the edge of the cliff."
"I guess someone that's so confident about her life and future isn't worried about falling the 80 feet to her death."
"It's sort of the opposite of Carl, but with the same result."
play music "canyon.ogg" fadein 3.0
show Jenna Neutralhips at center with dissolve
j "\"You know, one good thing about this place is stuff like this.\""
m "\"Hanging off the edge of a cliff?\""
j "\"Lack of people, the mountains. I'll miss that.\""
j "\"I hear the mountains back East are small, like hills.\""
m "\"That sounds nice, too.\""
"She picks up a sizable rock and tosses it off the edge, listening to the clatter and echo as it bounces down the cliff."
j "\"Doesn't really matter, though. I'll be living in a big city. Way bigger than Payton.\""
m "\"Are you nervous?\""
j "\"About living in a big city? No. I'm more anxious to get started with school, actually.\""
show Jenna Rejectedhips with dis
j "\"And of course, I'll miss you guys, too. A lot.\""
"She flicks her ears back at TJ who's flat on his back under a tree behind us, snoring lightly."
"I wipe my forearm across my forehead, the oils from my water-proof fur sliding nastily against each other."
show Jenna Neutralhips with dis
m "\"Sorry, but—\""
"I pull my shirt off."
m "\"I need to let my shirt dry out. It's fucking gross.\""
"She looks over at me, then, her silver and turquoise necklace catching the light and flashing briefly."
"Jenna looks perfect, of course. The fur on her face and arms is brushed with the lay, held together by some kind of spray, probably."
"By comparison I look like a soggy log covered in wet brown mold."
"I blush and look down, the bravado I had worked up to take off my shirt dissipating under her gaze."
"She doesn't laugh, though."
j "\"I was wondering when you were going to take that off. Looked really uncomfortable.\""
m "\"Uh, yeah. Sorry I'm gross...\""
j "\"It's not gross. It's just what your body does to survive.\""
"Jenna sometimes says things that I suspect carry a lot more meaning than what's on the surface level, but honestly, I'm too dumb to figure it out."
"I really hope my smell isn't overpowering the spray."
stop music fadeout 10.0
j "\"But—\""
"I'm in the middle of leaning to the side to see if I can catch a whiff of my butt musk and I jolt back up."
m "\"Huh?\""
j "\"What was kind of gross is that there was another smell...\""
m "\"Oh?\""
j "\"Yeah...did you pee on yourself?\""
"It takes me a second to register what she just said, then it hits me and this time I have to close my eyes out of shame."
"Of course she was going to smell that. Foxes can smell fucking everything on you that's happened in the last week."
m "\"Yeah. Yeah, I did.\""
show Jenna Smiling with dis
"She laughs this time and I look away, off into the canyon, again."
j "\"I know it can happen, but it just smells like it was a lot, is all.\""
"I sigh and lean back on my paws, letting my head hang back."
m "\"I uh...I just—\""
"I debate telling her exactly what happened since it seems so childish, but it's not like she's being mean."
"She has a demeanor about her that just makes you want to talk."
"Must be that psych degree at work."
play music "loneliness.ogg" fadein 5.0
m "\"I just saw something that scared me a little, so when I jumped I got some on me.\""
j "\"What did you see?\""
"She lays out flat on her back, legs still dangling over the side with her paws behind her head, I guess so she can get a better look at me."
"I avoid looking right at her in case she thinks I'm staring."
m "\"Okay, this is gonna sound stupid, but I just felt like I was being watched. You know when you psych yourself up and everything looks scary?\""
j "\"Of course.\""
m "\"So I felt that behind me, and when I looked I saw what sort of looked like a face in some sage brush.\""
"Just talking about it right now is getting my fur to prickle."
"I hadn't really thought about it since it happened, and now that I am it's only now that I'm realizing how weird it all was."
show Jenna with dis
j "\"Huh, like a face you recognized?\""
m "\"No...no it was sort of flat, like it didn't have a muzzle, and white.\""
"I look back at Jenna, but she's not looking at me, instead it's like she's looking past me."
j "\"That is weird.\""
m "\"Yeah...yeah, but it was a rock.\""
j "\"We're wired to recognize faces, so we find them in a lot things.\""
m "\"Yeah, I mean, the twigs and stuff were falling across it in a way that it made it look like it had eyes and stuff, but then I realized what it was.\""
m "\"But I jumped and got pee on myself. So that's what happened. What's weird is that when I was leaving I couldn't see it anymore.\""
show Jenna Depressed with dis
"I say the last part with a laugh, mostly to hide how freaked out I am about it."
"When I look at Jenna again I can see the fur on her neck has lifted a little."
m "\"Was probably just the angle, though. You alright?\""
show Jenna with dis
"Jenna looks back at me, and I can tell she's debating whether or not to tell me something."
"I wait."
j "\"Just made me think about when I was a kid. Hadn't thought about it for years, actually.\""
"I pause."

m "\"Do you wanna talk about it?\""
"I'm worried I'm about to open up a can of worms."
j "\"It wasn't traumatizing, or anything like that. Well, it was, actually, but it wasn't real.\""
m "\"Did you see a face?\""
j "\"Yeah, not exactly like yours, though. It was more of a red color, but it was flat, too. That's what made me think of it.\""
m "\"Whoa...\""
j "\"Yeah. It had a body, too, but I can't really remember exactly what it was like.\""
m "\"Did you dream it?\""
j "\"No, not really a dream. At least not in the sense that I was asleep when it happened.\""
j "\"I'd just see it walking around in broad daylight, sometimes.\""
m "\"What the hell? Are these like, real, solid memories? Like it really happened?\""
j "\"I don't know. It usually happened when I was sad, or angry, like when dad was having one of his...moments.\""
j "\"I'd just see it walk past a doorway, or sit in a closet.\""
m "\"Really? What the fuck?\""
j "\"This was a long time ago, like, when I was five. I don't want you thinking I'm crazy, Chase.\""
m "\"I don't. I saw things, too, as a kid.\""
j "\"Yeah, I think you've told me.\""
"I had and it's something I really don't want to think about right now."
j "\"I'm pretty sure it's just something my mind made up because I was under a lot of stress. The brain can make up whatever it wants, really.\""
j "\"It's part of the reason I went into the field that I did. I want to help figure these things out.\""
m "\"Do you see it anymore...at all?\""
stop music fadeout 5.0
"She's quiet for a while, then shakes her head."
j "\"No.\""
play sound "phonebuzz.ogg"
show Jenna Smiling with dis
"My phone goes off then and I jump with a little yelp. Jenna laughs and it breaks the tension a little bit, so I laugh with her."
m "\"I know you said no phones, but you already used yours so I think I get a freebie.\""
j "\"Hey, I had to record your reaction for posterity.\""
"Looking at the message I see it's from Leo."
call text_chase("leo") from _call_text_chase_38
call text_0("", "Where are you") from _call_text_0_39
""
#"\"{i}Where are you{/i}\""
"I stare at it for a second."
"It seems a little short. Usually Leo throws in cheesy emoticons for everything."
"When he's not angry, of course."
"Jenna notices my expression."
j "\"What's up?\""
m "\"It's just Leo.\""
#"I type out a quick response, telling him I'm hiking with TJ and Jenna and did we forget to tell him that?"
"I type out a quick response."
play sound "texting3.ogg"
$ renpy.pause(1.0, hard=False)
call text("m", "I'm hiking with TJ and Jenna and did we forget to tell you that?") from _call_text_49
""
"Almost instantly I get a response."
play sound "phonebuzz.ogg"
$ renpy.pause(1.0, hard=False)
#"\"{i}Yeah u did{/i}\""
call text("", "Yeah u did") from _call_text_50
""
"He's definitely got something up his ass."
j "\"Wolf boy getting pissy?\""
call text_end from _call_text_end_38 
m "\"Uh, maybe? I can never tell with him.\""
play sound "phonebuzz.ogg"
"Jenna's phone goes off right then."
j "\"Ah, speak of the devil!\""
"Since it seems like she's inviting me, I lean over to read her phone."
"\"{i}What the hell{/i}\""
"I feel myself getting a little angry."
m "\"What the fuck's his problem?\""
"Jenna gives a little playful smirk as she sits up and puts her phone away without responding."
j "\"Aww, he's jealous.\""
"That gets me flustered for some reason."
m "\"You think so?\""
j "\"That, and he probably wants us all to hang out together, which we should! But we need some time away before we give Flynn another chance.\""
j "\"Anyway, we should head back. If we start now we can grab dinner at the diner by 6.\""
"Jenna gets up and goes to wake up TJ, but I'm sort of lost in thought. I feel bad for Leo."
"Was he mad at me for not talking to him by the lake yesterday?"
stop background fadeout 3.0

scene bg diner with fade
play music "neutraldiner.ogg"
"After being out in the desert for so long it feels absolutely amazing to be sitting in the air conditioned diner."
"Having already ordered our food I lean back against the booth, my eyes feeling a little heavy."
show TJ at right with dissolve
t "\"So thanks again for going with me guys. It wouldn't have been as much fun if there wasn't anyone to share it with.\""
show Jenna Smilinghips at left behind TJ with dissolve
j "\"Of course, TJ. I had a lot of fun, too.\""
"I put in my affirmative as well, grinning."
m "\"And sorry you guys had to put up with my slowness...and smell.\""
j "\"Ugh, stop apologizing for it. It's like you're speciesist against your own kind.\""
t "\"I'll be sure next time that we don't do such a long trail. If there is a next time...I hope there is!\""
j "\"Maybe. There's not exactly much else to do out here.\""
"The thought of hiking again makes my knees weak, but I don't say anything."
if Jenna_Route == "Gay":
    j "\"So Chase, I have to ask, have you been dating around at Pueblo?\""
    "That question takes me by surprise and I pause, looking at Jenna. TJ looks surprised as well, but looks at me curiously."
    j "\"It has been years since you and Leo were together proper. You two were pretty outspoken in all your social media pictures.\""
    "TJ stirs some from his initial shock at the topic shift and nods - speaking up."
    t "\"Yeah! In comparison to back in the day, you've been pretty quiet on that front.\""
    "I feel myself cringe inwardly in remembrance of all the kissing-selfies and cheesy song quotes we'd post."
    "Leo did most of it, but I was by no means innocent."
    "As of late, I haven't really posted much. Most of the people who are still on my timeline just rant about political stuff."
    "As the two look on expectantly, I feel myself shift in the pleather diner seat uncomfortably."
    m "\"Well, uh, not really?\""
    j "\"Oh?\""
    m "\"Yeah..I guess after a relationship as long as Leo and I's, I've kind of just been focused on, ya know, adulthood.\""
    t "\"Adulthood is difficult - a reasonable thing to keep you occupied.\""
    "TJ nods with a broad smile - his big ears flopping a little."
    j "\"Well, have you engaged in anything more 'casual' since?\""
    "I feel myself blanch a little before recombobulating - TJ just looking confused, thankfully."
    m "\"I downloaded one of those gay apps for meeting guys. All it really does is make me feel like crap, though.\""
    "I look sidelong toward the lynx beside Jenna. He gives me a curious look."
    m "\"People on there can be pretty speciest. I see a lot of 'no mustelidaes', 'no otters', and..uh..'no musk-types'.\""
    m "\"I met up with a few guys, but it was all pretty awkward and didn't go anywhere. Most didn't look like their profile picture.\""
    t "\"That's awful. I can't imagine putting yourself up for that sort of thing.\""
    "He pauses, then quickly holds up his paws defensively."
    t "\"I mean, meeting someone you like and love..'organically' - I think that's the word? - is important.\""
    j "\"Well, Chase here doesn't have that luxury. According to a study I read, about 1 out of every 25 people are gay.\""
    j "\"Then, the chances of both parties having mutual attraction lowers the compatability chances even more so.\""
    j "\"The online component is almost a necessity depending on one's region - Echo seeming to be the bizarre exception.\""
    "I see TJ's face shift to a guilty expression - the grey feline muttering a quiet 'oh' before taking a long drink of water."
    m "\"I uninstalled it though when I visited my parents over Christmas.\""
    m "\"I did eventually reinstall it but I guess I haven't looked at it much since then."
    j "\"I think you should check back into it. I'm actually a bit curious what sort of results you'll get in Echo.\""
    "My mind reels back to 15 year old me posting a photoshopped picture of myself on PaytonList Male-for-Male and the horrible aftermath."
    m "\"I don't know, Jenna. Probably wouldn't get much anyway. Most results would be from Payton - miles away.\""
    m "\"Plus, I'm pretty sure I already know the only result is gonna be a certain shirtless Gila.\""
    j "\"Honestly, I hate to sound like one of those podcasts, but something has to be in the water here.\""
    j "\"First Flynn, then Leo, then you - I watched all of you grow up and turn out gay.\""
    j "\"I still remember you sitting on the edge of my bed, sniffling about your parents finding out and how much of a 'deviant' you were.\""
    j "\"Completely unaware that I'd had the same sort of conversation with both Flynn and Leo about a year earlier.\""
    m "\"Oh God.\""
    "I place my face into my palm."
    m "\"It is kind of weird, I guess.\""
    "Jenna grins, then looks out the window."
    
    
    
elif Jenna_Route == "Bi":

    j "\"So Chase, I have to ask, have you been seeing any guys at Pueblo?\""
    "That question takes me by surprise and I pause, looking at Jenna. TJ looks surprised as well, but looks at me curiously."
    j "\"It has been years since you and Leo were together proper. You two were pretty outspoken in all your social media pictures.\""
    "TJ stirs some from his initial shock at the topic shift and nods - speaking up."
    t "\"Yeah! In comparison to back in the day, you've been pretty quiet on that front.\""
    "I feel myself cringe inwardly in remembrance of all the kissing-selfies and cheesy song quotes we'd post."
    "Leo did most of it, but I was by no means innocent."
    "As of late, I haven't really posted much. Most of the people who are still on my timeline just rant about political stuff."
    "As the two look on expectantly, I feel myself shift in the pleather diner seat uncomfortably."
    m "\"Well, uh, not really?\""
    j "\"Oh?\""
    m "\"Yeah..I guess after a relationship as long as Leo and I's, I've kind of just been focused on, ya know, adulthood.\""
    t "\"Adulthood is difficult - a reasonable thing to keep you occupied.\""
    "TJ nods with a broad smile - his big ears flopping a little."
    j "\"Well, have you engaged in anything more 'casual' since?\""
    "I feel myself blanch a little before recombobulating - TJ just looking confused, thankfully."
    m "\"I downloaded one of those gay apps for meeting guys. All it really does is make me feel like crap, though.\""
    "I look sidelong toward the lynx beside Jenna. He gives me a curious look."
    m "\"People on there can be pretty speciest. I see a lot of 'no mustelidaes', 'no otters', and..uh..'no musk-types'.\""
    m "\"I met up with a few guys, but it was all pretty awkward and didn't go anywhere. Most didn't look like their profile picture.\""
    t "\"That's awful. I can't imagine putting yourself up for that sort of thing.\""
    "He pauses, then quickly holds up his paws defensively."
    t "\"I mean, meeting someone you like and love..'organically' - I think that's the word? - is important.\""
    j "\"Well, Chase here doesn't have that luxury. According to a study I read, about 1 out of every 25 people are gay.\""
    j "\"Then, the chances of both parties having mutual attraction lowers the compatability chances even more so.\""
    j "\"The online component is almost a necessity depending on one's region - Echo seeming to be the bizarre exception.\""
    "I see TJ's face shift to a guilty expression - the grey feline muttering a quiet 'oh' before taking a long drink of water."
    m "\"I uninstalled it though when I visited my parents over Christmas. Haven't had much of a thought to install it back.\""
    j "\"I think you should reinstall it. I'm actually a bit curious what sort of results you'll get in Echo.\""
    "My mind reels back to 15 year old me posting a photoshopped picture of myself on PaytonList Male-for-Male and the horrible aftermath."
    m "\"I don't know, Jenna. Probably wouldn't get much anyway. Most results would be from Payton 30 miles away.\""
    m "\"Plus, I'm pretty sure I already know the only result is gonna be a certain shirtless Gila.\""
    j "\"Honestly, I hate to sound like one of those podcasts, but something has to be in the water here.\""
    j "\"First Flynn, then Leo, then you - I watched all of you grow up and turn out to like guys.\""
    j "\"I still remember you sitting on the edge of my bed, sniffling about your parents finding out and how much of a 'deviant' you were.\""
    j "\"Completely unaware that I'd had the same sort of conversation with both Flynn and Leo about a year earlier.\""
    m "\"Oh God.\""
    "I place my face into my palm."
    m "\"..It is kind of weird, I guess.\""
    
    j "\"But now that you're officially bi, your horizons have expanded, yes?\""
    j "\"I have to ask; have you been dating any girls?\""
    "I'm taken off-guard, looking back up to Jenna. TJ stops gulping down his ice-water."
    m "\"Hmm...not really, actually. I mean, I guess you could say I lean towards males, but it's not like—\""
    "I was about to say that I sometimes look at straight porn when I'm in the mood, but that might be a little inappropriate with TJ there."
    "Hell, it's probably inappropriate to say in front of Jenna, too. Do guys talk about porn in front of girls?"
    m "\"It's not like I don't notice girls.\""
    "I finish the sentence lamely, but TJ just nods."
    t "\"That makes sense.\""
    show Jenna Teasinghips with dis
    j "\"Well, have you ever slept with a girl?\""
    show TJ Surprised with dis
    t "\"Jenna!\""
    "TJ's face going from cheerful interest to outright horror is so comical I start laughing despite Jenna's question surprising me as well."
    show Jenna Smilinghips with dis
    j "\"Hey, this is how boys talk, right? I've been hanging out with you guys since the fourth grade. Don't exclude me just because I'm a girl.\""
    t "\"I don't talk like that!\""
    "Despite TJ's reaction I'm not too bothered by it."
    m "\"No, I haven't. I kissed a girl once at a party, but that was it.\""
    j "\"Hmm. Do you WANT to be with a girl, just to see what it's like?\""
    "Now I'm starting to get a little embarrassed."
    "Whether TJ is more appalled, or not, I can't tell since he's got his face buried in his paws."
    m "\"I don't—Maybe? I dunno...\""
    j "\"Just curious. I'm just wondering why I didn't pick up on this about you before.\""
    "Jenna grins, then looks out the window."
    "I notice then, with the way the sunset is lighting up the diner, how pretty her eyes are. It almost looks unnatural the way they glow."
    show TJ with dis
j "\"So I need to ask you a favor, Chase.\""
"I stiffen, wondering what the hell it might be after that conversation."
j "\"I'm wondering if you could drive me to the mall. I want to get a few things.\""
m "\"Oh sure. What do you need?\""
show Jenna Sheepish with dis
"Jenna hesitates and, for the first time today, SHE'S the one that seems embarrassed."
j "\"Well, you know in Pueblo we don't exactly have a great comic book shop, even though it's huge.\""
m "\"Oh yeah?\""
"I wouldn't really know. I never did go to that section of the mall."
j "\"What's especially lacking is the manga selection.\""
"I smile."
"I'd forgotten the way that, after getting her first job, I'd drive Jenna to the mall once a week and she'd buy her favorite manga."
"Jenna's still not looking at me, but I grin."
m "\"Yeah! It'll be just like when we were in high school. Have you been keeping up on all of those series?\""
"I remember being amazed at how much material was in those books compared to the comics, even if they weren't colored."
"Jenna looks back at me and I can see that she's a little relieved. Did she think I was gonna make fun of her for it?"
j "\"I keep up with it online, mostly. This is more for old time's sake.\""
j "\"Believe it or not that mall has some of the happiest memories I have of this place, aside from Leo's house.\""
"Of course I'd believe that."
j "\"I guess there are a few special edition volumes I want to get that they might have. I was always surprised with what they were able to bring in.\""
m "\"Well, that's cool! You know, I watched an anime since I last saw you.\""
show Jenna Smiling with dis
j "\"Oh really? What was it?\""
m "\"Uh, I can't really remember. Ichirohe...it was a long title, but it was about this old wolf guy that becomes a samurai—\""
j "\"{i}ichiroheian o inoru{/i}?\""
"She says it quickly with what sounds to me like a perfect accent."
m "\"Maybe? That sounds about right.\""
"Jenna makes a face like she swallowed a lemon."
j "\"It is. It's the only old wolf samurai show I know. You gotta watch some of the older stuff. Anime these days is just.. you know?\""
m "\"Uh, no?\""
j "\"Well, we need to do that, too. One of these nights we're going to marathon {i}Ganbatte Ne!{/i}. The hotel Wi-Fi is good enough for it, I think.\""
j "\"It's got this sort of western-style, medieval atmosphere to it.\""
"While I never really watched anime, even if ichi—whatever-it-was wasn't bad..."
"...the idea of staying up late with Jenna watching old foreign cartoons sounds like a lot of fun."
j "\"Wanna join us, TJ?\""
"TJ looks up from his phone."
t "\"Huh, what?\""
j "\"Do you want to watch anime with us?\""
t "\"Uh, sure. Why not?\""
m "\"Hey, no phones!\""
"I tease him, reaching for it and take it from him."
t "\"I thought that was only for the hike?\""
"I glance over the screen, expecting to see some Christian social group, or something, but instead it's a text thread from Leo."
stop music fadeout 5.0
"\"{i}Yo teej where you at{/i}\""
"\"{i}Hi Leo. We're hiking.{/i}\""
"\"{i}You going somewhere after that{/i}\""
"\"{i}Yeah, the diner. Do you want to meet us there?{/i}\""
"\"{i}Is Chase going to{/i}\""
"\"{i}Yeah, he's here.{/i}\""
show TJ Annoyed with dis
t "\"Are you reading my texts? That's really rude.\""
"I look up at TJ, who's glaring at me from across the table."
play sound "phonebuzz.ogg"
"I look back down at the phone."
"\"Alright on my way\""
m "\"Leo's coming?\""
show TJ Neutral with dis
t "\"Yup! He's been messaging me all day.\""
show Jenna with dis
"Jenna and I look at each other, both of our brows raised."
t "\"What?\""
play music "quiet.ogg"
"But that's when Leo's van pulls in front of the diner and I hear Jenna sigh loudly."
"Leo's bulky form bounces out of the truck, doing a little jog up to the diner."
"The bell to the door rings as Leo walks in, all smiles."
show TJ with dis
t "\"Hey Leo!\""
show Leo at center behind Jenna with dissolve
l "\"TJ.\""
"Leo immediately squeezes into the booth next to me, almost sandwiching me between him and the window."
l "\"Chaaaase, what's up?\"" 
"He wraps a big arm around my neck and yanks me roughly into a hug, forcing a little squeak out of my throat."
l "\"See, this is how it should be! We came here to hang out, not break up into little groups and fight!\""
j "\"That was Flynn's fault.\""
"Jenna says it quietly, eying Leo's arm around my neck."
l "\"Yeah, well, I'm gonna get him to apologize. Things take a little bit of time, you know?"
"Jenna doesn't say anything, instead choosing to look over the menu, even though we've already ordered."
show Leo Wry with dis
l "\"You have fun hiking?\""
"Leo turns his goofy, tongue-out smile on me."
show Leo Neutral with dis
"I'm about to answer, but that's when his face changes, and I see his nose twitching."
l "\"You...smell like a girl.\""
"His head snaps to Jenna and it's instantly obvious as to what he's thinking."
show Jenna Smiling with dis
"Jenna, who's looking up, now, just smiles sweetly, not trying to explain the situation at all."
"Leo tenses up, arm tightening around my neck, almost choking me."
m "\"I forgot my musk stuff, so Jenna lent me hers!\""
"Leo looks back at me, and I can tell he's trying to decide whether or not to believe me."
"TJ, though, for once, chimes in with something useful, cheerfully unaware."
t "\"Yeah, it was pretty funny. Sorry, Chase.\""
"He looks at me apologetically, but honestly I could kiss him right now."
"Leo relaxes a little, but his ears are still pointed straight up, a sure sign that's he's still tense."
show Leo with dis
l "\"Alright...well, next time you go, I'm coming, too.\""
l "\"Anyway, I'm planning Carl's birthday party tomorrow.\""
m "\"What? That's like a month away.\""
l "\"Yeah, well, there's not much else to do.\""
show Jenna Annoyed with dis
"Jenna leans back in her seat and folds her ears down."
j "\"That's reeeally short notice, Leo. Couldn't you have told us this before we came so we could prepare?\""
l "\"Well, I was planning to do that today, but you guys just took off without telling me.\""
show TJ Surprised with dis
t "\"I don't have a gift!\""
show Leo Neutral with dis
"Leo rubs his face."
l "\"We've still got time to do that. Just wanted to tell you what's up.\""
"We chat for a while longer, then we get our food."
"Leo orders a milkshake and hangs out with us the whole time."
"Usually I would love to have Leo around, but something about this feels forced and awkward, and Jenna's gone pretty quiet."
"Leo doesn't let go of my neck the entire time..."

window hide
scene bg AllWednesday
with opening_fade
stop music fadeout 6.0
$ renpy.pause(3.0, hard=True)

jump jennawednesday