label JennaMonday:
"I look towards Leo, hunched forward, ears down, looking like an angry gargoyle perched on the ledge of a church."
m "\"Hold on, Jenna.\""
"I turn back around to face her."
show Jenna Neutralhips at center with dissolve
j "\"Hmm?\""
"I look back over my shoulder at Leo, watching his ears flick towards us."
m "\"I think...I think Leo wants to be left alone.\""
show Jenna Rejected with dis
"Jenna folds her arms and looks past me."
j "\"You sure? I thought you could get him to calm down.\""
"I look at Jenna for a while, realizing that I'd just rather talk to someone more collected, rather than a big angry wolf."
m "\"Yeah, I'm sure.\""
j "\"Well, alright. Should we head back, then?\""
m "\"Okay.\""
play background "trailsteps.ogg"
scene bg deserttrail with dissolve
hide TJ
hide Jenna
hide Leo
hide Flynn
hide Carl
"As we start disappearing into the sage brush, I look back in time to catch a glimpse of Leo looking over his shoulder."
"I look back down at the ground, wondering if it would have been a good idea to at least tell him that I felt like he needed time alone."
"I notice Jenna looking around, her huge ears perked up wide like sails."
m "\"What're you looking for?\""
j "\"TJ.\""
"If it was up to me I'd be leaving TJ alone as well, but Jenna always worried about him."
"I follow her through the brush in silence, unsure of what to say."
j "\"So why didn't you hang back with Leo?\""
"I move along with her for a while, thinking it over."
m "\"I dunno. When he's in a bad mood he's really only good for a fight, you know?\""
j "\"Hmm.\""
"I catch up and start walking alongside her since I was starting to taste the dirt being kicked up by her feet."
m "\"Yeah, thought it would be a good idea to let him cool down for a bit.\""
"I sort of envy the way she's dressed right now, with her short shorts and tank top. Jeans don't exactly breathe well."
"I finally start to see our picnic again. Carl's still sitting in the lawn chair, his head hanging over the back and smoke wafting around him."
"Jenna stops and puts her paws on her hips, looking around."
stop background fadeout 3.0
show Jenna at center with dissolve
m "\"Where do you think he went?\""
j "\"There aren't many places he could have gone.\""
"Her eyes seem to settle and I follow her gaze to a clump of brush and trees next to the river."
"If TJ had anywhere to hide in the short amount of time that he did, that would really be the only place he could have done it."
hide Jenna with dissolve
"Without a word, Jenna starts in that direction. I tag along awkwardly, kind of feeling like I'm invisible to her right now."
play background "river.ogg" fadein 5.0
scene bg riverbank with dissolve
"As soon as we break through the brush, we spot TJ."
"I watch as Jenna immediately goes to his side and sits down."
"TJ's ears perk, but otherwise he doesn't look up."
"After a while, Jenna wraps an arm around TJ's shoulders. I see him bristle for a second, and Jenna says something to him that I don't quite catch."
"Finally, he leans in and hugs her and I can hear him sniffling."
"I'm starting to feel like I'm intruding and I start to back away, but Jenna sees me and jerks her head."
j "\"Where are you going, Chase? Come here.\""
"TJ pulls back from Jenna and starts wiping at his eyes."
t "\"Chase?\""
m "\"Uh, yeah.\""
"I feel like TJ would be embarrassed to have me around, and he probably is, but Jenna's pretty insistent, so I move forward to stand next to them."
j "\"I was just telling TJ about the time we used to float the river on the old inner tube.\""
show Jenna at left
show TJ Rejected at right
with dissolve
"I smile and sit down next to Jenna, stretching my legs out."
t "\"Do you remember that, Chase?\""
stop background fadeout 10.0
play music "intimate.ogg" fadein 10.0
"His voice is strained and a little crackly, but he seems to have things under control, now."
m "\"Do I? Always thought it was ridiculous to use one of those things when you could just float on your back.\""
j "\"Sorry we're not all living floaties, Chase.\""
"We sit there for a while, and now it isn't as awkward."
"I feel like if it were just me and TJ, things would be a lot more tense."
"Jenna has a way of making things feel natural and easy. It's like her confidence is a shield to all my weird, awkward stupidity."
"I hear TJ shift and sniffle as he wipes his face again."
t "\"I'm sorry guys. I didn't mean—\""
show Jenna Annoyed with dis
j "\"Nope. You stop right there, TJ.\""
"He does stop. It's hard not to when she has a tone like that."
j "\"Flynn is an absolute dick. NEVER let him affect how you feel about things. He only thinks about himself and how HE feels.\""
j "\"Right, Chase?\""
"I feel like this is just a little bit unfair to Flynn. Yeah, he was pretty selfish, but he did care about other people."
"At least, I think he does, even though he hardly ever admits to it."
"Probably best to agree with Jenna right now, though."
m "\"Yeah, he's...he's just not thinking straight right now. I think coming here might have been a bad idea.\""
j "\"That really shouldn't matter.\""
j "\"In fact, we probably should have gone to the lake. What happened happened and there's not much we can do about it.\""
j "\"Letting it absolutely rule our lives like this, to the point of preventing us from going where we want to go; that's pretty messed up.\""
j "\"We all went through it and it was awful, but we stayed friends and here we are.\""
j "\"Maybe we should celebrate that instead of accusing each other of bullshit?\""
m "\"Yeah...\""
"Of course, what Flynn had been saying wasn't complete bullshit. None of us really know exactly what happened....except TJ."
j "\"I didn't have any reason to come here, and if I had the same mindset as Flynn I never would have.\""
"TJ glances over at Jenna."
t "\"H—how are things with...with you and—\""
j "\"My family? Same as it's been for the past five years:\""
j "\"I don't know.\""
t "\"Maybe...maybe you could try—?\""
show Jenna Rejected with dis
"Jenna sighs deeply."
t "\"Sorry! I didn't mean—\""
j "\"No, TJ, it's fine, it's just—\""
"She seems to be thinking hard about what she's going to say."
"Man, the things that Jenna COULD say about her family. I have too many bad memories about that."
j "\"That family is completely broken, like, there's no fixing it. Going back there would just mean trouble...I've learned my lesson.\""
j "\"With Adam and dad gone it's just my mom and Jeremy now, anyway. Not much of a family to go back to...\""
t "\"Has your dad not—.. has anyone seen him since?\""
j "\"As far as I know, no. But I wouldn't really care if he is back.\""
j "\"And if he really is missing, well, mom never filed a missing person's report, so I guess it wouldn't matter.\""
t "\"I'm sorry.\""
j "\"Why? You're not the one that messed it all up.\""
"TJ looks away, his ears down."
"Jenna sighs and puts an arm back around TJ's shoulders."
j "\"And here I am bringing everyone down when the point was to make you feel better.\""
show Jenna Smiling with dis
j "\"Chase! Remind us of something happy.\""
"I jump, then scramble after being put on the spot."
m "\"Uh, remember when we called it Yeeyaw River?\""
j "\"I remember when YOU called it Yeeyaw, Chase. You had a bit of a speech impediment back then.\""
m "\"Uh...yeah.\""
show TJ with dis
t "\"I remember that. It was kind of cute.\""
"It's quiet for a moment, then Jenna gives TJ a little nudge."
j "\"So how's school going, TJ?\""
t "\"It's not bad. I got accepted into the athletic training program, which is really cool because they're really selective.\""
t "\"I think I'm one of twenty that they chose.\""
j "\"Wow, that's fantastic, TJ!\""
"TJ smiles, though he's still looking at his feet."
t "\"Thanks...hey, but you got into Weston!\""
j "\"I did.\""
"I furrow my brow at that."
m "\"Hey, come on. Weston is like, THE stereotypical best school in the country.\""
"She looks over at me and smiles."
j "\"It's great, I know. Just a lot of stress. Sometimes I'd like to get a break.\""
"That was a little surprising to hear from Jenna. Usually she was so energized and had a get 'er done attitude about almost anything."
"That's why I assume she got into Weston in the first place."
m "\"Maybe you should take a break, then? It's kind of up to you, isn't it?\""
j "\"Just because I want it doesn't mean I need it. Hey Teej, weren't you wanting to go hiking while we were here?"
t "\"Yeah...I know things are a bit bad right now, but it could be fun to go.\""
j "\"Of course, TJ, I was planning to go with you anyway.\""
t "\"Oh cool!\""
"At that point all of TJ's gloomy demeanor disappears; his tail quirked and his ears raised up."
"Jenna looks sideways at me, meaningfully."
m "\"Uh...\""
"Yeah, definitely didn't want to do that. I'm not even doing anything and already I'm sweating buckets and looking at the shiney water longingly."
"I would have jumped in the water by now if TJ wasn't here. For some reason that would seem inappropriate."
"Right then I feel something press down hard on my paw which is splayed out behind me."
"Looking over, I see that Jenna has her paw on mine, leaning on it."
m "\"Oh um, yeah, definitely. I'm going...\""
t "\"Yes!\""
"Jenna lifts her paw off mine, and I gulp."
"It didn't really hurt, but something about her suddenly touching me like that..."
j "\"It's settled then. We should probably get back. We want to get a lot of rest before the hike tomorrow.\""

#dream?

jump jennatuesday
